import type { Question } from "../types";

/**
 * Clásicos Disney y Walt Disney Animation Studios.
 *
 * Convenciones del banco (ver también lib/preguntas.ts):
 * - Títulos y nombres del doblaje de España.
 * - `accepted` es una lista de huecos obligatorios; cada hueco lleva variantes.
 *   El corrector ya perdona tildes, mayúsculas y erratas, así que aquí solo se
 *   ponen alternativas de verdad (apodos, apellido suelto, sinónimos).
 * - Las preguntas de dificultad "dificil" van siempre en formato "multiple".
 */
export const DISNEY: Question[] = [
  // --- El Rey León ---
  {
    id: "reyleon-pumba",
    franchise: "El Rey León",
    emoji: "🦁",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el jabalí verrugoso que acompaña a Timón?",
    hint: "(Solo el nombre.)",
    accepted: [["Pumba", "Pumbaa"]],
    official: "Pumba",
  },
  {
    id: "reyleon-rafiki",
    franchise: "El Rey León",
    emoji: "🦁",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el mandril chamán que presenta a Simba en la Roca del Rey?",
    options: ["Rafiki", "Zazú", "Banzai", "Shenzi"],
    correct: 0,
    official: "Rafiki",
  },
  {
    id: "reyleon-zazu",
    franchise: "El Rey León",
    emoji: "🦁",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es un cálao rojo, mayordomo del rey, siempre nervioso y con aires de secretario.",
    hint: "(Solo el nombre.)",
    accepted: [["Zazú", "Zazu"]],
    official: "Zazú",
  },
  {
    id: "reyleon-hakuna",
    franchise: "El Rey León",
    emoji: "🦁",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el lema de Timón y Pumba: «Hakuna ___».",
    accepted: [["Matata"]],
    official: "Hakuna Matata",
    note: "Significa «vive y sé feliz» en suajili.",
  },

  // --- La Sirenita ---
  {
    id: "sirenita-voz",
    franchise: "La Sirenita",
    emoji: "🧜",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué le entrega Ariel a Úrsula a cambio de tener piernas?",
    hint: "(Una palabra.)",
    accepted: [["voz", "su voz", "la voz"]],
    official: "Su voz",
  },
  {
    id: "sirenita-triton",
    franchise: "La Sirenita",
    emoji: "🧜",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el padre de Ariel, rey del mar?",
    hint: "(Solo el nombre.)",
    accepted: [["Tritón", "Rey Tritón"]],
    official: "Tritón",
  },
  {
    id: "sirenita-morenas",
    franchise: "La Sirenita",
    emoji: "🧜",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman las dos morenas que sirven a Úrsula?",
    options: [
      "Flotsam y Jetsam",
      "Morgana y Undina",
      "Scylla y Caribdis",
      "Kelp y Coral",
    ],
    correct: 0,
    official: "Flotsam y Jetsam",
  },

  // --- Aladdín ---
  {
    id: "aladdin-rajah",
    franchise: "Aladdín",
    emoji: "🧞",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la tigresa de Jasmín?",
    hint: "(Solo el nombre.)",
    accepted: [["Rajah", "Raja"]],
    official: "Rajah",
  },
  {
    id: "aladdin-mundo",
    franchise: "Aladdín",
    emoji: "🧞",
    difficulty: "facil",
    format: "completar",
    prompt:
      "Completa el título de la canción que cantan Aladdín y Jasmín sobre la alfombra: «Un mundo ___».",
    accepted: [["ideal"]],
    official: "Un mundo ideal",
  },
  {
    id: "aladdin-cueva",
    franchise: "Aladdín",
    emoji: "🧞",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el lugar donde Aladdín encuentra la lámpara?",
    options: [
      "La Cueva de las Maravillas",
      "La Gruta de los Deseos",
      "El Templo de Agrabah",
      "La Caverna Dorada",
    ],
    correct: 0,
    official: "La Cueva de las Maravillas",
  },

  // --- La Bella y la Bestia ---
  {
    id: "bella-lumiere",
    franchise: "La Bella y la Bestia",
    emoji: "🌹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el candelabro del castillo de la Bestia?",
    hint: "(Solo el nombre.)",
    accepted: [["Lumière", "Lumiere"]],
    official: "Lumière",
  },
  {
    id: "bella-gaston",
    franchise: "La Bella y la Bestia",
    emoji: "🌹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el cazador presumido que pretende casarse con Bella?",
    hint: "(Solo el nombre.)",
    accepted: [["Gastón", "Gaston"]],
    official: "Gastón",
  },
  {
    id: "bella-dindon",
    franchise: "La Bella y la Bestia",
    emoji: "🌹",
    difficulty: "dificil",
    format: "multiple",
    prompt:
      "¿Cómo se llama en el doblaje español el mayordomo convertido en reloj de sobremesa?",
    options: ["Din-Don", "Tic-Tac", "Cogsworth", "Campanón"],
    correct: 0,
    official: "Din-Don",
    note: "En la versión original se llama Cogsworth.",
  },

  // --- Blancanieves ---
  {
    id: "blancanieves-enanito",
    franchise: "Blancanieves",
    emoji: "🍎",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál de estos NO es uno de los siete enanitos?",
    options: ["Risitas", "Mudito", "Gruñón", "Dormilón"],
    correct: 0,
    official: "Risitas",
  },
  {
    id: "blancanieves-espejo",
    franchise: "Blancanieves",
    emoji: "🍎",
    difficulty: "facil",
    format: "vf",
    prompt: "La Reina Malvada consulta a un espejo mágico para saber quién es la más bella.",
    correct: true,
    official: "Verdadero",
  },

  // --- Cenicienta ---
  {
    id: "cenicienta-lucifer",
    franchise: "Cenicienta",
    emoji: "👠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el gato de la madrastra de Cenicienta?",
    hint: "(Solo el nombre.)",
    accepted: [["Lucifer"]],
    official: "Lucifer",
  },
  {
    id: "cenicienta-hora",
    franchise: "Cenicienta",
    emoji: "👠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿A qué hora se rompe el hechizo del Hada Madrina?",
    hint: "(La hora.)",
    accepted: [["medianoche", "las doce", "12", "doce de la noche"]],
    official: "A medianoche",
  },

  // --- Peter Pan ---
  {
    id: "peterpan-campanilla",
    franchise: "Peter Pan",
    emoji: "🧚",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el hada que acompaña a Peter Pan?",
    hint: "(Solo el nombre.)",
    accepted: [["Campanilla"]],
    official: "Campanilla",
  },
  {
    id: "peterpan-isla",
    franchise: "Peter Pan",
    emoji: "🧚",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la isla donde nunca se crece?",
    accepted: [["Nunca Jamás", "País de Nunca Jamás", "Nunca Nunca"]],
    official: "El País de Nunca Jamás",
  },
  {
    id: "peterpan-barco",
    franchise: "Peter Pan",
    emoji: "🧚",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el barco pirata del capitán Garfio?",
    options: ["Jolly Roger", "Perla Negra", "Calavera", "Nautilus"],
    correct: 0,
    official: "El Jolly Roger",
  },

  // --- El libro de la selva ---
  {
    id: "selva-baloo",
    franchise: "El libro de la selva",
    emoji: "🐻",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el oso despreocupado que enseña a Mowgli a vivir sin agobios?",
    hint: "(Solo el nombre.)",
    accepted: [["Baloo"]],
    official: "Baloo",
  },
  {
    id: "selva-kaa",
    franchise: "El libro de la selva",
    emoji: "🐻",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la serpiente pitón que hipnotiza a Mowgli?",
    hint: "(Solo el nombre.)",
    accepted: [["Kaa"]],
    official: "Kaa",
  },
  {
    id: "selva-sherekhan",
    franchise: "El libro de la selva",
    emoji: "🐻",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el tigre de Bengala al que todos temen?",
    hint: "(Solo el nombre.)",
    accepted: [["Shere Khan", "Shere-Khan", "Shir Khan"]],
    official: "Shere Khan",
  },
  {
    id: "selva-louie",
    franchise: "El libro de la selva",
    emoji: "🐻",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el orangután que quiere aprender a hacer fuego?",
    options: ["Rey Louie", "Rey Akela", "Rey Hathi", "Rey Bandar"],
    correct: 0,
    official: "El Rey Louie",
  },

  // --- Pinocho ---
  {
    id: "pinocho-grillo",
    franchise: "Pinocho",
    emoji: "🪵",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el grillo que hace de conciencia de Pinocho?",
    hint: "(Solo el nombre.)",
    accepted: [["Pepito Grillo", "Pepito"]],
    official: "Pepito Grillo",
  },
  {
    id: "pinocho-geppetto",
    franchise: "Pinocho",
    emoji: "🪵",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el carpintero que talla a Pinocho?",
    hint: "(Solo el nombre.)",
    accepted: [["Geppetto", "Gepetto"]],
    official: "Geppetto",
  },
  {
    id: "pinocho-ballena",
    franchise: "Pinocho",
    emoji: "🪵",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la enorme ballena que se traga a Geppetto?",
    options: ["Monstro", "Leviatán", "Cetus", "Bruto"],
    correct: 0,
    official: "Monstro",
  },

  // --- Dumbo ---
  {
    id: "dumbo-pluma",
    franchise: "Dumbo",
    emoji: "🐘",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué objeto cree Dumbo que le da el poder de volar?",
    hint: "(Una palabra.)",
    accepted: [["pluma", "una pluma", "pluma mágica"]],
    official: "Una pluma",
    note: "En realidad vuela solo, la pluma es un truco de confianza.",
  },

  // --- 101 dálmatas ---
  {
    id: "dalmatas-cruella",
    franchise: "101 dálmatas",
    emoji: "🐕",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la villana obsesionada con hacerse un abrigo de piel de cachorro?",
    accepted: [["Cruella de Vil", "Cruella"]],
    official: "Cruella de Vil",
  },
  {
    id: "dalmatas-padres",
    franchise: "101 dálmatas",
    emoji: "🐕",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llaman los dos dálmatas adultos, padres de los cachorros?",
    options: [
      "Pongo y Perdita",
      "Pongo y Peggy",
      "Danny y Perdita",
      "Rolly y Penny",
    ],
    correct: 0,
    official: "Pongo y Perdita",
  },

  // --- Los Aristogatos ---
  {
    id: "aristogatos-gatitos",
    franchise: "Los Aristogatos",
    emoji: "🎹",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman los tres gatitos de Duquesa?",
    options: [
      "Marie, Berlioz y Toulouse",
      "Marie, Chopin y Monet",
      "Mimi, Berlioz y Renoir",
      "Marie, Bizet y Degas",
    ],
    correct: 0,
    official: "Marie, Berlioz y Toulouse",
  },

  // --- Hércules ---
  {
    id: "hercules-hades",
    franchise: "Hércules",
    emoji: "⚡",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el dios del inframundo que hace de villano?",
    hint: "(Solo el nombre.)",
    accepted: [["Hades"]],
    official: "Hades",
  },
  {
    id: "hercules-secuaces",
    franchise: "Hércules",
    emoji: "⚡",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llaman los dos demonios torpes que sirven a Hades?",
    options: [
      "Pena y Pánico",
      "Furia y Rabia",
      "Miedo y Duda",
      "Caos y Ruina",
    ],
    correct: 0,
    official: "Pena y Pánico",
  },
  {
    id: "hercules-meg",
    franchise: "Hércules",
    emoji: "⚡",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la joven que trabaja para Hades y acaba enamorando a Hércules?",
    hint: "(Solo el nombre.)",
    accepted: [["Megara", "Meg"]],
    official: "Megara",
  },

  // --- Mulán ---
  {
    id: "mulan-shang",
    franchise: "Mulán",
    emoji: "🐉",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el capitán que instruye a los reclutas del ejército chino?",
    hint: "(Solo el nombre.)",
    accepted: [["Li Shang", "Shang"]],
    official: "Li Shang",
  },
  {
    id: "mulan-shanyu",
    franchise: "Mulán",
    emoji: "🐉",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el líder de los hunos que invade China?",
    options: ["Shan Yu", "Chi Fu", "Yao", "Ling"],
    correct: 0,
    official: "Shan Yu",
  },

  // --- Tarzán ---
  {
    id: "tarzan-jane",
    franchise: "Tarzán",
    emoji: "🌴",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la joven inglesa de la que se enamora Tarzán?",
    hint: "(Solo el nombre.)",
    accepted: [["Jane", "Jane Porter"]],
    official: "Jane",
  },
  {
    id: "tarzan-tantor",
    franchise: "Tarzán",
    emoji: "🌴",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el elefante miedoso amigo de Tarzán?",
    options: ["Tantor", "Hathi", "Dumbo", "Terk"],
    correct: 0,
    official: "Tantor",
  },

  // --- El jorobado de Notre Dame ---
  {
    id: "jorobado-quasimodo",
    franchise: "El jorobado de Notre Dame",
    emoji: "🔔",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el campanero protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Quasimodo", "Cuasimodo"]],
    official: "Quasimodo",
  },
  {
    id: "jorobado-frollo",
    franchise: "El jorobado de Notre Dame",
    emoji: "🔔",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el juez que tiene encerrado a Quasimodo en el campanario?",
    options: ["Claude Frollo", "Phoebus", "Clopin", "Gastón"],
    correct: 0,
    official: "Claude Frollo",
  },

  // --- Pocahontas ---
  {
    id: "pocahontas-meeko",
    franchise: "Pocahontas",
    emoji: "🍃",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el mapache glotón que acompaña a Pocahontas?",
    hint: "(Solo el nombre.)",
    accepted: [["Meeko", "Miko"]],
    official: "Meeko",
  },
  {
    id: "pocahontas-smith",
    franchise: "Pocahontas",
    emoji: "🍃",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el colono inglés del que se enamora Pocahontas?",
    accepted: [["John Smith", "Smith"]],
    official: "John Smith",
  },

  // --- Lilo & Stitch ---
  {
    id: "stitch-jumba",
    franchise: "Lilo & Stitch",
    emoji: "🌺",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el científico alienígena que creó a Stitch?",
    hint: "(Solo el nombre.)",
    accepted: [["Jumba", "Jumba Jookiba"]],
    official: "Jumba",
  },
  {
    id: "stitch-pleakley",
    franchise: "Lilo & Stitch",
    emoji: "🌺",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el alienígena de un solo ojo, experto en la Tierra, que acompaña a Jumba?",
    options: ["Pleakley", "Cobra Bubbles", "Gantu", "Jacques"],
    correct: 0,
    official: "Pleakley",
  },

  // --- Zootrópolis ---
  {
    id: "zootropolis-flash",
    franchise: "Zootrópolis",
    emoji: "🦊",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Trabaja en la oficina de tráfico, es un perezoso y tarda una eternidad en terminar cada frase.",
    hint: "(Solo el nombre.)",
    accepted: [["Flash"]],
    official: "Flash",
  },
  {
    id: "zootropolis-mrbig",
    franchise: "Zootrópolis",
    emoji: "🦊",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es Mr. Big, el temido jefe del crimen de Tundratown?",
    options: ["Una musaraña", "Un oso polar", "Una comadreja", "Un topo"],
    correct: 0,
    official: "Una musaraña",
  },

  // --- Frozen ---
  {
    id: "frozen-olaf",
    franchise: "Frozen",
    emoji: "❄️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el muñeco de nieve que sueña con el verano?",
    hint: "(Solo el nombre.)",
    accepted: [["Olaf"]],
    official: "Olaf",
  },
  {
    id: "frozen-arendelle",
    franchise: "Frozen",
    emoji: "❄️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el reino de Elsa y Anna?",
    hint: "(Solo el nombre.)",
    accepted: [["Arendelle"]],
    official: "Arendelle",
  },
  {
    id: "frozen-hans",
    franchise: "Frozen",
    emoji: "❄️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el príncipe que resulta ser el villano de la primera película?",
    options: ["Hans", "Kristoff", "Weselton", "Erik"],
    correct: 0,
    official: "Hans",
  },

  // --- Enredados ---
  {
    id: "enredados-maximus",
    franchise: "Enredados",
    emoji: "🏰",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el caballo del palacio que persigue a Flynn como si fuera un sabueso?",
    hint: "(Solo el nombre.)",
    accepted: [["Maximus", "Máximus"]],
    official: "Maximus",
  },
  {
    id: "enredados-gothel",
    franchise: "Enredados",
    emoji: "🏰",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la mujer que encierra a Rapunzel en la torre?",
    options: ["Madre Gothel", "Madame Medusa", "Madre Malvina", "Dama Tremaine"],
    correct: 0,
    official: "Madre Gothel",
  },

  // --- Vaiana ---
  {
    id: "vaiana-heihei",
    franchise: "Vaiana",
    emoji: "🌊",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el gallo bobo que se cuela en la barca de Vaiana?",
    hint: "(Solo el nombre.)",
    accepted: [["Heihei", "Hei Hei"]],
    official: "Heihei",
  },
  {
    id: "vaiana-tamatoa",
    franchise: "Vaiana",
    emoji: "🌊",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el cangrejo gigante y presumido que colecciona objetos brillantes?",
    options: ["Tamatoa", "Te Ka", "Matai", "Kakamora"],
    correct: 0,
    official: "Tamatoa",
  },
  {
    id: "vaiana-tala",
    franchise: "Vaiana",
    emoji: "🌊",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la abuela de Vaiana, que baila con las mantarrayas?",
    hint: "(Solo el nombre.)",
    accepted: [["Tala"]],
    official: "Tala",
  },

  // --- Encanto ---
  {
    id: "encanto-mirabel",
    franchise: "Encanto",
    emoji: "🕯️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la protagonista, la única de la familia sin ningún don?",
    hint: "(Solo el nombre.)",
    accepted: [["Mirabel"]],
    official: "Mirabel",
  },
  {
    id: "encanto-madrigal",
    franchise: "Encanto",
    emoji: "🕯️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuál es el apellido de la familia protagonista?",
    hint: "(Solo el apellido.)",
    accepted: [["Madrigal"]],
    official: "Madrigal",
  },
  {
    id: "encanto-luisa",
    franchise: "Encanto",
    emoji: "🕯️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el don de Luisa?",
    options: [
      "Una fuerza descomunal",
      "Hablar con los animales",
      "Curar comiendo",
      "Cambiar de aspecto",
    ],
    correct: 0,
    official: "Una fuerza descomunal",
  },

  // --- Big Hero 6 ---
  {
    id: "bighero-hiro",
    franchise: "Big Hero 6",
    emoji: "🤖",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el niño genio protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Hiro", "Hiro Hamada"]],
    official: "Hiro Hamada",
  },
  {
    id: "bighero-ciudad",
    franchise: "Big Hero 6",
    emoji: "🤖",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la ciudad donde transcurre la película?",
    options: ["San Fransokyo", "Neo Tokio", "Osaka City", "San Kyoto"],
    correct: 0,
    official: "San Fransokyo",
    note: "Es una mezcla de San Francisco y Tokio.",
  },

  // --- Rompe Ralph ---
  {
    id: "ralph-vanellope",
    franchise: "Rompe Ralph",
    emoji: "🕹️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la niña con fallos de programación que conduce un kart?",
    hint: "(Solo el nombre.)",
    accepted: [["Vanellope", "Vanelope"]],
    official: "Vanellope",
  },
  {
    id: "ralph-calhoun",
    franchise: "Rompe Ralph",
    emoji: "🕹️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la sargento del videojuego bélico Hero's Duty?",
    options: ["Calhoun", "Ripley", "Turbo", "Nesquik"],
    correct: 0,
    official: "La sargento Calhoun",
  },

  // --- Tiana y el sapo ---
  {
    id: "tiana-ray",
    franchise: "Tiana y el sapo",
    emoji: "🐸",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la luciérnaga enamorada de una estrella?",
    options: ["Ray", "Louis", "Lawrence", "Stella"],
    correct: 0,
    official: "Ray",
  },
  {
    id: "tiana-facilier",
    franchise: "Tiana y el sapo",
    emoji: "🐸",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el brujo vudú que convierte al príncipe en sapo?",
    options: [
      "El doctor Facilier",
      "El barón Samedi",
      "El doctor Vudú",
      "Mama Odie",
    ],
    correct: 0,
    official: "El doctor Facilier",
    note: "También se le conoce como el Hombre Sombra.",
  },

  // --- El emperador y sus locuras ---
  {
    id: "emperador-pacha",
    franchise: "El emperador y sus locuras",
    emoji: "🦙",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el campesino bonachón que ayuda a Kuzco a volver a palacio?",
    hint: "(Solo el nombre.)",
    accepted: [["Pacha"]],
    official: "Pacha",
  },

  // --- Atlantis ---
  {
    id: "atlantis-kida",
    franchise: "Atlantis",
    emoji: "🔱",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la princesa de Atlantis?",
    options: ["Kida", "Nadia", "Atlana", "Maia"],
    correct: 0,
    official: "Kida",
  },

  // --- El planeta del tesoro ---
  {
    id: "tesoro-silver",
    franchise: "El planeta del tesoro",
    emoji: "🚀",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el cocinero cíborg que hace de mentor y traidor?",
    options: ["John Silver", "Billy Bones", "Amelia", "Scroop"],
    correct: 0,
    official: "John Silver",
  },

  // --- Bolt ---
  {
    id: "bolt-rino",
    franchise: "Bolt",
    emoji: "⚡",
    difficulty: "media",
    format: "describir",
    prompt:
      "Es un hámster que vive dentro de una bola de plástico y es el mayor fan de la serie de Bolt.",
    hint: "(Solo el nombre.)",
    accepted: [["Rino", "Rhino"]],
    official: "Rino",
  },

  // --- Raya ---
  {
    id: "raya-namaari",
    franchise: "Raya y el último dragón",
    emoji: "🐲",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la guerrera de Colmillo que es rival de Raya?",
    options: ["Namaari", "Virana", "Noi", "Tong"],
    correct: 0,
    official: "Namaari",
  },

  // --- Wish ---
  {
    id: "wish-magnifico",
    franchise: "Wish",
    emoji: "⭐",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el rey que guarda los deseos de sus súbditos?",
    options: ["Magnífico", "Amaya", "Sabino", "Valentino"],
    correct: 0,
    official: "El rey Magnífico",
  },

  // --- Hermano Oso ---
  {
    id: "hermanooso-koda",
    franchise: "Hermano Oso",
    emoji: "🐾",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el osezno parlanchín que acompaña al protagonista?",
    options: ["Koda", "Denahi", "Sitka", "Tanana"],
    correct: 0,
    official: "Koda",
  },

  // --- Pato Donald ---
  {
    id: "donald-daisy",
    franchise: "Pato Donald",
    emoji: "🦆",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la novia del Pato Donald?",
    hint: "(Solo el nombre.)",
    accepted: [["Daisy"]],
    official: "Daisy",
  },

  // --- Orden cronológico y relacionar (transversales Disney) ---
  {
    id: "orden-disney-clasicos",
    franchise: "Clásicos Disney",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Disney de la más antigua a la más reciente.",
    items: ["Blancanieves", "Cenicienta", "El libro de la selva", "La Bella y la Bestia"],
    official: "Blancanieves (1937), Cenicienta (1950), El libro de la selva (1967) y La Bella y la Bestia (1991)",
  },
  {
    id: "orden-disney-renacimiento",
    franchise: "Disney años 90 y 2000",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de la más antigua a la más reciente.",
    items: ["La Sirenita", "El Rey León", "Mulán", "Lilo & Stitch"],
    official: "La Sirenita (1989), El Rey León (1994), Mulán (1998) y Lilo & Stitch (2002)",
  },
  {
    id: "orden-disney-moderno",
    franchise: "Disney reciente",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de la más antigua a la más reciente.",
    items: ["Enredados", "Frozen", "Vaiana", "Encanto"],
    official: "Enredados (2010), Frozen (2013), Vaiana (2016) y Encanto (2021)",
  },
  {
    id: "relacionar-mascotas-disney",
    franchise: "Mascotas Disney",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada animal con el personaje al que acompaña.",
    pairs: [
      { left: "Rajah", right: "Jasmín" },
      { left: "Meeko", right: "Pocahontas" },
      { left: "Maximus", right: "Flynn Rider" },
      { left: "Heihei", right: "Vaiana" },
    ],
    official: "Rajah–Jasmín, Meeko–Pocahontas, Maximus–Flynn Rider y Heihei–Vaiana",
  },
  {
    id: "relacionar-villanos-disney",
    franchise: "Villanos Disney",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada villano con su película.",
    pairs: [
      { left: "Hades", right: "Hércules" },
      { left: "Madre Gothel", right: "Enredados" },
      { left: "Shan Yu", right: "Mulán" },
      { left: "Cruella de Vil", right: "101 dálmatas" },
    ],
    official:
      "Hades–Hércules, Madre Gothel–Enredados, Shan Yu–Mulán y Cruella de Vil–101 dálmatas",
  },
];
