import type { Question } from "../types";

/**
 * Clásicos Disney y Walt Disney Animation Studios.
 *
 * Convenciones del banco (ver también lib/preguntas.ts):
 * - Títulos y nombres del doblaje de España.
 * - `accepted` es una lista de huecos obligatorios; cada hueco lleva variantes.
 *   El corrector ya perdona tildes, mayúsculas y erratas, así que aquí solo se
 *   ponen alternativas de verdad (apodos, apellido suelto, sinónimos).
 * - Las preguntas de dificultad "dificil" van siempre en formato "multiple".
 */
export const DISNEY: Question[] = [
  // --- El Rey León ---
  {
    id: "reyleon-pumba",
    franchise: "El Rey León",
    emoji: "🦁",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el jabalí verrugoso que acompaña a Timón?",
    hint: "(Solo el nombre.)",
    accepted: [["Pumba", "Pumbaa"]],
    official: "Pumba",
  },
  {
    id: "reyleon-rafiki",
    franchise: "El Rey León",
    emoji: "🦁",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el mandril chamán que presenta a Simba en la Roca del Rey?",
    options: ["Rafiki", "Zazú", "Banzai", "Shenzi"],
    correct: 0,
    official: "Rafiki",
  },
  {
    id: "reyleon-zazu",
    franchise: "El Rey León",
    emoji: "🦁",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es un cálao rojo, mayordomo del rey, siempre nervioso y con aires de secretario.",
    hint: "(Solo el nombre.)",
    accepted: [["Zazú", "Zazu"]],
    official: "Zazú",
  },
  {
    id: "reyleon-hakuna",
    franchise: "El Rey León",
    emoji: "🦁",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el lema de Timón y Pumba: «Hakuna ___».",
    accepted: [["Matata"]],
    official: "Hakuna Matata",
    note: "Significa «vive y sé feliz» en suajili.",
  },

  // --- La Sirenita ---
  {
    id: "sirenita-voz",
    franchise: "La Sirenita",
    emoji: "🧜",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué le entrega Ariel a Úrsula a cambio de tener piernas?",
    hint: "(Una palabra.)",
    accepted: [["voz", "su voz", "la voz"]],
    official: "Su voz",
  },
  {
    id: "sirenita-triton",
    franchise: "La Sirenita",
    emoji: "🧜",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el padre de Ariel, rey del mar?",
    hint: "(Solo el nombre.)",
    accepted: [["Tritón", "Rey Tritón"]],
    official: "Tritón",
  },
  {
    id: "sirenita-morenas",
    franchise: "La Sirenita",
    emoji: "🧜",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman las dos morenas que sirven a Úrsula?",
    options: [
      "Flotsam y Jetsam",
      "Morgana y Undina",
      "Scylla y Caribdis",
      "Kelp y Coral",
    ],
    correct: 0,
    official: "Flotsam y Jetsam",
  },

  // --- Aladdín ---
  {
    id: "aladdin-rajah",
    franchise: "Aladdín",
    emoji: "🧞",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la tigresa de Jasmín?",
    hint: "(Solo el nombre.)",
    accepted: [["Rajah", "Raja"]],
    official: "Rajah",
  },
  {
    id: "aladdin-mundo",
    franchise: "Aladdín",
    emoji: "🧞",
    difficulty: "facil",
    format: "completar",
    prompt:
      "Completa el título de la canción que cantan Aladdín y Jasmín sobre la alfombra: «Un mundo ___».",
    accepted: [["ideal"]],
    official: "Un mundo ideal",
  },
  {
    id: "aladdin-cueva",
    franchise: "Aladdín",
    emoji: "🧞",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el lugar donde Aladdín encuentra la lámpara?",
    options: [
      "La Cueva de las Maravillas",
      "La Gruta de los Deseos",
      "El Templo de Agrabah",
      "La Caverna Dorada",
    ],
    correct: 0,
    official: "La Cueva de las Maravillas",
  },

  // --- La Bella y la Bestia ---
  {
    id: "bella-lumiere",
    franchise: "La Bella y la Bestia",
    emoji: "🌹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el candelabro del castillo de la Bestia?",
    hint: "(Solo el nombre.)",
    accepted: [["Lumière", "Lumiere"]],
    official: "Lumière",
  },
  {
    id: "bella-gaston",
    franchise: "La Bella y la Bestia",
    emoji: "🌹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el cazador presumido que pretende casarse con Bella?",
    hint: "(Solo el nombre.)",
    accepted: [["Gastón", "Gaston"]],
    official: "Gastón",
  },
  {
    id: "bella-dindon",
    franchise: "La Bella y la Bestia",
    emoji: "🌹",
    difficulty: "dificil",
    format: "multiple",
    prompt:
      "¿Cómo se llama en el doblaje español el mayordomo convertido en reloj de sobremesa?",
    options: ["Din-Don", "Tic-Tac", "Cogsworth", "Campanón"],
    correct: 0,
    official: "Din-Don",
    note: "En la versión original se llama Cogsworth.",
  },

  // --- Blancanieves ---
  {
    id: "blancanieves-enanito",
    franchise: "Blancanieves",
    emoji: "🍎",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál de estos NO es uno de los siete enanitos?",
    options: ["Risitas", "Mudito", "Gruñón", "Dormilón"],
    correct: 0,
    official: "Risitas",
  },
  {
    id: "blancanieves-espejo",
    franchise: "Blancanieves",
    emoji: "🍎",
    difficulty: "facil",
    format: "vf",
    prompt: "La Reina Malvada consulta a un espejo mágico para saber quién es la más bella.",
    correct: true,
    official: "Verdadero",
  },

  // --- Cenicienta ---
  {
    id: "cenicienta-lucifer",
    franchise: "Cenicienta",
    emoji: "👠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el gato de la madrastra de Cenicienta?",
    hint: "(Solo el nombre.)",
    accepted: [["Lucifer"]],
    official: "Lucifer",
  },
  {
    id: "cenicienta-hora",
    franchise: "Cenicienta",
    emoji: "👠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿A qué hora se rompe el hechizo del Hada Madrina?",
    hint: "(La hora.)",
    accepted: [["medianoche", "las doce", "12", "doce de la noche"]],
    official: "A medianoche",
  },

  // --- Peter Pan ---
  {
    id: "peterpan-campanilla",
    franchise: "Peter Pan",
    emoji: "🧚",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el hada que acompaña a Peter Pan?",
    hint: "(Solo el nombre.)",
    accepted: [["Campanilla"]],
    official: "Campanilla",
  },
  {
    id: "peterpan-isla",
    franchise: "Peter Pan",
    emoji: "🧚",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la isla donde nunca se crece?",
    accepted: [["Nunca Jamás", "País de Nunca Jamás", "Nunca Nunca"]],
    official: "El País de Nunca Jamás",
  },
  {
    id: "peterpan-barco",
    franchise: "Peter Pan",
    emoji: "🧚",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el barco pirata del capitán Garfio?",
    options: ["Jolly Roger", "Perla Negra", "Calavera", "Nautilus"],
    correct: 0,
    official: "El Jolly Roger",
  },

  // --- El libro de la selva ---
  {
    id: "selva-baloo",
    franchise: "El libro de la selva",
    emoji: "🐻",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el oso despreocupado que enseña a Mowgli a vivir sin agobios?",
    hint: "(Solo el nombre.)",
    accepted: [["Baloo"]],
    official: "Baloo",
  },
  {
    id: "selva-kaa",
    franchise: "El libro de la selva",
    emoji: "🐻",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la serpiente pitón que hipnotiza a Mowgli?",
    hint: "(Solo el nombre.)",
    accepted: [["Kaa"]],
    official: "Kaa",
  },
  {
    id: "selva-sherekhan",
    franchise: "El libro de la selva",
    emoji: "🐻",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el tigre de Bengala al que todos temen?",
    hint: "(Solo el nombre.)",
    accepted: [["Shere Khan", "Shere-Khan", "Shir Khan"]],
    official: "Shere Khan",
  },
  {
    id: "selva-louie",
    franchise: "El libro de la selva",
    emoji: "🐻",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el orangután que quiere aprender a hacer fuego?",
    options: ["Rey Louie", "Rey Akela", "Rey Hathi", "Rey Bandar"],
    correct: 0,
    official: "El Rey Louie",
  },

  // --- Pinocho ---
  {
    id: "pinocho-grillo",
    franchise: "Pinocho",
    emoji: "🪵",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el grillo que hace de conciencia de Pinocho?",
    hint: "(Solo el nombre.)",
    accepted: [["Pepito Grillo", "Pepito"]],
    official: "Pepito Grillo",
  },
  {
    id: "pinocho-geppetto",
    franchise: "Pinocho",
    emoji: "🪵",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el carpintero que talla a Pinocho?",
    hint: "(Solo el nombre.)",
    accepted: [["Geppetto", "Gepetto"]],
    official: "Geppetto",
  },
  {
    id: "pinocho-ballena",
    franchise: "Pinocho",
    emoji: "🪵",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la enorme ballena que se traga a Geppetto?",
    options: ["Monstro", "Leviatán", "Cetus", "Bruto"],
    correct: 0,
    official: "Monstro",
  },

  // --- Dumbo ---
  {
    id: "dumbo-pluma",
    franchise: "Dumbo",
    emoji: "🐘",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué objeto cree Dumbo que le da el poder de volar?",
    hint: "(Una palabra.)",
    accepted: [["pluma", "una pluma", "pluma mágica"]],
    official: "Una pluma",
    note: "En realidad vuela solo, la pluma es un truco de confianza.",
  },

  // --- 101 dálmatas ---
  {
    id: "dalmatas-cruella",
    franchise: "101 dálmatas",
    emoji: "🐕",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la villana obsesionada con hacerse un abrigo de piel de cachorro?",
    accepted: [["Cruella de Vil", "Cruella"]],
    official: "Cruella de Vil",
  },
  {
    id: "dalmatas-padres",
    franchise: "101 dálmatas",
    emoji: "🐕",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llaman los dos dálmatas adultos, padres de los cachorros?",
    options: [
      "Pongo y Perdita",
      "Pongo y Peggy",
      "Danny y Perdita",
      "Rolly y Penny",
    ],
    correct: 0,
    official: "Pongo y Perdita",
  },

  // --- Los Aristogatos ---
  {
    id: "aristogatos-gatitos",
    franchise: "Los Aristogatos",
    emoji: "🎹",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman los tres gatitos de Duquesa?",
    options: [
      "Marie, Berlioz y Toulouse",
      "Marie, Chopin y Monet",
      "Mimi, Berlioz y Renoir",
      "Marie, Bizet y Degas",
    ],
    correct: 0,
    official: "Marie, Berlioz y Toulouse",
  },

  // --- Hércules ---
  {
    id: "hercules-hades",
    franchise: "Hércules",
    emoji: "⚡",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el dios del inframundo que hace de villano?",
    hint: "(Solo el nombre.)",
    accepted: [["Hades"]],
    official: "Hades",
  },
  {
    id: "hercules-secuaces",
    franchise: "Hércules",
    emoji: "⚡",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llaman los dos demonios torpes que sirven a Hades?",
    options: [
      "Pena y Pánico",
      "Furia y Rabia",
      "Miedo y Duda",
      "Caos y Ruina",
    ],
    correct: 0,
    official: "Pena y Pánico",
  },
  {
    id: "hercules-meg",
    franchise: "Hércules",
    emoji: "⚡",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la joven que trabaja para Hades y acaba enamorando a Hércules?",
    hint: "(Solo el nombre.)",
    accepted: [["Megara", "Meg"]],
    official: "Megara",
  },

  // --- Mulán ---
  {
    id: "mulan-shang",
    franchise: "Mulán",
    emoji: "🐉",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el capitán que instruye a los reclutas del ejército chino?",
    hint: "(Solo el nombre.)",
    accepted: [["Li Shang", "Shang"]],
    official: "Li Shang",
  },
  {
    id: "mulan-shanyu",
    franchise: "Mulán",
    emoji: "🐉",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el líder de los hunos que invade China?",
    options: ["Shan Yu", "Chi Fu", "Yao", "Ling"],
    correct: 0,
    official: "Shan Yu",
  },

  // --- Tarzán ---
  {
    id: "tarzan-jane",
    franchise: "Tarzán",
    emoji: "🌴",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la joven inglesa de la que se enamora Tarzán?",
    hint: "(Solo el nombre.)",
    accepted: [["Jane", "Jane Porter"]],
    official: "Jane",
  },
  {
    id: "tarzan-tantor",
    franchise: "Tarzán",
    emoji: "🌴",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el elefante miedoso amigo de Tarzán?",
    options: ["Tantor", "Hathi", "Dumbo", "Terk"],
    correct: 0,
    official: "Tantor",
  },

  // --- El jorobado de Notre Dame ---
  {
    id: "jorobado-quasimodo",
    franchise: "El jorobado de Notre Dame",
    emoji: "🔔",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el campanero protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Quasimodo", "Cuasimodo"]],
    official: "Quasimodo",
  },
  {
    id: "jorobado-frollo",
    franchise: "El jorobado de Notre Dame",
    emoji: "🔔",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el juez que tiene encerrado a Quasimodo en el campanario?",
    options: ["Claude Frollo", "Phoebus", "Clopin", "Gastón"],
    correct: 0,
    official: "Claude Frollo",
  },

  // --- Pocahontas ---
  {
    id: "pocahontas-meeko",
    franchise: "Pocahontas",
    emoji: "🍃",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el mapache glotón que acompaña a Pocahontas?",
    hint: "(Solo el nombre.)",
    accepted: [["Meeko", "Miko"]],
    official: "Meeko",
  },
  {
    id: "pocahontas-smith",
    franchise: "Pocahontas",
    emoji: "🍃",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el colono inglés del que se enamora Pocahontas?",
    accepted: [["John Smith", "Smith"]],
    official: "John Smith",
  },

  // --- Lilo & Stitch ---
  {
    id: "stitch-jumba",
    franchise: "Lilo & Stitch",
    emoji: "🌺",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el científico alienígena que creó a Stitch?",
    hint: "(Solo el nombre.)",
    accepted: [["Jumba", "Jumba Jookiba"]],
    official: "Jumba",
  },
  {
    id: "stitch-pleakley",
    franchise: "Lilo & Stitch",
    emoji: "🌺",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el alienígena de un solo ojo, experto en la Tierra, que acompaña a Jumba?",
    options: ["Pleakley", "Cobra Bubbles", "Gantu", "Jacques"],
    correct: 0,
    official: "Pleakley",
  },

  // --- Zootrópolis ---
  {
    id: "zootropolis-flash",
    franchise: "Zootrópolis",
    emoji: "🦊",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Trabaja en la oficina de tráfico, es un perezoso y tarda una eternidad en terminar cada frase.",
    hint: "(Solo el nombre.)",
    accepted: [["Flash"]],
    official: "Flash",
  },
  {
    id: "zootropolis-mrbig",
    franchise: "Zootrópolis",
    emoji: "🦊",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es Mr. Big, el temido jefe del crimen de Tundratown?",
    options: ["Una musaraña", "Un oso polar", "Una comadreja", "Un topo"],
    correct: 0,
    official: "Una musaraña",
  },

  // --- Frozen ---
  {
    id: "frozen-olaf",
    franchise: "Frozen",
    emoji: "❄️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el muñeco de nieve que sueña con el verano?",
    hint: "(Solo el nombre.)",
    accepted: [["Olaf"]],
    official: "Olaf",
  },
  {
    id: "frozen-arendelle",
    franchise: "Frozen",
    emoji: "❄️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el reino de Elsa y Anna?",
    hint: "(Solo el nombre.)",
    accepted: [["Arendelle"]],
    official: "Arendelle",
  },
  {
    id: "frozen-hans",
    franchise: "Frozen",
    emoji: "❄️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el príncipe que resulta ser el villano de la primera película?",
    options: ["Hans", "Kristoff", "Weselton", "Erik"],
    correct: 0,
    official: "Hans",
  },

  // --- Enredados ---
  {
    id: "enredados-maximus",
    franchise: "Enredados",
    emoji: "🏰",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el caballo del palacio que persigue a Flynn como si fuera un sabueso?",
    hint: "(Solo el nombre.)",
    accepted: [["Maximus", "Máximus"]],
    official: "Maximus",
  },
  {
    id: "enredados-gothel",
    franchise: "Enredados",
    emoji: "🏰",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la mujer que encierra a Rapunzel en la torre?",
    options: ["Madre Gothel", "Madame Medusa", "Madre Malvina", "Dama Tremaine"],
    correct: 0,
    official: "Madre Gothel",
  },

  // --- Vaiana ---
  {
    id: "vaiana-heihei",
    franchise: "Vaiana",
    emoji: "🌊",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el gallo bobo que se cuela en la barca de Vaiana?",
    hint: "(Solo el nombre.)",
    accepted: [["Heihei", "Hei Hei"]],
    official: "Heihei",
  },
  {
    id: "vaiana-tamatoa",
    franchise: "Vaiana",
    emoji: "🌊",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el cangrejo gigante y presumido que colecciona objetos brillantes?",
    options: ["Tamatoa", "Te Ka", "Matai", "Kakamora"],
    correct: 0,
    official: "Tamatoa",
  },
  {
    id: "vaiana-tala",
    franchise: "Vaiana",
    emoji: "🌊",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la abuela de Vaiana, que baila con las mantarrayas?",
    hint: "(Solo el nombre.)",
    accepted: [["Tala"]],
    official: "Tala",
  },

  // --- Encanto ---
  {
    id: "encanto-mirabel",
    franchise: "Encanto",
    emoji: "🕯️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la protagonista, la única de la familia sin ningún don?",
    hint: "(Solo el nombre.)",
    accepted: [["Mirabel"]],
    official: "Mirabel",
  },
  {
    id: "encanto-madrigal",
    franchise: "Encanto",
    emoji: "🕯️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuál es el apellido de la familia protagonista?",
    hint: "(Solo el apellido.)",
    accepted: [["Madrigal"]],
    official: "Madrigal",
  },
  {
    id: "encanto-luisa",
    franchise: "Encanto",
    emoji: "🕯️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el don de Luisa?",
    options: [
      "Una fuerza descomunal",
      "Hablar con los animales",
      "Curar comiendo",
      "Cambiar de aspecto",
    ],
    correct: 0,
    official: "Una fuerza descomunal",
  },

  // --- Big Hero 6 ---
  {
    id: "bighero-hiro",
    franchise: "Big Hero 6",
    emoji: "🤖",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el niño genio protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Hiro", "Hiro Hamada"]],
    official: "Hiro Hamada",
  },
  {
    id: "bighero-ciudad",
    franchise: "Big Hero 6",
    emoji: "🤖",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la ciudad donde transcurre la película?",
    options: ["San Fransokyo", "Neo Tokio", "Osaka City", "San Kyoto"],
    correct: 0,
    official: "San Fransokyo",
    note: "Es una mezcla de San Francisco y Tokio.",
  },

  // --- Rompe Ralph ---
  {
    id: "ralph-vanellope",
    franchise: "Rompe Ralph",
    emoji: "🕹️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la niña con fallos de programación que conduce un kart?",
    hint: "(Solo el nombre.)",
    accepted: [["Vanellope", "Vanelope"]],
    official: "Vanellope",
  },
  {
    id: "ralph-calhoun",
    franchise: "Rompe Ralph",
    emoji: "🕹️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la sargento del videojuego bélico Hero's Duty?",
    options: ["Calhoun", "Ripley", "Turbo", "Nesquik"],
    correct: 0,
    official: "La sargento Calhoun",
  },

  // --- Tiana y el sapo ---
  {
    id: "tiana-ray",
    franchise: "Tiana y el sapo",
    emoji: "🐸",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la luciérnaga enamorada de una estrella?",
    options: ["Ray", "Louis", "Lawrence", "Stella"],
    correct: 0,
    official: "Ray",
  },
  {
    id: "tiana-facilier",
    franchise: "Tiana y el sapo",
    emoji: "🐸",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el brujo vudú que convierte al príncipe en sapo?",
    options: [
      "El doctor Facilier",
      "El barón Samedi",
      "El doctor Vudú",
      "Mama Odie",
    ],
    correct: 0,
    official: "El doctor Facilier",
    note: "También se le conoce como el Hombre Sombra.",
  },

  // --- El emperador y sus locuras ---
  {
    id: "emperador-pacha",
    franchise: "El emperador y sus locuras",
    emoji: "🦙",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el campesino bonachón que ayuda a Kuzco a volver a palacio?",
    hint: "(Solo el nombre.)",
    accepted: [["Pacha"]],
    official: "Pacha",
  },

  // --- Atlantis ---
  {
    id: "atlantis-kida",
    franchise: "Atlantis",
    emoji: "🔱",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la princesa de Atlantis?",
    options: ["Kida", "Nadia", "Atlana", "Maia"],
    correct: 0,
    official: "Kida",
  },

  // --- El planeta del tesoro ---
  {
    id: "tesoro-silver",
    franchise: "El planeta del tesoro",
    emoji: "🚀",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el cocinero cíborg que hace de mentor y traidor?",
    options: ["John Silver", "Billy Bones", "Amelia", "Scroop"],
    correct: 0,
    official: "John Silver",
  },

  // --- Bolt ---
  {
    id: "bolt-rino",
    franchise: "Bolt",
    emoji: "⚡",
    difficulty: "media",
    format: "describir",
    prompt:
      "Es un hámster que vive dentro de una bola de plástico y es el mayor fan de la serie de Bolt.",
    hint: "(Solo el nombre.)",
    accepted: [["Rino", "Rhino"]],
    official: "Rino",
  },

  // --- Raya ---
  {
    id: "raya-namaari",
    franchise: "Raya y el último dragón",
    emoji: "🐲",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la guerrera de Colmillo que es rival de Raya?",
    options: ["Namaari", "Virana", "Noi", "Tong"],
    correct: 0,
    official: "Namaari",
  },

  // --- Wish ---
  {
    id: "wish-magnifico",
    franchise: "Wish",
    emoji: "⭐",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el rey que guarda los deseos de sus súbditos?",
    options: ["Magnífico", "Amaya", "Sabino", "Valentino"],
    correct: 0,
    official: "El rey Magnífico",
  },

  // --- Hermano Oso ---
  {
    id: "hermanooso-koda",
    franchise: "Hermano Oso",
    emoji: "🐾",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el osezno parlanchín que acompaña al protagonista?",
    options: ["Koda", "Denahi", "Sitka", "Tanana"],
    correct: 0,
    official: "Koda",
  },

  // --- Pato Donald ---
  {
    id: "donald-daisy",
    franchise: "Pato Donald",
    emoji: "🦆",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la novia del Pato Donald?",
    hint: "(Solo el nombre.)",
    accepted: [["Daisy"]],
    official: "Daisy",
  },

  // --- Orden cronológico y relacionar (transversales Disney) ---
  {
    id: "orden-disney-clasicos",
    franchise: "Clásicos Disney",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Disney de la más antigua a la más reciente.",
    items: ["Blancanieves", "Cenicienta", "El libro de la selva", "La Bella y la Bestia"],
    official: "Blancanieves (1937), Cenicienta (1950), El libro de la selva (1967) y La Bella y la Bestia (1991)",
  },
  {
    id: "orden-disney-renacimiento",
    franchise: "Disney años 90 y 2000",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de la más antigua a la más reciente.",
    items: ["La Sirenita", "El Rey León", "Mulán", "Lilo & Stitch"],
    official: "La Sirenita (1989), El Rey León (1994), Mulán (1998) y Lilo & Stitch (2002)",
  },
  {
    id: "orden-disney-moderno",
    franchise: "Disney reciente",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de la más antigua a la más reciente.",
    items: ["Enredados", "Frozen", "Vaiana", "Encanto"],
    official: "Enredados (2010), Frozen (2013), Vaiana (2016) y Encanto (2021)",
  },
  {
    id: "relacionar-mascotas-disney",
    franchise: "Mascotas Disney",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada animal con el personaje al que acompaña.",
    pairs: [
      { left: "Rajah", right: "Jasmín" },
      { left: "Meeko", right: "Pocahontas" },
      { left: "Maximus", right: "Flynn Rider" },
      { left: "Heihei", right: "Vaiana" },
    ],
    official: "Rajah–Jasmín, Meeko–Pocahontas, Maximus–Flynn Rider y Heihei–Vaiana",
  },
  {
    id: "relacionar-villanos-disney",
    franchise: "Villanos Disney",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada villano con su película.",
    pairs: [
      { left: "Hades", right: "Hércules" },
      { left: "Madre Gothel", right: "Enredados" },
      { left: "Shan Yu", right: "Mulán" },
      { left: "Cruella de Vil", right: "101 dálmatas" },
    ],
    official:
      "Hades–Hércules, Madre Gothel–Enredados, Shan Yu–Mulán y Cruella de Vil–101 dálmatas",
  },

  // --- La Bella Durmiente ---
  {
    id: "bellador-aurora",
    franchise: "La Bella Durmiente",
    emoji: "🌹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la princesa que duerme cien años tras pincharse con una rueca?",
    hint: "(Solo el nombre.)",
    accepted: [["Aurora", "Rosa"]],
    official: "Aurora",
    note: "Las tres hadas la crían en el bosque con el nombre de Rosa.",
  },
  {
    id: "bellador-hadas",
    franchise: "La Bella Durmiente",
    emoji: "🌹",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llaman las tres hadas madrinas de Aurora?",
    options: [
      "Flora, Fauna y Primavera",
      "Flora, Fauna y Alegría",
      "Aurora, Fauna y Primavera",
      "Flora, Selva y Primavera",
    ],
    correct: 0,
    official: "Flora, Fauna y Primavera",
  },
  {
    id: "bellador-malefica",
    franchise: "La Bella Durmiente",
    emoji: "🌹",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Villana de cuernos negros y capa morada, se ofende por no ser invitada a un bautizo y acaba convertida en dragón.",
    hint: "(Solo el nombre.)",
    accepted: [["Maléfica"]],
    official: "Maléfica",
  },
  {
    id: "bellador-vestido",
    franchise: "La Bella Durmiente",
    emoji: "🌹",
    difficulty: "media",
    format: "vf",
    prompt: "Flora y Primavera se pelean por si el vestido de Aurora debe ser rosa o azul.",
    correct: true,
    official: "Verdadero",
    note: "El vestido cambia de color hasta el último plano de la película.",
  },

  // --- Bambi ---
  {
    id: "bambi-tambor",
    franchise: "Bambi",
    emoji: "🦌",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el conejo amigo de Bambi que golpea el suelo con la pata?",
    hint: "(Solo el nombre.)",
    accepted: [["Tambor"]],
    official: "Tambor",
  },
  {
    id: "bambi-flor",
    franchise: "Bambi",
    emoji: "🦌",
    difficulty: "media",
    format: "describir",
    prompt:
      "Es una mofeta tímida que se sonroja por todo y se llama como la planta con la que la confunden.",
    hint: "(Solo el nombre.)",
    accepted: [["Flor"]],
    official: "Flor",
  },
  {
    id: "bambi-faline",
    franchise: "Bambi",
    emoji: "🦌",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la cervatilla de la que se enamora Bambi?",
    options: ["Faline", "Falina", "Fauna", "Feline"],
    correct: 0,
    official: "Faline",
  },

  // --- Alicia en el País de las Maravillas ---
  {
    id: "alicia-gato",
    franchise: "Alicia en el País de las Maravillas",
    emoji: "🐇",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Gato a rayas rosas y moradas que aparece y desaparece dejando su sonrisa flotando en el aire.",
    hint: "(El nombre o de dónde es.)",
    accepted: [["Cheshire", "Gato de Cheshire", "Gato Risón"]],
    official: "El Gato de Cheshire",
  },
  {
    id: "alicia-conejo",
    franchise: "Alicia en el País de las Maravillas",
    emoji: "🐇",
    difficulty: "facil",
    format: "completar",
    prompt:
      "Completa lo que va repitiendo el Conejo Blanco mientras mira su reloj: «Llego tarde, llego ___».",
    accepted: [["tarde"]],
    official: "Llego tarde, llego tarde",
  },
  {
    id: "alicia-reina",
    franchise: "Alicia en el País de las Maravillas",
    emoji: "🐇",
    difficulty: "media",
    format: "completar",
    prompt: "Completa la sentencia favorita de la Reina de Corazones: «¡Que le corten la ___!».",
    accepted: [["cabeza"]],
    official: "¡Que le corten la cabeza!",
  },
  {
    id: "alicia-oruga",
    franchise: "Alicia en el País de las Maravillas",
    emoji: "🐇",
    difficulty: "media",
    format: "vf",
    prompt: "La Oruga Azul fuma en narguile y habla formando letras con el humo.",
    correct: true,
    official: "Verdadero",
  },

  // --- Robin Hood ---
  {
    id: "robinhood-animal",
    franchise: "Robin Hood",
    emoji: "🏹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué animal es Robin Hood en la película de Disney?",
    hint: "(El animal.)",
    accepted: [["zorro"]],
    official: "Un zorro",
  },
  {
    id: "robinhood-juan",
    franchise: "Robin Hood",
    emoji: "🏹",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es el Príncipe Juan, el villano que se chupa el dedo?",
    options: ["Un león", "Un tigre", "Un lobo", "Un oso"],
    correct: 0,
    official: "Un león",
  },
  {
    id: "robinhood-littlejohn",
    franchise: "Robin Hood",
    emoji: "🏹",
    difficulty: "media",
    format: "describir",
    prompt: "Oso grandote y bonachón, el mejor amigo de Robin y su compañero de fechorías.",
    hint: "(Solo el nombre.)",
    accepted: [["Little John", "Pequeño Juan"]],
    official: "Little John",
  },

  // --- Los Aristogatos ---
  {
    id: "aristogatos-duquesa",
    franchise: "Los Aristogatos",
    emoji: "🎹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la elegante gata blanca madre de los tres gatitos?",
    hint: "(Solo el nombre.)",
    accepted: [["Duquesa"]],
    official: "Duquesa",
  },
  {
    id: "aristogatos-omalley",
    franchise: "Los Aristogatos",
    emoji: "🎹",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el gato callejero que ayuda a Duquesa y a sus gatitos a volver a casa?",
    options: ["Thomas O'Malley", "Scat Cat", "Romeo", "Napoleón"],
    correct: 0,
    official: "Thomas O'Malley",
  },
  {
    id: "aristogatos-edgar",
    franchise: "Los Aristogatos",
    emoji: "🎹",
    difficulty: "media",
    format: "vf",
    prompt:
      "Quien abandona a los gatos en el campo es el mayordomo, que quiere quedarse la herencia.",
    correct: true,
    official: "Verdadero",
    note: "El mayordomo se llama Edgar.",
  },

  // --- Dumbo ---
  {
    id: "dumbo-timothy",
    franchise: "Dumbo",
    emoji: "🐘",
    difficulty: "media",
    format: "corta",
    prompt: "¿Qué animal es Timothy, el amigo que convence a Dumbo de que puede volar?",
    hint: "(El animal.)",
    accepted: [["ratón"]],
    official: "Un ratón",
  },
  {
    id: "dumbo-madre",
    franchise: "Dumbo",
    emoji: "🐘",
    difficulty: "facil",
    format: "vf",
    prompt:
      "A la madre de Dumbo la encierran por revolverse contra unos niños que se burlaban de las orejas de su cría.",
    correct: true,
    official: "Verdadero",
    note: "La encierran como «elefante loco», y de ahí sale la escena de la nana entre rejas.",
  },

  // --- Winnie the Pooh ---
  {
    id: "pooh-igor",
    franchise: "Winnie the Pooh",
    emoji: "🍯",
    difficulty: "facil",
    format: "describir",
    prompt: "Burro gris y melancólico al que se le cae la cola y que nunca espera nada bueno.",
    hint: "(Solo el nombre.)",
    accepted: [["Ígor"]],
    official: "Ígor",
  },
  {
    id: "pooh-miel",
    franchise: "Winnie the Pooh",
    emoji: "🍯",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué es lo que más le gusta comer a Winnie the Pooh?",
    hint: "(Una palabra.)",
    accepted: [["miel"]],
    official: "La miel",
  },
  {
    id: "pooh-tigger",
    franchise: "Winnie the Pooh",
    emoji: "🍯",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es Tigger, el amigo naranja que se mueve dando botes?",
    options: ["Un tigre", "Un gato", "Un canguro", "Un leopardo"],
    correct: 0,
    official: "Un tigre",
  },

  // --- Mickey Mouse ---
  {
    id: "mickey-perro",
    franchise: "Mickey Mouse",
    emoji: "🐭",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el perro de Mickey Mouse?",
    hint: "(Solo el nombre.)",
    accepted: [["Pluto"]],
    official: "Pluto",
  },
  {
    id: "mickey-aprendiz",
    franchise: "Mickey Mouse",
    emoji: "🐭",
    difficulty: "media",
    format: "describir",
    prompt:
      "En este episodio de Fantasía, Mickey se pone el sombrero de su maestro y encanta a una escoba para que acarree el agua por él.",
    hint: "(El título del episodio.)",
    accepted: [["El aprendiz de brujo", "aprendiz de brujo"]],
    official: "El aprendiz de brujo",
  },
  {
    id: "mickey-goofy",
    franchise: "Mickey Mouse",
    emoji: "🐭",
    difficulty: "media",
    format: "vf",
    prompt: "Pluto y Goofy son los dos perros de la pandilla, pero solo uno de ellos habla.",
    correct: true,
    official: "Verdadero",
    note: "Goofy habla y anda de pie; Pluto se comporta como un perro.",
  },

  // --- Pato Donald ---
  {
    id: "donald-sobrinos",
    franchise: "Pato Donald",
    emoji: "🦆",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llaman en España los tres sobrinos del Pato Donald?",
    options: [
      "Juanito, Jorgito y Jaimito",
      "Juanito, Jorgito y Jacobito",
      "Hugo, Paco y Luis",
      "Juanito, Pepito y Jaimito",
    ],
    correct: 0,
    official: "Juanito, Jorgito y Jaimito",
  },
  {
    id: "donald-tio",
    franchise: "Pato Donald",
    emoji: "🦆",
    difficulty: "facil",
    format: "describir",
    prompt: "Pato riquísimo con chistera y monóculo que se baña en su depósito lleno de monedas.",
    hint: "(Solo el nombre.)",
    accepted: [["Tío Gilito", "Gilito"]],
    official: "El Tío Gilito",
  },

  // --- Hermano Oso ---
  {
    id: "hermanooso-kenai",
    franchise: "Hermano Oso",
    emoji: "🐻",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el joven al que los espíritus convierten en oso?",
    hint: "(Solo el nombre.)",
    accepted: [["Kenai"]],
    official: "Kenai",
  },
  {
    id: "hermanooso-castigo",
    franchise: "Hermano Oso",
    emoji: "🐻",
    difficulty: "media",
    format: "vf",
    prompt: "Kenai se convierte en oso como castigo de los espíritus por haber matado a uno.",
    correct: true,
    official: "Verdadero",
  },

  // --- El emperador y sus locuras ---
  {
    id: "kuzco-animal",
    franchise: "El emperador y sus locuras",
    emoji: "🦙",
    difficulty: "facil",
    format: "corta",
    prompt: "¿En qué animal convierten al emperador Kuzco?",
    hint: "(El animal.)",
    accepted: [["llama"]],
    official: "Una llama",
  },
  {
    id: "kuzco-yzma",
    franchise: "El emperador y sus locuras",
    emoji: "🦙",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la consejera que intenta destronar a Kuzco?",
    options: ["Yzma", "Izma", "Ysma", "Yzmara"],
    correct: 0,
    official: "Yzma",
    note: "Su forzudo y despistado ayudante es Kronk.",
  },

  // --- Atlantis ---
  {
    id: "atlantis-milo",
    franchise: "Atlantis",
    emoji: "🌊",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el lingüista con gafas que guía la expedición a Atlantis?",
    hint: "(El nombre basta.)",
    accepted: [["Milo", "Milo Thatch", "Thatch"]],
    official: "Milo Thatch",
  },
  {
    id: "atlantis-rourke",
    franchise: "Atlantis",
    emoji: "🌊",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el comandante que dirige la expedición y acaba traicionando a Milo?",
    options: ["Rourke", "Helga", "Vinny", "Preston Whitmore"],
    correct: 0,
    official: "El comandante Rourke",
  },

  // --- El planeta del tesoro ---
  {
    id: "planetatesoro-jim",
    franchise: "El planeta del tesoro",
    emoji: "🪐",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el joven protagonista que embarca en busca del tesoro de Flint?",
    hint: "(El nombre basta.)",
    accepted: [["Jim", "Jim Hawkins", "Hawkins"]],
    official: "Jim Hawkins",
  },
  {
    id: "planetatesoro-morph",
    franchise: "El planeta del tesoro",
    emoji: "🪐",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la masa rosa que cambia de forma e imita a todo el mundo?",
    options: ["Morph", "Blob", "Puff", "Mimic"],
    correct: 0,
    official: "Morph",
  },

  // --- Los Rescatadores ---
  {
    id: "rescatadores-ratones",
    franchise: "Los Rescatadores",
    emoji: "🐁",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman los dos ratones de la Sociedad de Rescate?",
    options: [
      "Bernardo y Bianca",
      "Bernardo y Blanca",
      "Bernabé y Bianca",
      "Bertrand y Bianca",
    ],
    correct: 0,
    official: "Bernardo y Bianca",
  },

  // --- Tod y Toby ---
  {
    id: "todytoby-animales",
    franchise: "Tod y Toby",
    emoji: "🦊",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué son Tod y Toby, los dos amigos a los que la vida acaba enfrentando?",
    options: [
      "Un zorro y un perro de caza",
      "Un lobo y un perro pastor",
      "Un zorro y un tejón",
      "Un perro y un gato",
    ],
    correct: 0,
    official: "Un zorro y un perro de caza",
  },

  // --- Cronologías y relaciones de Disney ---
  {
    id: "orden-disney-clasicos-40",
    franchise: "Clásicos Disney",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estos clásicos de Disney de la más antigua a la más reciente.",
    items: ["Blancanieves", "Pinocho", "Dumbo", "Bambi"],
    official: "Blancanieves (1937), Pinocho (1940), Dumbo (1941) y Bambi (1942)",
  },
  {
    id: "orden-disney-clasicos-50",
    franchise: "Clásicos Disney",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Disney de la más antigua a la más reciente.",
    items: ["Cenicienta", "Alicia en el País de las Maravillas", "Peter Pan", "La Bella Durmiente"],
    official:
      "Cenicienta (1950), Alicia en el País de las Maravillas (1951), Peter Pan (1953) y La Bella Durmiente (1959)",
  },
  {
    id: "orden-disney-60-70",
    franchise: "Clásicos Disney",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Disney de la más antigua a la más reciente.",
    items: ["101 dálmatas", "El libro de la selva", "Los Aristogatos", "Robin Hood"],
    official:
      "101 dálmatas (1961), El libro de la selva (1967), Los Aristogatos (1970) y Robin Hood (1973)",
  },
  {
    id: "orden-disney-90-primeras",
    franchise: "Disney años 90 y 2000",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Disney de la más antigua a la más reciente.",
    items: ["La Sirenita", "La Bella y la Bestia", "Aladdín", "El Rey León"],
    official:
      "La Sirenita (1989), La Bella y la Bestia (1991), Aladdín (1992) y El Rey León (1994)",
  },
  {
    id: "orden-disney-finales-90",
    franchise: "Disney años 90 y 2000",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Disney de la más antigua a la más reciente.",
    items: ["Pocahontas", "El jorobado de Notre Dame", "Hércules", "Tarzán"],
    official:
      "Pocahontas (1995), El jorobado de Notre Dame (1996), Hércules (1997) y Tarzán (1999)",
  },
  {
    id: "orden-disney-2000",
    franchise: "Disney años 90 y 2000",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Disney de la más antigua a la más reciente.",
    items: ["El emperador y sus locuras", "Atlantis", "El planeta del tesoro", "Hermano Oso"],
    official:
      "El emperador y sus locuras (2000), Atlantis (2001), El planeta del tesoro (2002) y Hermano Oso (2003)",
  },
  {
    id: "orden-disney-2010",
    franchise: "Disney reciente",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Disney de la más antigua a la más reciente.",
    items: ["Enredados", "Rompe Ralph", "Frozen", "Big Hero 6"],
    official: "Enredados (2010), Rompe Ralph (2012), Frozen (2013) y Big Hero 6 (2014)",
  },
  {
    id: "orden-disney-2020",
    franchise: "Disney reciente",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Disney de la más antigua a la más reciente.",
    items: ["Tiana y el sapo", "Zootrópolis", "Raya y el último dragón", "Wish"],
    official:
      "Tiana y el sapo (2009), Zootrópolis (2016), Raya y el último dragón (2021) y Wish (2023)",
  },
  {
    id: "relacionar-princesas-reino",
    franchise: "Princesas Disney",
    emoji: "👑",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada princesa con el lugar donde transcurre su historia.",
    pairs: [
      { left: "Elsa", right: "Arendelle" },
      { left: "Jasmín", right: "Agrabah" },
      { left: "Vaiana", right: "Motunui" },
      { left: "Mirabel", right: "Colombia" },
    ],
    official: "Elsa–Arendelle, Jasmín–Agrabah, Vaiana–Motunui y Mirabel–Colombia",
  },
  {
    id: "relacionar-princesas-companero",
    franchise: "Princesas Disney",
    emoji: "👑",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada protagonista con su acompañante.",
    pairs: [
      { left: "Ariel", right: "Flounder" },
      { left: "Rapunzel", right: "Pascal" },
      { left: "Mulán", right: "Mushu" },
      { left: "Tiana", right: "Louis" },
    ],
    official: "Ariel–Flounder, Rapunzel–Pascal, Mulán–Mushu y Tiana–Louis",
  },
  {
    id: "relacionar-villanos-clasicos",
    franchise: "Villanos Disney",
    emoji: "😈",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada villano con su película.",
    pairs: [
      { left: "Úrsula", right: "La Sirenita" },
      { left: "Jafar", right: "Aladdín" },
      { left: "Scar", right: "El Rey León" },
      { left: "Gastón", right: "La Bella y la Bestia" },
    ],
    official: "Úrsula–La Sirenita, Jafar–Aladdín, Scar–El Rey León y Gastón–La Bella y la Bestia",
  },
  {
    id: "relacionar-villanos-viejos",
    franchise: "Villanos Disney",
    emoji: "😈",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cuál de estos villanos NO pertenece a la película que se indica?",
    options: [
      "Yzma, en Atlantis",
      "Maléfica, en La Bella Durmiente",
      "Cruella de Vil, en 101 dálmatas",
      "Lady Tremaine, en Cenicienta",
    ],
    correct: 0,
    official: "Yzma es de El emperador y sus locuras, no de Atlantis",
  },
  {
    id: "relacionar-mascotas-dueno",
    franchise: "Mascotas Disney",
    emoji: "🐾",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada mascota con su dueño.",
    pairs: [
      { left: "Pluto", right: "Mickey" },
      { left: "Abú", right: "Aladdín" },
      { left: "Pegaso", right: "Hércules" },
      { left: "Sven", right: "Kristoff" },
    ],
    official: "Pluto–Mickey, Abú–Aladdín, Pegaso–Hércules y Sven–Kristoff",
  },
  {
    id: "relacionar-conciencias",
    franchise: "Compañeros Disney",
    emoji: "🎭",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada personaje con la película en la que hace de guía o consejero.",
    pairs: [
      { left: "Pepito Grillo", right: "Pinocho" },
      { left: "Zazú", right: "El Rey León" },
      { left: "Sebastián", right: "La Sirenita" },
      { left: "Timothy", right: "Dumbo" },
    ],
    official: "Pepito Grillo–Pinocho, Zazú–El Rey León, Sebastián–La Sirenita y Timothy–Dumbo",
  },
  {
    id: "relacionar-transformaciones",
    franchise: "Compañeros Disney",
    emoji: "🎭",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué película alguien se convierte en rana?",
    options: ["Tiana y el sapo", "Hermano Oso", "El emperador y sus locuras", "Enredados"],
    correct: 0,
    official: "Tiana y el sapo",
    note: "En Hermano Oso el protagonista se vuelve oso y en El emperador y sus locuras, llama.",
  },

  // --- Frases y canciones ---
  {
    id: "completar-sirenita-cancion",
    franchise: "La Sirenita",
    emoji: "🧜",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el título de la canción de Sebastián: «Bajo el ___».",
    accepted: [["mar"]],
    official: "Bajo el mar",
  },
  {
    id: "completar-frozen-cancion",
    franchise: "Frozen",
    emoji: "❄️",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el estribillo de Elsa en el doblaje español: «Suéltalo, ___».",
    accepted: [["suéltalo", "sueltalo"]],
    official: "Suéltalo, suéltalo",
  },
  {
    id: "completar-hercules-cancion",
    franchise: "Hércules",
    emoji: "⚡",
    difficulty: "media",
    format: "completar",
    prompt: "Completa el título de la canción sobre la fama de Hércules: «De cero a ___».",
    accepted: [["héroe", "heroe"]],
    official: "De cero a héroe",
  },
  {
    id: "completar-blancanieves-espejo",
    franchise: "Blancanieves",
    emoji: "🍎",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa lo que pregunta la Reina: «Espejito, espejito, ¿quién es la más ___ del reino?».",
    accepted: [["bella", "hermosa"]],
    official: "¿Quién es la más bella del reino?",
  },
  {
    id: "completar-genio-aladdin",
    franchise: "Aladdín",
    emoji: "🧞",
    difficulty: "media",
    format: "completar",
    prompt: "Completa lo que ofrece el Genio al salir de la lámpara: «Tienes derecho a tres ___».",
    accepted: [["deseos"]],
    official: "Tres deseos",
  },
  {
    id: "completar-peterpan-estrella",
    franchise: "Peter Pan",
    emoji: "🧚",
    difficulty: "media",
    format: "completar",
    prompt: "Completa las señas de la isla de Peter Pan: «La segunda estrella a la ___».",
    accepted: [["derecha"]],
    official: "La segunda estrella a la derecha",
  },
  {
    id: "completar-mulan-mushu",
    franchise: "Mulán",
    emoji: "🗡️",
    difficulty: "media",
    format: "completar",
    prompt: "Completa el nombre del dragón guardián de Mulán: «Mu___».",
    accepted: [["shu"]],
    official: "Mushu",
  },
  {
    id: "completar-encanto-bruno",
    franchise: "Encanto",
    emoji: "🕯️",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el título de la canción de Encanto: «No se habla de ___».",
    accepted: [["Bruno"]],
    official: "No se habla de Bruno",
  },

  // --- Verdadero o falso ---
  {
    id: "vf-sirenita-ariel",
    franchise: "La Sirenita",
    emoji: "🧜",
    difficulty: "facil",
    format: "vf",
    prompt: "Ariel entrega su voz a Úrsula a cambio de tener piernas.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "vf-reyleon-scar",
    franchise: "El Rey León",
    emoji: "🦁",
    difficulty: "facil",
    format: "vf",
    prompt: "Scar es el hermano de Mufasa y, por tanto, tío de Simba.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "vf-frozen-olaf",
    franchise: "Frozen",
    emoji: "❄️",
    difficulty: "facil",
    format: "vf",
    prompt: "Olaf es un muñeco de nieve que sueña con conocer el verano.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "vf-cenicienta-zapato",
    franchise: "Cenicienta",
    emoji: "👠",
    difficulty: "facil",
    format: "vf",
    prompt: "A Cenicienta se le cae un guante al salir corriendo del baile.",
    correct: false,
    official: "Falso: se le cae un zapato de cristal",
  },
  {
    id: "vf-pinocho-nariz",
    franchise: "Pinocho",
    emoji: "🪵",
    difficulty: "facil",
    format: "vf",
    prompt: "A Pinocho le crecen las orejas cada vez que dice una mentira.",
    correct: false,
    official: "Falso: le crece la nariz",
    note: "Las orejas de burro le salen en la Isla de los Juegos, y por otro motivo.",
  },
  {
    id: "vf-jorobado-quasimodo",
    franchise: "El jorobado de Notre Dame",
    emoji: "🔔",
    difficulty: "media",
    format: "vf",
    prompt: "Quasimodo vive encerrado en la catedral y se ocupa de tocar las campanas.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "vf-tarzan-gorilas",
    franchise: "Tarzán",
    emoji: "🦍",
    difficulty: "facil",
    format: "vf",
    prompt: "A Tarzán lo cría una manada de chimpancés.",
    correct: false,
    official: "Falso: lo crían gorilas",
    note: "Su madre adoptiva es Kala; Terk, su amiga, sí es una gorila más joven.",
  },
  {
    id: "vf-zootropolis-judy",
    franchise: "Zootrópolis",
    emoji: "🐰",
    difficulty: "media",
    format: "vf",
    prompt: "Judy Hopps es la primera coneja que entra en la policía de Zootrópolis.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "vf-encanto-mirabel",
    franchise: "Encanto",
    emoji: "🕯️",
    difficulty: "media",
    format: "vf",
    prompt: "Mirabel es la única de la familia Madrigal que no recibe ningún don.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "vf-vaiana-maui",
    franchise: "Vaiana",
    emoji: "🌊",
    difficulty: "media",
    format: "vf",
    prompt: "Maui es un semidiós que cambia de forma gracias a un anzuelo mágico.",
    correct: true,
    official: "Verdadero",
  },

  // --- Identifica el personaje ---
  {
    id: "describir-ursula",
    franchise: "La Sirenita",
    emoji: "🧜",
    difficulty: "facil",
    format: "describir",
    prompt: "Bruja del mar mitad pulpo, con el pelo blanco y dos morenas como secuaces.",
    hint: "(Solo el nombre.)",
    accepted: [["Úrsula"]],
    official: "Úrsula",
  },
  {
    id: "describir-lumiere",
    franchise: "La Bella y la Bestia",
    emoji: "🌹",
    difficulty: "media",
    format: "describir",
    prompt: "Candelabro encantado, galante y con acento francés, que dirige el número de bienvenida.",
    hint: "(Solo el nombre.)",
    accepted: [["Lumière", "Lumiere"]],
    official: "Lumière",
  },
  {
    id: "describir-rafiki",
    franchise: "El Rey León",
    emoji: "🦁",
    difficulty: "media",
    format: "describir",
    prompt: "Mandril chamán con un bastón, que presenta a Simba en la Roca del Rey.",
    hint: "(Solo el nombre.)",
    accepted: [["Rafiki"]],
    official: "Rafiki",
  },
  {
    id: "describir-cruella",
    franchise: "101 dálmatas",
    emoji: "🐕",
    difficulty: "facil",
    format: "describir",
    prompt: "Mujer de melena mitad blanca mitad negra que quiere un abrigo hecho con cachorros.",
    hint: "(Solo el nombre.)",
    accepted: [["Cruella", "Cruella de Vil"]],
    official: "Cruella de Vil",
  },
  {
    id: "describir-hada-madrina",
    franchise: "Cenicienta",
    emoji: "👠",
    difficulty: "facil",
    format: "describir",
    prompt: "Señora regordeta con capa azul que convierte una calabaza en carroza.",
    hint: "(Quién es.)",
    accepted: [["Hada Madrina", "el Hada Madrina", "hada"]],
    official: "El Hada Madrina",
  },
  {
    id: "describir-campanilla",
    franchise: "Peter Pan",
    emoji: "🧚",
    difficulty: "facil",
    format: "describir",
    prompt: "Hada diminuta y celosa que deja un rastro de polvo dorado por donde pasa.",
    hint: "(Solo el nombre.)",
    accepted: [["Campanilla"]],
    official: "Campanilla",
  },
  {
    id: "describir-baloo",
    franchise: "El libro de la selva",
    emoji: "🐻",
    difficulty: "facil",
    format: "describir",
    prompt: "Oso perezoso y juerguista que enseña a Mowgli a vivir sin preocupaciones.",
    hint: "(Solo el nombre.)",
    accepted: [["Baloo"]],
    official: "Baloo",
  },
  {
    id: "describir-olaf",
    franchise: "Frozen",
    emoji: "❄️",
    difficulty: "facil",
    format: "describir",
    prompt: "Muñeco de nieve con nariz de zanahoria al que se le caen los trozos a cada rato.",
    hint: "(Solo el nombre.)",
    accepted: [["Olaf"]],
    official: "Olaf",
  },
  {
    id: "describir-madre-gothel",
    franchise: "Enredados",
    emoji: "💇",
    difficulty: "media",
    format: "describir",
    prompt: "Mujer que secuestra a una niña para usar el poder de su pelo y no envejecer.",
    hint: "(Solo el nombre.)",
    accepted: [["Madre Gothel", "Gothel"]],
    official: "Madre Gothel",
  },

  // --- Respuesta corta y opciones ---
  {
    id: "sirenita-tridente",
    franchise: "La Sirenita",
    emoji: "🧜",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el padre de Ariel, rey del mar?",
    hint: "(Solo el nombre.)",
    accepted: [["Tritón", "Rey Tritón"]],
    official: "El rey Tritón",
  },
  {
    id: "bella-chip",
    franchise: "La Bella y la Bestia",
    emoji: "🌹",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la tacita, hijo de la señora Potts?",
    hint: "(Solo el nombre.)",
    accepted: [["Chip"]],
    official: "Chip",
  },
  {
    id: "enredados-camaleon",
    franchise: "Enredados",
    emoji: "💇",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el camaleón que acompaña a Rapunzel?",
    hint: "(Solo el nombre.)",
    accepted: [["Pascal"]],
    official: "Pascal",
  },
  {
    id: "zootropolis-perezoso",
    franchise: "Zootrópolis",
    emoji: "🐰",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el perezoso que atiende en la oficina de tráfico?",
    hint: "(Solo el nombre.)",
    accepted: [["Flash"]],
    official: "Flash",
  },
  {
    id: "bighero-hermano",
    franchise: "Big Hero 6",
    emoji: "🤖",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el hermano de Hiro, el que construyó a Baymax?",
    hint: "(Solo el nombre.)",
    accepted: [["Tadashi"]],
    official: "Tadashi",
  },
  {
    id: "raya-dragon",
    franchise: "Raya y el último dragón",
    emoji: "🐉",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la dragona de agua que Raya consigue despertar?",
    hint: "(Solo el nombre.)",
    accepted: [["Sisu"]],
    official: "Sisu",
  },
  {
    id: "wish-estrella",
    franchise: "Wish",
    emoji: "⭐",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la joven que pide un deseo y hace bajar a una estrella?",
    options: ["Asha", "Aisha", "Amaya", "Alma"],
    correct: 0,
    official: "Asha",
  },
  {
    id: "tiana-luciernaga",
    franchise: "Tiana y el sapo",
    emoji: "🐸",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la luciérnaga enamorada de una estrella?",
    options: ["Ray", "Louis", "Naveen", "Facilier"],
    correct: 0,
    official: "Ray",
    note: "Louis es el cocodrilo trompetista y Naveen, el príncipe convertido en rana.",
  },
  {
    id: "pocahontas-mapache",
    franchise: "Pocahontas",
    emoji: "🍃",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el mapache que acompaña a Pocahontas?",
    options: ["Meeko", "Flit", "Percy", "Kocoum"],
    correct: 0,
    official: "Meeko",
    note: "Flit es el colibrí y Percy, el perro del gobernador.",
  },
  {
    id: "lilo-experimento",
    franchise: "Lilo & Stitch",
    emoji: "👽",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Con qué número de experimento se conoce a Stitch?",
    options: ["626", "621", "628", "662"],
    correct: 0,
    official: "El experimento 626",
  },
];
