import type { Question } from "../types";

/** Pixar, DreamWorks, Illumination, Sony y otros estudios de largometraje. */
export const ESTUDIOS: Question[] = [
  // --- Toy Story ---
  {
    id: "toystory-andy",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el niño dueño de Woody y Buzz?",
    hint: "(Solo el nombre.)",
    accepted: [["Andy"]],
    official: "Andy",
  },
  {
    id: "toystory-sid",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el vecino que destroza y recompone juguetes?",
    hint: "(Solo el nombre.)",
    accepted: [["Sid"]],
    official: "Sid",
  },
  {
    id: "toystory-jessie",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la vaquera pelirroja que aparece en Toy Story 2?",
    hint: "(Solo el nombre.)",
    accepted: [["Jessie"]],
    official: "Jessie",
  },
  {
    id: "toystory-lotso",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el oso de peluche rosa que manda en la guardería en Toy Story 3?",
    options: ["Lotso", "Bigotitos", "Chuckles", "Ken"],
    correct: 0,
    official: "Lotso",
  },
  {
    id: "toystory-infinito",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa la frase de Buzz Lightyear: «Hasta el ___ y más allá».",
    accepted: [["infinito"]],
    official: "Hasta el infinito y más allá",
  },

  // --- Monstruos S.A. ---
  {
    id: "monstruos-boo",
    franchise: "Monstruos S.A.",
    emoji: "👹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo llama Sulley a la niña humana que se cuela en la fábrica?",
    hint: "(Solo el nombre.)",
    accepted: [["Boo"]],
    official: "Boo",
  },
  {
    id: "monstruos-waternoose",
    franchise: "Monstruos S.A.",
    emoji: "👹",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el presidente de la fábrica Monstruos S.A.?",
    options: ["Waternoose", "Fungus", "Roz", "Nictófilo"],
    correct: 0,
    official: "Henry J. Waternoose",
  },
  {
    id: "monstruos-celia",
    franchise: "Monstruos S.A.",
    emoji: "👹",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es la recepcionista de la fábrica, novia de Mike, y en lugar de pelo tiene serpientes.",
    hint: "(Solo el nombre.)",
    accepted: [["Celia"]],
    official: "Celia",
  },

  // --- Buscando a Nemo / Dory ---
  {
    id: "nemo-bruce",
    franchise: "Buscando a Nemo",
    emoji: "🐠",
    difficulty: "facil",
    format: "corta",
    prompt:
      "¿Cómo se llama el tiburón que lidera el grupo de escualos que intentan no comer peces?",
    hint: "(Solo el nombre.)",
    accepted: [["Bruce"]],
    official: "Bruce",
  },
  {
    id: "nemo-nigel",
    franchise: "Buscando a Nemo",
    emoji: "🐠",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Nigel, el que ayuda a Marlin en el puerto de Sídney?",
    options: ["Un pelícano", "Una gaviota", "Un cormorán", "Un albatros"],
    correct: 0,
    official: "Un pelícano",
  },
  {
    id: "dory-hank",
    franchise: "Buscando a Dory",
    emoji: "🐙",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el pulpo de siete tentáculos que ayuda a Dory?",
    options: ["Hank", "Bailey", "Destiny", "Gerald"],
    correct: 0,
    official: "Hank",
  },

  // --- Los Increíbles ---
  {
    id: "increibles-dash",
    franchise: "Los Increíbles",
    emoji: "🦸",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el hijo de la familia, capaz de correr a toda velocidad?",
    hint: "(Solo el nombre.)",
    accepted: [["Dash"]],
    official: "Dash",
  },
  {
    id: "increibles-elastigirl",
    franchise: "Los Increíbles",
    emoji: "🦸",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuál es el nombre de superheroína de Helen Parr?",
    accepted: [["Elastigirl", "Elástigirl"]],
    official: "Elastigirl",
  },

  // --- Cars ---
  {
    id: "cars-mate",
    franchise: "Cars",
    emoji: "🏎️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la grúa oxidada y bonachona, mejor amigo de Rayo McQueen?",
    hint: "(Solo el nombre.)",
    accepted: [["Mate", "Mater"]],
    official: "Mate",
  },
  {
    id: "cars-radiador",
    franchise: "Cars",
    emoji: "🏎️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el pueblo perdido en el que acaba varado Rayo McQueen?",
    options: ["Radiador Springs", "Motor City", "Villa Pistón", "Ruta Springs"],
    correct: 0,
    official: "Radiador Springs",
  },
  {
    id: "cars-doc",
    franchise: "Cars",
    emoji: "🏎️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el viejo Hudson del pueblo, que fue tres veces campeón?",
    options: ["Doc Hudson", "Rey Weathers", "Sheriff", "Chick Hicks"],
    correct: 0,
    official: "Doc Hudson",
  },

  // --- Ratatouille ---
  {
    id: "ratatouille-gusteau",
    franchise: "Ratatouille",
    emoji: "🍲",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el chef fallecido cuyo lema es «cualquiera puede cocinar»?",
    accepted: [["Gusteau", "Auguste Gusteau"]],
    official: "Auguste Gusteau",
  },
  {
    id: "ratatouille-skinner",
    franchise: "Ratatouille",
    emoji: "🍲",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el chef bajito que dirige el restaurante y sospecha de la rata?",
    options: ["Skinner", "Horst", "Lalo", "Mustafá"],
    correct: 0,
    official: "Skinner",
  },
  {
    id: "ratatouille-colette",
    franchise: "Ratatouille",
    emoji: "🍲",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la única mujer de la cocina, que enseña el oficio al protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Colette"]],
    official: "Colette",
  },

  // --- WALL·E ---
  {
    id: "walle-axiom",
    franchise: "WALL·E",
    emoji: "🛸",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la nave donde viven los humanos?",
    options: ["Axiom", "Odisea", "Buy n Large", "Elysium"],
    correct: 0,
    official: "La Axiom",
  },
  {
    id: "walle-cucaracha",
    franchise: "WALL·E",
    emoji: "🛸",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué bichito acompaña a WALL·E en la Tierra desierta?",
    hint: "(El animal.)",
    accepted: [["cucaracha", "una cucaracha"]],
    official: "Una cucaracha",
  },

  // --- Up ---
  {
    id: "up-dug",
    franchise: "Up",
    emoji: "🎈",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es un perro con un collar que traduce sus pensamientos en voz alta y se distrae con las ardillas.",
    hint: "(Solo el nombre.)",
    accepted: [["Dug", "Doug"]],
    official: "Dug",
  },
  {
    id: "up-russell",
    franchise: "Up",
    emoji: "🎈",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el niño explorador que viaja sin querer en la casa voladora?",
    hint: "(Solo el nombre.)",
    accepted: [["Russell"]],
    official: "Russell",
  },
  {
    id: "up-kevin",
    franchise: "Up",
    emoji: "🎈",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo llama Russell al ave gigante de colores que encuentran?",
    options: ["Kevin", "Carla", "Pipo", "Beta"],
    correct: 0,
    official: "Kevin",
    note: "Resulta ser hembra, pero el nombre se le queda.",
  },

  // --- Del revés ---
  {
    id: "delreves-riley",
    franchise: "Del revés",
    emoji: "🧠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la niña en cuya cabeza viven las emociones?",
    hint: "(Solo el nombre.)",
    accepted: [["Riley"]],
    official: "Riley",
  },
  {
    id: "delreves-bingbong",
    franchise: "Del revés",
    emoji: "🧠",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el amigo imaginario rosa, mezcla de elefante y algodón de azúcar?",
    options: ["Bing Bong", "Bong Bing", "Pomponio", "Ding Dong"],
    correct: 0,
    official: "Bing Bong",
  },
  {
    id: "delreves-ansiedad",
    franchise: "Del revés",
    emoji: "🧠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuál es la nueva emoción que toma el mando en Del revés 2?",
    hint: "(Solo el nombre de la emoción.)",
    accepted: [["Ansiedad"]],
    official: "Ansiedad",
  },

  // --- Coco ---
  {
    id: "coco-ernesto",
    franchise: "Coco",
    emoji: "💀",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el cantante al que Miguel admira y cree que es su bisabuelo?",
    accepted: [["Ernesto de la Cruz", "Ernesto"]],
    official: "Ernesto de la Cruz",
  },
  {
    id: "coco-hector",
    franchise: "Coco",
    emoji: "💀",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el esqueleto tramposo que guía a Miguel por la tierra de los muertos?",
    options: ["Héctor", "Chicharrón", "Julio", "Óscar"],
    correct: 0,
    official: "Héctor",
  },

  // --- Soul ---
  {
    id: "soul-22",
    franchise: "Soul",
    emoji: "🎷",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el alma que lleva siglos negándose a nacer?",
    options: ["22", "7", "Moonwind", "Terry"],
    correct: 0,
    official: "22",
  },

  // --- Red ---
  {
    id: "red-4town",
    franchise: "Red",
    emoji: "🐼",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el grupo musical al que adoran Mei y sus amigas?",
    options: ["4*Town", "5*Star", "3*Boys", "TownBoyz"],
    correct: 0,
    official: "4*Town",
  },

  // --- Elemental ---
  {
    id: "elemental-protagonistas",
    franchise: "Elemental",
    emoji: "🔥",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llaman la chica de fuego y el chico de agua protagonistas?",
    hint: "(Los dos nombres.)",
    accepted: [["Ember"], ["Wade"]],
    official: "Ember y Wade",
  },

  // --- Bichos ---
  {
    id: "bichos-hopper",
    franchise: "Bichos",
    emoji: "🐜",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el saltamontes que extorsiona al hormiguero?",
    options: ["Hopper", "Molt", "Thumper", "Manny"],
    correct: 0,
    official: "Hopper",
  },

  // --- Onward ---
  {
    id: "onward-hermanos",
    franchise: "Onward",
    emoji: "🧝",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llaman los dos hermanos elfos protagonistas?",
    options: ["Ian y Barley", "Ian y Wilden", "Elmo y Barley", "Corey y Ian"],
    correct: 0,
    official: "Ian y Barley",
  },

  // --- Luca ---
  {
    id: "luca-giulia",
    franchise: "Luca",
    emoji: "🛵",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la niña humana que se hace amiga de Luca y Alberto?",
    hint: "(Solo el nombre.)",
    accepted: [["Giulia", "Julia"]],
    official: "Giulia",
  },

  // --- Shrek ---
  {
    id: "shrek-asno",
    franchise: "Shrek",
    emoji: "🧅",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué animal es el compañero parlanchín e insoportable de Shrek?",
    hint: "(El animal.)",
    accepted: [["asno", "burro"]],
    official: "Un asno",
  },
  {
    id: "shrek-duloc",
    franchise: "Shrek",
    emoji: "🧅",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el reino perfectamente ordenado de Lord Farquaad?",
    options: ["Duloc", "Farquaadia", "Muy Muy Lejano", "Vallefresco"],
    correct: 0,
    official: "Duloc",
  },
  {
    id: "shrek-farquaad",
    franchise: "Shrek",
    emoji: "🧅",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el villano bajito de la primera película?",
    options: ["Lord Farquaad", "Rumpelstiltskin", "Charming", "Lord Fiquad"],
    correct: 0,
    official: "Lord Farquaad",
  },

  // --- Madagascar ---
  {
    id: "madagascar-alex",
    franchise: "Madagascar",
    emoji: "🦓",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el león, estrella del zoo de Nueva York?",
    hint: "(Solo el nombre.)",
    accepted: [["Alex"]],
    official: "Alex",
  },
  {
    id: "madagascar-melman",
    franchise: "Madagascar",
    emoji: "🦓",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la jirafa hipocondríaca del grupo?",
    options: ["Melman", "Marty", "Mort", "Maurice"],
    correct: 0,
    official: "Melman",
  },
  {
    id: "madagascar-marty",
    franchise: "Madagascar",
    emoji: "🦓",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la cebra que sueña con vivir en libertad?",
    hint: "(Solo el nombre.)",
    accepted: [["Marty"]],
    official: "Marty",
  },

  // --- Kung Fu Panda ---
  {
    id: "kfp-po",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el panda protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Po"]],
    official: "Po",
  },
  {
    id: "kfp-shifu",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el maestro panda rojo que entrena a Po?",
    hint: "(Solo el nombre.)",
    accepted: [["Shifu"]],
    official: "El maestro Shifu",
  },
  {
    id: "kfp-oogway",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es el maestro Oogway, el más sabio del Valle de la Paz?",
    options: ["Una tortuga", "Un cocodrilo", "Un mono", "Un buitre"],
    correct: 0,
    official: "Una tortuga",
  },
  {
    id: "kfp-ping",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es el señor Ping, el padre adoptivo de Po que regenta el local de fideos?",
    options: ["Un ganso", "Un pato", "Una grulla", "Un cisne"],
    correct: 0,
    official: "Un ganso",
  },

  // --- Cómo entrenar a tu dragón ---
  {
    id: "dragon-hipo",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🐲",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el joven vikingo protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Hipo"]],
    official: "Hipo",
  },
  {
    id: "dragon-astrid",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🐲",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la joven vikinga que acaba siendo pareja del protagonista?",
    options: ["Astrid", "Brusca", "Heather", "Ingrid"],
    correct: 0,
    official: "Astrid",
  },
  {
    id: "dragon-bocon",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🐲",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el herrero manco que instruye a los jóvenes de Mema?",
    options: ["Bocón", "Patapez", "Mocoso", "Gordo"],
    correct: 0,
    official: "Bocón",
  },

  // --- El príncipe de Egipto ---
  {
    id: "egipto-sefora",
    franchise: "El príncipe de Egipto",
    emoji: "🏜️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la mujer con la que se casa Moisés?",
    options: ["Séfora", "Miriam", "Jocabed", "Nefertari"],
    correct: 0,
    official: "Séfora",
  },

  // --- Megamind ---
  {
    id: "megamind-minion",
    franchise: "Megamind",
    emoji: "🦹",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el pez que ayuda a Megamind desde un robot con cuerpo de gorila?",
    options: ["Minion", "Esbirro", "Bubbles", "Gill"],
    correct: 0,
    official: "Minion",
  },

  // --- Los Croods ---
  {
    id: "croods-grug",
    franchise: "Los Croods",
    emoji: "🦴",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el padre cavernícola, obsesionado con no salir de la cueva?",
    options: ["Grug", "Guy", "Thunk", "Ugga"],
    correct: 0,
    official: "Grug",
  },

  // --- El origen de los guardianes ---
  {
    id: "guardianes-pitch",
    franchise: "El origen de los guardianes",
    emoji: "🌙",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el villano que siembra pesadillas?",
    options: ["Pitch", "Sandman", "Norte", "Umbra"],
    correct: 0,
    official: "Pitch, el Coco",
  },

  // --- Trolls ---
  {
    id: "trolls-poppy",
    franchise: "Trolls",
    emoji: "🎨",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la princesa troll, siempre optimista y de color rosa?",
    hint: "(Solo el nombre.)",
    accepted: [["Poppy"]],
    official: "Poppy",
  },

  // --- El gato con botas ---
  {
    id: "gatobotas-kitty",
    franchise: "El gato con botas",
    emoji: "🐈",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la gata que acompaña al Gato con Botas?",
    options: [
      "Kitty Patitas Suaves",
      "Kitty Zarpas Blandas",
      "Gata Miau",
      "Perrito",
    ],
    correct: 0,
    official: "Kitty Patitas Suaves",
  },

  // --- Bee Movie ---
  {
    id: "beemovie-demanda",
    franchise: "Bee Movie",
    emoji: "🐝",
    difficulty: "facil",
    format: "vf",
    prompt: "En Bee Movie las abejas llevan a los humanos a juicio por robarles la miel.",
    correct: true,
    official: "Verdadero",
  },

  // --- Mi villano favorito ---
  {
    id: "gru-nefario",
    franchise: "Mi villano favorito",
    emoji: "🌙",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el anciano científico que inventa los cachivaches de Gru?",
    hint: "(Solo el nombre.)",
    accepted: [["Nefario", "Doctor Nefario", "Dr. Nefario"]],
    official: "El doctor Nefario",
  },
  {
    id: "gru-elmacho",
    franchise: "Mi villano favorito",
    emoji: "🌙",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el villano de Gru 2, un luchador mexicano que se creía muerto?",
    options: ["El Macho", "El Diablo", "Balthazar", "Vector"],
    correct: 0,
    official: "El Macho",
  },
  {
    id: "minions-scarlet",
    franchise: "Los Minions",
    emoji: "🍌",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la supervillana a la que sirven los Minions en su propia película?",
    options: ["Scarlet Overkill", "Ruby Steele", "Violet Vicious", "Lucy Wilde"],
    correct: 0,
    official: "Scarlet Overkill",
  },

  // --- Canta ---
  {
    id: "canta-buster",
    franchise: "Canta",
    emoji: "🎤",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es un koala arruinado y optimista que organiza un concurso de canto para salvar su teatro.",
    accepted: [["Buster Moon", "Buster", "Moon"]],
    official: "Buster Moon",
  },
  {
    id: "canta-rosita",
    franchise: "Canta",
    emoji: "🎤",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la cerdita madre de veinticinco cochinillos que se presenta al concurso?",
    options: ["Rosita", "Ash", "Meena", "Nana"],
    correct: 0,
    official: "Rosita",
  },

  // --- El Lorax ---
  {
    id: "lorax-arboles",
    franchise: "El Lorax",
    emoji: "🌳",
    difficulty: "facil",
    format: "vf",
    prompt: "El Lorax se presenta a sí mismo diciendo que habla en nombre de los árboles.",
    correct: true,
    official: "Verdadero",
  },

  // --- El Grinch ---
  {
    id: "grinch-max",
    franchise: "El Grinch",
    emoji: "🎄",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el perro del Grinch, al que disfraza de reno?",
    hint: "(Solo el nombre.)",
    accepted: [["Max"]],
    official: "Max",
  },

  // --- Spider-Man: Un nuevo universo ---
  {
    id: "spiderverse-gwen",
    franchise: "Spider-Man: Un nuevo universo",
    emoji: "🕷️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuál es el nombre real de Spider-Gwen?",
    options: ["Gwen Stacy", "Gwen Watson", "Gwen Parker", "Gwen Morales"],
    correct: 0,
    official: "Gwen Stacy",
  },

  // --- Lluvia de albóndigas ---
  {
    id: "albondigas-flint",
    franchise: "Lluvia de albóndigas",
    emoji: "🍔",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el inventor que crea la máquina que convierte agua en comida?",
    options: ["Flint Lockwood", "Tim Lockwood", "Chester V", "Brent"],
    correct: 0,
    official: "Flint Lockwood",
  },

  // --- Hotel Transilvania ---
  {
    id: "hoteltransilvania-frank",
    franchise: "Hotel Transilvania",
    emoji: "🧛",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué monstruo es Frank, uno de los mejores amigos de Drácula?",
    options: [
      "El monstruo de Frankenstein",
      "Un hombre lobo",
      "Una momia",
      "El hombre invisible",
    ],
    correct: 0,
    official: "El monstruo de Frankenstein",
  },

  // --- El Gigante de Hierro ---
  {
    id: "gigante-espacio",
    franchise: "El Gigante de Hierro",
    emoji: "🤖",
    difficulty: "facil",
    format: "vf",
    prompt: "El Gigante de Hierro es un robot llegado del espacio que cae cerca de un pueblo de Maine.",
    correct: true,
    official: "Verdadero",
  },

  // --- Chicken Run ---
  {
    id: "chickenrun-rocky",
    franchise: "Chicken Run",
    emoji: "🐔",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el gallo americano que presume de saber volar?",
    options: ["Rocky", "Fowler", "Nick", "Mac"],
    correct: 0,
    official: "Rocky",
  },

  // --- Wallace y Gromit ---
  {
    id: "wallace-queso",
    franchise: "Wallace y Gromit",
    emoji: "🧀",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cuál es el queso favorito de Wallace?",
    options: ["Wensleydale", "Cheddar", "Stilton", "Brie"],
    correct: 0,
    official: "El Wensleydale",
  },

  // --- Coraline ---
  {
    id: "coraline-botones",
    franchise: "Coraline",
    emoji: "🔘",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué tienen en los ojos los habitantes del otro mundo de Coraline?",
    hint: "(Una palabra.)",
    accepted: [["botones", "botón"]],
    official: "Botones",
  },

  // --- Pesadilla antes de Navidad ---
  {
    id: "pesadilla-jack",
    franchise: "Pesadilla antes de Navidad",
    emoji: "🎃",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el Rey Calabaza que decide adueñarse de la Navidad?",
    accepted: [["Jack Skellington", "Jack"]],
    official: "Jack Skellington",
  },
  {
    id: "pesadilla-sally",
    franchise: "Pesadilla antes de Navidad",
    emoji: "🎃",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la muñeca de trapo enamorada de Jack?",
    options: ["Sally", "Shock", "Lock", "Emily"],
    correct: 0,
    official: "Sally",
  },

  // --- Anastasia ---
  {
    id: "anastasia-rasputin",
    franchise: "Anastasia",
    emoji: "👑",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el hechicero que maldice a la familia imperial rusa?",
    options: ["Rasputín", "Dimitri", "Vladimir", "Bartok"],
    correct: 0,
    official: "Rasputín",
  },

  // --- El Principito ---
  {
    id: "principito-rosa",
    franchise: "El Principito",
    emoji: "🌹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué flor cuida el Principito en su asteroide?",
    hint: "(La flor.)",
    accepted: [["rosa", "una rosa", "la rosa"]],
    official: "Una rosa",
  },

  // --- Klaus ---
  {
    id: "klaus-juguetero",
    franchise: "Klaus",
    emoji: "🛷",
    difficulty: "facil",
    format: "vf",
    prompt: "Klaus es un juguetero solitario que vive apartado en una cabaña del bosque.",
    correct: true,
    official: "Verdadero",
  },

  // --- Orden cronológico y relacionar (transversales) ---
  {
    id: "orden-pixar-primeros",
    franchise: "Pixar clásico",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Bichos", "Buscando a Nemo", "WALL·E", "Del revés"],
    official: "Bichos (1998), Buscando a Nemo (2003), WALL·E (2008) y Del revés (2015)",
  },
  {
    id: "orden-pixar-reciente",
    franchise: "Pixar reciente",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Coco", "Soul", "Luca", "Red"],
    official: "Coco (2017), Soul (2020), Luca (2021) y Red (2022)",
  },
  {
    id: "orden-dreamworks",
    franchise: "DreamWorks",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de DreamWorks de la más antigua a la más reciente.",
    items: ["Shrek", "Madagascar", "Kung Fu Panda", "Los Croods"],
    official: "Shrek (2001), Madagascar (2005), Kung Fu Panda (2008) y Los Croods (2013)",
  },
  {
    id: "relacionar-estudios",
    franchise: "Estudios de animación",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada película con el estudio que la produjo.",
    pairs: [
      { left: "Shrek", right: "DreamWorks" },
      { left: "Coco", right: "Pixar" },
      { left: "Mi villano favorito", right: "Illumination" },
      { left: "Hotel Transilvania", right: "Sony Animation" },
    ],
    official:
      "Shrek–DreamWorks, Coco–Pixar, Mi villano favorito–Illumination y Hotel Transilvania–Sony Animation",
  },
  {
    id: "relacionar-villanos-pixar",
    franchise: "Villanos Pixar",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada villano con su película.",
    pairs: [
      { left: "Hopper", right: "Bichos" },
      { left: "Lotso", right: "Toy Story 3" },
      { left: "Skinner", right: "Ratatouille" },
      { left: "Waternoose", right: "Monstruos S.A." },
    ],
    official:
      "Hopper–Bichos, Lotso–Toy Story 3, Skinner–Ratatouille y Waternoose–Monstruos S.A.",
  },
];
