import type { Question } from "../types";

/** Pixar, DreamWorks, Illumination, Sony y otros estudios de largometraje. */
export const ESTUDIOS: Question[] = [
  // --- Toy Story ---
  {
    id: "toystory-andy",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el niño dueño de Woody y Buzz?",
    hint: "(Solo el nombre.)",
    accepted: [["Andy"]],
    official: "Andy",
  },
  {
    id: "toystory-sid",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el vecino que destroza y recompone juguetes?",
    hint: "(Solo el nombre.)",
    accepted: [["Sid"]],
    official: "Sid",
  },
  {
    id: "toystory-jessie",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la vaquera pelirroja que aparece en Toy Story 2?",
    hint: "(Solo el nombre.)",
    accepted: [["Jessie"]],
    official: "Jessie",
  },
  {
    id: "toystory-lotso",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el oso de peluche rosa que manda en la guardería en Toy Story 3?",
    options: ["Lotso", "Bigotitos", "Chuckles", "Ken"],
    correct: 0,
    official: "Lotso",
  },
  {
    id: "toystory-infinito",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa la frase de Buzz Lightyear: «Hasta el ___ y más allá».",
    accepted: [["infinito"]],
    official: "Hasta el infinito y más allá",
  },

  // --- Monstruos S.A. ---
  {
    id: "monstruos-boo",
    franchise: "Monstruos S.A.",
    emoji: "👹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo llama Sulley a la niña humana que se cuela en la fábrica?",
    hint: "(Solo el nombre.)",
    accepted: [["Boo"]],
    official: "Boo",
  },
  {
    id: "monstruos-waternoose",
    franchise: "Monstruos S.A.",
    emoji: "👹",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el presidente de la fábrica Monstruos S.A.?",
    options: ["Waternoose", "Fungus", "Roz", "Nictófilo"],
    correct: 0,
    official: "Henry J. Waternoose",
  },
  {
    id: "monstruos-celia",
    franchise: "Monstruos S.A.",
    emoji: "👹",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es la recepcionista de la fábrica, novia de Mike, y en lugar de pelo tiene serpientes.",
    hint: "(Solo el nombre.)",
    accepted: [["Celia"]],
    official: "Celia",
  },

  // --- Buscando a Nemo / Dory ---
  {
    id: "nemo-bruce",
    franchise: "Buscando a Nemo",
    emoji: "🐠",
    difficulty: "facil",
    format: "corta",
    prompt:
      "¿Cómo se llama el tiburón que lidera el grupo de escualos que intentan no comer peces?",
    hint: "(Solo el nombre.)",
    accepted: [["Bruce"]],
    official: "Bruce",
  },
  {
    id: "nemo-nigel",
    franchise: "Buscando a Nemo",
    emoji: "🐠",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Nigel, el que ayuda a Marlin en el puerto de Sídney?",
    options: ["Un pelícano", "Una gaviota", "Un cormorán", "Un albatros"],
    correct: 0,
    official: "Un pelícano",
  },
  {
    id: "dory-hank",
    franchise: "Buscando a Dory",
    emoji: "🐙",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el pulpo de siete tentáculos que ayuda a Dory?",
    options: ["Hank", "Bailey", "Destiny", "Gerald"],
    correct: 0,
    official: "Hank",
  },

  // --- Los Increíbles ---
  {
    id: "increibles-dash",
    franchise: "Los Increíbles",
    emoji: "🦸",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el hijo de la familia, capaz de correr a toda velocidad?",
    hint: "(Solo el nombre.)",
    accepted: [["Dash"]],
    official: "Dash",
  },
  {
    id: "increibles-elastigirl",
    franchise: "Los Increíbles",
    emoji: "🦸",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuál es el nombre de superheroína de Helen Parr?",
    accepted: [["Elastigirl", "Elástigirl"]],
    official: "Elastigirl",
  },

  // --- Cars ---
  {
    id: "cars-mate",
    franchise: "Cars",
    emoji: "🏎️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la grúa oxidada y bonachona, mejor amigo de Rayo McQueen?",
    hint: "(Solo el nombre.)",
    accepted: [["Mate", "Mater"]],
    official: "Mate",
  },
  {
    id: "cars-radiador",
    franchise: "Cars",
    emoji: "🏎️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el pueblo perdido en el que acaba varado Rayo McQueen?",
    options: ["Radiador Springs", "Motor City", "Villa Pistón", "Ruta Springs"],
    correct: 0,
    official: "Radiador Springs",
  },
  {
    id: "cars-doc",
    franchise: "Cars",
    emoji: "🏎️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el viejo Hudson del pueblo, que fue tres veces campeón?",
    options: ["Doc Hudson", "Rey Weathers", "Sheriff", "Chick Hicks"],
    correct: 0,
    official: "Doc Hudson",
  },

  // --- Ratatouille ---
  {
    id: "ratatouille-gusteau",
    franchise: "Ratatouille",
    emoji: "🍲",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el chef fallecido cuyo lema es «cualquiera puede cocinar»?",
    accepted: [["Gusteau", "Auguste Gusteau"]],
    official: "Auguste Gusteau",
  },
  {
    id: "ratatouille-skinner",
    franchise: "Ratatouille",
    emoji: "🍲",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el chef bajito que dirige el restaurante y sospecha de la rata?",
    options: ["Skinner", "Horst", "Lalo", "Mustafá"],
    correct: 0,
    official: "Skinner",
  },
  {
    id: "ratatouille-colette",
    franchise: "Ratatouille",
    emoji: "🍲",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la única mujer de la cocina, que enseña el oficio al protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Colette"]],
    official: "Colette",
  },

  // --- WALL·E ---
  {
    id: "walle-axiom",
    franchise: "WALL·E",
    emoji: "🛸",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la nave donde viven los humanos?",
    options: ["Axiom", "Odisea", "Buy n Large", "Elysium"],
    correct: 0,
    official: "La Axiom",
  },
  {
    id: "walle-cucaracha",
    franchise: "WALL·E",
    emoji: "🛸",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué bichito acompaña a WALL·E en la Tierra desierta?",
    hint: "(El animal.)",
    accepted: [["cucaracha", "una cucaracha"]],
    official: "Una cucaracha",
  },

  // --- Up ---
  {
    id: "up-dug",
    franchise: "Up",
    emoji: "🎈",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es un perro con un collar que traduce sus pensamientos en voz alta y se distrae con las ardillas.",
    hint: "(Solo el nombre.)",
    accepted: [["Dug", "Doug"]],
    official: "Dug",
  },
  {
    id: "up-russell",
    franchise: "Up",
    emoji: "🎈",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el niño explorador que viaja sin querer en la casa voladora?",
    hint: "(Solo el nombre.)",
    accepted: [["Russell"]],
    official: "Russell",
  },
  {
    id: "up-kevin",
    franchise: "Up",
    emoji: "🎈",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo llama Russell al ave gigante de colores que encuentran?",
    options: ["Kevin", "Carla", "Pipo", "Beta"],
    correct: 0,
    official: "Kevin",
    note: "Resulta ser hembra, pero el nombre se le queda.",
  },

  // --- Del revés ---
  {
    id: "delreves-riley",
    franchise: "Del revés",
    emoji: "🧠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la niña en cuya cabeza viven las emociones?",
    hint: "(Solo el nombre.)",
    accepted: [["Riley"]],
    official: "Riley",
  },
  {
    id: "delreves-bingbong",
    franchise: "Del revés",
    emoji: "🧠",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el amigo imaginario rosa, mezcla de elefante y algodón de azúcar?",
    options: ["Bing Bong", "Bong Bing", "Pomponio", "Ding Dong"],
    correct: 0,
    official: "Bing Bong",
  },
  {
    id: "delreves-ansiedad",
    franchise: "Del revés",
    emoji: "🧠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuál es la nueva emoción que toma el mando en Del revés 2?",
    hint: "(Solo el nombre de la emoción.)",
    accepted: [["Ansiedad"]],
    official: "Ansiedad",
  },

  // --- Coco ---
  {
    id: "coco-ernesto",
    franchise: "Coco",
    emoji: "💀",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el cantante al que Miguel admira y cree que es su bisabuelo?",
    accepted: [["Ernesto de la Cruz", "Ernesto"]],
    official: "Ernesto de la Cruz",
  },
  {
    id: "coco-hector",
    franchise: "Coco",
    emoji: "💀",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el esqueleto tramposo que guía a Miguel por la tierra de los muertos?",
    options: ["Héctor", "Chicharrón", "Julio", "Óscar"],
    correct: 0,
    official: "Héctor",
  },

  // --- Soul ---
  {
    id: "soul-22",
    franchise: "Soul",
    emoji: "🎷",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el alma que lleva siglos negándose a nacer?",
    options: ["22", "7", "Moonwind", "Terry"],
    correct: 0,
    official: "22",
  },

  // --- Red ---
  {
    id: "red-4town",
    franchise: "Red",
    emoji: "🐼",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el grupo musical al que adoran Mei y sus amigas?",
    options: ["4*Town", "5*Star", "3*Boys", "TownBoyz"],
    correct: 0,
    official: "4*Town",
  },

  // --- Elemental ---
  {
    id: "elemental-protagonistas",
    franchise: "Elemental",
    emoji: "🔥",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llaman la chica de fuego y el chico de agua protagonistas?",
    hint: "(Los dos nombres.)",
    accepted: [["Ember"], ["Wade"]],
    official: "Ember y Wade",
  },

  // --- Bichos ---
  {
    id: "bichos-hopper",
    franchise: "Bichos",
    emoji: "🐜",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el saltamontes que extorsiona al hormiguero?",
    options: ["Hopper", "Molt", "Thumper", "Manny"],
    correct: 0,
    official: "Hopper",
  },

  // --- Onward ---
  {
    id: "onward-hermanos",
    franchise: "Onward",
    emoji: "🧝",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llaman los dos hermanos elfos protagonistas?",
    options: ["Ian y Barley", "Ian y Wilden", "Elmo y Barley", "Corey y Ian"],
    correct: 0,
    official: "Ian y Barley",
  },

  // --- Luca ---
  {
    id: "luca-giulia",
    franchise: "Luca",
    emoji: "🛵",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la niña humana que se hace amiga de Luca y Alberto?",
    hint: "(Solo el nombre.)",
    accepted: [["Giulia", "Julia"]],
    official: "Giulia",
  },

  // --- Shrek ---
  {
    id: "shrek-asno",
    franchise: "Shrek",
    emoji: "🧅",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué animal es el compañero parlanchín e insoportable de Shrek?",
    hint: "(El animal.)",
    accepted: [["asno", "burro"]],
    official: "Un asno",
  },
  {
    id: "shrek-duloc",
    franchise: "Shrek",
    emoji: "🧅",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el reino perfectamente ordenado de Lord Farquaad?",
    options: ["Duloc", "Farquaadia", "Muy Muy Lejano", "Vallefresco"],
    correct: 0,
    official: "Duloc",
  },
  {
    id: "shrek-farquaad",
    franchise: "Shrek",
    emoji: "🧅",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el villano bajito de la primera película?",
    options: ["Lord Farquaad", "Rumpelstiltskin", "Charming", "Lord Fiquad"],
    correct: 0,
    official: "Lord Farquaad",
  },

  // --- Madagascar ---
  {
    id: "madagascar-alex",
    franchise: "Madagascar",
    emoji: "🦓",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el león, estrella del zoo de Nueva York?",
    hint: "(Solo el nombre.)",
    accepted: [["Alex"]],
    official: "Alex",
  },
  {
    id: "madagascar-melman",
    franchise: "Madagascar",
    emoji: "🦓",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la jirafa hipocondríaca del grupo?",
    options: ["Melman", "Marty", "Mort", "Maurice"],
    correct: 0,
    official: "Melman",
  },
  {
    id: "madagascar-marty",
    franchise: "Madagascar",
    emoji: "🦓",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la cebra que sueña con vivir en libertad?",
    hint: "(Solo el nombre.)",
    accepted: [["Marty"]],
    official: "Marty",
  },

  // --- Kung Fu Panda ---
  {
    id: "kfp-po",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el panda protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Po"]],
    official: "Po",
  },
  {
    id: "kfp-shifu",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el maestro panda rojo que entrena a Po?",
    hint: "(Solo el nombre.)",
    accepted: [["Shifu"]],
    official: "El maestro Shifu",
  },
  {
    id: "kfp-oogway",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es el maestro Oogway, el más sabio del Valle de la Paz?",
    options: ["Una tortuga", "Un cocodrilo", "Un mono", "Un buitre"],
    correct: 0,
    official: "Una tortuga",
  },
  {
    id: "kfp-ping",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es el señor Ping, el padre adoptivo de Po que regenta el local de fideos?",
    options: ["Un ganso", "Un pato", "Una grulla", "Un cisne"],
    correct: 0,
    official: "Un ganso",
  },

  // --- Cómo entrenar a tu dragón ---
  {
    id: "dragon-hipo",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🐲",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el joven vikingo protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Hipo"]],
    official: "Hipo",
  },
  {
    id: "dragon-astrid",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🐲",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la joven vikinga que acaba siendo pareja del protagonista?",
    options: ["Astrid", "Brusca", "Heather", "Ingrid"],
    correct: 0,
    official: "Astrid",
  },
  {
    id: "dragon-bocon",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🐲",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el herrero manco que instruye a los jóvenes de Mema?",
    options: ["Bocón", "Patapez", "Mocoso", "Gordo"],
    correct: 0,
    official: "Bocón",
  },

  // --- El príncipe de Egipto ---
  {
    id: "egipto-sefora",
    franchise: "El príncipe de Egipto",
    emoji: "🏜️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la mujer con la que se casa Moisés?",
    options: ["Séfora", "Miriam", "Jocabed", "Nefertari"],
    correct: 0,
    official: "Séfora",
  },

  // --- Megamind ---
  {
    id: "megamind-minion",
    franchise: "Megamind",
    emoji: "🦹",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el pez que ayuda a Megamind desde un robot con cuerpo de gorila?",
    options: ["Minion", "Esbirro", "Bubbles", "Gill"],
    correct: 0,
    official: "Minion",
  },

  // --- Los Croods ---
  {
    id: "croods-grug",
    franchise: "Los Croods",
    emoji: "🦴",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el padre cavernícola, obsesionado con no salir de la cueva?",
    options: ["Grug", "Guy", "Thunk", "Ugga"],
    correct: 0,
    official: "Grug",
  },

  // --- El origen de los guardianes ---
  {
    id: "guardianes-pitch",
    franchise: "El origen de los guardianes",
    emoji: "🌙",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el villano que siembra pesadillas?",
    options: ["Pitch", "Sandman", "Norte", "Umbra"],
    correct: 0,
    official: "Pitch, el Coco",
  },

  // --- Trolls ---

  // --- El gato con botas ---
  {
    id: "gatobotas-kitty",
    franchise: "El gato con botas",
    emoji: "🐾",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la gata que acompaña al Gato con Botas?",
    options: [
      "Kitty Patitas Suaves",
      "Kitty Zarpas Blandas",
      "Gata Miau",
      "Perrito",
    ],
    correct: 0,
    official: "Kitty Patitas Suaves",
  },

  // --- Bee Movie ---
  {
    id: "beemovie-demanda",
    franchise: "Bee Movie",
    emoji: "🐝",
    difficulty: "facil",
    format: "vf",
    prompt: "En Bee Movie las abejas llevan a los humanos a juicio por robarles la miel.",
    correct: true,
    official: "Verdadero",
  },

  // --- Mi villano favorito ---
  {
    id: "gru-nefario",
    franchise: "Mi villano favorito",
    emoji: "🌙",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el anciano científico que inventa los cachivaches de Gru?",
    hint: "(Solo el nombre.)",
    accepted: [["Nefario", "Doctor Nefario", "Dr. Nefario"]],
    official: "El doctor Nefario",
  },
  {
    id: "gru-elmacho",
    franchise: "Mi villano favorito",
    emoji: "🌙",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el villano de Gru 2, un luchador mexicano que se creía muerto?",
    options: ["El Macho", "El Diablo", "Balthazar", "Vector"],
    correct: 0,
    official: "El Macho",
  },
  {
    id: "minions-scarlet",
    franchise: "Los Minions",
    emoji: "🍌",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la supervillana a la que sirven los Minions en su propia película?",
    options: ["Scarlet Overkill", "Ruby Steele", "Violet Vicious", "Lucy Wilde"],
    correct: 0,
    official: "Scarlet Overkill",
  },

  // --- Canta ---
  {
    id: "canta-buster",
    franchise: "Canta",
    emoji: "🎤",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es un koala arruinado y optimista que organiza un concurso de canto para salvar su teatro.",
    accepted: [["Buster Moon", "Buster", "Moon"]],
    official: "Buster Moon",
  },
  {
    id: "canta-rosita",
    franchise: "Canta",
    emoji: "🎤",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la cerdita madre de veinticinco cochinillos que se presenta al concurso?",
    options: ["Rosita", "Ash", "Meena", "Nana"],
    correct: 0,
    official: "Rosita",
  },

  // --- El Lorax ---
  {
    id: "lorax-arboles",
    franchise: "El Lorax",
    emoji: "🌳",
    difficulty: "facil",
    format: "vf",
    prompt: "El Lorax se presenta a sí mismo diciendo que habla en nombre de los árboles.",
    correct: true,
    official: "Verdadero",
  },

  // --- El Grinch ---
  {
    id: "grinch-max",
    franchise: "El Grinch",
    emoji: "🎄",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el perro del Grinch, al que disfraza de reno?",
    hint: "(Solo el nombre.)",
    accepted: [["Max"]],
    official: "Max",
  },

  // --- Spider-Man: Un nuevo universo ---
  {
    id: "spiderverse-gwen",
    franchise: "Spider-Man",
    emoji: "🕷️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuál es el nombre real de Spider-Gwen?",
    options: ["Gwen Stacy", "Gwen Watson", "Gwen Parker", "Gwen Morales"],
    correct: 0,
    official: "Gwen Stacy",
  },

  // --- Lluvia de albóndigas ---
  {
    id: "albondigas-flint",
    franchise: "Lluvia de albóndigas",
    emoji: "🍔",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el inventor que crea la máquina que convierte agua en comida?",
    options: ["Flint Lockwood", "Tim Lockwood", "Chester V", "Brent"],
    correct: 0,
    official: "Flint Lockwood",
  },

  // --- Hotel Transilvania ---
  {
    id: "hoteltransilvania-frank",
    franchise: "Hotel Transilvania",
    emoji: "🧛",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué monstruo es Frank, uno de los mejores amigos de Drácula?",
    options: [
      "El monstruo de Frankenstein",
      "Un hombre lobo",
      "Una momia",
      "El hombre invisible",
    ],
    correct: 0,
    official: "El monstruo de Frankenstein",
  },

  // --- El Gigante de Hierro ---
  {
    id: "gigante-espacio",
    franchise: "El Gigante de Hierro",
    emoji: "🤖",
    difficulty: "facil",
    format: "vf",
    prompt: "El Gigante de Hierro es un robot llegado del espacio que cae cerca de un pueblo de Maine.",
    correct: true,
    official: "Verdadero",
  },

  // --- Chicken Run ---
  {
    id: "chickenrun-rocky",
    franchise: "Chicken Run",
    emoji: "🐔",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el gallo americano que presume de saber volar?",
    options: ["Rocky", "Fowler", "Nick", "Mac"],
    correct: 0,
    official: "Rocky",
  },

  // --- Wallace y Gromit ---
  {
    id: "wallace-queso",
    franchise: "Wallace y Gromit",
    emoji: "🧀",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cuál es el queso favorito de Wallace?",
    options: ["Wensleydale", "Cheddar", "Stilton", "Brie"],
    correct: 0,
    official: "El Wensleydale",
  },

  // --- Coraline ---
  {
    id: "coraline-botones",
    franchise: "Coraline",
    emoji: "🔘",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué tienen en los ojos los habitantes del otro mundo de Coraline?",
    hint: "(Una palabra.)",
    accepted: [["botones", "botón"]],
    official: "Botones",
  },

  // --- Pesadilla antes de Navidad ---
  {
    id: "pesadilla-jack",
    franchise: "Pesadilla antes de Navidad",
    emoji: "🎃",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el Rey Calabaza que decide adueñarse de la Navidad?",
    accepted: [["Jack Skellington", "Jack"]],
    official: "Jack Skellington",
  },
  {
    id: "pesadilla-sally",
    franchise: "Pesadilla antes de Navidad",
    emoji: "🎃",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la muñeca de trapo enamorada de Jack?",
    options: ["Sally", "Shock", "Lock", "Emily"],
    correct: 0,
    official: "Sally",
  },

  // --- Anastasia ---

  // --- El Principito ---
  {
    id: "principito-rosa",
    franchise: "El Principito",
    emoji: "🌹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué flor cuida el Principito en su asteroide?",
    hint: "(La flor.)",
    accepted: [["rosa", "una rosa", "la rosa"]],
    official: "Una rosa",
  },

  // --- Klaus ---
  {
    id: "klaus-juguetero",
    franchise: "Klaus",
    emoji: "🛷",
    difficulty: "facil",
    format: "vf",
    prompt: "Klaus es un juguetero solitario que vive apartado en una cabaña del bosque.",
    correct: true,
    official: "Verdadero",
  },

  // --- Orden cronológico y relacionar (transversales) ---
  {
    id: "orden-pixar-primeros",
    franchise: "Pixar clásico",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Bichos", "Buscando a Nemo", "WALL·E", "Del revés"],
    official: "Bichos (1998), Buscando a Nemo (2003), WALL·E (2008) y Del revés (2015)",
  },
  {
    id: "orden-pixar-reciente",
    franchise: "Pixar reciente",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Coco", "Soul", "Luca", "Red"],
    official: "Coco (2017), Soul (2020), Luca (2021) y Red (2022)",
  },
  {
    id: "orden-dreamworks",
    franchise: "DreamWorks",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de DreamWorks de la más antigua a la más reciente.",
    items: ["Shrek", "Madagascar", "Kung Fu Panda", "Los Croods"],
    official: "Shrek (2001), Madagascar (2005), Kung Fu Panda (2008) y Los Croods (2013)",
  },
  {
    id: "relacionar-estudios",
    franchise: "Estudios de animación",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada película con el estudio que la produjo.",
    pairs: [
      { left: "Shrek", right: "DreamWorks" },
      { left: "Coco", right: "Pixar" },
      { left: "Mi villano favorito", right: "Illumination" },
      { left: "Hotel Transilvania", right: "Sony Animation" },
    ],
    official:
      "Shrek–DreamWorks, Coco–Pixar, Mi villano favorito–Illumination y Hotel Transilvania–Sony Animation",
  },
  {
    id: "relacionar-villanos-pixar",
    franchise: "Villanos Pixar",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada villano con su película.",
    pairs: [
      { left: "Hopper", right: "Bichos" },
      { left: "Lotso", right: "Toy Story 3" },
      { left: "Skinner", right: "Ratatouille" },
      { left: "Waternoose", right: "Monstruos S.A." },
    ],
    official: "Hopper–Bichos, Lotso–Toy Story 3, Skinner–Ratatouille y Waternoose–Monstruos S.A.",
  },

  // --- Ice Age ---
  {
    id: "edadhielo-scrat",
    franchise: "Ice Age",
    emoji: "🌰",
    difficulty: "facil",
    format: "describir",
    prompt: "Ardilla dientes de sable que persigue una bellota por toda la película y nunca la consigue.",
    hint: "(Solo el nombre.)",
    accepted: [["Scrat"]],
    official: "Scrat",
  },
  {
    id: "edadhielo-manny",
    franchise: "Ice Age",
    emoji: "🦣",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el mamut gruñón del grupo?",
    hint: "(Solo el nombre.)",
    accepted: [["Manny"]],
    official: "Manny",
  },
  {
    id: "edadhielo-sid",
    franchise: "Ice Age",
    emoji: "🌰",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Sid, el charlatán del grupo?",
    options: ["Un perezoso", "Un oso hormiguero", "Un tejón", "Un mono"],
    correct: 0,
    official: "Un perezoso",
  },
  {
    id: "edadhielo-diego",
    franchise: "Ice Age",
    emoji: "🐯",
    difficulty: "facil",
    format: "vf",
    prompt: "Diego se une al grupo desde el primer momento, sin ninguna segunda intención.",
    correct: false,
    official: "Falso: al principio quiere entregar al bebé a su manada",
  },

  // --- Brave (Indomable) ---
  {
    id: "brave-merida",
    franchise: "Brave",
    emoji: "🏹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la princesa pelirroja escocesa que prefiere el arco a casarse?",
    hint: "(Solo el nombre.)",
    accepted: [["Mérida", "Merida"]],
    official: "Mérida",
  },
  {
    id: "brave-madre",
    franchise: "Brave",
    emoji: "🏹",
    difficulty: "media",
    format: "vf",
    prompt: "Mérida convierte a su madre en loba sin querer, por culpa de un pastel encantado.",
    correct: false,
    official: "Falso: la convierte en osa",
  },

  // --- El viaje de Arlo ---
  {
    id: "arlo-dinosaurio",
    franchise: "El viaje de Arlo",
    emoji: "🦕",
    difficulty: "media",
    format: "multiple",
    prompt: "En esta película de Pixar, ¿qué relación hay entre el dinosaurio Arlo y el niño Spot?",
    options: [
      "El niño es la mascota del dinosaurio",
      "El dinosaurio es la mascota del niño",
      "Son hermanos adoptivos",
      "El niño es un espíritu imaginario",
    ],
    correct: 0,
    official: "El niño hace de mascota del dinosaurio",
    note: "La película imagina que el meteorito nunca cayó y los dinosaurios siguieron vivos.",
  },

  // --- Río ---
  {
    id: "rio-blu",
    franchise: "Río",
    emoji: "🦜",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el guacamayo azul que no sabe volar?",
    hint: "(Solo el nombre.)",
    accepted: [["Blu"]],
    official: "Blu",
  },
  {
    id: "rio-ciudad",
    franchise: "Río",
    emoji: "🦜",
    difficulty: "facil",
    format: "vf",
    prompt: "La película transcurre en São Paulo, en pleno carnaval.",
    correct: false,
    official: "Falso: transcurre en Río de Janeiro",
  },

  // --- Mascotas ---
  {
    id: "mascotas-max",
    franchise: "Mascotas",
    emoji: "🐶",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el terrier protagonista al que le cambia la vida cuando llega Duque?",
    hint: "(Solo el nombre.)",
    accepted: [["Max"]],
    official: "Max",
  },
  {
    id: "mascotas-conejo",
    franchise: "Mascotas",
    emoji: "🐰",
    difficulty: "media",
    format: "describir",
    prompt: "Conejito blanco y adorable que en realidad lidera una banda de animales abandonados.",
    hint: "(Solo el nombre.)",
    accepted: [["Pompón", "Snowball"]],
    official: "Pompón",
    note: "Pompón en el doblaje de España; Snowball en el original.",
  },

  // --- Bichos ---
  {
    id: "bichos-flik",
    franchise: "Bichos",
    emoji: "🐜",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la hormiga inventora que busca guerreros para defender el hormiguero?",
    hint: "(Solo el nombre.)",
    accepted: [["Flik"]],
    official: "Flik",
  },
  {
    id: "bichos-circo",
    franchise: "Bichos",
    emoji: "🐜",
    difficulty: "media",
    format: "vf",
    prompt:
      "Los guerreros que Flik contrata resultan ser soldados de verdad, curtidos en mil batallas.",
    correct: false,
    official: "Falso: son artistas de circo que se hacen pasar por guerreros",
  },

  // --- Buscando a Dory ---
  {
    id: "dory-memoria",
    franchise: "Buscando a Dory",
    emoji: "🐠",
    difficulty: "facil",
    format: "vf",
    prompt: "Dory tiene una memoria excelente y recuerda perfectamente dónde dejó a sus padres.",
    correct: false,
    official: "Falso: apenas puede retener recuerdos, ese es todo el problema",
  },

  // --- Luca ---
  {
    id: "luca-monstruos",
    franchise: "Luca",
    emoji: "🐟",
    difficulty: "media",
    format: "vf",
    prompt: "Luca y Alberto son monstruos marinos que toman forma humana al mojarse.",
    correct: false,
    official: "Falso: es al revés, se vuelven humanos al secarse",
  },
  {
    id: "luca-vespa",
    franchise: "Luca",
    emoji: "🐟",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuál es el gran sueño de Luca y Alberto durante el verano italiano?",
    options: ["Comprarse una Vespa", "Ganar un barco", "Ir a la escuela", "Encontrar un tesoro"],
    correct: 0,
    official: "Comprarse una Vespa",
  },

  // --- Soul ---
  {
    id: "soul-joe",
    franchise: "Soul",
    emoji: "🎬",
    difficulty: "media",
    format: "corta",
    prompt: "¿A qué se dedica Joe Gardner, el protagonista?",
    hint: "(Su oficio o su instrumento.)",
    accepted: [["músico", "pianista", "profesor de música", "piano", "jazz"]],
    official: "Es pianista de jazz y profesor de música",
  },

  // --- Red ---
  {
    id: "red-panda",
    franchise: "Red",
    emoji: "🎬",
    difficulty: "facil",
    format: "corta",
    prompt: "¿En qué animal se transforma Mei cuando se emociona?",
    hint: "(El animal.)",
    accepted: [["panda rojo", "panda", "oso panda rojo"]],
    official: "Un panda rojo gigante",
  },

  // --- Onward ---
  {
    id: "onward-hechizo",
    franchise: "Onward",
    emoji: "🧝",
    difficulty: "media",
    format: "vf",
    prompt: "Los dos hermanos elfos intentan resucitar a su padre con un hechizo que sale a medias.",
    correct: true,
    official: "Verdadero",
    note: "El hechizo solo trae de vuelta la mitad de abajo, de cintura para abajo.",
  },

  // --- Elemental ---
  {
    id: "elemental-parejas",
    franchise: "Elemental",
    emoji: "🎬",
    difficulty: "media",
    format: "multiple",
    prompt: "¿De qué elementos son los dos protagonistas de Elemental?",
    options: ["Fuego y agua", "Tierra y aire", "Fuego y tierra", "Agua y aire"],
    correct: 0,
    official: "Fuego y agua",
  },

  // --- Monstruos University ---
  {
    id: "monstruosu-universidad",
    franchise: "Monstruos University",
    emoji: "🎓",
    difficulty: "media",
    format: "vf",
    prompt: "En esta precuela, Mike y Sulley empiezan siendo rivales antes de hacerse amigos.",
    correct: true,
    official: "Verdadero",
  },

  // --- Toy Story ---
  {
    id: "toystory-zurg",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "media",
    format: "describir",
    prompt: "Villano morado del espacio que se presenta como el padre de Buzz Lightyear.",
    hint: "(Solo el nombre.)",
    accepted: [["Zurg", "Emperador Zurg"]],
    official: "El emperador Zurg",
  },

  // --- Los Increíbles ---
  {
    id: "increibles-edna",
    franchise: "Los Increíbles",
    emoji: "🦸",
    difficulty: "media",
    format: "describir",
    prompt: "Diseñadora bajita de gafas enormes que se niega en rotundo a ponerle capa a un traje.",
    hint: "(Solo el nombre.)",
    accepted: [["Edna", "Edna Moda"]],
    official: "Edna Moda",
  },
  {
    id: "increibles-poderes",
    franchise: "Los Increíbles",
    emoji: "🦸",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el poder de Violeta, la hija mayor?",
    options: [
      "Volverse invisible y crear campos de fuerza",
      "Correr a gran velocidad",
      "Estirarse como una goma",
      "Tener una fuerza descomunal",
    ],
    correct: 0,
    official: "Volverse invisible y crear campos de fuerza",
    note: "Correr es lo de Dash y estirarse, lo de su madre.",
  },

  // --- Ratatouille ---
  {
    id: "ratatouille-lema",
    franchise: "Ratatouille",
    emoji: "🐀",
    difficulty: "media",
    format: "completar",
    prompt: "Completa el lema del chef Gusteau: «Cualquiera puede ___».",
    accepted: [["cocinar"]],
    official: "Cualquiera puede cocinar",
  },


  // --- Coco ---
  {
    id: "coco-dante",
    franchise: "Coco",
    emoji: "💀",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el perro sin pelo que acompaña a Miguel?",
    hint: "(Solo el nombre.)",
    accepted: [["Dante"]],
    official: "Dante",
  },

  // --- Shrek ---
  {
    id: "shrek-cebolla",
    franchise: "Shrek",
    emoji: "👹",
    difficulty: "media",
    format: "completar",
    prompt: "Completa lo que Shrek le explica a Asno: «Los ogros son como las ___: tienen capas».",
    accepted: [["cebollas", "cebolla"]],
    official: "Los ogros son como las cebollas",
  },

  // --- Madagascar ---
  {
    id: "madagascar-julien",
    franchise: "Madagascar",
    emoji: "🦁",
    difficulty: "media",
    format: "describir",
    prompt: "Lémur que se autoproclama rey de la isla y no para de bailar.",
    hint: "(Solo el nombre.)",
    accepted: [["Julien", "Rey Julien"]],
    official: "El rey Julien",
  },
  {
    id: "madagascar-pinguinos",
    franchise: "Madagascar",
    emoji: "🐧",
    difficulty: "media",
    format: "vf",
    prompt:
      "Los cuatro pingüinos se quedaron en un gag de la película y nunca tuvieron nada propio.",
    correct: false,
    official: "Falso: tienen serie y película propias",
  },

  // --- Kung Fu Panda ---

  // --- Cómo entrenar a tu dragón ---
  {
    id: "dragon-desdentao",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🐲",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama en España el dragón furia nocturna de Hipo?",
    hint: "(Una palabra.)",
    accepted: [["Desdentao", "Desdentado"]],
    official: "Desdentao",
  },

  // --- El origen de los guardianes ---
  {
    id: "guardianes-jack",
    franchise: "El origen de los guardianes",
    emoji: "❄️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuál de estos personajes es el protagonista al que nadie ve porque nadie cree en él?",
    options: ["Jack Frost", "Papá Noel", "El Conejo de Pascua", "El Hada de los Dientes"],
    correct: 0,
    official: "Jack Frost",
  },

  // --- El gato con botas ---
  {
    id: "gatobotas-huevo",
    franchise: "El gato con botas",
    emoji: "🐱",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el huevo que fue amigo de la infancia del Gato con Botas?",
    options: ["Humpty Dumpty", "Eggy", "Ovo", "Tortolini"],
    correct: 0,
    official: "Humpty Dumpty",
  },

  // --- Chicken Run ---
  {
    id: "chickenrun-fuga",
    franchise: "Chicken Run",
    emoji: "🐔",
    difficulty: "media",
    format: "vf",
    prompt: "Las gallinas de la granja intentan escapar antes de acabar convertidas en empanadas.",
    correct: true,
    official: "Verdadero",
  },



  // --- Klaus ---
  {
    id: "klaus-cartero",
    franchise: "Klaus",
    emoji: "📮",
    difficulty: "media",
    format: "vf",
    prompt: "Klaus cuenta un origen de Papá Noel a partir de un cartero destinado a una isla helada.",
    correct: true,
    official: "Verdadero",
    note: "Es una película española, dirigida por Sergio Pablos.",
  },

  // --- El Gigante de Hierro ---
  {
    id: "gigantehierro-hogarth",
    franchise: "El Gigante de Hierro",
    emoji: "🤖",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el niño que se hace amigo del gigante metálico?",
    options: ["Hogarth", "Howard", "Herbert", "Hank"],
    correct: 0,
    official: "Hogarth",
  },

  // --- Mi villano favorito ---
  {
    id: "gru-ninas",
    franchise: "Mi villano favorito",
    emoji: "🌙",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llaman las tres niñas que adopta Gru?",
    options: [
      "Margo, Edith y Agnes",
      "Margo, Edith y Alice",
      "Maggie, Edith y Agnes",
      "Margo, Elsa y Agnes",
    ],
    correct: 0,
    official: "Margo, Edith y Agnes",
  },

  // --- Los Minions ---
  {
    id: "minions-color",
    franchise: "Los Minions",
    emoji: "🍌",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De qué color son los minions?",
    hint: "(Un color.)",
    accepted: [["amarillo", "amarillos"]],
    official: "Amarillos",
  },

  // --- El Grinch ---

  // --- Canta ---
  {
    id: "canta-koala",
    franchise: "Canta",
    emoji: "🎤",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es Buster Moon, el dueño del teatro que organiza el concurso?",
    options: ["Un koala", "Un panda", "Un mapache", "Un oso"],
    correct: 0,
    official: "Un koala",
  },

  // --- Spider-Man: Un nuevo universo ---
  {
    id: "spiderverse-miles",
    franchise: "Spider-Man",
    emoji: "🕷️",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el adolescente que se convierte en el nuevo Spider-Man?",
    hint: "(El nombre basta.)",
    accepted: [["Miles", "Miles Morales", "Morales"]],
    official: "Miles Morales",
  },

  // --- Hotel Transilvania ---
  {
    id: "hoteltransilvania-mavis",
    franchise: "Hotel Transilvania",
    emoji: "🧛",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la hija de Drácula que quiere salir a conocer el mundo?",
    hint: "(Solo el nombre.)",
    accepted: [["Mavis"]],
    official: "Mavis",
  },

  // --- Lluvia de albóndigas ---
  {
    id: "albondigas-invento",
    franchise: "Lluvia de albóndigas",
    emoji: "🍔",
    difficulty: "media",
    format: "vf",
    prompt: "El invento de Flint convierte el agua en comida, que empieza a caer del cielo.",
    correct: true,
    official: "Verdadero",
  },

  // --- Cronologías y relaciones de estudios ---
  {
    id: "orden-pixar-90-2000",
    franchise: "Pixar clásico",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Toy Story", "Monstruos S.A.", "Los Increíbles", "Cars"],
    official: "Toy Story (1995), Monstruos S.A. (2001), Los Increíbles (2004) y Cars (2006)",
  },
  {
    id: "orden-pixar-2010",
    franchise: "Pixar reciente",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Up", "Toy Story 3", "Del revés", "Coco"],
    official: "Up (2009), Toy Story 3 (2010), Del revés (2015) y Coco (2017)",
  },
  {
    id: "orden-pixar-2020",
    franchise: "Pixar reciente",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Onward", "Luca", "Red", "Elemental"],
    official: "Onward (2020), Luca (2021), Red (2022) y Elemental (2023)",
  },
  {
    id: "orden-dreamworks-amplio",
    franchise: "DreamWorks",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de DreamWorks de la más antigua a la más reciente.",
    items: ["El príncipe de Egipto", "Shrek", "Cómo entrenar a tu dragón", "Trolls"],
    official:
      "El príncipe de Egipto (1998), Shrek (2001), Cómo entrenar a tu dragón (2010) y Trolls (2016)",
  },
  {
    id: "orden-illumination",
    franchise: "Estudios de animación",
    emoji: "🎞️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cuál de estas películas es la más antigua?",
    options: ["Mi villano favorito", "El Lorax", "Los Minions", "El Grinch"],
    correct: 0,
    official: "Mi villano favorito (2010)",
    note: "Después llegaron El Lorax (2012), Los Minions (2015) y El Grinch (2018).",
  },
  {
    id: "relacionar-pixar-protagonistas",
    franchise: "Pixar clásico",
    emoji: "🎬",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada protagonista con su película.",
    pairs: [
      { left: "Remy", right: "Ratatouille" },
      { left: "Carl", right: "Up" },
      { left: "Miguel", right: "Coco" },
      { left: "Riley", right: "Del revés" },
    ],
    official: "Remy–Ratatouille, Carl–Up, Miguel–Coco y Riley–Del revés",
  },
  {
    id: "relacionar-pixar-mascotas",
    franchise: "Pixar reciente",
    emoji: "🎬",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada animal con la película en la que aparece.",
    pairs: [
      { left: "Dante", right: "Coco" },
      { left: "Dug", right: "Up" },
      { left: "Hank", right: "Buscando a Dory" },
      { left: "Scrat", right: "Ice Age" },
    ],
    official: "Dante–Coco, Dug–Up, Hank–Buscando a Dory y Scrat–Ice Age",
  },
  {
    id: "relacionar-dreamworks-personajes",
    franchise: "DreamWorks",
    emoji: "🎬",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada personaje con su película.",
    pairs: [
      { left: "Po", right: "Kung Fu Panda" },
      { left: "Fiona", right: "Shrek" },
      { left: "Alex", right: "Madagascar" },
      { left: "Hipo", right: "Cómo entrenar a tu dragón" },
    ],
    official: "Po–Kung Fu Panda, Fiona–Shrek, Alex–Madagascar e Hipo–Cómo entrenar a tu dragón",
  },
  {
    id: "estudios-quien-hizo-dragon",
    franchise: "Estudios de animación",
    emoji: "🏢",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué estudio hizo Cómo entrenar a tu dragón?",
    options: ["DreamWorks", "Pixar", "Illumination", "Sony Animation"],
    correct: 0,
    official: "DreamWorks",
  },
  {
    id: "relacionar-emociones-reves",
    franchise: "Del revés",
    emoji: "🧠",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada emoción de Del revés con su color.",
    pairs: [
      { left: "Alegría", right: "Amarillo" },
      { left: "Tristeza", right: "Azul" },
      { left: "Ira", right: "Rojo" },
      { left: "Asco", right: "Verde" },
    ],
    official: "Alegría–amarillo, Tristeza–azul, Ira–rojo y Asco–verde",
  },
  {
    id: "relacionar-robots-pelicula",
    franchise: "Robots de la animación",
    emoji: "🤖",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada robot con la película en la que aparece.",
    pairs: [
      { left: "Baymax", right: "Big Hero 6" },
      { left: "EVA", right: "WALL·E" },
      { left: "Zurg", right: "Toy Story" },
    ],
    official: "Baymax–Big Hero 6, EVA–WALL·E y Zurg–Toy Story",
  },
  {
    id: "vf-pixar-lampara",
    franchise: "Pixar clásico",
    emoji: "💡",
    difficulty: "media",
    format: "vf",
    prompt: "El logotipo de Pixar incluye una lámpara de escritorio que aplasta la letra I.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "vf-toystory-primera",
    franchise: "Pixar clásico",
    emoji: "🎬",
    difficulty: "media",
    format: "vf",
    prompt: "Shrek fue el primer largometraje hecho enteramente por ordenador.",
    correct: false,
    official: "Falso: fue Toy Story, seis años antes",
  },
  {
    id: "describir-sulley",
    franchise: "Monstruos S.A.",
    emoji: "👾",
    difficulty: "facil",
    format: "describir",
    prompt: "Monstruo enorme, azul con lunares morados, el mejor asustador de la fábrica.",
    hint: "(Solo el nombre.)",
    accepted: [["Sulley", "Sully", "James P. Sullivan"]],
    official: "Sulley",
  },
  {
    id: "describir-gru",
    franchise: "Mi villano favorito",
    emoji: "🌙",
    difficulty: "facil",
    format: "describir",
    prompt: "Villano narizón de bufanda y acento raro que planea robar la Luna.",
    hint: "(Solo el nombre.)",
    accepted: [["Gru"]],
    official: "Gru",
  },

  // --- Secuelas: Toy Story ---
  {
    id: "toystory-forky",
    franchise: "Toy Story",
    emoji: "🍴",
    difficulty: "facil",
    format: "corta",
    prompt: "En Toy Story 4, ¿con qué objeto de plástico fabrica Bonnie su juguete nuevo?",
    hint: "(Un cubierto.)",
    accepted: [["tenedor", "un tenedor"]],
    official: "Con un tenedor de plástico",
  },
  {
    id: "toystory-guarderia",
    franchise: "Toy Story",
    emoji: "🧸",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿A dónde van a parar los juguetes en Toy Story 3?",
    options: ["A una guardería", "A un desván", "A un mercadillo", "A un museo"],
    correct: 0,
    official: "A una guardería",
  },
  {
    id: "toystory-ken",
    franchise: "Toy Story",
    emoji: "💇",
    difficulty: "media",
    format: "vf",
    prompt: "En Toy Story 3, Ken y Barbie se caen fatal desde el primer momento.",
    correct: false,
    official: "Falso: se enamoran nada más verse",
  },
  {
    id: "toystory-betty",
    franchise: "Toy Story",
    emoji: "🐑",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama en España la pastorcilla de porcelana que reaparece en Toy Story 4?",
    hint: "(Solo el nombre.)",
    accepted: [["Betty", "Bo Peep"]],
    official: "Betty",
  },
  {
    id: "toystory-basurero",
    franchise: "Toy Story",
    emoji: "🔥",
    difficulty: "media",
    format: "vf",
    prompt: "En Toy Story 3 los juguetes acaban salvándose por los pelos de un incinerador de basura.",
    correct: true,
    official: "Verdadero",
  },

  // --- Secuelas: Shrek ---
  {
    id: "shrek-suegros",
    franchise: "Shrek",
    emoji: "🏰",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿A quién conoce Shrek en la segunda película?",
    options: ["A los padres de Fiona", "A los padres de Asno", "Al rey Arturo", "A Rumpelstiltskin"],
    correct: 0,
    official: "A los padres de Fiona",
  },
  {
    id: "shrek-gatobotas-aparicion",
    franchise: "Shrek",
    emoji: "🧅",
    difficulty: "facil",
    format: "vf",
    prompt: "El Gato con Botas aparece por primera vez en Shrek 3.",
    correct: false,
    official: "Falso: aparece en Shrek 2, contratado para matar a Shrek",
  },
  {
    id: "shrek-hada",
    franchise: "Shrek",
    emoji: "🧚",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Quién es la villana de Shrek 2?",
    options: ["El Hada Madrina", "La Reina Malvada", "Rumpelstiltskin", "Lord Farquaad"],
    correct: 0,
    official: "El Hada Madrina",
  },
  {
    id: "shrek-arturo",
    franchise: "Shrek",
    emoji: "👑",
    difficulty: "media",
    format: "vf",
    prompt: "En Shrek 3, Shrek sale a buscar a un heredero al trono para no tener que reinar él.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "shrek-hijos",
    franchise: "Shrek",
    emoji: "👶",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuántos hijos tienen Shrek y Fiona al final de la saga?",
    options: ["Tres", "Uno", "Dos", "Cuatro"],
    correct: 0,
    official: "Tres",
  },

  // --- Secuelas: Madagascar ---
  {
    id: "madagascar-africa",
    franchise: "Madagascar",
    emoji: "🌍",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿A dónde llegan los animales en la segunda película?",
    options: ["A África", "A la Antártida", "A Australia", "A la India"],
    correct: 0,
    official: "A África",
  },
  {
    id: "madagascar-circo",
    franchise: "Madagascar",
    emoji: "🎪",
    difficulty: "facil",
    format: "vf",
    prompt: "En la tercera película los protagonistas se esconden en un circo ambulante por Europa.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "madagascar-padre",
    franchise: "Madagascar",
    emoji: "🦁",
    difficulty: "media",
    format: "vf",
    prompt: "En Madagascar 2, Alex llega a África pero no consigue dar con su familia.",
    correct: false,
    official: "Falso: se reencuentra con sus padres",
  },

  // --- Secuelas: Kung Fu Panda ---
  {
    id: "kfp-shen",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es Lord Shen, el villano de Kung Fu Panda 2?",
    options: ["Un pavo real", "Un buitre", "Un cocodrilo", "Un rinoceronte"],
    correct: 0,
    official: "Un pavo real",
  },
  {
    id: "kfp-padre",
    franchise: "Kung Fu Panda",
    emoji: "🐼",
    difficulty: "facil",
    format: "vf",
    prompt: "En Kung Fu Panda 3, Po conoce a su padre panda y descubre un pueblo entero de pandas.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "kfp-kai",
    franchise: "Kung Fu Panda",
    emoji: "🐂",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el villano toro que roba el chi de los maestros en Kung Fu Panda 3?",
    options: ["Kai", "Kang", "Kong", "Kuro"],
    correct: 0,
    official: "Kai",
  },
  {
    id: "kfp-camaleona",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es la villana de Kung Fu Panda 4, capaz de copiar cualquier técnica?",
    options: ["Una camaleona", "Una serpiente", "Una loba", "Una araña"],
    correct: 0,
    official: "Una camaleona",
  },

  // --- Secuelas: Cómo entrenar a tu dragón ---
  {
    id: "dragon-madre",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🐲",
    difficulty: "facil",
    format: "vf",
    prompt: "En la segunda película, Hipo reencuentra a su padre, al que creía muerto.",
    correct: false,
    official: "Falso: a quien reencuentra es a su madre",
  },
  {
    id: "dragon-mundooculto",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🌋",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué buscan los vikingos y los dragones en la tercera película?",
    options: ["El Mundo Oculto", "La Isla del Fuego", "El Nido del Alfa", "Las Tierras Altas"],
    correct: 0,
    official: "El Mundo Oculto",
  },
  {
    id: "dragon-furiadiurna",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🤍",
    difficulty: "media",
    format: "vf",
    prompt: "En la tercera película, Desdentao se enamora de una dragona blanca, la Furia Diurna.",
    correct: true,
    official: "Verdadero",
  },

  // --- Secuelas: Mi villano favorito y los Minions ---
  {
    id: "gru-lucy",
    franchise: "Mi villano favorito",
    emoji: "💘",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la agente pelirroja de la que se enamora Gru en la segunda película?",
    hint: "(Solo el nombre.)",
    accepted: [["Lucy"]],
    official: "Lucy",
  },
  {
    id: "gru-hermano",
    franchise: "Mi villano favorito",
    emoji: "👱",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué descubre Gru en la tercera película?",
    options: [
      "Que tiene un hermano gemelo",
      "Que su madre era una villana",
      "Que es adoptado",
      "Que tiene otra hija",
    ],
    correct: 0,
    official: "Que tiene un hermano gemelo, Dru",
  },
  {
    id: "gru-anti-villanos",
    franchise: "Mi villano favorito",
    emoji: "🕵️",
    difficulty: "media",
    format: "vf",
    prompt:
      "En la segunda película, Gru rechaza trabajar para la liga anti-villanos y sigue de villano.",
    correct: false,
    official: "Falso: acaba trabajando para ellos",
  },
  {
    id: "minions-tres",
    franchise: "Los Minions",
    emoji: "🍌",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llaman los tres minions protagonistas de su propia película?",
    options: [
      "Kevin, Stuart y Bob",
      "Kevin, Dave y Bob",
      "Stuart, Dave y Jerry",
      "Kevin, Stuart y Tim",
    ],
    correct: 0,
    official: "Kevin, Stuart y Bob",
  },
  {
    id: "minions-origen",
    franchise: "Los Minions",
    emoji: "🍌",
    difficulty: "media",
    format: "vf",
    prompt: "La segunda película de los Minions cuenta cómo conocieron a Gru ya de adulto.",
    correct: false,
    official: "Falso: lo conocen siendo Gru un niño",
  },

  // --- Secuelas: Ice Age ---
  {
    id: "iceage-deshielo",
    franchise: "Ice Age",
    emoji: "🌰",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el peligro de la segunda película de Ice Age?",
    options: [
      "El hielo se derrite y viene una inundación",
      "Un volcán en erupción",
      "Unos cazadores",
      "Una tormenta de nieve",
    ],
    correct: 0,
    official: "El deshielo y la inundación",
  },
  {
    id: "iceage-ellie",
    franchise: "Ice Age",
    emoji: "🦣",
    difficulty: "media",
    format: "vf",
    prompt: "Ellie, la mamut que conoce Manny, se había criado con otros mamuts.",
    correct: false,
    official: "Falso: se crio con zarigüeyas y se creía una de ellas",
  },
  {
    id: "iceage-dinosaurios",
    franchise: "Ice Age",
    emoji: "🌰",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Con qué se topan los protagonistas en la tercera película?",
    options: ["Con dinosaurios", "Con piratas", "Con humanos", "Con extraterrestres"],
    correct: 0,
    official: "Con dinosaurios",
  },
  {
    id: "iceage-espacio",
    franchise: "Ice Age",
    emoji: "🚀",
    difficulty: "media",
    format: "vf",
    prompt: "En la quinta película, Scrat acaba liándola en el espacio con una nave alienígena.",
    correct: true,
    official: "Verdadero",
  },

  // --- Secuelas: Cars ---
  {
    id: "cars-espias",
    franchise: "Cars",
    emoji: "🕵️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿De qué va Cars 2?",
    options: [
      "Mate se ve metido en una trama de espías",
      "Rayo se retira",
      "Sally monta un hotel",
      "Doc vuelve a competir",
    ],
    correct: 0,
    official: "Mate se ve metido en una trama de espías",
  },
  {
    id: "cars-cruz",
    franchise: "Cars",
    emoji: "🏁",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la joven entrenadora amarilla que aparece en Cars 3?",
    hint: "(El nombre basta.)",
    accepted: [["Cruz", "Cruz Ramírez", "Ramírez"]],
    official: "Cruz Ramírez",
  },
  {
    id: "cars-storm",
    franchise: "Cars",
    emoji: "⚡",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el corredor de nueva generación que desbanca a Rayo en Cars 3?",
    options: ["Jackson Storm", "Chick Hicks", "Rey Weathers", "Cal Weathers"],
    correct: 0,
    official: "Jackson Storm",
  },

  // --- Secuelas: Los Increíbles y Del revés ---
  {
    id: "increibles-elastigirl-2",
    franchise: "Los Increíbles",
    emoji: "🦸",
    difficulty: "facil",
    format: "vf",
    prompt: "En Los Increíbles 2, es Elastigirl la que sale a trabajar y Bob el que se queda en casa.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "increibles-jackjack",
    franchise: "Los Increíbles",
    emoji: "👶",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué pasa con Jack-Jack en la segunda película?",
    options: [
      "Se le descubren un montón de poderes a la vez",
      "Pierde sus poderes",
      "Lo secuestran",
      "Se hace mayor de golpe",
    ],
    correct: 0,
    official: "Se le descubren un montón de poderes a la vez",
  },
  {
    id: "delreves-nuevas",
    franchise: "Del revés",
    emoji: "😳",
    difficulty: "media",
    format: "multiple",
    prompt: "Además de Ansiedad, ¿qué otras emociones nuevas llegan en Del revés 2?",
    options: [
      "Envidia, Vergüenza y Aburrimiento",
      "Envidia, Orgullo y Culpa",
      "Vergüenza, Culpa y Nostalgia",
      "Aburrimiento, Orgullo y Envidia",
    ],
    correct: 0,
    official: "Envidia, Vergüenza y Aburrimiento",
  },
  {
    id: "delreves-adolescente",
    franchise: "Del revés",
    emoji: "🧠",
    difficulty: "facil",
    format: "vf",
    prompt: "Del revés 2 arranca cuando Riley se marcha a la universidad.",
    correct: false,
    official: "Falso: arranca cuando llega a la adolescencia",
  },

  // --- Secuelas: Hotel Transilvania, Canta, El gato con botas ---
  {
    id: "hoteltransilvania-nieto",
    franchise: "Hotel Transilvania",
    emoji: "🧛",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué le preocupa a Drácula en la segunda película?",
    options: [
      "Que su nieto no tenga colmillos",
      "Que cierren el hotel",
      "Que Mavis se mude",
      "Que lo descubran los humanos",
    ],
    correct: 0,
    official: "Que su nieto no tenga colmillos",
  },
  {
    id: "hoteltransilvania-crucero",
    franchise: "Hotel Transilvania",
    emoji: "🧛",
    difficulty: "media",
    format: "vf",
    prompt: "La tercera película transcurre entera dentro del hotel, sin salir de él.",
    correct: false,
    official: "Falso: los monstruos se van de crucero",
  },
  {
    id: "hoteltransilvania-humanos",
    franchise: "Hotel Transilvania",
    emoji: "🔮",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué ocurre en la cuarta película?",
    options: [
      "Los monstruos se vuelven humanos y al revés",
      "El hotel se hunde",
      "Drácula pierde sus poderes para siempre",
      "Mavis se convierte en humana",
    ],
    correct: 0,
    official: "Los monstruos se vuelven humanos y los humanos, monstruos",
  },
  {
    id: "canta-ciudad",
    franchise: "Canta",
    emoji: "🎤",
    difficulty: "media",
    format: "vf",
    prompt:
      "En Canta 2, la pandilla decide quedarse en su teatro de siempre y no salir de la ciudad.",
    correct: false,
    official: "Falso: se van a probar suerte a una gran ciudad del espectáculo",
  },
  {
    id: "canta-leon",
    franchise: "Canta",
    emoji: "🎤",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué animal es Clay Calloway, la estrella retirada que buscan en Canta 2?",
    options: ["Un león", "Un lobo", "Un oso", "Un tigre"],
    correct: 0,
    official: "Un león",
  },
  {
    id: "gatobotas-vidas",
    franchise: "El gato con botas",
    emoji: "🐾",
    difficulty: "facil",
    format: "corta",
    prompt: "En El último deseo, ¿cuántas de sus vidas le quedan al Gato al empezar?",
    hint: "(Un número.)",
    accepted: [["1", "una"]],
    official: "Una",
  },
  {
    id: "gatobotas-muerte",
    franchise: "El gato con botas",
    emoji: "🐾",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Quién persigue al Gato en El último deseo?",
    options: ["La Muerte, en forma de lobo", "Un cazarrecompensas", "Humpty Dumpty", "Un dragón"],
    correct: 0,
    official: "La Muerte, con forma de lobo",
  },

  // --- Secuelas: Trolls, Río y Vaiana ---
  {
    id: "trolls-generos",
    franchise: "Trolls",
    emoji: "🎸",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué descubren los trolls en Gira mundial?",
    options: [
      "Que hay tribus de trolls de otros estilos musicales",
      "Que la música se acaba",
      "Que son robots",
      "Que viven en un sueño",
    ],
    correct: 0,
    official: "Que hay tribus de trolls de otros estilos musicales",
  },
  {
    id: "trolls-ramon",
    franchise: "Trolls",
    emoji: "💙",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama en España el troll gruñón y azul que acompaña a Poppy?",
    hint: "(Solo el nombre.)",
    accepted: [["Ramón"]],
    official: "Ramón",
  },
  {
    id: "trolls-banda",
    franchise: "Trolls",
    emoji: "🎤",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué se cuenta en la tercera película de Trolls?",
    options: [
      "Que Ramón tuvo una banda con sus hermanos",
      "Que Poppy es adoptada",
      "Que los trolls pierden la voz",
      "Que el reino se hunde",
    ],
    correct: 0,
    official: "Que Ramón tuvo una banda de pop con sus hermanos",
  },
  {
    id: "rio-amazonas",
    franchise: "Río",
    emoji: "🌴",
    difficulty: "media",
    format: "multiple",
    prompt: "¿A dónde viajan Blu y Perla en Río 2?",
    options: ["Al Amazonas", "A Nueva York", "A la Patagonia", "A África"],
    correct: 0,
    official: "Al Amazonas",
  },
  {
    id: "rio-familia",
    franchise: "Río",
    emoji: "🦜",
    difficulty: "media",
    format: "vf",
    prompt: "En Río 2, Blu y Perla descubren que quedan más guacamayos azules en libertad.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "vaiana-secuela",
    franchise: "Vaiana",
    emoji: "⛵",
    difficulty: "facil",
    format: "vf",
    prompt: "En Vaiana 2, la protagonista vuelve a hacerse a la mar con una tripulación, ya no sola.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "vaiana-maui-vuelve",
    franchise: "Vaiana",
    emoji: "🪝",
    difficulty: "facil",
    format: "vf",
    prompt: "Maui no aparece en Vaiana 2.",
    correct: false,
    official: "Falso: vuelve a acompañarla",
  },

  // --- Sagas en conjunto ---
  {
    id: "orden-secuelas-pixar",
    franchise: "Pixar reciente",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas secuelas de Pixar de la más antigua a la más reciente.",
    items: ["Toy Story 3", "Monstruos University", "Los Increíbles 2", "Del revés 2"],
    official:
      "Toy Story 3 (2010), Monstruos University (2013), Los Increíbles 2 (2018) y Del revés 2 (2024)",
  },
  {
    id: "relacionar-secuelas-villanos",
    franchise: "Estudios de animación",
    emoji: "😈",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada villano con la secuela en la que aparece.",
    pairs: [
      { left: "Lotso", right: "Toy Story 3" },
      { left: "Lord Shen", right: "Kung Fu Panda 2" },
      { left: "El Hada Madrina", right: "Shrek 2" },
      { left: "Jackson Storm", right: "Cars 3" },
    ],
    official:
      "Lotso–Toy Story 3, Lord Shen–Kung Fu Panda 2, el Hada Madrina–Shrek 2 y Jackson Storm–Cars 3",
  },
  {
    id: "sagas-mas-largas",
    franchise: "Estudios de animación",
    emoji: "🔢",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cuál de estas sagas de animación tiene más películas?",
    options: ["Ice Age", "Toy Story", "Kung Fu Panda", "Cómo entrenar a tu dragón"],
    correct: 0,
    official: "Ice Age, con cinco",
  },
  {
    id: "completar-gatobotas-deseo",
    franchise: "El gato con botas",
    emoji: "⭐",
    difficulty: "media",
    format: "completar",
    prompt: "Completa el título de la segunda película del Gato con Botas: «El último ___».",
    accepted: [["deseo"]],
    official: "El último deseo",
  },

  // --- Ice Age ---
  {
    id: "iceage-bebe",
    franchise: "Ice Age",
    emoji: "👶",
    difficulty: "facil",
    format: "vf",
    prompt: "La primera película arranca con la manada intentando devolver un bebé humano a su tribu.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "iceage-bellota",
    franchise: "Ice Age",
    emoji: "🦣",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué persigue Scrat sin descanso a lo largo de toda la saga?",
    hint: "(Un fruto.)",
    accepted: [["bellota", "una bellota", "la bellota"]],
    official: "Una bellota",
  },
  {
    id: "iceage-buck",
    franchise: "Ice Age",
    emoji: "🗡️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es Buck, el aventurero tuerto del mundo de los dinosaurios?",
    options: ["Una comadreja", "Un tejón", "Un zorro", "Una nutria"],
    correct: 0,
    official: "Una comadreja",
  },

  // --- Río ---
  {
    id: "rio-linda",
    franchise: "Río",
    emoji: "👩",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la dueña de Blu, que lo crio desde pequeño?",
    hint: "(Solo el nombre.)",
    accepted: [["Linda"]],
    official: "Linda",
  },
  {
    id: "rio-nigel",
    franchise: "Río",
    emoji: "🌴",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué ave es Nigel, el villano de la primera película?",
    options: ["Una cacatúa", "Un cuervo", "Un buitre", "Un halcón"],
    correct: 0,
    official: "Una cacatúa",
  },

  // --- Hotel Transilvania ---
  {
    id: "hoteltransilvania-johnny",
    franchise: "Hotel Transilvania",
    emoji: "🎒",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el humano mochilero que se cuela en el hotel?",
    hint: "(Solo el nombre.)",
    accepted: [["Johnny", "Jonathan"]],
    official: "Johnny",
  },
  {
    id: "hoteltransilvania-clientes",
    franchise: "Hotel Transilvania",
    emoji: "🏨",
    difficulty: "facil",
    format: "vf",
    prompt: "El hotel de Drácula es un alojamiento para turistas humanos.",
    correct: false,
    official: "Falso: es justo al revés, un refugio de monstruos lejos de los humanos",
  },

  // --- Coraline ---
  {
    id: "coraline-otramadre",
    franchise: "Coraline",
    emoji: "🚪",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué encuentra Coraline al cruzar la puertecita tapiada de su casa?",
    hint: "(Un lugar.)",
    accepted: [["otro mundo", "un mundo paralelo", "el otro mundo", "mundo paralelo"]],
    official: "Un mundo paralelo, igual al suyo pero mejor",
  },
  {
    id: "coraline-gato",
    franchise: "Coraline",
    emoji: "🐈‍⬛",
    difficulty: "media",
    format: "vf",
    prompt: "El gato negro que acompaña a Coraline no habla en ningún momento.",
    correct: false,
    official: "Falso: en el otro mundo habla",
  },

  // --- Wallace y Gromit ---
  {
    id: "wallace-gromit",
    franchise: "Wallace y Gromit",
    emoji: "🧀",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Quién es Gromit?",
    options: ["El perro de Wallace", "Su vecino", "Su sobrino", "Su socio inventor"],
    correct: 0,
    official: "El perro de Wallace",
  },
  {
    id: "wallace-habla",
    franchise: "Wallace y Gromit",
    emoji: "🤐",
    difficulty: "facil",
    format: "vf",
    prompt: "Gromit no dice ni una palabra en toda la serie: se expresa solo con la mirada.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "wallace-tecnica",
    franchise: "Wallace y Gromit",
    emoji: "🧀",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Con qué técnica está hecha la serie?",
    options: ["Con plastilina, cuadro a cuadro", "A mano, en papel", "Por ordenador", "Con recortables"],
    correct: 0,
    official: "Con plastilina, cuadro a cuadro",
  },

  // --- Chicken Run ---
  {
    id: "chickenrun-ginger",
    franchise: "Chicken Run",
    emoji: "🐔",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la gallina que organiza la fuga de la granja?",
    hint: "(Solo el nombre.)",
    accepted: [["Ginger"]],
    official: "Ginger",
  },
  {
    id: "chickenrun-tecnica",
    franchise: "Chicken Run",
    emoji: "🐔",
    difficulty: "facil",
    format: "vf",
    prompt: "Chicken Run está hecha con animación por ordenador.",
    correct: false,
    official: "Falso: es plastilina, del mismo estudio que Wallace y Gromit",
  },

  // --- El Gigante de Hierro ---
  {
    id: "gigante-come",
    franchise: "El Gigante de Hierro",
    emoji: "🔩",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De qué se alimenta el gigante?",
    hint: "(Un material.)",
    accepted: [["metal", "hierro", "chatarra", "acero"]],
    official: "De metal",
  },
  {
    id: "gigante-arma",
    franchise: "El Gigante de Hierro",
    emoji: "🕊️",
    difficulty: "media",
    format: "vf",
    prompt: "El gigante descubre que fue construido como arma, y decide no comportarse como tal.",
    correct: true,
    official: "Verdadero",
  },

  // --- Anastasia ---
  {
    id: "anastasia-pais",
    franchise: "Anastasia",
    emoji: "🇷🇺",
    difficulty: "media",
    format: "multiple",
    prompt: "¿De qué país es la princesa Anastasia?",
    options: ["De Rusia", "De Austria", "De Francia", "De Inglaterra"],
    correct: 0,
    official: "De Rusia",
  },

  // --- El Principito ---
  {
    id: "principito-zorro",
    franchise: "El Principito",
    emoji: "🦊",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa la frase del zorro: «Lo esencial es invisible a los ___».",
    accepted: [["ojos"]],
    official: "Lo esencial es invisible a los ojos",
  },

  // --- Pesadilla antes de Navidad ---
  {
    id: "pesadilla-pueblo",
    franchise: "Pesadilla antes de Navidad",
    emoji: "🎲",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué pueblo es el rey Jack Skellington?",
    options: ["Del pueblo de Halloween", "Del pueblo de Navidad", "Del pueblo de Pascua", "Del pueblo del Terror"],
    correct: 0,
    official: "Del pueblo de Halloween",
  },
  {
    id: "pesadilla-oogie",
    franchise: "Pesadilla antes de Navidad",
    emoji: "🎲",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el saco lleno de bichos que hace de villano?",
    hint: "(Dos palabras.)",
    accepted: [["Oogie Boogie", "Oogie"]],
    official: "Oogie Boogie",
  },
  {
    id: "pesadilla-perro",
    franchise: "Pesadilla antes de Navidad",
    emoji: "👻",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el perro fantasma de Jack, con la nariz de calabaza?",
    hint: "(Solo el nombre.)",
    accepted: [["Zero"]],
    official: "Zero",
  },

  // --- Lluvia de albóndigas ---
  {
    id: "albondigas-pueblo",
    franchise: "Lluvia de albóndigas",
    emoji: "🌭",
    difficulty: "facil",
    format: "vf",
    prompt: "En la película, la comida que cae del cielo va siendo cada vez más pequeña.",
    correct: false,
    official: "Falso: se va haciendo gigante",
  },
  {
    id: "albondigas-mono",
    franchise: "Lluvia de albóndigas",
    emoji: "🐒",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el mono que acompaña a Flint y habla con un traductor?",
    options: ["Steve", "Bob", "Mike", "Coco"],
    correct: 0,
    official: "Steve",
  },

  // --- Laika ---
  {
    id: "boxtrolls-que-son",
    franchise: "Los Boxtrolls",
    emoji: "🎬",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué llevan puesto los boxtrolls a modo de ropa?",
    options: ["Cajas de cartón", "Latas", "Hojas", "Sacos de tela"],
    correct: 0,
    official: "Cajas de cartón",
  },
  {
    id: "boxtrolls-tecnica",
    franchise: "Los Boxtrolls",
    emoji: "🧱",
    difficulty: "media",
    format: "vf",
    prompt: "Los Boxtrolls está hecha con animación por ordenador.",
    correct: false,
    official: "Falso: es stop-motion, del estudio Laika",
  },
  {
    id: "kubo-instrumento",
    franchise: "Kubo",
    emoji: "🎎",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Con qué hace magia Kubo?",
    options: ["Con un instrumento de cuerda", "Con una espada", "Con un abanico", "Con un tambor"],
    correct: 0,
    official: "Con un instrumento de cuerda, tocando y plegando papel",
  },
  {
    id: "kubo-papel",
    franchise: "Kubo",
    emoji: "🎎",
    difficulty: "facil",
    format: "vf",
    prompt: "La magia de Kubo consiste en dar vida a figuras de papel plegado.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "paranorman-don",
    franchise: "ParaNorman",
    emoji: "👻",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué puede hacer Norman que nadie más puede?",
    options: ["Ver y hablar con los muertos", "Volar", "Leer la mente", "Ver el futuro"],
    correct: 0,
    official: "Ver y hablar con los muertos",
  },
  {
    id: "paranorman-zombis",
    franchise: "ParaNorman",
    emoji: "🧟",
    difficulty: "media",
    format: "vf",
    prompt: "En ParaNorman los zombis resultan ser más víctimas que monstruos.",
    correct: true,
    official: "Verdadero",
  },

  // --- Modernas ---
  {
    id: "mitchells-familia",
    franchise: "Los Mitchell contra las máquinas",
    emoji: "🚗",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿A quién se enfrenta la familia Mitchell durante su viaje en coche?",
    options: [
      "A una rebelión de máquinas",
      "A una plaga de insectos",
      "A unos ladrones",
      "A un huracán",
    ],
    correct: 0,
    official: "A una rebelión de máquinas y robots",
  },
  {
    id: "mitchells-perro",
    franchise: "Los Mitchell contra las máquinas",
    emoji: "🐶",
    difficulty: "media",
    format: "vf",
    prompt: "El perro de la familia resulta ser clave porque los robots no saben si es perro o pan.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "robotsalvaje-premisa",
    franchise: "El robot salvaje",
    emoji: "🤖",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Dónde acaba el robot protagonista de El robot salvaje?",
    options: [
      "En una isla desierta llena de animales",
      "En una ciudad futurista",
      "En una fábrica",
      "En el espacio",
    ],
    correct: 0,
    official: "En una isla desierta, entre animales salvajes",
  },
  {
    id: "robotsalvaje-oca",
    franchise: "El robot salvaje",
    emoji: "🦆",
    difficulty: "media",
    format: "vf",
    prompt: "El robot acaba criando a una cría de ganso como si fuera su madre.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "nimona-forma",
    franchise: "Nimona",
    emoji: "🦈",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuál es el poder de Nimona?",
    options: [
      "Cambiar de forma y convertirse en cualquier animal",
      "Volverse invisible",
      "Volar",
      "Controlar el fuego",
    ],
    correct: 0,
    official: "Cambiar de forma",
  },
  {
    id: "nimona-caballero",
    franchise: "Nimona",
    emoji: "⚔️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿De qué se acusa injustamente al caballero al que Nimona se une?",
    options: ["De asesinar a la reina", "De robar la corona", "De traicionar al reino", "De brujería"],
    correct: 0,
    official: "De asesinar a la reina",
  },

  // --- DreamWorks: Shrek ---
  {
    id: "shrek-fiona-noche",
    franchise: "Shrek",
    emoji: "🌙",
    difficulty: "facil",
    format: "vf",
    prompt: "Fiona se transforma en ogro al caer la noche por culpa de un hechizo.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "shrek-dragona",
    franchise: "Shrek",
    emoji: "🐉",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Quién custodia la torre donde está encerrada Fiona?",
    options: ["Una dragona", "Un ejército", "Un ogro", "Un mago"],
    correct: 0,
    official: "Una dragona, que acaba enamorándose de Asno",
  },
  {
    id: "shrek-cuentos",
    franchise: "Shrek",
    emoji: "📖",
    difficulty: "facil",
    format: "vf",
    prompt: "En el pantano de Shrek acaban refugiados un montón de personajes de cuentos clásicos.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "shrek-vive",
    franchise: "Shrek",
    emoji: "🏚️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Dónde vive Shrek?",
    hint: "(Un sitio.)",
    accepted: [["pantano", "un pantano", "su pantano", "ciénaga"]],
    official: "En un pantano",
  },

  // --- DreamWorks: Madagascar ---
  {
    id: "madagascar-zoo",
    franchise: "Madagascar",
    emoji: "🗽",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De dónde se escapan los animales al principio de la primera película?",
    options: ["Del zoo de Nueva York", "Del zoo de Londres", "De un circo", "De una reserva"],
    correct: 0,
    official: "Del zoo de Central Park, en Nueva York",
  },
  {
    id: "madagascar-gloria",
    franchise: "Madagascar",
    emoji: "🌍",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué animal es Gloria?",
    hint: "(El animal.)",
    accepted: [["hipopótamo", "hipopótama", "una hipopótama"]],
    official: "Una hipopótama",
  },
  {
    id: "madagascar-pinguinos-nombres",
    franchise: "Madagascar",
    emoji: "🐧",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llaman los cuatro pingüinos?",
    options: [
      "Skipper, Kowalski, Rico y Cabo",
      "Skipper, Kowalski, Rico y Bob",
      "Capitán, Kowalski, Rico y Cabo",
      "Skipper, Nikolai, Rico y Cabo",
    ],
    correct: 0,
    official: "Skipper, Kowalski, Rico y Cabo",
  },
  {
    id: "madagascar-marty-rayas",
    franchise: "Madagascar",
    emoji: "🌍",
    difficulty: "facil",
    format: "vf",
    prompt: "Marty es un caballo que sueña con conocer la naturaleza salvaje.",
    correct: false,
    official: "Falso: es una cebra",
  },

  // --- DreamWorks: Kung Fu Panda y dragones ---
  {
    id: "kfp-guerrero",
    franchise: "Kung Fu Panda",
    emoji: "🐉",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué título recibe Po al ser elegido?",
    hint: "(Dos palabras.)",
    accepted: [["Guerrero Dragón", "el Guerrero Dragón"]],
    official: "El Guerrero Dragón",
  },
  {
    id: "kfp-cinco",
    franchise: "Kung Fu Panda",
    emoji: "🥋",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el grupo de maestros del Palacio de Jade?",
    options: ["Los Cinco Furiosos", "Los Cinco Guerreros", "Los Cinco Dragones", "Los Cinco Sabios"],
    correct: 0,
    official: "Los Cinco Furiosos",
  },
  {
    id: "kfp-fideos",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "facil",
    format: "vf",
    prompt: "Antes de ser Guerrero Dragón, Po trabajaba de carnicero.",
    correct: false,
    official: "Falso: trabajaba en el puesto de fideos de su padre",
  },
  {
    id: "dragon-berk",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🏝️",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la isla donde viven los vikingos de la película?",
    hint: "(Una palabra.)",
    accepted: [["Berk"]],
    official: "Berk",
  },
  {
    id: "dragon-pierna",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🦿",
    difficulty: "facil",
    format: "vf",
    prompt: "Al final de la primera película, Hipo pierde una pierna, igual que Desdentao perdió parte de la cola.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "dragon-vikingos",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "⚔️",
    difficulty: "facil",
    format: "vf",
    prompt: "Al principio, los vikingos de Berk y los dragones son amigos.",
    correct: false,
    official: "Falso: llevan generaciones matándose",
  },

  // --- DreamWorks: el resto ---
  {
    id: "gatobotas-espada",
    franchise: "El gato con botas",
    emoji: "🐱",
    difficulty: "facil",
    format: "vf",
    prompt: "El Gato con Botas pelea con espada y lleva sombrero de mosquetero.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "gatobotas-ojos",
    franchise: "El gato con botas",
    emoji: "🥺",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el truco favorito del Gato con Botas para ablandar a cualquiera?",
    options: ["Poner ojitos tiernos", "Ronronear", "Fingir que duerme", "Cantar"],
    correct: 0,
    official: "Poner ojitos tiernos",
  },
  {
    id: "trolls-cantan",
    franchise: "Trolls",
    emoji: "🎶",
    difficulty: "facil",
    format: "vf",
    prompt: "Los trolls se pasan el día cantando, bailando y abrazándose.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "croods-epoca",
    franchise: "Los Croods",
    emoji: "🕳️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué época vive la familia Croods?",
    options: ["En la prehistoria", "En la Edad Media", "En el futuro", "En la Antigüedad"],
    correct: 0,
    official: "En la prehistoria",
  },
  {
    id: "croods-cueva",
    franchise: "Los Croods",
    emoji: "🕳️",
    difficulty: "facil",
    format: "vf",
    prompt: "Los Croods sobreviven porque no salen nunca de su cueva, hasta que esta se destruye.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "beemovie-abeja",
    franchise: "Bee Movie",
    emoji: "⚖️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué animal es Barry, el protagonista?",
    hint: "(El animal.)",
    accepted: [["abeja", "una abeja"]],
    official: "Una abeja",
  },
  {
    id: "beemovie-juicio",
    franchise: "Bee Movie",
    emoji: "⚖️",
    difficulty: "facil",
    format: "vf",
    prompt: "Barry acaba llevando a los humanos a juicio por quedarse con toda la miel.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "egipto-moises",
    franchise: "El príncipe de Egipto",
    emoji: "🌊",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué personaje bíblico protagoniza la película?",
    hint: "(Solo el nombre.)",
    accepted: [["Moisés", "Moises"]],
    official: "Moisés",
  },
  {
    id: "egipto-mar",
    franchise: "El príncipe de Egipto",
    emoji: "🌊",
    difficulty: "facil",
    format: "vf",
    prompt: "Una de las escenas más recordadas es la apertura del mar Rojo.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "megamind-villano",
    franchise: "Megamind",
    emoji: "🦹",
    difficulty: "facil",
    format: "vf",
    prompt: "Megamind es un supervillano que se queda sin sentido en la vida al derrotar al héroe.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "megamind-cabeza",
    franchise: "Megamind",
    emoji: "🦹",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo es físicamente Megamind?",
    options: [
      "Azul y con la cabeza enorme",
      "Verde y con cuernos",
      "Rojo y bajito",
      "Gris y sin cara",
    ],
    correct: 0,
    official: "Azul y con una cabeza enorme",
  },
  {
    id: "guardianes-quienes",
    franchise: "El origen de los guardianes",
    emoji: "🎅",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Quiénes son los guardianes que protegen a los niños?",
    options: [
      "Papá Noel, el Conejo de Pascua, el Hada de los Dientes y Sandman",
      "Los Reyes Magos",
      "Cuatro superhéroes",
      "Cuatro hadas",
    ],
    correct: 0,
    official: "Papá Noel, el Conejo de Pascua, el Hada de los Dientes y Sandman",
  },
  {
    id: "guardianes-creer",
    franchise: "El origen de los guardianes",
    emoji: "✨",
    difficulty: "media",
    format: "vf",
    prompt: "Los guardianes existen mientras los niños crean en ellos.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "spirit-animal",
    franchise: "Spirit",
    emoji: "🎬",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué animal es Spirit?",
    hint: "(El animal.)",
    accepted: [["caballo", "un caballo", "mustango", "potro"]],
    official: "Un caballo mustango",
  },
  {
    id: "spirit-habla",
    franchise: "Spirit",
    emoji: "🎬",
    difficulty: "media",
    format: "vf",
    prompt: "Spirit habla con los humanos a lo largo de la película.",
    correct: false,
    official: "Falso: los caballos no hablan, solo hay una voz que narra sus pensamientos",
  },
  {
    id: "monstruosaliens-premisa",
    franchise: "Monstruos contra alienígenas",
    emoji: "👽",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿A quién recluta el gobierno para frenar una invasión alienígena?",
    options: ["A un grupo de monstruos", "Al ejército", "A unos superhéroes", "A unos robots"],
    correct: 0,
    official: "A un grupo de monstruos",
  },
  {
    id: "anastasia-bartok",
    franchise: "Anastasia",
    emoji: "🇷🇺",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es Bartok, el ayudante parlanchín del villano?",
    options: ["Un murciélago", "Un cuervo", "Una rata", "Un gato"],
    correct: 0,
    official: "Un murciélago",
  },
  {
    id: "principito-cordero",
    franchise: "El Principito",
    emoji: "🌹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué le pide el Principito al piloto que le dibuje nada más conocerse?",
    hint: "(Un animal.)",
    accepted: [["cordero", "un cordero", "oveja", "una oveja"]],
    official: "Un cordero",
  },
  {
    id: "trolls-bergen",
    franchise: "Trolls",
    emoji: "😋",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué creen los bergen que necesitan para ser felices?",
    options: ["Comerse un troll", "Robarles la música", "Vivir con ellos", "Dormir cien años"],
    correct: 0,
    official: "Comerse un troll",
  },
  {
    id: "coco-guitarra",
    franchise: "Coco",
    emoji: "💀",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué instrumento quiere tocar Miguel contra la voluntad de su familia?",
    hint: "(Un instrumento.)",
    accepted: [["guitarra", "la guitarra"]],
    official: "La guitarra",
  },
  {
    id: "walle-eva",
    franchise: "WALL·E",
    emoji: "🥚",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la robot blanca y ovalada que llega a la Tierra?",
    hint: "(Solo el nombre.)",
    accepted: [["EVA", "Eve"]],
    official: "EVA",
  },
];
