import type { Question } from "../types";

/** Pixar, DreamWorks, Illumination, Sony y otros estudios de largometraje. */
export const ESTUDIOS: Question[] = [
  // --- Toy Story ---
  {
    id: "toystory-andy",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el niño dueño de Woody y Buzz?",
    hint: "(Solo el nombre.)",
    accepted: [["Andy"]],
    official: "Andy",
  },
  {
    id: "toystory-sid",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el vecino que destroza y recompone juguetes?",
    hint: "(Solo el nombre.)",
    accepted: [["Sid"]],
    official: "Sid",
  },
  {
    id: "toystory-jessie",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la vaquera pelirroja que aparece en Toy Story 2?",
    hint: "(Solo el nombre.)",
    accepted: [["Jessie"]],
    official: "Jessie",
  },
  {
    id: "toystory-lotso",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el oso de peluche rosa que manda en la guardería en Toy Story 3?",
    options: ["Lotso", "Bigotitos", "Chuckles", "Ken"],
    correct: 0,
    official: "Lotso",
  },
  {
    id: "toystory-infinito",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa la frase de Buzz Lightyear: «Hasta el ___ y más allá».",
    accepted: [["infinito"]],
    official: "Hasta el infinito y más allá",
  },

  // --- Monstruos S.A. ---
  {
    id: "monstruos-boo",
    franchise: "Monstruos S.A.",
    emoji: "👹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo llama Sulley a la niña humana que se cuela en la fábrica?",
    hint: "(Solo el nombre.)",
    accepted: [["Boo"]],
    official: "Boo",
  },
  {
    id: "monstruos-waternoose",
    franchise: "Monstruos S.A.",
    emoji: "👹",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el presidente de la fábrica Monstruos S.A.?",
    options: ["Waternoose", "Fungus", "Roz", "Nictófilo"],
    correct: 0,
    official: "Henry J. Waternoose",
  },
  {
    id: "monstruos-celia",
    franchise: "Monstruos S.A.",
    emoji: "👹",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es la recepcionista de la fábrica, novia de Mike, y en lugar de pelo tiene serpientes.",
    hint: "(Solo el nombre.)",
    accepted: [["Celia"]],
    official: "Celia",
  },

  // --- Buscando a Nemo / Dory ---
  {
    id: "nemo-bruce",
    franchise: "Buscando a Nemo",
    emoji: "🐠",
    difficulty: "facil",
    format: "corta",
    prompt:
      "¿Cómo se llama el tiburón que lidera el grupo de escualos que intentan no comer peces?",
    hint: "(Solo el nombre.)",
    accepted: [["Bruce"]],
    official: "Bruce",
  },
  {
    id: "nemo-nigel",
    franchise: "Buscando a Nemo",
    emoji: "🐠",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Nigel, el que ayuda a Marlin en el puerto de Sídney?",
    options: ["Un pelícano", "Una gaviota", "Un cormorán", "Un albatros"],
    correct: 0,
    official: "Un pelícano",
  },
  {
    id: "dory-hank",
    franchise: "Buscando a Dory",
    emoji: "🐙",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el pulpo de siete tentáculos que ayuda a Dory?",
    options: ["Hank", "Bailey", "Destiny", "Gerald"],
    correct: 0,
    official: "Hank",
  },

  // --- Los Increíbles ---
  {
    id: "increibles-dash",
    franchise: "Los Increíbles",
    emoji: "🦸",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el hijo de la familia, capaz de correr a toda velocidad?",
    hint: "(Solo el nombre.)",
    accepted: [["Dash"]],
    official: "Dash",
  },
  {
    id: "increibles-elastigirl",
    franchise: "Los Increíbles",
    emoji: "🦸",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuál es el nombre de superheroína de Helen Parr?",
    accepted: [["Elastigirl", "Elástigirl"]],
    official: "Elastigirl",
  },

  // --- Cars ---
  {
    id: "cars-mate",
    franchise: "Cars",
    emoji: "🏎️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la grúa oxidada y bonachona, mejor amigo de Rayo McQueen?",
    hint: "(Solo el nombre.)",
    accepted: [["Mate", "Mater"]],
    official: "Mate",
  },
  {
    id: "cars-radiador",
    franchise: "Cars",
    emoji: "🏎️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el pueblo perdido en el que acaba varado Rayo McQueen?",
    options: ["Radiador Springs", "Motor City", "Villa Pistón", "Ruta Springs"],
    correct: 0,
    official: "Radiador Springs",
  },
  {
    id: "cars-doc",
    franchise: "Cars",
    emoji: "🏎️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el viejo Hudson del pueblo, que fue tres veces campeón?",
    options: ["Doc Hudson", "Rey Weathers", "Sheriff", "Chick Hicks"],
    correct: 0,
    official: "Doc Hudson",
  },

  // --- Ratatouille ---
  {
    id: "ratatouille-gusteau",
    franchise: "Ratatouille",
    emoji: "🍲",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el chef fallecido cuyo lema es «cualquiera puede cocinar»?",
    accepted: [["Gusteau", "Auguste Gusteau"]],
    official: "Auguste Gusteau",
  },
  {
    id: "ratatouille-skinner",
    franchise: "Ratatouille",
    emoji: "🍲",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el chef bajito que dirige el restaurante y sospecha de la rata?",
    options: ["Skinner", "Horst", "Lalo", "Mustafá"],
    correct: 0,
    official: "Skinner",
  },
  {
    id: "ratatouille-colette",
    franchise: "Ratatouille",
    emoji: "🍲",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la única mujer de la cocina, que enseña el oficio al protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Colette"]],
    official: "Colette",
  },

  // --- WALL·E ---
  {
    id: "walle-axiom",
    franchise: "WALL·E",
    emoji: "🛸",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la nave donde viven los humanos?",
    options: ["Axiom", "Odisea", "Buy n Large", "Elysium"],
    correct: 0,
    official: "La Axiom",
  },
  {
    id: "walle-cucaracha",
    franchise: "WALL·E",
    emoji: "🛸",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué bichito acompaña a WALL·E en la Tierra desierta?",
    hint: "(El animal.)",
    accepted: [["cucaracha", "una cucaracha"]],
    official: "Una cucaracha",
  },

  // --- Up ---
  {
    id: "up-dug",
    franchise: "Up",
    emoji: "🎈",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es un perro con un collar que traduce sus pensamientos en voz alta y se distrae con las ardillas.",
    hint: "(Solo el nombre.)",
    accepted: [["Dug", "Doug"]],
    official: "Dug",
  },
  {
    id: "up-russell",
    franchise: "Up",
    emoji: "🎈",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el niño explorador que viaja sin querer en la casa voladora?",
    hint: "(Solo el nombre.)",
    accepted: [["Russell"]],
    official: "Russell",
  },
  {
    id: "up-kevin",
    franchise: "Up",
    emoji: "🎈",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo llama Russell al ave gigante de colores que encuentran?",
    options: ["Kevin", "Carla", "Pipo", "Beta"],
    correct: 0,
    official: "Kevin",
    note: "Resulta ser hembra, pero el nombre se le queda.",
  },

  // --- Del revés ---
  {
    id: "delreves-riley",
    franchise: "Del revés",
    emoji: "🧠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la niña en cuya cabeza viven las emociones?",
    hint: "(Solo el nombre.)",
    accepted: [["Riley"]],
    official: "Riley",
  },
  {
    id: "delreves-bingbong",
    franchise: "Del revés",
    emoji: "🧠",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el amigo imaginario rosa, mezcla de elefante y algodón de azúcar?",
    options: ["Bing Bong", "Bong Bing", "Pomponio", "Ding Dong"],
    correct: 0,
    official: "Bing Bong",
  },
  {
    id: "delreves-ansiedad",
    franchise: "Del revés",
    emoji: "🧠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuál es la nueva emoción que toma el mando en Del revés 2?",
    hint: "(Solo el nombre de la emoción.)",
    accepted: [["Ansiedad"]],
    official: "Ansiedad",
  },

  // --- Coco ---
  {
    id: "coco-ernesto",
    franchise: "Coco",
    emoji: "💀",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el cantante al que Miguel admira y cree que es su bisabuelo?",
    accepted: [["Ernesto de la Cruz", "Ernesto"]],
    official: "Ernesto de la Cruz",
  },
  {
    id: "coco-hector",
    franchise: "Coco",
    emoji: "💀",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el esqueleto tramposo que guía a Miguel por la tierra de los muertos?",
    options: ["Héctor", "Chicharrón", "Julio", "Óscar"],
    correct: 0,
    official: "Héctor",
  },

  // --- Soul ---
  {
    id: "soul-22",
    franchise: "Soul",
    emoji: "🎷",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el alma que lleva siglos negándose a nacer?",
    options: ["22", "7", "Moonwind", "Terry"],
    correct: 0,
    official: "22",
  },

  // --- Red ---
  {
    id: "red-4town",
    franchise: "Red",
    emoji: "🐼",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el grupo musical al que adoran Mei y sus amigas?",
    options: ["4*Town", "5*Star", "3*Boys", "TownBoyz"],
    correct: 0,
    official: "4*Town",
  },

  // --- Elemental ---
  {
    id: "elemental-protagonistas",
    franchise: "Elemental",
    emoji: "🔥",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llaman la chica de fuego y el chico de agua protagonistas?",
    hint: "(Los dos nombres.)",
    accepted: [["Ember"], ["Wade"]],
    official: "Ember y Wade",
  },

  // --- Bichos ---
  {
    id: "bichos-hopper",
    franchise: "Bichos",
    emoji: "🐜",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el saltamontes que extorsiona al hormiguero?",
    options: ["Hopper", "Molt", "Thumper", "Manny"],
    correct: 0,
    official: "Hopper",
  },

  // --- Onward ---
  {
    id: "onward-hermanos",
    franchise: "Onward",
    emoji: "🧝",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llaman los dos hermanos elfos protagonistas?",
    options: ["Ian y Barley", "Ian y Wilden", "Elmo y Barley", "Corey y Ian"],
    correct: 0,
    official: "Ian y Barley",
  },

  // --- Luca ---
  {
    id: "luca-giulia",
    franchise: "Luca",
    emoji: "🛵",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la niña humana que se hace amiga de Luca y Alberto?",
    hint: "(Solo el nombre.)",
    accepted: [["Giulia", "Julia"]],
    official: "Giulia",
  },

  // --- Shrek ---
  {
    id: "shrek-asno",
    franchise: "Shrek",
    emoji: "🧅",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué animal es el compañero parlanchín e insoportable de Shrek?",
    hint: "(El animal.)",
    accepted: [["asno", "burro"]],
    official: "Un asno",
  },
  {
    id: "shrek-duloc",
    franchise: "Shrek",
    emoji: "🧅",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el reino perfectamente ordenado de Lord Farquaad?",
    options: ["Duloc", "Farquaadia", "Muy Muy Lejano", "Vallefresco"],
    correct: 0,
    official: "Duloc",
  },
  {
    id: "shrek-farquaad",
    franchise: "Shrek",
    emoji: "🧅",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el villano bajito de la primera película?",
    options: ["Lord Farquaad", "Rumpelstiltskin", "Charming", "Lord Fiquad"],
    correct: 0,
    official: "Lord Farquaad",
  },

  // --- Madagascar ---
  {
    id: "madagascar-alex",
    franchise: "Madagascar",
    emoji: "🦓",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el león, estrella del zoo de Nueva York?",
    hint: "(Solo el nombre.)",
    accepted: [["Alex"]],
    official: "Alex",
  },
  {
    id: "madagascar-melman",
    franchise: "Madagascar",
    emoji: "🦓",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la jirafa hipocondríaca del grupo?",
    options: ["Melman", "Marty", "Mort", "Maurice"],
    correct: 0,
    official: "Melman",
  },
  {
    id: "madagascar-marty",
    franchise: "Madagascar",
    emoji: "🦓",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la cebra que sueña con vivir en libertad?",
    hint: "(Solo el nombre.)",
    accepted: [["Marty"]],
    official: "Marty",
  },

  // --- Kung Fu Panda ---
  {
    id: "kfp-po",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el panda protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Po"]],
    official: "Po",
  },
  {
    id: "kfp-shifu",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el maestro panda rojo que entrena a Po?",
    hint: "(Solo el nombre.)",
    accepted: [["Shifu"]],
    official: "El maestro Shifu",
  },
  {
    id: "kfp-oogway",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es el maestro Oogway, el más sabio del Valle de la Paz?",
    options: ["Una tortuga", "Un cocodrilo", "Un mono", "Un buitre"],
    correct: 0,
    official: "Una tortuga",
  },
  {
    id: "kfp-ping",
    franchise: "Kung Fu Panda",
    emoji: "🥟",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es el señor Ping, el padre adoptivo de Po que regenta el local de fideos?",
    options: ["Un ganso", "Un pato", "Una grulla", "Un cisne"],
    correct: 0,
    official: "Un ganso",
  },

  // --- Cómo entrenar a tu dragón ---
  {
    id: "dragon-hipo",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🐲",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el joven vikingo protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Hipo"]],
    official: "Hipo",
  },
  {
    id: "dragon-astrid",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🐲",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la joven vikinga que acaba siendo pareja del protagonista?",
    options: ["Astrid", "Brusca", "Heather", "Ingrid"],
    correct: 0,
    official: "Astrid",
  },
  {
    id: "dragon-bocon",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🐲",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el herrero manco que instruye a los jóvenes de Mema?",
    options: ["Bocón", "Patapez", "Mocoso", "Gordo"],
    correct: 0,
    official: "Bocón",
  },

  // --- El príncipe de Egipto ---
  {
    id: "egipto-sefora",
    franchise: "El príncipe de Egipto",
    emoji: "🏜️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la mujer con la que se casa Moisés?",
    options: ["Séfora", "Miriam", "Jocabed", "Nefertari"],
    correct: 0,
    official: "Séfora",
  },

  // --- Megamind ---
  {
    id: "megamind-minion",
    franchise: "Megamind",
    emoji: "🦹",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el pez que ayuda a Megamind desde un robot con cuerpo de gorila?",
    options: ["Minion", "Esbirro", "Bubbles", "Gill"],
    correct: 0,
    official: "Minion",
  },

  // --- Los Croods ---
  {
    id: "croods-grug",
    franchise: "Los Croods",
    emoji: "🦴",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el padre cavernícola, obsesionado con no salir de la cueva?",
    options: ["Grug", "Guy", "Thunk", "Ugga"],
    correct: 0,
    official: "Grug",
  },

  // --- El origen de los guardianes ---
  {
    id: "guardianes-pitch",
    franchise: "El origen de los guardianes",
    emoji: "🌙",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el villano que siembra pesadillas?",
    options: ["Pitch", "Sandman", "Norte", "Umbra"],
    correct: 0,
    official: "Pitch, el Coco",
  },

  // --- Trolls ---
  {
    id: "trolls-poppy",
    franchise: "Trolls",
    emoji: "🎨",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la princesa troll, siempre optimista y de color rosa?",
    hint: "(Solo el nombre.)",
    accepted: [["Poppy"]],
    official: "Poppy",
  },

  // --- El gato con botas ---
  {
    id: "gatobotas-kitty",
    franchise: "El gato con botas",
    emoji: "🐈",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama la gata que acompaña al Gato con Botas?",
    options: [
      "Kitty Patitas Suaves",
      "Kitty Zarpas Blandas",
      "Gata Miau",
      "Perrito",
    ],
    correct: 0,
    official: "Kitty Patitas Suaves",
  },

  // --- Bee Movie ---
  {
    id: "beemovie-demanda",
    franchise: "Bee Movie",
    emoji: "🐝",
    difficulty: "facil",
    format: "vf",
    prompt: "En Bee Movie las abejas llevan a los humanos a juicio por robarles la miel.",
    correct: true,
    official: "Verdadero",
  },

  // --- Mi villano favorito ---
  {
    id: "gru-nefario",
    franchise: "Mi villano favorito",
    emoji: "🌙",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el anciano científico que inventa los cachivaches de Gru?",
    hint: "(Solo el nombre.)",
    accepted: [["Nefario", "Doctor Nefario", "Dr. Nefario"]],
    official: "El doctor Nefario",
  },
  {
    id: "gru-elmacho",
    franchise: "Mi villano favorito",
    emoji: "🌙",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el villano de Gru 2, un luchador mexicano que se creía muerto?",
    options: ["El Macho", "El Diablo", "Balthazar", "Vector"],
    correct: 0,
    official: "El Macho",
  },
  {
    id: "minions-scarlet",
    franchise: "Los Minions",
    emoji: "🍌",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la supervillana a la que sirven los Minions en su propia película?",
    options: ["Scarlet Overkill", "Ruby Steele", "Violet Vicious", "Lucy Wilde"],
    correct: 0,
    official: "Scarlet Overkill",
  },

  // --- Canta ---
  {
    id: "canta-buster",
    franchise: "Canta",
    emoji: "🎤",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es un koala arruinado y optimista que organiza un concurso de canto para salvar su teatro.",
    accepted: [["Buster Moon", "Buster", "Moon"]],
    official: "Buster Moon",
  },
  {
    id: "canta-rosita",
    franchise: "Canta",
    emoji: "🎤",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la cerdita madre de veinticinco cochinillos que se presenta al concurso?",
    options: ["Rosita", "Ash", "Meena", "Nana"],
    correct: 0,
    official: "Rosita",
  },

  // --- El Lorax ---
  {
    id: "lorax-arboles",
    franchise: "El Lorax",
    emoji: "🌳",
    difficulty: "facil",
    format: "vf",
    prompt: "El Lorax se presenta a sí mismo diciendo que habla en nombre de los árboles.",
    correct: true,
    official: "Verdadero",
  },

  // --- El Grinch ---
  {
    id: "grinch-max",
    franchise: "El Grinch",
    emoji: "🎄",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el perro del Grinch, al que disfraza de reno?",
    hint: "(Solo el nombre.)",
    accepted: [["Max"]],
    official: "Max",
  },

  // --- Spider-Man: Un nuevo universo ---
  {
    id: "spiderverse-gwen",
    franchise: "Spider-Man: Un nuevo universo",
    emoji: "🕷️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuál es el nombre real de Spider-Gwen?",
    options: ["Gwen Stacy", "Gwen Watson", "Gwen Parker", "Gwen Morales"],
    correct: 0,
    official: "Gwen Stacy",
  },

  // --- Lluvia de albóndigas ---
  {
    id: "albondigas-flint",
    franchise: "Lluvia de albóndigas",
    emoji: "🍔",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el inventor que crea la máquina que convierte agua en comida?",
    options: ["Flint Lockwood", "Tim Lockwood", "Chester V", "Brent"],
    correct: 0,
    official: "Flint Lockwood",
  },

  // --- Hotel Transilvania ---
  {
    id: "hoteltransilvania-frank",
    franchise: "Hotel Transilvania",
    emoji: "🧛",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué monstruo es Frank, uno de los mejores amigos de Drácula?",
    options: [
      "El monstruo de Frankenstein",
      "Un hombre lobo",
      "Una momia",
      "El hombre invisible",
    ],
    correct: 0,
    official: "El monstruo de Frankenstein",
  },

  // --- El Gigante de Hierro ---
  {
    id: "gigante-espacio",
    franchise: "El Gigante de Hierro",
    emoji: "🤖",
    difficulty: "facil",
    format: "vf",
    prompt: "El Gigante de Hierro es un robot llegado del espacio que cae cerca de un pueblo de Maine.",
    correct: true,
    official: "Verdadero",
  },

  // --- Chicken Run ---
  {
    id: "chickenrun-rocky",
    franchise: "Chicken Run",
    emoji: "🐔",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el gallo americano que presume de saber volar?",
    options: ["Rocky", "Fowler", "Nick", "Mac"],
    correct: 0,
    official: "Rocky",
  },

  // --- Wallace y Gromit ---
  {
    id: "wallace-queso",
    franchise: "Wallace y Gromit",
    emoji: "🧀",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cuál es el queso favorito de Wallace?",
    options: ["Wensleydale", "Cheddar", "Stilton", "Brie"],
    correct: 0,
    official: "El Wensleydale",
  },

  // --- Coraline ---
  {
    id: "coraline-botones",
    franchise: "Coraline",
    emoji: "🔘",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué tienen en los ojos los habitantes del otro mundo de Coraline?",
    hint: "(Una palabra.)",
    accepted: [["botones", "botón"]],
    official: "Botones",
  },

  // --- Pesadilla antes de Navidad ---
  {
    id: "pesadilla-jack",
    franchise: "Pesadilla antes de Navidad",
    emoji: "🎃",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el Rey Calabaza que decide adueñarse de la Navidad?",
    accepted: [["Jack Skellington", "Jack"]],
    official: "Jack Skellington",
  },
  {
    id: "pesadilla-sally",
    franchise: "Pesadilla antes de Navidad",
    emoji: "🎃",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la muñeca de trapo enamorada de Jack?",
    options: ["Sally", "Shock", "Lock", "Emily"],
    correct: 0,
    official: "Sally",
  },

  // --- Anastasia ---
  {
    id: "anastasia-rasputin",
    franchise: "Anastasia",
    emoji: "👑",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el hechicero que maldice a la familia imperial rusa?",
    options: ["Rasputín", "Dimitri", "Vladimir", "Bartok"],
    correct: 0,
    official: "Rasputín",
  },

  // --- El Principito ---
  {
    id: "principito-rosa",
    franchise: "El Principito",
    emoji: "🌹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué flor cuida el Principito en su asteroide?",
    hint: "(La flor.)",
    accepted: [["rosa", "una rosa", "la rosa"]],
    official: "Una rosa",
  },

  // --- Klaus ---
  {
    id: "klaus-juguetero",
    franchise: "Klaus",
    emoji: "🛷",
    difficulty: "facil",
    format: "vf",
    prompt: "Klaus es un juguetero solitario que vive apartado en una cabaña del bosque.",
    correct: true,
    official: "Verdadero",
  },

  // --- Orden cronológico y relacionar (transversales) ---
  {
    id: "orden-pixar-primeros",
    franchise: "Pixar clásico",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Bichos", "Buscando a Nemo", "WALL·E", "Del revés"],
    official: "Bichos (1998), Buscando a Nemo (2003), WALL·E (2008) y Del revés (2015)",
  },
  {
    id: "orden-pixar-reciente",
    franchise: "Pixar reciente",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Coco", "Soul", "Luca", "Red"],
    official: "Coco (2017), Soul (2020), Luca (2021) y Red (2022)",
  },
  {
    id: "orden-dreamworks",
    franchise: "DreamWorks",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de DreamWorks de la más antigua a la más reciente.",
    items: ["Shrek", "Madagascar", "Kung Fu Panda", "Los Croods"],
    official: "Shrek (2001), Madagascar (2005), Kung Fu Panda (2008) y Los Croods (2013)",
  },
  {
    id: "relacionar-estudios",
    franchise: "Estudios de animación",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada película con el estudio que la produjo.",
    pairs: [
      { left: "Shrek", right: "DreamWorks" },
      { left: "Coco", right: "Pixar" },
      { left: "Mi villano favorito", right: "Illumination" },
      { left: "Hotel Transilvania", right: "Sony Animation" },
    ],
    official:
      "Shrek–DreamWorks, Coco–Pixar, Mi villano favorito–Illumination y Hotel Transilvania–Sony Animation",
  },
  {
    id: "relacionar-villanos-pixar",
    franchise: "Villanos Pixar",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada villano con su película.",
    pairs: [
      { left: "Hopper", right: "Bichos" },
      { left: "Lotso", right: "Toy Story 3" },
      { left: "Skinner", right: "Ratatouille" },
      { left: "Waternoose", right: "Monstruos S.A." },
    ],
    official:
      "Hopper–Bichos, Lotso–Toy Story 3, Skinner–Ratatouille y Waternoose–Monstruos S.A.",
  },

  // --- La Edad de Hielo ---
  {
    id: "edadhielo-scrat",
    franchise: "La Edad de Hielo",
    emoji: "🌰",
    difficulty: "facil",
    format: "describir",
    prompt: "Ardilla dientes de sable que persigue una bellota por toda la película y nunca la consigue.",
    hint: "(Solo el nombre.)",
    accepted: [["Scrat"]],
    official: "Scrat",
  },
  {
    id: "edadhielo-manny",
    franchise: "La Edad de Hielo",
    emoji: "🦣",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el mamut gruñón del grupo?",
    hint: "(Solo el nombre.)",
    accepted: [["Manny"]],
    official: "Manny",
  },
  {
    id: "edadhielo-sid",
    franchise: "La Edad de Hielo",
    emoji: "🦥",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Sid, el charlatán del grupo?",
    options: ["Un perezoso", "Un oso hormiguero", "Un tejón", "Un mono"],
    correct: 0,
    official: "Un perezoso",
  },
  {
    id: "edadhielo-diego",
    franchise: "La Edad de Hielo",
    emoji: "🐯",
    difficulty: "facil",
    format: "vf",
    prompt: "Diego es un tigre dientes de sable que al principio quiere entregar al bebé a su manada.",
    correct: true,
    official: "Verdadero",
  },

  // --- Brave (Indomable) ---
  {
    id: "brave-merida",
    franchise: "Brave",
    emoji: "🏹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la princesa pelirroja escocesa que prefiere el arco a casarse?",
    hint: "(Solo el nombre.)",
    accepted: [["Mérida", "Merida"]],
    official: "Mérida",
  },
  {
    id: "brave-madre",
    franchise: "Brave",
    emoji: "🏹",
    difficulty: "media",
    format: "vf",
    prompt: "Mérida convierte a su madre en oso sin querer, por culpa de un pastel encantado.",
    correct: true,
    official: "Verdadero",
  },

  // --- El viaje de Arlo ---
  {
    id: "arlo-dinosaurio",
    franchise: "El viaje de Arlo",
    emoji: "🦕",
    difficulty: "media",
    format: "multiple",
    prompt: "En esta película de Pixar, ¿qué relación hay entre el dinosaurio Arlo y el niño Spot?",
    options: [
      "El niño es la mascota del dinosaurio",
      "El dinosaurio es la mascota del niño",
      "Son hermanos adoptivos",
      "El niño es un espíritu imaginario",
    ],
    correct: 0,
    official: "El niño hace de mascota del dinosaurio",
    note: "La película imagina que el meteorito nunca cayó y los dinosaurios siguieron vivos.",
  },

  // --- Río ---
  {
    id: "rio-blu",
    franchise: "Río",
    emoji: "🦜",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el guacamayo azul que no sabe volar?",
    hint: "(Solo el nombre.)",
    accepted: [["Blu"]],
    official: "Blu",
  },
  {
    id: "rio-ciudad",
    franchise: "Río",
    emoji: "🦜",
    difficulty: "facil",
    format: "vf",
    prompt: "La película transcurre en Río de Janeiro, en pleno carnaval.",
    correct: true,
    official: "Verdadero",
  },

  // --- Mascotas ---
  {
    id: "mascotas-max",
    franchise: "Mascotas",
    emoji: "🐶",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el terrier protagonista al que le cambia la vida cuando llega Duke?",
    hint: "(Solo el nombre.)",
    accepted: [["Max"]],
    official: "Max",
  },
  {
    id: "mascotas-conejo",
    franchise: "Mascotas",
    emoji: "🐰",
    difficulty: "media",
    format: "describir",
    prompt: "Conejito blanco y adorable que en realidad lidera una banda de animales abandonados.",
    hint: "(Solo el nombre.)",
    accepted: [["Snowball", "Bola de Nieve"]],
    official: "Snowball",
  },

  // --- Bichos ---
  {
    id: "bichos-flik",
    franchise: "Bichos",
    emoji: "🐜",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la hormiga inventora que busca guerreros para defender el hormiguero?",
    hint: "(Solo el nombre.)",
    accepted: [["Flik"]],
    official: "Flik",
  },
  {
    id: "bichos-circo",
    franchise: "Bichos",
    emoji: "🐜",
    difficulty: "media",
    format: "vf",
    prompt: "Los guerreros que Flik contrata resultan ser en realidad artistas de circo.",
    correct: true,
    official: "Verdadero",
  },

  // --- Buscando a Dory ---
  {
    id: "dory-memoria",
    franchise: "Buscando a Dory",
    emoji: "🐠",
    difficulty: "facil",
    format: "vf",
    prompt: "Dory busca a sus padres a pesar de que apenas puede retener recuerdos.",
    correct: true,
    official: "Verdadero",
  },

  // --- Luca ---
  {
    id: "luca-monstruos",
    franchise: "Luca",
    emoji: "🐟",
    difficulty: "media",
    format: "vf",
    prompt: "Luca y Alberto son monstruos marinos que toman forma humana al secarse.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "luca-vespa",
    franchise: "Luca",
    emoji: "🛵",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuál es el gran sueño de Luca y Alberto durante el verano italiano?",
    options: ["Comprarse una Vespa", "Ganar un barco", "Ir a la escuela", "Encontrar un tesoro"],
    correct: 0,
    official: "Comprarse una Vespa",
  },

  // --- Soul ---
  {
    id: "soul-joe",
    franchise: "Soul",
    emoji: "🎷",
    difficulty: "media",
    format: "corta",
    prompt: "¿A qué se dedica Joe Gardner, el protagonista?",
    hint: "(Su oficio o su instrumento.)",
    accepted: [["músico", "pianista", "profesor de música", "piano", "jazz"]],
    official: "Es pianista de jazz y profesor de música",
  },

  // --- Red ---
  {
    id: "red-panda",
    franchise: "Red",
    emoji: "🐼",
    difficulty: "facil",
    format: "corta",
    prompt: "¿En qué animal se transforma Mei cuando se emociona?",
    hint: "(El animal.)",
    accepted: [["panda rojo", "panda", "oso panda rojo"]],
    official: "Un panda rojo gigante",
  },

  // --- Onward ---
  {
    id: "onward-hechizo",
    franchise: "Onward",
    emoji: "🧝",
    difficulty: "media",
    format: "vf",
    prompt: "Los dos hermanos elfos intentan resucitar a su padre con un hechizo que sale a medias.",
    correct: true,
    official: "Verdadero",
    note: "El hechizo solo trae de vuelta la mitad de abajo, de cintura para abajo.",
  },

  // --- Elemental ---
  {
    id: "elemental-parejas",
    franchise: "Elemental",
    emoji: "🔥",
    difficulty: "media",
    format: "multiple",
    prompt: "¿De qué elementos son los dos protagonistas de Elemental?",
    options: ["Fuego y agua", "Tierra y aire", "Fuego y tierra", "Agua y aire"],
    correct: 0,
    official: "Fuego y agua",
  },

  // --- Monstruos University ---
  {
    id: "monstruosu-universidad",
    franchise: "Monstruos University",
    emoji: "🎓",
    difficulty: "media",
    format: "vf",
    prompt: "En esta precuela, Mike y Sulley empiezan siendo rivales antes de hacerse amigos.",
    correct: true,
    official: "Verdadero",
  },

  // --- Toy Story ---
  {
    id: "toystory-zurg",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "media",
    format: "describir",
    prompt: "Villano morado del espacio que se presenta como el padre de Buzz Lightyear.",
    hint: "(Solo el nombre.)",
    accepted: [["Zurg", "Emperador Zurg"]],
    official: "El emperador Zurg",
  },

  // --- Los Increíbles ---
  {
    id: "increibles-edna",
    franchise: "Los Increíbles",
    emoji: "🦸",
    difficulty: "media",
    format: "describir",
    prompt: "Diseñadora bajita de gafas enormes que se niega en rotundo a ponerle capa a un traje.",
    hint: "(Solo el nombre.)",
    accepted: [["Edna", "Edna Moda"]],
    official: "Edna Moda",
  },
  {
    id: "increibles-poderes",
    franchise: "Los Increíbles",
    emoji: "🦸",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el poder de Violeta, la hija mayor?",
    options: [
      "Volverse invisible y crear campos de fuerza",
      "Correr a gran velocidad",
      "Estirarse como una goma",
      "Tener una fuerza descomunal",
    ],
    correct: 0,
    official: "Volverse invisible y crear campos de fuerza",
    note: "Correr es lo de Dash y estirarse, lo de su madre.",
  },

  // --- Ratatouille ---
  {
    id: "ratatouille-lema",
    franchise: "Ratatouille",
    emoji: "🐀",
    difficulty: "media",
    format: "completar",
    prompt: "Completa el lema del chef Gusteau: «Cualquiera puede ___».",
    accepted: [["cocinar"]],
    official: "Cualquiera puede cocinar",
  },


  // --- Coco ---
  {
    id: "coco-dante",
    franchise: "Coco",
    emoji: "💀",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el perro sin pelo que acompaña a Miguel?",
    hint: "(Solo el nombre.)",
    accepted: [["Dante"]],
    official: "Dante",
  },

  // --- Shrek ---
  {
    id: "shrek-cebolla",
    franchise: "Shrek",
    emoji: "👹",
    difficulty: "media",
    format: "completar",
    prompt: "Completa lo que Shrek le explica a Asno: «Los ogros son como las ___: tienen capas».",
    accepted: [["cebollas", "cebolla"]],
    official: "Los ogros son como las cebollas",
  },

  // --- Madagascar ---
  {
    id: "madagascar-julien",
    franchise: "Madagascar",
    emoji: "🦁",
    difficulty: "media",
    format: "describir",
    prompt: "Lémur que se autoproclama rey de la isla y no para de bailar.",
    hint: "(Solo el nombre.)",
    accepted: [["Julien", "Rey Julien"]],
    official: "El rey Julien",
  },
  {
    id: "madagascar-pinguinos",
    franchise: "Madagascar",
    emoji: "🐧",
    difficulty: "media",
    format: "vf",
    prompt: "Los cuatro pingüinos de la película acabaron teniendo su propia serie y su película.",
    correct: true,
    official: "Verdadero",
  },

  // --- Kung Fu Panda ---
  {
    id: "kungfupanda-oogway",
    franchise: "Kung Fu Panda",
    emoji: "🐼",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es el maestro Oogway, el más sabio de todos?",
    options: ["Una tortuga", "Un panda rojo", "Una grulla", "Un mono"],
    correct: 0,
    official: "Una tortuga",
    note: "Shifu es el panda rojo.",
  },

  // --- Cómo entrenar a tu dragón ---
  {
    id: "dragon-desdentao",
    franchise: "Cómo entrenar a tu dragón",
    emoji: "🐲",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama en España el dragón furia nocturna de Hipo?",
    hint: "(Una palabra.)",
    accepted: [["Desdentao", "Desdentado"]],
    official: "Desdentao",
  },

  // --- El origen de los guardianes ---
  {
    id: "guardianes-jack",
    franchise: "El origen de los guardianes",
    emoji: "❄️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuál de estos personajes es el protagonista al que nadie ve porque nadie cree en él?",
    options: ["Jack Frost", "Papá Noel", "El Conejo de Pascua", "El Hada de los Dientes"],
    correct: 0,
    official: "Jack Frost",
  },

  // --- El gato con botas ---
  {
    id: "gatobotas-huevo",
    franchise: "El gato con botas",
    emoji: "🐱",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el huevo que fue amigo de la infancia del Gato con Botas?",
    options: ["Humpty Dumpty", "Eggy", "Ovo", "Tortolini"],
    correct: 0,
    official: "Humpty Dumpty",
  },

  // --- Chicken Run ---
  {
    id: "chickenrun-fuga",
    franchise: "Chicken Run",
    emoji: "🐔",
    difficulty: "media",
    format: "vf",
    prompt: "Las gallinas de la granja intentan escapar antes de acabar convertidas en empanadas.",
    correct: true,
    official: "Verdadero",
  },



  // --- Klaus ---
  {
    id: "klaus-cartero",
    franchise: "Klaus",
    emoji: "📮",
    difficulty: "media",
    format: "vf",
    prompt: "Klaus cuenta un origen de Papá Noel a partir de un cartero destinado a una isla helada.",
    correct: true,
    official: "Verdadero",
    note: "Es una película española, dirigida por Sergio Pablos.",
  },

  // --- El Gigante de Hierro ---
  {
    id: "gigantehierro-hogarth",
    franchise: "El Gigante de Hierro",
    emoji: "🤖",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el niño que se hace amigo del gigante metálico?",
    options: ["Hogarth", "Howard", "Herbert", "Hank"],
    correct: 0,
    official: "Hogarth",
  },

  // --- Mi villano favorito ---
  {
    id: "gru-ninas",
    franchise: "Mi villano favorito",
    emoji: "🌙",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llaman las tres niñas que adopta Gru?",
    options: [
      "Margo, Edith y Agnes",
      "Margo, Edith y Alice",
      "Maggie, Edith y Agnes",
      "Margo, Elsa y Agnes",
    ],
    correct: 0,
    official: "Margo, Edith y Agnes",
  },

  // --- Los Minions ---
  {
    id: "minions-color",
    franchise: "Los Minions",
    emoji: "🍌",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De qué color son los minions?",
    hint: "(Un color.)",
    accepted: [["amarillo", "amarillos"]],
    official: "Amarillos",
  },

  // --- El Grinch ---
  {
    id: "grinch-perro",
    franchise: "El Grinch",
    emoji: "🎄",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el perro del Grinch?",
    hint: "(Solo el nombre.)",
    accepted: [["Max"]],
    official: "Max",
  },

  // --- Canta ---
  {
    id: "canta-koala",
    franchise: "Canta",
    emoji: "🎤",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es Buster Moon, el dueño del teatro que organiza el concurso?",
    options: ["Un koala", "Un panda", "Un mapache", "Un oso"],
    correct: 0,
    official: "Un koala",
  },

  // --- Spider-Man: Un nuevo universo ---
  {
    id: "spiderverse-miles",
    franchise: "Spider-Man: Un nuevo universo",
    emoji: "🕷️",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el adolescente que se convierte en el nuevo Spider-Man?",
    hint: "(El nombre basta.)",
    accepted: [["Miles", "Miles Morales", "Morales"]],
    official: "Miles Morales",
  },

  // --- Hotel Transilvania ---
  {
    id: "hoteltransilvania-mavis",
    franchise: "Hotel Transilvania",
    emoji: "🧛",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la hija de Drácula que quiere salir a conocer el mundo?",
    hint: "(Solo el nombre.)",
    accepted: [["Mavis"]],
    official: "Mavis",
  },

  // --- Lluvia de albóndigas ---
  {
    id: "albondigas-invento",
    franchise: "Lluvia de albóndigas",
    emoji: "🍔",
    difficulty: "media",
    format: "vf",
    prompt: "El invento de Flint convierte el agua en comida, que empieza a caer del cielo.",
    correct: true,
    official: "Verdadero",
  },

  // --- Cronologías y relaciones de estudios ---
  {
    id: "orden-pixar-90-2000",
    franchise: "Pixar clásico",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Toy Story", "Monstruos S.A.", "Los Increíbles", "Cars"],
    official: "Toy Story (1995), Monstruos S.A. (2001), Los Increíbles (2004) y Cars (2006)",
  },
  {
    id: "orden-pixar-2010",
    franchise: "Pixar reciente",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Up", "Toy Story 3", "Del revés", "Coco"],
    official: "Up (2009), Toy Story 3 (2010), Del revés (2015) y Coco (2017)",
  },
  {
    id: "orden-pixar-2020",
    franchise: "Pixar reciente",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Onward", "Luca", "Red", "Elemental"],
    official: "Onward (2020), Luca (2021), Red (2022) y Elemental (2023)",
  },
  {
    id: "orden-dreamworks-amplio",
    franchise: "DreamWorks",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de DreamWorks de la más antigua a la más reciente.",
    items: ["El príncipe de Egipto", "Shrek", "Cómo entrenar a tu dragón", "Trolls"],
    official:
      "El príncipe de Egipto (1998), Shrek (2001), Cómo entrenar a tu dragón (2010) y Trolls (2016)",
  },
  {
    id: "orden-illumination",
    franchise: "Estudios de animación",
    emoji: "🎞️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cuál de estas películas es la más antigua?",
    options: ["Mi villano favorito", "El Lorax", "Los Minions", "El Grinch"],
    correct: 0,
    official: "Mi villano favorito (2010)",
    note: "Después llegaron El Lorax (2012), Los Minions (2015) y El Grinch (2018).",
  },
  {
    id: "relacionar-pixar-protagonistas",
    franchise: "Pixar clásico",
    emoji: "🎬",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada protagonista con su película.",
    pairs: [
      { left: "Remy", right: "Ratatouille" },
      { left: "Carl", right: "Up" },
      { left: "Miguel", right: "Coco" },
      { left: "Riley", right: "Del revés" },
    ],
    official: "Remy–Ratatouille, Carl–Up, Miguel–Coco y Riley–Del revés",
  },
  {
    id: "relacionar-pixar-mascotas",
    franchise: "Pixar reciente",
    emoji: "🎬",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada animal con la película en la que aparece.",
    pairs: [
      { left: "Dante", right: "Coco" },
      { left: "Dug", right: "Up" },
      { left: "Hank", right: "Buscando a Dory" },
      { left: "Scrat", right: "La Edad de Hielo" },
    ],
    official: "Dante–Coco, Dug–Up, Hank–Buscando a Dory y Scrat–La Edad de Hielo",
  },
  {
    id: "relacionar-dreamworks-personajes",
    franchise: "DreamWorks",
    emoji: "🎬",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada personaje con su película.",
    pairs: [
      { left: "Po", right: "Kung Fu Panda" },
      { left: "Fiona", right: "Shrek" },
      { left: "Alex", right: "Madagascar" },
      { left: "Hipo", right: "Cómo entrenar a tu dragón" },
    ],
    official: "Po–Kung Fu Panda, Fiona–Shrek, Alex–Madagascar e Hipo–Cómo entrenar a tu dragón",
  },
  {
    id: "estudios-quien-hizo-dragon",
    franchise: "Estudios de animación",
    emoji: "🏢",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué estudio hizo Cómo entrenar a tu dragón?",
    options: ["DreamWorks", "Pixar", "Illumination", "Sony Animation"],
    correct: 0,
    official: "DreamWorks",
  },
  {
    id: "relacionar-emociones-reves",
    franchise: "Del revés",
    emoji: "🧠",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada emoción de Del revés con su color.",
    pairs: [
      { left: "Alegría", right: "Amarillo" },
      { left: "Tristeza", right: "Azul" },
      { left: "Ira", right: "Rojo" },
      { left: "Asco", right: "Verde" },
    ],
    official: "Alegría–amarillo, Tristeza–azul, Ira–rojo y Asco–verde",
  },
  {
    id: "relacionar-robots-pelicula",
    franchise: "Robots de la animación",
    emoji: "🤖",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada robot con la película en la que aparece.",
    pairs: [
      { left: "Baymax", right: "Big Hero 6" },
      { left: "EVA", right: "WALL·E" },
      { left: "Zurg", right: "Toy Story" },
    ],
    official: "Baymax–Big Hero 6, EVA–WALL·E y Zurg–Toy Story",
  },
  {
    id: "vf-pixar-lampara",
    franchise: "Pixar clásico",
    emoji: "💡",
    difficulty: "media",
    format: "vf",
    prompt: "El logotipo de Pixar incluye una lámpara de escritorio que aplasta la letra I.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "vf-toystory-primera",
    franchise: "Pixar clásico",
    emoji: "🎬",
    difficulty: "media",
    format: "vf",
    prompt: "Toy Story fue el primer largometraje hecho enteramente por ordenador.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "completar-buzz-frase",
    franchise: "Toy Story",
    emoji: "🚀",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el lema de Buzz Lightyear: «Hasta el infinito y ___ allá».",
    accepted: [["más", "mas"]],
    official: "Hasta el infinito y más allá",
  },
  {
    id: "describir-sulley",
    franchise: "Monstruos S.A.",
    emoji: "👾",
    difficulty: "facil",
    format: "describir",
    prompt: "Monstruo enorme, azul con lunares morados, el mejor asustador de la fábrica.",
    hint: "(Solo el nombre.)",
    accepted: [["Sulley", "Sully", "James P. Sullivan"]],
    official: "Sulley",
  },
  {
    id: "describir-gru",
    franchise: "Mi villano favorito",
    emoji: "🌙",
    difficulty: "facil",
    format: "describir",
    prompt: "Villano narizón de bufanda y acento raro que planea robar la Luna.",
    hint: "(Solo el nombre.)",
    accepted: [["Gru"]],
    official: "Gru",
  },
  {
    id: "describir-po",
    franchise: "Kung Fu Panda",
    emoji: "🐼",
    difficulty: "facil",
    format: "describir",
    prompt: "Panda tragón que trabaja en el puesto de fideos de su padre y acaba siendo el Guerrero Dragón.",
    hint: "(Solo el nombre.)",
    accepted: [["Po"]],
    official: "Po",
  },
];
