import type { Question } from "../types";

/**
 * Tema «Historia».
 *
 * La condición de partida la puso Oscar: **historia de varias culturas, no
 * solo europea**. Eso no se cumple metiendo dos preguntas de Egipto en un banco
 * de reyes de Castilla, así que aquí Europa es una cultura más y ocupa menos de
 * una quinta parte. África, América precolombina, China, India, el mundo
 * islámico y el Pacífico tienen tanto sitio como ella.
 *
 * Por eso mismo se agrupa **por cultura y no por siglos**: «Edad Media» o «Edad
 * Moderna» son cortes europeos que no dicen nada de la historia de Malí o de
 * los mexicas, y ordenar el tema así habría devuelto Europa al centro por la
 * puerta de atrás.
 *
 * Convenciones propias, además de las generales:
 *
 * - **`franchise` es la civilización o el imperio**, no la época. Así la regla
 *   de no repetir franquicia en 8 preguntas evita que salgan cuatro de Roma
 *   seguidas. `categoriaDe` la lleva a su cultura.
 * - **Fechas contrastadas**. Lo más frágil de un banco de historia son los años
 *   y los nombres propios, así que lo menos canónico se comprobó contra fuentes
 *   antes de escribirlo: Caral, Kush, Aksum, el Gran Zimbabue, Malí, Zheng He,
 *   la llegada de los polinesios a Nueva Zelanda y la fundación de
 *   Tenochtitlan. Consultado el 27 de septiembre de 2026.
 * - **Nada de «descubrimiento»** cuando había gente viviendo allí, ni de
 *   civilizaciones «sin historia». No es remilgo: es que la pregunta sería
 *   falsa.
 */
export const HISTORIA: Question[] = [
  // --- Mesopotamia y Egipto ---
  {
    id: "hist-escritura-sumeria",
    franchise: "Mesopotamia",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el sistema de escritura que inventaron los sumerios, a base de cuñas sobre barro?",
    options: ["Cuneiforme", "Jeroglífica", "Alfabética", "Ideográfica"],
    correct: 0,
    official: "La escritura cuneiforme",
  },
  {
    id: "hist-hammurabi",
    franchise: "Mesopotamia",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué rey de Babilonia dio nombre a uno de los códigos de leyes más antiguos que se conservan?",
    hint: "(Solo el nombre.)",
    accepted: [["Hammurabi", "Hamurabi"]],
    official: "Hammurabi",
  },
  {
    id: "hist-mesopotamia-rios",
    franchise: "Mesopotamia",
    difficulty: "facil",
    format: "multiple",
    prompt: "«Mesopotamia» significa «entre ríos». ¿Entre qué dos ríos?",
    options: ["El Tigris y el Éufrates", "El Nilo y el Jordán", "El Indo y el Ganges", "El Danubio y el Rin"],
    correct: 0,
    official: "El Tigris y el Éufrates",
  },
  {
    id: "hist-gilgamesh",
    franchise: "Mesopotamia",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el poema mesopotámico considerado una de las obras literarias más antiguas del mundo?",
    options: ["La epopeya de Gilgamesh", "El libro de los muertos", "El Enuma Elish", "El código de Ur-Nammu"],
    correct: 0,
    official: "La epopeya de Gilgamesh",
  },
  {
    id: "hist-egipto-jeroglificos",
    franchise: "Antiguo Egipto",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué piedra permitió descifrar los jeroglíficos egipcios, al traer el mismo texto en tres escrituras?",
    accepted: [["Rosetta", "la piedra de Rosetta", "la piedra Rosetta"]],
    official: "La piedra de Rosetta",
  },
  {
    id: "hist-egipto-nilo",
    franchise: "Antiguo Egipto",
    difficulty: "facil",
    format: "vf",
    prompt: "Las crecidas anuales del Nilo eran lo que hacía fértil la tierra de Egipto.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "hist-egipto-hatshepsut",
    franchise: "Antiguo Egipto",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué mujer gobernó Egipto como faraón y se hizo representar con la barba postiza del cargo?",
    options: ["Hatshepsut", "Nefertiti", "Cleopatra VII", "Nefertari"],
    correct: 0,
    official: "Hatshepsut",
  },
  {
    id: "hist-egipto-cleopatra",
    franchise: "Antiguo Egipto",
    difficulty: "dificil",
    format: "multiple",
    prompt: "Cleopatra VII fue la última faraona de Egipto. ¿De qué origen era su dinastía?",
    options: ["Griego (macedonio)", "Persa", "Nubio", "Romano"],
    correct: 0,
    official: "Griego, de origen macedonio",
    note: "Los Ptolomeos venían de un general de Alejandro Magno.",
  },
  {
    id: "hist-kush-faraones",
    franchise: "Reino de Kush",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿De dónde venían los faraones de la dinastía XXV, que llegaron a gobernar todo Egipto?",
    options: ["De Nubia, el reino de Kush", "De Libia", "De Persia", "De Creta"],
    correct: 0,
    official: "De Nubia, el reino de Kush",
    note: "Piankhi fue el primero. Kush duró desde el 780 a. C. hasta el 350 d. C.",
  },
  {
    id: "hist-kush-meroe",
    franchise: "Reino de Kush",
    difficulty: "media",
    format: "vf",
    prompt: "En Sudán se conservan más pirámides que en Egipto.",
    correct: true,
    official: "Verdadero",
    note: "Las levantaron los reyes de Kush, sobre todo en Meroe.",
  },
  {
    id: "hist-kush-capitales",
    franchise: "Reino de Kush",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena las tres capitales sucesivas del reino de Kush, de la más antigua a la más reciente.",
    items: ["Kerma", "Napata", "Meroe"],
    official: "Kerma, Napata y Meroe",
  },

  // --- Grecia y Roma ---
  {
    id: "hist-grecia-democracia",
    franchise: "Antigua Grecia",
    difficulty: "facil",
    format: "corta",
    prompt: "¿En qué ciudad griega nació la democracia?",
    accepted: [["Atenas"]],
    official: "Atenas",
  },
  {
    id: "hist-grecia-democracia-limites",
    franchise: "Antigua Grecia",
    difficulty: "media",
    format: "vf",
    prompt: "En la democracia ateniense podían votar todos los habitantes de la ciudad.",
    correct: false,
    official: "Falso",
    note: "Solo los varones ciudadanos: quedaban fuera las mujeres, los esclavos y los extranjeros.",
  },
  {
    id: "hist-alejandro",
    franchise: "Antigua Grecia",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Hasta dónde llegó por el este el imperio de Alejandro Magno?",
    options: ["Hasta el río Indo", "Hasta China", "Hasta el Ganges", "Hasta Japón"],
    correct: 0,
    official: "Hasta el río Indo",
  },
  {
    id: "hist-roma-republica",
    franchise: "Antigua Roma",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué forma de gobierno tuvo Roma antes del Imperio?",
    options: ["La República", "La democracia", "El califato", "La tetrarquía"],
    correct: 0,
    official: "La República",
  },
  {
    id: "hist-roma-augusto",
    franchise: "Antigua Roma",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Quién fue el primer emperador de Roma?",
    hint: "(Solo el nombre.)",
    accepted: [["Augusto", "Octavio", "Octavio Augusto", "César Augusto"]],
    official: "Augusto",
  },
  {
    id: "hist-roma-476",
    franchise: "Antigua Roma",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué año cayó el Imperio romano de Occidente?",
    options: ["476", "410", "395", "1453"],
    correct: 0,
    official: "476",
  },
  {
    id: "hist-bizancio",
    franchise: "Imperio bizantino",
    difficulty: "dificil",
    format: "multiple",
    prompt: "El Imperio romano de Oriente siguió mil años más. ¿Con la caída de qué ciudad terminó, en 1453?",
    options: ["Constantinopla", "Roma", "Atenas", "Alejandría"],
    correct: 0,
    official: "Constantinopla",
  },
  {
    id: "hist-bizancio-justiniano",
    franchise: "Imperio bizantino",
    difficulty: "facil",
    format: "vf",
    prompt: "Santa Sofía, en Estambul, se construyó como iglesia y más tarde fue mezquita.",
    correct: true,
    official: "Verdadero",
  },

  // --- China ---
  {
    id: "hist-china-qin",
    franchise: "China imperial",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué se enterró junto al primer emperador de China, Qin Shi Huang, y se encontró en 1974?",
    options: [
      "Un ejército de guerreros de terracota",
      "Una biblioteca de bambú",
      "Un barco funerario",
      "Una ciudad en miniatura de oro",
    ],
    correct: 0,
    official: "Un ejército de guerreros de terracota",
  },
  {
    id: "hist-china-muralla",
    franchise: "China imperial",
    difficulty: "facil",
    format: "vf",
    prompt: "La Gran Muralla se construyó de una vez y bajo un solo emperador.",
    correct: false,
    official: "Falso",
    note: "Se levantó y rehízo durante siglos; lo que hoy se visita es sobre todo de la dinastía Ming.",
  },
  {
    id: "hist-china-inventos",
    franchise: "China imperial",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada invento chino con para qué servía.",
    pairs: [
      { left: "La brújula", right: "Orientarse en la navegación" },
      { left: "La imprenta de tipos móviles", right: "Reproducir textos" },
      { left: "La pólvora", right: "Fuegos y armas" },
      { left: "El papel", right: "Escribir" },
    ],
    official:
      "La brújula–orientarse, la imprenta–reproducir textos, la pólvora–fuegos y armas y el papel–escribir",
  },
  {
    id: "hist-china-seda",
    franchise: "China imperial",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la red de rutas comerciales que unía China con el Mediterráneo?",
    accepted: [["la Ruta de la Seda", "Ruta de la Seda"]],
    official: "La Ruta de la Seda",
  },
  {
    id: "hist-china-tang",
    franchise: "China imperial",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué dinastía china, entre los siglos VII y X, se considera la edad dorada de su poesía y su arte?",
    options: ["La Tang", "La Ming", "La Qing", "La Han"],
    correct: 0,
    official: "La dinastía Tang",
  },
  {
    id: "hist-zheng-he",
    franchise: "China imperial",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Quién mandó las grandes flotas chinas que entre 1405 y 1433 llegaron hasta la costa de África?",
    options: ["Zheng He", "Qin Shi Huang", "Kublai Kan", "Confucio"],
    correct: 0,
    official: "Zheng He",
    note: "Almirante musulmán nacido en Yunnan, al mando de la Flota del Tesoro de los Ming.",
  },
  {
    id: "hist-zheng-he-vf",
    franchise: "China imperial",
    difficulty: "media",
    format: "vf",
    prompt: "Las flotas de Zheng He navegaron por el Índico décadas antes de que los portugueses doblaran el cabo de Buena Esperanza.",
    correct: true,
    official: "Verdadero",
    note: "Zarparon en 1405; Vasco da Gama llegó a la India en 1498.",
  },
  {
    id: "hist-china-confucio",
    franchise: "China imperial",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué pensador chino puso el orden, la familia y el respeto a los mayores en el centro de su doctrina?",
    hint: "(Solo el nombre.)",
    accepted: [["Confucio"]],
    official: "Confucio",
  },
  {
    id: "hist-china-examenes",
    franchise: "China imperial",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se elegían los funcionarios de la China imperial?",
    options: [
      "Por exámenes de acceso",
      "Por herencia familiar",
      "Por sorteo",
      "Los nombraba el ejército",
    ],
    correct: 0,
    official: "Por exámenes de acceso",
  },

  // --- Japón y Corea ---
  {
    id: "hist-japon-samurai",
    franchise: "Japón",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué título llevaba el jefe militar que gobernaba Japón de hecho, por encima del emperador?",
    options: ["Sogún", "Samurái", "Daimio", "Ronin"],
    correct: 0,
    official: "Sogún",
  },
  {
    id: "hist-japon-sakoku",
    franchise: "Japón",
    difficulty: "dificil",
    format: "multiple",
    prompt: "Durante más de dos siglos Japón se cerró casi por completo al exterior. ¿Cómo se conoce esa política?",
    options: ["Sakoku", "Bushido", "Meiji", "Shogunato"],
    correct: 0,
    official: "El sakoku",
  },
  {
    id: "hist-japon-meiji",
    franchise: "Japón",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué pasó en Japón con la Restauración Meiji, en 1868?",
    options: [
      "Se devolvió el poder al emperador y el país se industrializó a toda prisa",
      "Japón se dividió en dos países",
      "Se prohibió el comercio exterior",
      "Los samuráis tomaron el poder",
    ],
    correct: 0,
    official: "Se devolvió el poder al emperador y el país se industrializó a toda prisa",
  },
  {
    id: "hist-japon-ronin",
    franchise: "Japón",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llamaba al samurái que se quedaba sin señor al que servir?",
    accepted: [["ronin", "rōnin"]],
    official: "Ronin",
  },
  {
    id: "hist-corea-hangul",
    franchise: "Corea",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el alfabeto coreano, creado en el siglo XV para que la gente común pudiera leer y escribir?",
    options: ["Hangul", "Kanji", "Hanja", "Katakana"],
    correct: 0,
    official: "El hangul",
  },
  {
    id: "hist-corea-vf",
    franchise: "Corea",
    difficulty: "media",
    format: "vf",
    prompt: "Corea quedó dividida en dos países tras la Segunda Guerra Mundial.",
    correct: true,
    official: "Verdadero",
    note: "Se repartió en dos zonas de ocupación y la guerra de 1950-1953 consolidó la separación.",
  },

  // --- India ---
  {
    id: "hist-indo",
    franchise: "Civilización del Indo",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué civilización levantó hace más de cuatro mil años ciudades con alcantarillado como Mohenjo-Daro?",
    options: [
      "La civilización del valle del Indo",
      "La civilización védica",
      "El Imperio maurya",
      "El Imperio gupta",
    ],
    correct: 0,
    official: "La civilización del valle del Indo",
  },
  {
    id: "hist-asoka",
    franchise: "Imperio maurya",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué emperador indio se convirtió al budismo tras espantarse de la matanza de una guerra que él mismo había ganado?",
    options: ["Asoka", "Chandragupta", "Akbar", "Sha Jahan"],
    correct: 0,
    official: "Asoka",
  },
  {
    id: "hist-buda",
    franchise: "India antigua",
    difficulty: "facil",
    format: "corta",
    prompt: "¿En qué país nació el budismo?",
    accepted: [["India", "la India"]],
    official: "En la India",
  },
  {
    id: "hist-cero",
    franchise: "India antigua",
    difficulty: "media",
    format: "vf",
    prompt: "El cero como número, tal y como se usa hoy, se desarrolló en la India.",
    correct: true,
    official: "Verdadero",
    note: "De ahí pasó al mundo islámico y luego a Europa; por eso los llamamos «números arábigos».",
  },
  {
    id: "hist-taj-mahal",
    franchise: "Imperio mogol",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Para qué se construyó el Taj Mahal?",
    options: [
      "Como tumba de la esposa del emperador",
      "Como palacio de verano",
      "Como templo hindú",
      "Como fortaleza",
    ],
    correct: 0,
    official: "Como tumba de la esposa del emperador",
    note: "Lo levantó Sha Jahan para Mumtaz Mahal.",
  },
  {
    id: "hist-gandhi",
    franchise: "India contemporánea",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Quién encabezó con métodos no violentos la lucha por la independencia de la India?",
    hint: "(Solo el apellido.)",
    accepted: [["Gandhi", "Mahatma Gandhi"]],
    official: "Mahatma Gandhi",
  },
  {
    id: "hist-india-1947",
    franchise: "India contemporánea",
    difficulty: "dificil",
    format: "multiple",
    prompt: "Al independizarse de Gran Bretaña en 1947, ¿en cuántos países se dividió la India británica?",
    options: ["En dos: India y Pakistán", "En uno solo", "En tres", "En cuatro"],
    correct: 0,
    official: "En dos: India y Pakistán",
    note: "Bangladés se separó de Pakistán más tarde, en 1971.",
  },

  // --- El mundo islámico ---
  {
    id: "hist-hegira",
    franchise: "Islam medieval",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué acontecimiento marca el año 1 del calendario musulmán?",
    options: [
      "La marcha de Mahoma de La Meca a Medina",
      "El nacimiento de Mahoma",
      "La toma de Jerusalén",
      "La fundación de Bagdad",
    ],
    correct: 0,
    official: "La hégira: la marcha de Mahoma de La Meca a Medina",
  },
  {
    id: "hist-casa-sabiduria",
    franchise: "Islam medieval",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué ciudad estaba la Casa de la Sabiduría, donde se tradujo y amplió el saber griego, persa e indio?",
    options: ["Bagdad", "El Cairo", "Damasco", "Córdoba"],
    correct: 0,
    official: "Bagdad",
  },
  {
    id: "hist-algebra",
    franchise: "Islam medieval",
    difficulty: "media",
    format: "vf",
    prompt: "Las palabras «álgebra» y «algoritmo» vienen del mundo islámico.",
    correct: true,
    official: "Verdadero",
    note: "«Algoritmo» viene del nombre del matemático Al-Juarismi.",
  },
  {
    id: "hist-alandalus",
    franchise: "Al-Ándalus",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué nombre recibía el territorio de la península ibérica bajo dominio musulmán?",
    accepted: [["Al-Ándalus", "Al Andalus", "Alándalus"]],
    official: "Al-Ándalus",
  },
  {
    id: "hist-alhambra",
    franchise: "Al-Ándalus",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué ciudad está la Alhambra, el palacio del último reino musulmán de la península?",
    options: ["Granada", "Córdoba", "Sevilla", "Toledo"],
    correct: 0,
    official: "Granada",
  },
  {
    id: "hist-ibn-battuta",
    franchise: "Islam medieval",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué viajero marroquí del siglo XIV recorrió más mundo que Marco Polo y lo dejó escrito?",
    options: ["Ibn Battuta", "Averroes", "Al-Idrisi", "Avicena"],
    correct: 0,
    official: "Ibn Battuta",
  },
  {
    id: "hist-otomano",
    franchise: "Imperio otomano",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué imperio tomó Constantinopla en 1453 y la convirtió en su capital?",
    options: ["El otomano", "El persa", "El mongol", "El austrohúngaro"],
    correct: 0,
    official: "El Imperio otomano",
  },
  {
    id: "hist-otomano-vf",
    franchise: "Imperio otomano",
    difficulty: "media",
    format: "vf",
    prompt: "El Imperio otomano desapareció tras la Primera Guerra Mundial.",
    correct: true,
    official: "Verdadero",
    note: "De su desmembramiento salió la Turquía actual, en 1923.",
  },

  // --- África ---
  {
    id: "hist-mansa-musa",
    franchise: "Imperio de Malí",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué emperador de Malí, en el siglo XIV, pasa por ser la persona más rica de la historia?",
    options: ["Mansa Musa", "Sundiata Keita", "Askia Muhammad", "Shaka Zulú"],
    correct: 0,
    official: "Mansa Musa",
    note: "Reinó entre 1312 y 1337 sobre un imperio que vivía del oro.",
  },
  {
    id: "hist-tombuctu",
    franchise: "Imperio de Malí",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Por qué fue famosa Tombuctú en la Edad Media?",
    options: [
      "Por sus bibliotecas y su universidad",
      "Por sus minas de diamantes",
      "Por ser un puerto de mar",
      "Por sus pirámides",
    ],
    correct: 0,
    official: "Por sus bibliotecas y su universidad",
  },
  {
    id: "hist-mali-vf",
    franchise: "Imperio de Malí",
    difficulty: "media",
    format: "vf",
    prompt: "El Imperio de Malí basaba su riqueza en el comercio de oro y sal a través del Sáhara.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "hist-gran-zimbabue",
    franchise: "Gran Zimbabue",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué era el Gran Zimbabue, esa ciudad de enormes muros de piedra sin argamasa?",
    options: [
      "La capital de un reino shona",
      "Una fortaleza construida por portugueses",
      "Un templo egipcio",
      "Una colonia árabe",
    ],
    correct: 0,
    official: "La capital de un reino shona",
    note: "Entre los siglos XIII y XV llegó a tener unos 20.000 habitantes.",
  },
  {
    id: "hist-aksum",
    franchise: "Reino de Aksum",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué zona de África estaba el reino de Aksum, uno de los primeros en adoptar el cristianismo?",
    options: [
      "En la actual Etiopía y Eritrea",
      "En el Congo",
      "En Marruecos",
      "En Sudáfrica",
    ],
    correct: 0,
    official: "En la actual Etiopía y Eritrea",
  },
  {
    id: "hist-etiopia-vf",
    franchise: "Etiopía",
    difficulty: "media",
    format: "vf",
    prompt: "Etiopía es de los poquísimos países africanos que nunca llegaron a ser colonia europea.",
    correct: true,
    official: "Verdadero",
    note: "Derrotó a Italia en Adua, en 1896; la ocupación italiana de 1936 duró cinco años.",
  },
  {
    id: "hist-benin",
    franchise: "Reino de Benín",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Por qué es célebre el reino de Benín, en la actual Nigeria?",
    options: [
      "Por sus placas y cabezas de bronce",
      "Por sus pirámides escalonadas",
      "Por su escritura jeroglífica",
      "Por sus acueductos",
    ],
    correct: 0,
    official: "Por sus placas y cabezas de bronce",
    note: "Buena parte están hoy en museos europeos, saqueadas en 1897.",
  },
  {
    id: "hist-africa-reparto",
    franchise: "África colonial",
    difficulty: "media",
    format: "multiple",
    prompt: "En la Conferencia de Berlín de 1884-1885 las potencias europeas se repartieron África. ¿Quién no estuvo invitado?",
    options: [
      "Ningún africano",
      "Francia",
      "Alemania",
      "El Reino Unido",
    ],
    correct: 0,
    official: "Ningún africano",
  },
  {
    id: "hist-africa-fronteras",
    franchise: "África colonial",
    difficulty: "media",
    format: "vf",
    prompt: "Muchas fronteras africanas actuales son líneas rectas trazadas por europeos sin mirar quién vivía a cada lado.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "hist-mandela",
    franchise: "Sudáfrica",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Quién salió de veintisiete años de cárcel para acabar siendo presidente de Sudáfrica?",
    hint: "(Solo el apellido.)",
    accepted: [["Mandela", "Nelson Mandela"]],
    official: "Nelson Mandela",
  },
  {
    id: "hist-apartheid",
    franchise: "Sudáfrica",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llamaba el sistema de segregación racial de Sudáfrica?",
    accepted: [["apartheid", "el apartheid"]],
    official: "El apartheid",
  },

  // --- América precolombina ---
  {
    id: "hist-caral",
    franchise: "Civilización caral",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Dónde está Caral, la ciudad más antigua conocida de América, levantada hacia el 2600 a. C.?",
    options: ["En Perú", "En México", "En Guatemala", "En Bolivia"],
    correct: 0,
    official: "En Perú",
    note: "En el valle de Supe, y es contemporánea de las pirámides de Egipto.",
  },
  {
    id: "hist-maya-escritura",
    franchise: "Civilización maya",
    difficulty: "facil",
    format: "vf",
    prompt: "Los mayas desarrollaron un sistema de escritura propio.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "hist-maya-cero",
    franchise: "Civilización maya",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué destacaron especialmente los mayas, hasta el punto de manejar el cero y predecir eclipses?",
    options: ["En astronomía y matemáticas", "En navegación", "En metalurgia del hierro", "En cría de caballos"],
    correct: 0,
    official: "En astronomía y matemáticas",
  },
  {
    id: "hist-tenochtitlan",
    franchise: "Imperio mexica",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Sobre qué estaba construida Tenochtitlan, la capital mexica?",
    options: [
      "Sobre una isla en un lago",
      "Sobre la ladera de un volcán",
      "En la selva",
      "En la costa del Caribe",
    ],
    correct: 0,
    official: "Sobre una isla en un lago",
    note: "Fundada en 1325 en el lago de Texcoco; hoy es la Ciudad de México.",
  },
  {
    id: "hist-tenochtitlan-poblacion",
    franchise: "Imperio mexica",
    difficulty: "media",
    format: "vf",
    prompt: "Cuando llegaron los españoles, Tenochtitlan tenía menos habitantes que cualquier ciudad europea de la época.",
    correct: false,
    official: "Falso",
    note: "Rondaba los 200.000 habitantes: era mayor que cualquier ciudad de Europa entonces.",
  },
  {
    id: "hist-mexica-nahuatl",
    franchise: "Imperio mexica",
    difficulty: "media",
    format: "corta",
    prompt: "¿Qué lengua hablaban los mexicas, y de la que vienen palabras como «chocolate» o «tomate»?",
    accepted: [["náhuatl", "nahuatl", "el náhuatl"]],
    official: "El náhuatl",
  },
  {
    id: "hist-inca-machu",
    franchise: "Imperio inca",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué país está Machu Picchu?",
    options: ["Perú", "México", "Chile", "Ecuador"],
    correct: 0,
    official: "Perú",
  },
  {
    id: "hist-inca-quipu",
    franchise: "Imperio inca",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo llevaban los incas sus cuentas y registros, sin escritura tal y como la entendemos?",
    options: [
      "Con quipus, cuerdas con nudos",
      "Con tablillas de barro",
      "Con pinturas en cuevas",
      "Con monedas marcadas",
    ],
    correct: 0,
    official: "Con quipus, cuerdas con nudos",
  },
  {
    id: "hist-inca-caminos",
    franchise: "Imperio inca",
    difficulty: "facil",
    format: "vf",
    prompt: "Los incas construyeron una red de caminos de miles de kilómetros sin usar la rueda ni animales de tiro.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "hist-precolombina-orden",
    franchise: "América precolombina",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas civilizaciones americanas de la más antigua a la más reciente.",
    items: ["Caral", "Los mayas clásicos", "Los mexicas", "El Imperio inca"],
    official: "Caral, los mayas clásicos, los mexicas y el Imperio inca",
  },
  {
    id: "hist-america-viruela",
    franchise: "América precolombina",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué causó la mayor mortandad entre los pueblos americanos tras la llegada de los europeos?",
    options: [
      "Las enfermedades traídas de Europa",
      "Las batallas",
      "El hambre por las sequías",
      "Los terremotos",
    ],
    correct: 0,
    official: "Las enfermedades traídas de Europa",
    note: "Sobre todo la viruela, ante la que no tenían defensas.",
  },

  // --- Oceanía y el Pacífico ---
  {
    id: "hist-polinesios",
    franchise: "Polinesia",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se orientaban los navegantes polinesios para cruzar miles de kilómetros de océano abierto?",
    options: [
      "Por las estrellas, el oleaje y las aves",
      "Con brújula",
      "Siguiendo la costa",
      "Con mapas de papel",
    ],
    correct: 0,
    official: "Por las estrellas, el oleaje y las aves",
  },
  {
    id: "hist-maories",
    franchise: "Nueva Zelanda",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cuándo llegaron los polinesios a Nueva Zelanda, de donde salieron los maoríes?",
    options: ["Entre 1250 y 1300", "Hacia el 500 a. C.", "En el siglo XVI", "Hacia el año 1000 a. C."],
    correct: 0,
    official: "Entre 1250 y 1300",
    note: "Es una de las últimas tierras grandes que se poblaron.",
  },
  {
    id: "hist-maories-vf",
    franchise: "Nueva Zelanda",
    difficulty: "facil",
    format: "vf",
    prompt: "Los maoríes llegaron a Nueva Zelanda navegando en canoas desde otras islas del Pacífico.",
    correct: true,
    official: "Verdadero",
    note: "Venían de la Polinesia oriental.",
  },
  {
    id: "hist-rapa-nui",
    franchise: "Rapa Nui",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llaman las grandes estatuas de piedra de la isla de Pascua?",
    options: ["Moáis", "Tikis", "Totems", "Menhires"],
    correct: 0,
    official: "Los moáis",
  },
  {
    id: "hist-rapa-nui-vf",
    franchise: "Rapa Nui",
    difficulty: "media",
    format: "vf",
    prompt: "La isla de Pascua está a más de tres mil kilómetros de la costa habitada más cercana.",
    correct: true,
    official: "Verdadero",
    note: "Es de los lugares habitados más aislados del planeta.",
  },
  {
    id: "hist-australia",
    franchise: "Australia",
    difficulty: "facil",
    format: "vf",
    prompt: "Los aborígenes australianos llevan en el continente más de cuarenta mil años.",
    correct: true,
    official: "Verdadero",
    note: "Es una de las culturas vivas más antiguas que se conocen.",
  },
  {
    id: "hist-australia-cook",
    franchise: "Australia",
    difficulty: "facil",
    format: "vf",
    prompt: "Cuando los británicos llegaron a Australia, el continente estaba deshabitado.",
    correct: false,
    official: "Falso",
    note: "Vivían allí cientos de pueblos aborígenes, con sus lenguas propias.",
  },

  // --- Europa medieval y moderna ---
  {
    id: "hist-peste-negra",
    franchise: "Europa medieval",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué epidemia se llevó por delante a un tercio de la población europea en el siglo XIV?",
    options: ["La peste negra", "La viruela", "El cólera", "La gripe española"],
    correct: 0,
    official: "La peste negra",
  },
  {
    id: "hist-imprenta",
    franchise: "Europa moderna",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Quién montó en Europa la imprenta de tipos móviles hacia 1450?",
    hint: "(Solo el apellido.)",
    accepted: [["Gutenberg"]],
    official: "Gutenberg",
  },
  {
    id: "hist-imprenta-vf",
    franchise: "Europa moderna",
    difficulty: "media",
    format: "vf",
    prompt: "La imprenta de tipos móviles se inventó en Europa antes que en ningún otro sitio.",
    correct: false,
    official: "Falso",
    note: "En China y en Corea ya se imprimía con tipos móviles siglos antes que Gutenberg.",
  },
  {
    id: "hist-revolucion-francesa",
    franchise: "Europa moderna",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué año empezó la Revolución francesa?",
    options: ["1789", "1776", "1804", "1848"],
    correct: 0,
    official: "1789",
  },
  {
    id: "hist-revolucion-industrial",
    franchise: "Europa moderna",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué país arrancó la Revolución industrial?",
    options: ["En Gran Bretaña", "En Francia", "En Alemania", "En Estados Unidos"],
    correct: 0,
    official: "En Gran Bretaña",
  },

  // --- El mundo contemporáneo ---
  {
    id: "hist-primera-guerra",
    franchise: "Primera Guerra Mundial",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Entre qué años se libró la Primera Guerra Mundial?",
    options: ["1914-1918", "1939-1945", "1904-1910", "1920-1925"],
    correct: 0,
    official: "1914-1918",
  },
  {
    id: "hist-segunda-guerra",
    franchise: "Segunda Guerra Mundial",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Entre qué años se libró la Segunda Guerra Mundial?",
    options: ["1939-1945", "1914-1918", "1936-1939", "1945-1950"],
    correct: 0,
    official: "1939-1945",
  },
  {
    id: "hist-muro-berlin",
    franchise: "Guerra Fría",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué año cayó el muro de Berlín?",
    options: ["1989", "1961", "1991", "1979"],
    correct: 0,
    official: "1989",
  },
  {
    id: "hist-guerra-fria",
    franchise: "Guerra Fría",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué dos potencias se enfrentaron en la Guerra Fría?",
    options: [
      "Estados Unidos y la Unión Soviética",
      "Estados Unidos y China",
      "Alemania y Japón",
      "Reino Unido y Francia",
    ],
    correct: 0,
    official: "Estados Unidos y la Unión Soviética",
  },
  {
    id: "hist-descolonizacion",
    franchise: "Descolonización",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué década se independizaron de golpe la mayoría de las colonias africanas?",
    options: ["En los años sesenta", "En los años veinte", "En los años noventa", "En los años treinta"],
    correct: 0,
    official: "En los años sesenta",
    note: "Solo en 1960 se independizaron diecisiete países africanos.",
  },
  {
    id: "hist-orden-siglo-xx",
    franchise: "Siglo XX",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estos hechos del siglo XX del más antiguo al más reciente.",
    items: [
      "El final de la Primera Guerra Mundial",
      "El final de la Segunda Guerra Mundial",
      "La llegada del ser humano a la Luna",
      "La caída del muro de Berlín",
    ],
    official:
      "El final de la Primera Guerra Mundial (1918), el de la Segunda (1945), la llegada a la Luna (1969) y la caída del muro (1989)",
  },
  // --- Ampliación: más formatos y más peso de lo no europeo ---
  {
    id: "hist-desc-mexicas",
    franchise: "Imperio mexica",
    difficulty: "media",
    format: "describir",
    prompt:
      "Pueblo que fundó su capital sobre una isla en un lago del altiplano, dominó Mesoamérica y hablaba náhuatl.",
    hint: "(El nombre del pueblo.)",
    accepted: [["mexicas", "aztecas", "los mexicas", "los aztecas", "mexica", "azteca"]],
    official: "Los mexicas, también llamados aztecas",
  },
  {
    id: "hist-desc-incas",
    franchise: "Imperio inca",
    difficulty: "media",
    format: "describir",
    prompt:
      "Imperio andino que unió miles de kilómetros con caminos y puentes de cuerda, y llevaba sus cuentas con nudos.",
    accepted: [["incas", "los incas", "el Imperio inca", "inca"]],
    official: "El Imperio inca",
  },
  {
    id: "hist-desc-gengis",
    franchise: "Imperio mongol",
    difficulty: "media",
    format: "describir",
    prompt:
      "Guerrero de las estepas que unificó a las tribus mongolas y levantó el imperio contiguo más grande de la historia.",
    hint: "(Solo el nombre.)",
    accepted: [["Gengis Kan", "Gengis Khan", "Genghis Khan", "Gengis"]],
    official: "Gengis Kan",
  },
  {
    id: "hist-desc-nilo",
    franchise: "Antiguo Egipto",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué río recorre Egipto de sur a norte y hacía posible la agricultura en pleno desierto?",
    accepted: [["Nilo", "el Nilo"]],
    official: "El Nilo",
  },
  {
    id: "hist-desc-sahara",
    franchise: "Imperio de Malí",
    difficulty: "media",
    format: "describir",
    prompt:
      "Imperio de África occidental que vivió del oro y de las caravanas que cruzaban el desierto, y cuyo emperador más famoso arruinó los precios de Egipto al pasar por allí repartiendo oro.",
    accepted: [["Malí", "Mali", "el Imperio de Malí", "Imperio de Mali"]],
    official: "El Imperio de Malí",
  },

  {
    id: "hist-orden-escrituras",
    franchise: "Mesopotamia",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estos hitos de la escritura y la lectura, del más antiguo al más reciente.",
    items: [
      "La escritura cuneiforme en Mesopotamia",
      "Los primeros alfabetos del Mediterráneo",
      "El papel en China",
      "La imprenta de Gutenberg",
    ],
    official:
      "La escritura cuneiforme, los primeros alfabetos, el papel en China y la imprenta de Gutenberg",
  },
  {
    id: "hist-orden-china",
    franchise: "China imperial",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cuál de estas dinastías chinas es la más antigua?",
    options: ["La Qin", "La Tang", "La Ming", "La Qing"],
    correct: 0,
    official: "La dinastía Qin",
    note: "Qin (siglo III a. C.), Tang (VII-X), Ming (XIV-XVII) y Qing (XVII-XX).",
  },
  {
    id: "hist-orden-dinastias",
    franchise: "China imperial",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas dinastías chinas de la más antigua a la más reciente.",
    items: ["Qin", "Han", "Tang", "Ming"],
    official: "Qin, Han, Tang y Ming",
  },
  {
    id: "hist-orden-africa",
    franchise: "África",
    difficulty: "dificil",
    format: "multiple",
    prompt: "De estos tres imperios de África occidental, ¿cuál fue el primero?",
    options: ["Ghana", "Malí", "Songhai", "Benín"],
    correct: 0,
    official: "El Imperio de Ghana",
    note: "Ghana, luego Malí y después Songhai, cada uno heredando las rutas del oro del anterior.",
  },
  {
    id: "hist-orden-pacifico",
    franchise: "Polinesia",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas tierras según cuándo llegaron a ellas los seres humanos, de lo más antiguo a lo más reciente.",
    items: ["Australia", "Las islas de la Polinesia occidental", "Rapa Nui", "Nueva Zelanda"],
    official:
      "Australia (hace más de 40.000 años), la Polinesia occidental, Rapa Nui y Nueva Zelanda (entre 1250 y 1300)",
  },
  {
    id: "hist-orden-imperios",
    franchise: "Siglo XX",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estos hechos del más antiguo al más reciente.",
    items: [
      "La caída de Constantinopla",
      "La Revolución francesa",
      "La independencia de la India",
      "El final del apartheid en Sudáfrica",
    ],
    official:
      "La caída de Constantinopla (1453), la Revolución francesa (1789), la independencia de la India (1947) y el final del apartheid (años noventa)",
  },

  {
    id: "hist-rel-escrituras",
    franchise: "Mesopotamia",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada civilización con su escritura.",
    pairs: [
      { left: "Mesopotamia", right: "Cuneiforme" },
      { left: "Antiguo Egipto", right: "Jeroglíficos" },
      { left: "Los mayas", right: "Glifos" },
      { left: "China", right: "Caracteres" },
    ],
    official:
      "Mesopotamia–cuneiforme, Egipto–jeroglíficos, los mayas–glifos y China–caracteres",
  },
  {
    id: "hist-rel-capitales",
    franchise: "América precolombina",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada imperio con su capital.",
    pairs: [
      { left: "El Imperio inca", right: "Cuzco" },
      { left: "El Imperio mexica", right: "Tenochtitlan" },
      { left: "El Imperio otomano", right: "Estambul" },
      { left: "El Imperio de Malí", right: "Niani" },
    ],
    official: "Inca–Cuzco, mexica–Tenochtitlan, otomano–Estambul y Malí–Niani",
  },
  {
    id: "hist-rel-rios",
    franchise: "Civilización del Indo",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada civilización antigua con el río junto al que creció.",
    pairs: [
      { left: "Antiguo Egipto", right: "El Nilo" },
      { left: "Mesopotamia", right: "El Tigris y el Éufrates" },
      { left: "La civilización del Indo", right: "El Indo" },
      { left: "La China antigua", right: "El río Amarillo" },
    ],
    official:
      "Egipto–el Nilo, Mesopotamia–el Tigris y el Éufrates, el Indo–el Indo y China–el río Amarillo",
  },
  {
    id: "hist-rel-personajes",
    franchise: "África",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿De qué imperio fue emperador Mansa Musa?",
    options: ["De Malí", "De Songhai", "De Etiopía", "De Benín"],
    correct: 0,
    official: "Del Imperio de Malí",
  },
  {
    id: "hist-rel-lugares",
    franchise: "Siglo XX",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada figura histórica con el sitio donde dejó huella.",
    pairs: [
      { left: "Asoka", right: "La India" },
      { left: "Zheng He", right: "China" },
      { left: "Mansa Musa", right: "Malí" },
      { left: "Nelson Mandela", right: "Sudáfrica" },
    ],
    official: "Asoka–la India, Zheng He–China, Mansa Musa–Malí y Mandela–Sudáfrica",
  },

  {
    id: "hist-comp-muralla",
    franchise: "China imperial",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el nombre de la fortificación más famosa de China: «La Gran ___».",
    accepted: [["Muralla", "muralla"]],
    official: "La Gran Muralla",
  },
  {
    id: "hist-comp-hammurabi",
    franchise: "Mesopotamia",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el nombre de uno de los códigos de leyes más antiguos: «El código de ___».",
    accepted: [["Hammurabi", "Hamurabi"]],
    official: "El código de Hammurabi",
  },
  {
    id: "hist-comp-terracota",
    franchise: "China imperial",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el nombre del ejército enterrado con el primer emperador chino: «Los guerreros de ___».",
    accepted: [["terracota", "terracotta"]],
    official: "Los guerreros de terracota",
  },

  {
    id: "hist-egipto-piramides",
    franchise: "Antiguo Egipto",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Para qué se construyeron las pirámides de Egipto?",
    options: ["Como tumbas de los faraones", "Como templos de culto al sol", "Como graneros", "Como observatorios"],
    correct: 0,
    official: "Como tumbas de los faraones",
  },
  {
    id: "hist-egipto-momias",
    franchise: "Antiguo Egipto",
    difficulty: "facil",
    format: "vf",
    prompt: "Los egipcios momificaban a sus muertos porque creían en una vida después de la muerte.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "hist-grecia-juegos",
    franchise: "Antigua Grecia",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué lugar de Grecia se celebraban los juegos que dieron nombre a las Olimpiadas?",
    options: ["Olimpia", "Atenas", "Esparta", "Delfos"],
    correct: 0,
    official: "Olimpia",
  },
  {
    id: "hist-grecia-filosofos",
    franchise: "Antigua Grecia",
    difficulty: "facil",
    format: "orden",
    prompt: "Ordena a estos tres filósofos griegos según quién enseñó a quién.",
    items: ["Sócrates", "Platón", "Aristóteles"],
    official: "Sócrates enseñó a Platón, y Platón a Aristóteles",
  },
  {
    id: "hist-roma-acueductos",
    franchise: "Antigua Roma",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Para qué servían los acueductos romanos?",
    options: ["Para llevar agua a las ciudades", "Para cruzar ejércitos", "Como murallas", "Para el comercio"],
    correct: 0,
    official: "Para llevar agua a las ciudades",
  },
  {
    id: "hist-roma-latin",
    franchise: "Antigua Roma",
    difficulty: "facil",
    format: "vf",
    prompt: "El castellano, el francés, el italiano y el portugués vienen todos del latín.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "hist-india-castas",
    franchise: "India antigua",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué era el sistema de castas de la India?",
    options: [
      "Una división hereditaria y rígida de la sociedad",
      "Un sistema de impuestos",
      "Una forma de elegir al rey",
      "Un calendario religioso",
    ],
    correct: 0,
    official: "Una división hereditaria y rígida de la sociedad",
  },
  {
    id: "hist-india-gupta",
    franchise: "India antigua",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué imperio indio, entre los siglos IV y VI, se considera la edad dorada de sus matemáticas y su arte?",
    options: ["El gupta", "El maurya", "El mogol", "El chola"],
    correct: 0,
    official: "El Imperio gupta",
  },
  {
    id: "hist-islam-cinco",
    franchise: "Islam medieval",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Hacia qué ciudad rezan los musulmanes?",
    options: ["La Meca", "Medina", "Jerusalén", "Bagdad"],
    correct: 0,
    official: "La Meca",
  },
  {
    id: "hist-alandalus-cordoba",
    franchise: "Al-Ándalus",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué ciudad fue capital del califato de Al-Ándalus y una de las mayores de Europa en el siglo X?",
    options: ["Córdoba", "Toledo", "Sevilla", "Zaragoza"],
    correct: 0,
    official: "Córdoba",
  },
  {
    id: "hist-japon-escritura",
    franchise: "Japón",
    difficulty: "media",
    format: "vf",
    prompt: "La escritura japonesa se inventó en Japón sin ninguna influencia de fuera.",
    correct: false,
    official: "Falso",
    note: "Se construyó a partir de caracteres tomados de China.",
  },
  {
    id: "hist-japon-hiroshima",
    franchise: "Japón",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Sobre qué dos ciudades japonesas se lanzaron bombas atómicas en 1945?",
    options: [
      "Hiroshima y Nagasaki",
      "Tokio y Kioto",
      "Osaka y Kobe",
      "Nagoya y Sapporo",
    ],
    correct: 0,
    official: "Hiroshima y Nagasaki",
  },
  {
    id: "hist-corea-imprenta",
    franchise: "Corea",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué hizo Corea con metal ya en el siglo XIII, antes que nadie en Europa?",
    options: [
      "Imprimir con tipos móviles",
      "Fabricar relojes",
      "Acuñar billetes",
      "Construir puentes colgantes",
    ],
    correct: 0,
    official: "Imprimir con tipos móviles",
  },
  {
    id: "hist-maya-ciudades",
    franchise: "Civilización maya",
    difficulty: "media",
    format: "vf",
    prompt: "Los mayas formaron un imperio unificado bajo un solo rey.",
    correct: false,
    official: "Falso",
    note: "Fueron muchas ciudades-estado independientes, que competían entre sí.",
  },
  {
    id: "hist-maya-donde",
    franchise: "Civilización maya",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué zona vivían los mayas?",
    options: [
      "El sur de México y Centroamérica",
      "Los Andes",
      "El Caribe",
      "El norte de Estados Unidos",
    ],
    correct: 0,
    official: "En el sur de México y Centroamérica",
  },
  {
    id: "hist-inca-cuzco",
    franchise: "Imperio inca",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuál era la capital del Imperio inca?",
    accepted: [["Cuzco", "Cusco"]],
    official: "Cuzco",
  },
  {
    id: "hist-africa-lucy",
    franchise: "África",
    difficulty: "facil",
    format: "vf",
    prompt: "Los primeros seres humanos surgieron en Asia.",
    correct: false,
    official: "Falso",
    note: "Surgieron en África: es donde están los restos más antiguos.",
  },
  {
    id: "hist-africa-swahili",
    franchise: "África",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué unía las ciudades swahili de la costa índica de África con Arabia, la India y China?",
    options: [
      "El comercio marítimo con los monzones",
      "Una calzada de piedra",
      "Un ferrocarril",
      "Un canal artificial",
    ],
    correct: 0,
    official: "El comercio marítimo, aprovechando los monzones",
  },
  {
    id: "hist-esclavitud",
    franchise: "África colonial",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿A qué continente se llevó por la fuerza a millones de africanos entre los siglos XVI y XIX?",
    options: ["A América", "A Asia", "A Oceanía", "A la Antártida"],
    correct: 0,
    official: "A América",
  },
  {
    id: "hist-oceania-navegacion",
    franchise: "Polinesia",
    difficulty: "media",
    format: "vf",
    prompt: "Los polinesios poblaron islas repartidas por un océano más ancho que todos los continentes juntos.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "hist-contemporaneo-luna",
    franchise: "Siglo XX",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué año pisó por primera vez un ser humano la Luna?",
    options: ["1969", "1957", "1961", "1975"],
    correct: 0,
    official: "1969",
  },
  {
    id: "hist-contemporaneo-onu",
    franchise: "Siglo XX",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Después de qué guerra se fundó la ONU?",
    options: [
      "De la Segunda Guerra Mundial",
      "De la Primera Guerra Mundial",
      "De la Guerra Fría",
      "De la guerra de Corea",
    ],
    correct: 0,
    official: "De la Segunda Guerra Mundial",
  },
  {
    id: "hist-contemporaneo-vf-descolonizacion",
    franchise: "Descolonización",
    difficulty: "media",
    format: "vf",
    prompt: "La mayoría de los países africanos son independientes desde hace más de dos siglos.",
    correct: false,
    official: "Falso",
    note: "Casi todos lo son desde los años sesenta del siglo XX.",
  },
];
