import type { Question } from "../types";

/**
 * Series de imagen real: la hornada de Disney Channel y Nickelodeon de los 2000
 * y 2010, que es la que se veía aquí en Clan, Boing y Disney Channel.
 *
 * No son animación, y durante un tiempo el banco solo tuvo dibujos. Dejó de
 * tener sentido cuando entró el Universo Cinematográfico de Marvel: si está
 * Endgame, Hannah Montana también.
 */
export const IMAGEN_REAL: Question[] = [
  // --- Hannah Montana ---
  {
    id: "hannah-doblevida",
    franchise: "Hannah Montana",
    emoji: "🎤",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el secreto de Miley Stewart?",
    options: [
      "De noche es una estrella del pop con peluca",
      "Es una espía",
      "Viaja en el tiempo",
      "Tiene una hermana gemela",
    ],
    correct: 0,
    official: "De noche es la estrella del pop Hannah Montana",
  },
  {
    id: "hannah-peluca",
    franchise: "Hannah Montana",
    emoji: "💇",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De qué color es la peluca con la que Miley se convierte en Hannah Montana?",
    hint: "(Un color.)",
    accepted: [["rubia", "rubio", "amarilla"]],
    official: "Rubia",
  },
  {
    id: "hannah-actriz",
    franchise: "Hannah Montana",
    emoji: "⭐",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué actriz y cantante interpreta a Hannah Montana?",
    hint: "(El nombre basta.)",
    accepted: [["Miley Cyrus", "Miley"]],
    official: "Miley Cyrus",
  },
  {
    id: "hannah-padre",
    franchise: "Hannah Montana",
    emoji: "🎸",
    difficulty: "media",
    format: "vf",
    prompt: "El actor que hace de padre de Miley en la serie es su padre también en la vida real.",
    correct: true,
    official: "Verdadero",
  },

  // --- Los magos de Waverly Place ---
  {
    id: "magos-familia",
    franchise: "Los magos de Waverly Place",
    emoji: "🪄",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué tienen de especial los hermanos Russo?",
    options: ["Son magos en secreto", "Son vampiros", "Viajan en el tiempo", "Son alienígenas"],
    correct: 0,
    official: "Son magos, y lo llevan en secreto",
  },
  {
    id: "magos-alex",
    franchise: "Los magos de Waverly Place",
    emoji: "🎭",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la hermana protagonista, la más gamberra de los tres?",
    hint: "(Solo el nombre.)",
    accepted: [["Alex", "Alex Russo"]],
    official: "Alex Russo",
  },
  {
    id: "magos-actriz",
    franchise: "Los magos de Waverly Place",
    emoji: "⭐",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué actriz y cantante interpreta a Alex Russo?",
    options: ["Selena Gomez", "Demi Lovato", "Miley Cyrus", "Ariana Grande"],
    correct: 0,
    official: "Selena Gomez",
  },
  {
    id: "magos-negocio",
    franchise: "Los magos de Waverly Place",
    emoji: "🥪",
    difficulty: "media",
    format: "vf",
    prompt: "Los padres de los Russo regentan una tienda de bocadillos en Nueva York.",
    correct: true,
    official: "Verdadero",
  },

  // --- Buena suerte, Charlie ---
  {
    id: "charlie-videodiarios",
    franchise: "Buena suerte Charlie",
    emoji: "📹",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué graba Teddy a lo largo de toda la serie?",
    options: [
      "Videodiarios de consejos para su hermana pequeña",
      "Un programa de cocina",
      "Un canal de música",
      "Un documental del instituto",
    ],
    correct: 0,
    official: "Videodiarios de consejos para su hermana pequeña Charlie",
  },
  {
    id: "charlie-frase",
    franchise: "Buena suerte Charlie",
    emoji: "🍀",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa cómo termina Teddy cada videodiario: «Buena suerte, ___».",
    accepted: [["Charlie"]],
    official: "Buena suerte, Charlie",
  },
  {
    id: "charlie-apellido",
    franchise: "Buena suerte Charlie",
    emoji: "🏠",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se apellida la familia protagonista?",
    options: ["Duncan", "Stewart", "Russo", "Baxter"],
    correct: 0,
    official: "Duncan",
  },

  // --- Zack y Cody ---
  {
    id: "zackcody-gemelos",
    franchise: "Zack y Cody",
    emoji: "👬",
    difficulty: "facil",
    format: "vf",
    prompt: "Zack y Cody son hermanos gemelos.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "zackcody-hotel",
    franchise: "Zack y Cody",
    emoji: "🏨",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Dónde viven Zack y Cody en la primera serie?",
    options: ["En un hotel de lujo", "En un internado", "En un barco", "En un rascacielos"],
    correct: 0,
    official: "En un hotel de lujo, el Tipton",
  },
  {
    id: "zackcody-crucero",
    franchise: "Zack y Cody",
    emoji: "🚢",
    difficulty: "media",
    format: "vf",
    prompt: "La continuación de la serie traslada a los gemelos a un crucero.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "zackcody-london",
    franchise: "Zack y Cody",
    emoji: "💅",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la heredera del hotel, tan rica como despistada?",
    hint: "(Solo el nombre.)",
    accepted: [["London", "London Tipton"]],
    official: "London Tipton",
  },

  // --- Es tan Raven ---
  {
    id: "raven-visiones",
    franchise: "Es tan Raven",
    emoji: "🔮",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el don de Raven?",
    options: [
      "Tiene visiones del futuro",
      "Lee la mente",
      "Se vuelve invisible",
      "Habla con animales",
    ],
    correct: 0,
    official: "Tiene visiones del futuro",
  },
  {
    id: "raven-lio",
    franchise: "Es tan Raven",
    emoji: "😬",
    difficulty: "media",
    format: "vf",
    prompt: "Las visiones de Raven siempre le salen bien y evita el problema a la primera.",
    correct: false,
    official: "Falso: por intentar evitarlas suele liarla más",
  },
  {
    id: "raven-disfraces",
    franchise: "Es tan Raven",
    emoji: "🎭",
    difficulty: "media",
    format: "vf",
    prompt: "Raven se disfraza constantemente para colarse donde no debe.",
    correct: true,
    official: "Verdadero",
  },

  // --- Lizzie McGuire ---
  {
    id: "lizzie-dibujo",
    franchise: "Lizzie McGuire",
    emoji: "✏️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué recurso usa la serie para enseñar lo que Lizzie piensa de verdad?",
    options: [
      "Una versión suya en dibujos animados",
      "Una voz en off",
      "Un diario que se lee en pantalla",
      "Flashbacks",
    ],
    correct: 0,
    official: "Una versión suya en dibujos animados",
  },
  {
    id: "lizzie-actriz",
    franchise: "Lizzie McGuire",
    emoji: "⭐",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué actriz interpretó a Lizzie McGuire?",
    options: ["Hilary Duff", "Amanda Bynes", "Raven-Symoné", "Ashley Tisdale"],
    correct: 0,
    official: "Hilary Duff",
  },

  // --- Phil del futuro y Cory en la Casa Blanca ---
  {
    id: "phil-futuro",
    franchise: "Phil del futuro",
    emoji: "⏳",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Por qué se queda atrapada la familia de Phil en nuestra época?",
    options: [
      "Se les avería la máquina del tiempo",
      "Los persiguen",
      "Pierden un mapa",
      "Se esconden",
    ],
    correct: 0,
    official: "Se les avería la máquina del tiempo",
  },
  {
    id: "cory-casablanca",
    franchise: "Cory en la Casa Blanca",
    emoji: "🏛️",
    difficulty: "media",
    format: "vf",
    prompt: "Cory acaba viviendo en la Casa Blanca porque su padre trabaja allí de cocinero.",
    correct: true,
    official: "Verdadero",
  },

  // --- Sonny entre estrellas y Camp Rock ---
  {
    id: "sonny-programa",
    franchise: "Sonny entre estrellas",
    emoji: "📺",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué consigue Sonny al principio de la serie?",
    options: [
      "Entrar en el reparto de un programa de humor",
      "Ganar un concurso de canto",
      "Un papel en el cine",
      "Una beca",
    ],
    correct: 0,
    official: "Entrar en el reparto de un programa de humor",
  },
  {
    id: "camprock-grupo",
    franchise: "Camp Rock",
    emoji: "🎸",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué grupo de hermanos protagonizó Camp Rock junto a Demi Lovato?",
    options: ["Los Jonas Brothers", "Los Backstreet Boys", "Big Time Rush", "One Direction"],
    correct: 0,
    official: "Los Jonas Brothers",
  },
  {
    id: "camprock-campamento",
    franchise: "Camp Rock",
    emoji: "🏕️",
    difficulty: "facil",
    format: "vf",
    prompt: "Camp Rock transcurre en un campamento de verano dedicado a la música.",
    correct: true,
    official: "Verdadero",
  },

  // --- High School Musical ---
  {
    id: "hsm-instituto",
    franchise: "High School Musical",
    emoji: "🏀",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el instituto de High School Musical?",
    hint: "(Dos palabras.)",
    accepted: [["East High"]],
    official: "East High",
  },
  {
    id: "hsm-troy",
    franchise: "High School Musical",
    emoji: "⭐",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿A qué deporte juega Troy Bolton?",
    options: ["Baloncesto", "Fútbol americano", "Béisbol", "Natación"],
    correct: 0,
    official: "Baloncesto",
  },
  {
    id: "hsm-actor",
    franchise: "High School Musical",
    emoji: "⭐",
    difficulty: "media",
    format: "corta",
    prompt: "¿Qué actor saltó a la fama interpretando a Troy Bolton?",
    hint: "(El nombre basta.)",
    accepted: [["Zac Efron", "Efron", "Zac"]],
    official: "Zac Efron",
  },

  // --- Violetta y Soy Luna ---
  {
    id: "violetta-pais",
    franchise: "Violetta",
    emoji: "🎹",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué país se rodó Violetta?",
    options: ["Argentina", "México", "España", "Colombia"],
    correct: 0,
    official: "Argentina",
  },
  {
    id: "violetta-talento",
    franchise: "Violetta",
    emoji: "🎤",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el talento de Violetta que su padre intenta esconder?",
    options: ["Cantar", "Bailar", "Pintar", "Actuar"],
    correct: 0,
    official: "Cantar",
  },
  {
    id: "soyluna-patines",
    franchise: "Soy Luna",
    emoji: "🎬",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué deporte marca la vida de Luna?",
    options: ["El patinaje", "La gimnasia", "El baile de salón", "La natación"],
    correct: 0,
    official: "El patinaje",
  },

  // --- Otras de Disney Channel ---
  {
    id: "jessie-nanny",
    franchise: "Jessie",
    emoji: "🍼",
    difficulty: "media",
    format: "multiple",
    prompt: "¿De qué trabaja Jessie al llegar a Nueva York?",
    options: ["De niñera", "De camarera", "De actriz", "De profesora"],
    correct: 0,
    official: "De niñera de una familia con cuatro hijos",
  },
  {
    id: "austinally-musica",
    franchise: "Austin y Ally",
    emoji: "🎼",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se reparten el trabajo Austin y Ally?",
    options: [
      "Ella compone y él canta",
      "Él compone y ella canta",
      "Los dos cantan a dúo",
      "Ella toca y él baila",
    ],
    correct: 0,
    official: "Ally compone y Austin canta",
  },
  {
    id: "shakeitup-baile",
    franchise: "A todo ritmo",
    emoji: "💃",
    difficulty: "media",
    format: "vf",
    prompt: "Las protagonistas de A todo ritmo consiguen entrar como bailarinas en un programa de televisión.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "livymaddie-gemelas",
    franchise: "Liv y Maddie",
    emoji: "👯",
    difficulty: "media",
    format: "vf",
    prompt: "En Liv y Maddie, una sola actriz interpreta a las dos hermanas gemelas.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "descendientes-hijos",
    franchise: "Descendientes",
    emoji: "🍎",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Quiénes son los protagonistas de Descendientes?",
    options: [
      "Los hijos de los villanos de Disney",
      "Los hijos de las princesas",
      "Unos magos",
      "Unos deportistas",
    ],
    correct: 0,
    official: "Los hijos de los villanos de Disney",
  },
  {
    id: "descendientes-maléfica",
    franchise: "Descendientes",
    emoji: "💜",
    difficulty: "media",
    format: "corta",
    prompt: "¿De qué villana es hija Mal, la protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Maléfica"]],
    official: "De Maléfica",
  },

  // --- iCarly ---
  {
    id: "icarly-webshow",
    franchise: "iCarly",
    emoji: "🍖",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué montan Carly y sus amigos?",
    options: [
      "Un programa de humor por internet",
      "Una banda de música",
      "Una revista del instituto",
      "Un canal de radio",
    ],
    correct: 0,
    official: "Un programa de humor por internet",
  },
  {
    id: "icarly-sam",
    franchise: "iCarly",
    emoji: "🍖",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la mejor amiga de Carly, la bruta que se pasa el día comiendo?",
    hint: "(Solo el nombre.)",
    accepted: [["Sam", "Sam Puckett"]],
    official: "Sam",
  },
  {
    id: "icarly-hermano",
    franchise: "iCarly",
    emoji: "🎨",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿A qué se dedica Spencer, el hermano mayor de Carly?",
    options: ["Es escultor", "Es abogado", "Es músico", "Es cocinero"],
    correct: 0,
    official: "Es escultor",
  },

  // --- Drake y Josh ---
  {
    id: "drakejosh-hermanos",
    franchise: "Drake y Josh",
    emoji: "👦",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué relación tienen Drake y Josh?",
    options: [
      "Son hermanastros",
      "Son hermanos gemelos",
      "Son primos",
      "Son vecinos",
    ],
    correct: 0,
    official: "Son hermanastros",
  },
  {
    id: "drakejosh-megan",
    franchise: "Drake y Josh",
    emoji: "😈",
    difficulty: "media",
    format: "vf",
    prompt: "La hermana pequeña, Megan, se pasa la serie haciéndoles la vida imposible.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "drakejosh-guitarra",
    franchise: "Drake y Josh",
    emoji: "👦",
    difficulty: "media",
    format: "vf",
    prompt: "De los dos hermanos, el músico es Josh y el estudioso es Drake.",
    correct: false,
    official: "Falso: es al revés, Drake es el de la guitarra",
  },

  // --- Victorious ---
  {
    id: "victorious-instituto",
    franchise: "Victorious",
    emoji: "🎭",
    difficulty: "media",
    format: "multiple",
    prompt: "¿A qué clase de instituto entra Tori Vega?",
    options: [
      "A uno de artes escénicas",
      "A uno militar",
      "A un internado",
      "A uno de ciencias",
    ],
    correct: 0,
    official: "A Hollywood Arts, un instituto de artes escénicas",
  },
  {
    id: "victorious-ariana",
    franchise: "Victorious",
    emoji: "⭐",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué cantante hoy famosísima salía en Victorious haciendo de Cat?",
    options: ["Ariana Grande", "Selena Gomez", "Dua Lipa", "Billie Eilish"],
    correct: 0,
    official: "Ariana Grande",
  },
  {
    id: "victorious-spinoff",
    franchise: "Victorious",
    emoji: "🐱",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Con qué otra serie de Nickelodeon se cruzó Victorious en un spin-off?",
    options: ["iCarly", "Drake y Josh", "Zoey 101", "Big Time Rush"],
    correct: 0,
    official: "Con iCarly, en Sam y Cat",
  },

  // --- Zoey 101, Big Time Rush y Los Thundermans ---
  {
    id: "zoey-internado",
    franchise: "Zoey 101",
    emoji: "🏫",
    difficulty: "media",
    format: "vf",
    prompt: "Zoey es de las primeras chicas en entrar en un internado que hasta entonces era solo de chicos.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "bigtimerush-banda",
    franchise: "Big Time Rush",
    emoji: "🎤",
    difficulty: "media",
    format: "multiple",
    prompt: "¿De qué va Big Time Rush?",
    options: [
      "Cuatro amigos montan un grupo de música",
      "Cuatro amigos juegan al hockey",
      "Una familia se muda a Los Ángeles",
      "Unos chicos ganan la lotería",
    ],
    correct: 0,
    official: "Cuatro amigos que acaban montando un grupo de música",
  },
  {
    id: "thundermans-familia",
    franchise: "Los Thundermans",
    emoji: "⚡",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué esconde la familia Thunderman a sus vecinos?",
    options: [
      "Que son superhéroes",
      "Que son extraterrestres",
      "Que son espías",
      "Que son magos",
    ],
    correct: 0,
    official: "Que son superhéroes",
  },
  {
    id: "ned-manual",
    franchise: "Manual de supervivencia escolar de Ned",
    emoji: "🎬",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué formato tiene esta serie?",
    options: [
      "Ned da consejos al espectador para sobrevivir al instituto",
      "Un diario secreto",
      "Un concurso",
      "Un documental",
    ],
    correct: 0,
    official: "Ned habla a cámara dando consejos para sobrevivir al instituto",
  },
  {
    id: "henrydanger-ayudante",
    franchise: "Henry Danger",
    emoji: "🦸",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué trabajo consigue Henry en la serie?",
    options: [
      "Ayudante de un superhéroe",
      "Repartidor de pizzas",
      "Socorrista",
      "Camarero",
    ],
    correct: 0,
    official: "Ayudante de un superhéroe, Capitán Man",
  },

  // --- Conjuntos ---
  {
    id: "relacionar-disneychannel",
    franchise: "Series de imagen real",
    emoji: "📺",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada protagonista con su serie.",
    pairs: [
      { left: "Miley Stewart", right: "Hannah Montana" },
      { left: "Alex Russo", right: "Los magos de Waverly Place" },
      { left: "Teddy Duncan", right: "Buena suerte Charlie" },
      { left: "Raven Baxter", right: "Es tan Raven" },
    ],
    official:
      "Miley Stewart–Hannah Montana, Alex Russo–Los magos de Waverly Place, Teddy Duncan–Buena suerte Charlie y Raven Baxter–Es tan Raven",
  },
  {
    id: "relacionar-nickelodeon-real",
    franchise: "Series de imagen real",
    emoji: "🟠",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada personaje con su serie de Nickelodeon.",
    pairs: [
      { left: "Carly Shay", right: "iCarly" },
      { left: "Megan", right: "Drake y Josh" },
      { left: "Tori Vega", right: "Victorious" },
      { left: "Zoey Brooks", right: "Zoey 101" },
    ],
    official:
      "Carly Shay–iCarly, Megan–Drake y Josh, Tori Vega–Victorious y Zoey Brooks–Zoey 101",
  },
  {
    id: "relacionar-cantantes-series",
    franchise: "Series de imagen real",
    emoji: "🎤",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada cantante con la serie en la que se dio a conocer.",
    pairs: [
      { left: "Miley Cyrus", right: "Hannah Montana" },
      { left: "Selena Gomez", right: "Los magos de Waverly Place" },
      { left: "Ariana Grande", right: "Victorious" },
      { left: "Demi Lovato", right: "Sonny entre estrellas" },
    ],
    official:
      "Miley Cyrus–Hannah Montana, Selena Gomez–Los magos de Waverly Place, Ariana Grande–Victorious y Demi Lovato–Sonny entre estrellas",
  },
  {
    id: "orden-disneychannel",
    franchise: "Series de imagen real",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de Disney Channel de la más antigua a la más reciente.",
    items: ["Lizzie McGuire", "Es tan Raven", "Hannah Montana", "Buena suerte Charlie"],
    official:
      "Lizzie McGuire (2001), Es tan Raven (2003), Hannah Montana (2006) y Buena suerte Charlie (2010)",
  },
  {
    id: "orden-nickelodeon-real",
    franchise: "Series de imagen real",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de Nickelodeon de la más antigua a la más reciente.",
    items: ["Drake y Josh", "Zoey 101", "iCarly", "Victorious"],
    official: "Drake y Josh (2004), Zoey 101 (2005), iCarly (2007) y Victorious (2010)",
  },
  {
    id: "imagenreal-cadena",
    franchise: "Series de imagen real",
    emoji: "🏢",
    difficulty: "facil",
    format: "vf",
    prompt: "Hannah Montana, Los magos de Waverly Place y Buena suerte Charlie son todas de Disney Channel.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "imagenreal-icarly-cadena",
    franchise: "Series de imagen real",
    emoji: "🏢",
    difficulty: "facil",
    format: "vf",
    prompt: "iCarly, Drake y Josh y Victorious eran series de Disney Channel.",
    correct: false,
    official: "Falso: son de Nickelodeon",
  },
];
