import type { Question } from "../types";

/**
 * Tema «Música»: canciones y artistas.
 *
 * Sale de cinco listas de Spotify (reggaetón y trap latino, fiesta española,
 * Duki, Eladio Carrión y Taylor Swift) más pop anglosajón de los 2000.
 *
 * Convenciones propias de este banco, además de las generales:
 *
 * - **`franchise` es el artista**, para que la regla de no repetir franquicia
 *   en 8 preguntas sirva aquí de no repetir artista. `categoriaDe` lo lleva a
 *   su género, que es lo que desglosa el resumen de fin de partida.
 * - **Ninguna pregunta cita la letra de una canción.** Era la idea original y
 *   no se puede hacer: reproducir letras no está permitido. Lo que hace las
 *   veces es contar de qué va la canción con otras palabras (`describir`),
 *   completar el **título** —que no es la letra— y preguntar por autoría,
 *   disco y año.
 * - **Los datos van contrastados uno a uno**, no escritos de memoria. Es la
 *   diferencia con el banco de Palomitas, y la pidió Oscar después de que una
 *   pregunta diera por bueno que Duki explotó con «Goteo» cuando fue con «She
 *   Don't Give a Fo». Fuente principal: Wikipedia en español e inglés,
 *   consultada el 27 de septiembre de 2026.
 */
export const MUSICA: Question[] = [
  // --- Duki ---
  {
    id: "duki-nombre",
    franchise: "Duki",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cuál es el nombre real de Duki?",
    hint: "(Nombre y primer apellido.)",
    accepted: [["Mauro", "Mauro Ezequiel"], ["Lombardo"]],
    official: "Mauro Ezequiel Lombardo",
  },
  {
    id: "duki-quinto-escalon",
    franchise: "Duki",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué competencia de freestyle se dio a conocer Duki, ganándola en 2016?",
    options: ["El Quinto Escalón", "Red Bull Batalla", "God Level", "FMS Argentina"],
    correct: 0,
    official: "El Quinto Escalón",
  },
  {
    id: "duki-she-dont-give",
    franchise: "Duki",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Con qué tema de 2017 irrumpió Duki en la escena y se metió en el top 10?",
    options: ["She Don't Give a Fo", "Goteo", "Hitboy", "Rockstar"],
    correct: 0,
    official: "She Don't Give a Fo",
    note: "Con Khea y Cazzu. «Goteo» llegó después, ya en su primer álbum.",
  },
  {
    id: "duki-vf-goteo",
    franchise: "Duki",
    difficulty: "media",
    format: "vf",
    prompt: "El tema con el que Duki saltó a la fama fue «Goteo».",
    correct: false,
    official: "Falso",
    note: "Fue «She Don't Give a Fo», de 2017. «Goteo» es de Súper sangre joven, de 2019.",
  },
  {
    id: "duki-super-sangre",
    franchise: "Duki",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se titula el primer álbum de estudio de Duki, publicado en 2019?",
    accepted: [["Súper sangre joven", "Super sangre joven"]],
    official: "Súper sangre joven",
  },
  {
    id: "duki-modo-diablo",
    franchise: "Duki",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el grupo que formó Duki en 2017 con YSY A y Neo Pistea?",
    options: ["Modo Diablo", "Mueva Records", "Dale Play", "Sauce Boyz"],
    correct: 0,
    official: "Modo Diablo",
  },
  {
    id: "duki-pais",
    franchise: "Duki",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué país es Duki?",
    options: ["Argentina", "Puerto Rico", "España", "Colombia"],
    correct: 0,
    official: "Argentina",
  },
  {
    id: "duki-vf-ep24",
    franchise: "Duki",
    difficulty: "media",
    format: "vf",
    prompt: "Duki publicó su EP «24» el día que cumplía veinticuatro años.",
    correct: true,
    official: "Verdadero",
    note: "Salió el 24 de junio de 2020, su cumpleaños.",
  },
  {
    id: "duki-yhlqmdlg",
    franchise: "Duki",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué álbum de Bad Bunny colabora Duki, en el tema «Hablamos Mañana»?",
    options: ["YHLQMDLG", "X 100pre", "Oasis", "Un Verano Sin Ti"],
    correct: 0,
    official: "YHLQMDLG",
  },
  {
    id: "duki-ameri",
    franchise: "Duki",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se titula el quinto álbum de estudio de Duki, de 2024?",
    options: ["Ameri", "Antes de Ameri", "Desde el fin del mundo", "5202"],
    correct: 0,
    official: "Ameri",
  },
  {
    id: "duki-vf-spotify",
    franchise: "Duki",
    difficulty: "facil",
    format: "vf",
    prompt: "Duki ha sido el artista argentino más escuchado del mundo en Spotify varios años seguidos.",
    correct: true,
    official: "Verdadero",
  },

  // --- Eladio Carrión ---
  {
    id: "eladio-natacion",
    franchise: "Eladio Carrión",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué deporte practicó Eladio Carrión a nivel internacional antes de dedicarse a la música?",
    options: ["Natación", "Baloncesto", "Boxeo", "Béisbol"],
    correct: 0,
    official: "Natación",
    note: "Representó a Puerto Rico en los Juegos Panamericanos de Guadalajara 2011.",
  },
  {
    id: "eladio-sauce-boyz",
    franchise: "Eladio Carrión",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se titula el álbum debut de Eladio Carrión, de 2020?",
    accepted: [["Sauce Boyz"]],
    official: "Sauce Boyz",
  },
  {
    id: "eladio-coco-chanel",
    franchise: "Eladio Carrión",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Con qué artista canta Eladio Carrión «Coco Chanel»?",
    options: ["Bad Bunny", "Myke Towers", "Rauw Alejandro", "Anuel AA"],
    correct: 0,
    official: "Bad Bunny",
  },
  {
    id: "eladio-mi-cubana",
    franchise: "Eladio Carrión",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué tema de 2018, junto a Cazzu, Khea y Ecko, le dio a Eladio Carrión el reconocimiento internacional?",
    options: ["Mi cubana", "Me enamoré de una yal", "Kemba Walker", "Gladiador"],
    correct: 0,
    official: "Mi cubana",
  },
  {
    id: "eladio-vf-nacimiento",
    franchise: "Eladio Carrión",
    difficulty: "media",
    format: "vf",
    prompt: "Eladio Carrión nació en Estados Unidos, no en Puerto Rico.",
    correct: true,
    official: "Verdadero",
    note: "Nació en Kansas City en 1994, en una familia puertorriqueña; se mudó a Humacao a los 11 años.",
  },
  {
    id: "eladio-monarca",
    franchise: "Eladio Carrión",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se titula el segundo álbum de Eladio Carrión, de 2021?",
    options: ["Monarca", "Sauce Boyz 2", "SEN2 KBRN", "3 Men 2 Kbrn"],
    correct: 0,
    official: "Monarca",
  },
  {
    id: "eladio-describir",
    franchise: "Eladio Carrión",
    difficulty: "media",
    format: "describir",
    prompt:
      "Rapero criado en Humacao que antes de la música llegó a competir nadando por Puerto Rico, y que empezó imitando voces de artistas urbanos.",
    hint: "(Nombre y apellido.)",
    accepted: [["Eladio", "Eladio Carrión"], ["Carrión", "Carrion", "Eladio Carrión"]],
    official: "Eladio Carrión",
  },

  // --- Bizarrap ---
  {
    id: "bzrp-nombre",
    franchise: "Bizarrap",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cuál es el nombre real de Bizarrap?",
    options: ["Gonzalo Julián Conde", "Mauro Lombardo", "Alejandro Conde", "Julián Bizarro"],
    correct: 0,
    official: "Gonzalo Julián Conde",
  },
  {
    id: "bzrp-sessions",
    franchise: "Bizarrap",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llaman las sesiones que Bizarrap graba con otros artistas?",
    options: ["BZRP Music Sessions", "Bizarrap Live", "Dale Play Sessions", "Sesiones del Conde"],
    correct: 0,
    official: "BZRP Music Sessions",
  },
  {
    id: "bzrp-relacionar",
    franchise: "Bizarrap",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada artista con el número de su BZRP Music Session.",
    pairs: [
      { left: "Eladio Carrión", right: "Vol. 40" },
      { left: "Quevedo", right: "Vol. 52" },
      { left: "Shakira", right: "Vol. 53" },
    ],
    official: "Eladio Carrión–Vol. 40, Quevedo–Vol. 52 y Shakira–Vol. 53",
  },
  {
    id: "bzrp-vf-freestyle",
    franchise: "Bizarrap",
    difficulty: "media",
    format: "vf",
    prompt: "Bizarrap empezó subiendo a YouTube vídeos editados de batallas de freestyle.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "bzrp-primera",
    franchise: "Bizarrap",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Con qué rapero argentino grabó Bizarrap su primera BZRP Music Session, en 2019?",
    options: ["Bhavi", "Duki", "Trueno", "Lit Killah"],
    correct: 0,
    official: "Bhavi",
  },

  // --- Bad Bunny ---
  {
    id: "badbunny-nombre",
    franchise: "Bad Bunny",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cuál es el nombre real de Bad Bunny?",
    hint: "(Con el nombre basta.)",
    accepted: [["Benito", "Benito Antonio", "Benito Martínez", "Benito Antonio Martínez Ocasio"]],
    official: "Benito Antonio Martínez Ocasio",
  },
  {
    id: "badbunny-supermercado",
    franchise: "Bad Bunny",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué trabajaba Bad Bunny mientras empezaba a subir sus temas a internet?",
    options: [
      "Empaquetando en un supermercado",
      "De camarero",
      "En una gasolinera",
      "De repartidor",
    ],
    correct: 0,
    official: "Empaquetando en un supermercado",
  },
  {
    id: "badbunny-pais",
    franchise: "Bad Bunny",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De qué país es Bad Bunny?",
    accepted: [["Puerto Rico"]],
    official: "Puerto Rico",
  },
  {
    id: "badbunny-soy-peor",
    franchise: "Bad Bunny",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué sencillo de 2016 lanzó a Bad Bunny al éxito?",
    options: ["Soy peor", "Mía", "Callaíta", "Diles"],
    correct: 0,
    official: "Soy peor",
  },
  {
    id: "badbunny-x100pre",
    franchise: "Bad Bunny",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se titula el álbum de estudio debut de Bad Bunny, de 2018?",
    options: ["X 100pre", "YHLQMDLG", "El Último Tour Del Mundo", "Oasis"],
    correct: 0,
    official: "X 100pre",
  },
  {
    id: "badbunny-oasis",
    franchise: "Bad Bunny",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Con qué artista colombiano grabó Bad Bunny el álbum conjunto «Oasis» en 2019?",
    options: ["J Balvin", "Maluma", "Karol G", "Feid"],
    correct: 0,
    official: "J Balvin",
  },
  {
    id: "badbunny-vf-soundcloud",
    franchise: "Bad Bunny",
    difficulty: "media",
    format: "vf",
    prompt: "Bad Bunny se dio a conocer ganando un concurso de televisión.",
    correct: false,
    official: "Falso",
    note: "Se dio a conocer subiendo sus canciones a SoundCloud.",
  },
  {
    id: "badbunny-cardib",
    franchise: "Bad Bunny",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Con qué artista canta Bad Bunny «I Like It», que llegó al número 1 en Estados Unidos?",
    options: ["Cardi B", "Drake", "Rihanna", "Nicki Minaj"],
    correct: 0,
    official: "Cardi B",
    note: "Con Drake hizo «Mía», que se quedó en el número 3.",
  },

  // --- Estopa ---
  {
    id: "estopa-hermanos",
    franchise: "Estopa",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se apellidan los dos hermanos que forman Estopa?",
    accepted: [["Muñoz", "Munoz"]],
    official: "David y José Manuel Muñoz",
  },
  {
    id: "estopa-cornella",
    franchise: "Estopa",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué ciudad son Estopa?",
    options: ["Cornellà de Llobregat", "Badalona", "Sabadell", "L'Hospitalet"],
    correct: 0,
    official: "Cornellà de Llobregat",
  },
  {
    id: "estopa-nombre",
    franchise: "Estopa",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿De dónde sale el nombre «Estopa»?",
    options: [
      "Del grito «¡Dale estopa!» del encargado de la fábrica donde trabajaban",
      "Del apodo del padre de los hermanos",
      "De una canción de Los Chichos",
      "Del barrio donde se criaron",
    ],
    correct: 0,
    official: "Del grito «¡Dale estopa!» del encargado de la fábrica donde trabajaban",
  },
  {
    id: "estopa-falda",
    franchise: "Estopa",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el título del primer gran éxito de Estopa: «La raja de tu ___».",
    accepted: [["falda"]],
    official: "La raja de tu falda",
  },
  {
    id: "estopa-destrangis",
    franchise: "Estopa",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se titula el segundo álbum de Estopa, de 2001?",
    accepted: [["Destrangis"]],
    official: "Destrangis",
  },
  {
    id: "estopa-1999",
    franchise: "Estopa",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué año salió el primer disco de Estopa?",
    options: ["1999", "1997", "2001", "2003"],
    correct: 0,
    official: "1999",
  },
  {
    id: "estopa-vf-primos",
    franchise: "Estopa",
    difficulty: "facil",
    format: "vf",
    prompt: "Los dos miembros de Estopa son primos.",
    correct: false,
    official: "Falso",
    note: "Son hermanos: David y José Manuel Muñoz.",
  },
  {
    id: "estopa-fabrica",
    franchise: "Estopa",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué tipo de fábrica trabajaban los hermanos Muñoz cuando empezaron a componer?",
    options: ["Una fábrica de coches", "Una fábrica de muebles", "Una imprenta", "Una fábrica textil"],
    correct: 0,
    official: "Una fábrica de coches",
  },
  {
    id: "estopa-genero",
    franchise: "Estopa",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué dos estilos mezcla la música de Estopa?",
    options: ["Rumba catalana y pop rock", "Flamenco y jazz", "Salsa y rock", "Rumba y reggae"],
    correct: 0,
    official: "Rumba catalana y pop rock",
  },
  {
    id: "estopa-describir",
    franchise: "Estopa",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Dúo de dos hermanos de Cornellà que mezcla rumba y rock, debutó en 1999 y vendió más de dos millones de copias con su primer disco.",
    accepted: [["Estopa"]],
    official: "Estopa",
  },

  // --- Huecco ---
  {
    id: "huecco-sugarless",
    franchise: "Huecco",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿De qué banda de rap-metal fue cantante Huecco antes de su carrera en solitario?",
    options: ["Sugarless", "Def Con Dos", "Hamlet", "Skunk D.F."],
    correct: 0,
    official: "Sugarless",
  },
  {
    id: "huecco-guerrera",
    franchise: "Huecco",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el título del tema con el que Huecco saltó a la fama en 2006: «Pa' mi ___».",
    accepted: [["guerrera"]],
    official: "Pa' mi guerrera",
  },
  {
    id: "huecco-rumbaton",
    franchise: "Huecco",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo bautizó Huecco su mezcla de rumba y reguetón?",
    options: ["Rumbatón", "Flamenkito", "Rumba urbana", "Reggaerrumba"],
    correct: 0,
    official: "Rumbatón",
  },
  {
    id: "huecco-cuba",
    franchise: "Huecco",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué país escribió Huecco su primer éxito en solitario?",
    options: ["Cuba", "México", "Estados Unidos", "República Dominicana"],
    correct: 0,
    official: "Cuba",
  },
  {
    id: "huecco-vf-grupo",
    franchise: "Huecco",
    difficulty: "media",
    format: "vf",
    prompt: "Huecco empezó su carrera en solitario y nunca había estado en un grupo.",
    correct: false,
    official: "Falso",
    note: "Estuvo diez años en Sugarless, una banda de rap-metal, hasta que se disolvió en 2005.",
  },

  // --- Marc Anthony ---
  {
    id: "marcanthony-khaled",
    franchise: "Marc Anthony",
    difficulty: "dificil",
    format: "multiple",
    prompt: "«Vivir mi vida», de Marc Anthony, es una adaptación de una canción de otro artista. ¿De quién?",
    options: ["Khaled", "Manu Chao", "Carlos Vives", "Juan Luis Guerra"],
    correct: 0,
    official: "Khaled",
    note: "El original es «C'est la vie», del argelino Khaled, publicado en 2012.",
  },
  {
    id: "marcanthony-redone",
    franchise: "Marc Anthony",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué productor está detrás de «C'est la vie», el original del que sale «Vivir mi vida»?",
    options: ["RedOne", "Timbaland", "Dr. Luke", "Pharrell Williams"],
    correct: 0,
    official: "RedOne",
  },
  {
    id: "marcanthony-vf-original",
    franchise: "Marc Anthony",
    difficulty: "media",
    format: "vf",
    prompt: "«Vivir mi vida» es una canción original de Marc Anthony.",
    correct: false,
    official: "Falso",
    note: "Es la versión en español de «C'est la vie», de Khaled.",
  },
  {
    id: "marcanthony-describir",
    franchise: "Marc Anthony",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Salsa adaptada de un éxito del argelino Khaled que se convirtió en el himno de reírse de los problemas y tirar hacia adelante.",
    accepted: [["Vivir mi vida"]],
    official: "Vivir mi vida",
  },

  // --- Taylor Swift ---
  {
    id: "taylor-1989-nombre",
    franchise: "Taylor Swift",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Por qué se titula «1989» ese álbum de Taylor Swift?",
    options: [
      "Es el año en que ella nació",
      "Es el año en que salió el disco",
      "Es el número de su casa",
      "Es el año en que empezó a cantar",
    ],
    correct: 0,
    official: "Es el año en que ella nació",
  },
  {
    id: "taylor-1989-anio",
    franchise: "Taylor Swift",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué año salió el álbum «1989»?",
    options: ["2014", "1989", "2012", "2017"],
    correct: 0,
    official: "2014",
  },
  {
    id: "taylor-country",
    franchise: "Taylor Swift",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué género dejó atrás Taylor Swift al publicar «1989», pasándose al pop?",
    accepted: [["country", "el country"]],
    official: "El country",
  },
  {
    id: "taylor-max-martin",
    franchise: "Taylor Swift",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué productor sueco es la mano principal detrás del sonido de «1989»?",
    options: ["Max Martin", "Jack Antonoff", "Ryan Tedder", "Aaron Dessner"],
    correct: 0,
    official: "Max Martin",
  },
  {
    id: "taylor-shake-it-off",
    franchise: "Taylor Swift",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál fue el primer sencillo de «1989»?",
    options: ["Shake It Off", "Blank Space", "Style", "Bad Blood"],
    correct: 0,
    official: "Shake It Off",
  },
  {
    id: "taylor-vf-1989",
    franchise: "Taylor Swift",
    difficulty: "media",
    format: "vf",
    prompt: "Taylor Swift tituló «1989» por el año en que se publicó el disco.",
    correct: false,
    official: "Falso",
    note: "Salió en 2014. El título es su año de nacimiento, como símbolo de empezar de nuevo.",
  },
  {
    id: "taylor-taylors-version",
    franchise: "Taylor Swift",
    difficulty: "facil",
    format: "vf",
    prompt: "Taylor Swift regrabó discos suyos antiguos y los publicó como «Taylor's Version».",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "taylor-orden",
    franchise: "Taylor Swift",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estos álbumes de Taylor Swift del más antiguo al más reciente.",
    items: ["Red", "1989", "Reputation"],
    official: "Red (2012), 1989 (2014) y Reputation (2017)",
  },

  // --- Los 2000 en inglés ---
  {
    id: "eminem-lose-yourself",
    franchise: "Eminem",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿A qué película pertenece «Lose Yourself», de Eminem?",
    options: ["8 Mile", "Get Rich or Die Tryin'", "Training Day", "Hustle & Flow"],
    correct: 0,
    official: "8 Mile",
  },
  {
    id: "eminem-vf-album",
    franchise: "Eminem",
    difficulty: "media",
    format: "vf",
    prompt: "«Lose Yourself» salió como parte de un álbum de estudio normal de Eminem.",
    correct: false,
    official: "Falso",
    note: "Salió en la banda sonora de 8 Mile, la película que él mismo protagonizó, en 2002.",
  },
  {
    id: "eminem-numero-uno",
    franchise: "Eminem",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué supuso «Lose Yourself» para Eminem en las listas de Estados Unidos?",
    options: [
      "Fue su primer número 1",
      "Fue su primer top 10",
      "Nunca entró en el top 20",
      "Fue su último número 1",
    ],
    correct: 0,
    official: "Fue su primer número 1",
    note: "Aguantó doce semanas seguidas en lo más alto del Billboard Hot 100.",
  },
  {
    id: "amy-back-to-black",
    franchise: "Amy Winehouse",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué álbum de Amy Winehouse está «Rehab»?",
    options: ["Back to Black", "Frank", "Lioness", "At the BBC"],
    correct: 0,
    official: "Back to Black",
  },
  {
    id: "amy-vf-primero",
    franchise: "Amy Winehouse",
    difficulty: "media",
    format: "vf",
    prompt: "«Back to Black» fue el primer álbum de Amy Winehouse.",
    correct: false,
    official: "Falso",
    note: "Fue el segundo y el último. El primero fue «Frank», de 2003.",
  },
  {
    id: "amy-productor",
    franchise: "Amy Winehouse",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué productor británico firma buena parte de «Back to Black»?",
    options: ["Mark Ronson", "Rick Rubin", "Brian Eno", "Nigel Godrich"],
    correct: 0,
    official: "Mark Ronson",
    note: "Lo produjo junto a Salaam Remi.",
  },
  {
    id: "amy-anio",
    franchise: "Amy Winehouse",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué año salió «Back to Black»?",
    options: ["2006", "2003", "2009", "2011"],
    correct: 0,
    official: "2006",
  },
  // --- Britney Spears ---
  {
    id: "britney-toxic-album",
    franchise: "Britney Spears",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué álbum de Britney Spears está «Toxic»?",
    options: ["In the Zone", "Oops!... I Did It Again", "Britney", "Blackout"],
    correct: 0,
    official: "In the Zone",
  },
  {
    id: "britney-oops-anio",
    franchise: "Britney Spears",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué año es «Oops!... I Did It Again»?",
    options: ["2000", "1998", "2003", "2005"],
    correct: 0,
    official: "2000",
  },
  {
    id: "britney-max-martin",
    franchise: "Britney Spears",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Quién escribió y produjo «Oops!... I Did It Again»?",
    options: ["Max Martin", "Timbaland", "Dr. Luke", "Pharrell Williams"],
    correct: 0,
    official: "Max Martin",
    note: "Junto a Rami Yacoub, en los estudios Cheiron de Estocolmo.",
  },
  {
    id: "britney-titanic",
    franchise: "Britney Spears",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué película menciona la parte hablada de «Oops!... I Did It Again»?",
    options: ["Titanic", "Pretty Woman", "Ghost", "Grease"],
    correct: 0,
    official: "Titanic",
  },
  {
    id: "britney-vf-toxic",
    franchise: "Britney Spears",
    difficulty: "media",
    format: "vf",
    prompt: "«Toxic» fue el primer sencillo del álbum «In the Zone».",
    correct: false,
    official: "Falso",
    note: "Fue el segundo. El primero fue «Me Against the Music».",
  },

  // --- Linkin Park ---
  {
    id: "linkinpark-hybrid",
    franchise: "Linkin Park",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se titula el álbum debut de Linkin Park, de 2000?",
    options: ["Hybrid Theory", "Meteora", "Minutes to Midnight", "Reanimation"],
    correct: 0,
    official: "Hybrid Theory",
  },
  {
    id: "linkinpark-chester",
    franchise: "Linkin Park",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llamaba el cantante de Linkin Park que murió en 2017?",
    hint: "(Nombre y apellido.)",
    accepted: [["Chester", "Chester Bennington"], ["Bennington", "Chester Bennington"]],
    official: "Chester Bennington",
  },
  {
    id: "linkinpark-meteora",
    franchise: "Linkin Park",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se titula el segundo álbum de Linkin Park, de 2003?",
    options: ["Meteora", "Hybrid Theory", "Minutes to Midnight", "A Thousand Suns"],
    correct: 0,
    official: "Meteora",
  },
  {
    id: "linkinpark-vf-intheend",
    franchise: "Linkin Park",
    difficulty: "media",
    format: "vf",
    prompt: "«In the End» fue el primer sencillo que se sacó de «Hybrid Theory».",
    correct: false,
    official: "Falso",
    note: "El primero fue «One Step Closer». «In the End» salió el cuarto, casi un año después.",
  },

  // --- The Killers ---
  {
    id: "killers-hotfuss",
    franchise: "The Killers",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué álbum de The Killers está «Mr. Brightside»?",
    options: ["Hot Fuss", "Sam's Town", "Day & Age", "Battle Born"],
    correct: 0,
    official: "Hot Fuss",
  },
  {
    id: "killers-brandon",
    franchise: "The Killers",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el cantante de The Killers?",
    hint: "(Nombre y apellido.)",
    accepted: [["Brandon", "Brandon Flowers"], ["Flowers", "Brandon Flowers"]],
    official: "Brandon Flowers",
  },
  {
    id: "killers-vf-segundo",
    franchise: "The Killers",
    difficulty: "media",
    format: "vf",
    prompt: "«Mr. Brightside» salió en el segundo disco de The Killers.",
    correct: false,
    official: "Falso",
    note: "Está en «Hot Fuss», su disco de debut, y fue de las primeras canciones que escribieron.",
  },

  // --- Coldplay ---
  {
    id: "coldplay-vivalavida",
    franchise: "Coldplay",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué grupo es «Viva la Vida»?",
    options: ["Coldplay", "Muse", "Keane", "The Verve"],
    correct: 0,
    official: "Coldplay",
  },
  {
    id: "coldplay-anio",
    franchise: "Coldplay",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué año salió «Viva la Vida»?",
    options: ["2008", "2005", "2011", "2002"],
    correct: 0,
    official: "2008",
  },
  {
    id: "coldplay-eno",
    franchise: "Coldplay",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué productor británico, antes en Roxy Music, trabajó en «Viva la Vida»?",
    options: ["Brian Eno", "Rick Rubin", "Nigel Godrich", "Mark Ronson"],
    correct: 0,
    official: "Brian Eno",
  },
  {
    id: "coldplay-vf-titulo",
    franchise: "Coldplay",
    difficulty: "facil",
    format: "vf",
    prompt: "«Viva la Vida» da nombre también al álbum en el que salió.",
    correct: true,
    official: "Verdadero",
    note: "El disco se llama «Viva la Vida or Death and All His Friends».",
  },

  // --- Rihanna ---
  {
    id: "rihanna-umbrella-jayz",
    franchise: "Rihanna",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué rapero acompaña a Rihanna en «Umbrella»?",
    options: ["Jay-Z", "Kanye West", "Drake", "Eminem"],
    correct: 0,
    official: "Jay-Z",
  },
  {
    id: "rihanna-good-girl",
    franchise: "Rihanna",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué álbum de Rihanna está «Umbrella»?",
    options: ["Good Girl Gone Bad", "Loud", "Anti", "Rated R"],
    correct: 0,
    official: "Good Girl Gone Bad",
  },
  {
    id: "rihanna-barbados",
    franchise: "Rihanna",
    difficulty: "media",
    format: "corta",
    prompt: "¿De qué isla del Caribe es Rihanna?",
    accepted: [["Barbados"]],
    official: "Barbados",
  },

  // --- Beyoncé ---
  {
    id: "beyonce-crazy-jayz",
    franchise: "Beyoncé",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Quién colabora con Beyoncé en «Crazy in Love»?",
    options: ["Jay-Z", "Usher", "Pharrell Williams", "Nelly"],
    correct: 0,
    official: "Jay-Z",
  },
  {
    id: "beyonce-dangerously",
    franchise: "Beyoncé",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se titula el álbum en solitario de Beyoncé donde está «Crazy in Love»?",
    options: ["Dangerously in Love", "B'Day", "4", "Lemonade"],
    correct: 0,
    official: "Dangerously in Love",
  },
  {
    id: "beyonce-anio",
    franchise: "Beyoncé",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué año es «Crazy in Love»?",
    options: ["2003", "2000", "2006", "2009"],
    correct: 0,
    official: "2003",
  },

  // --- Outkast ---
  {
    id: "outkast-andre",
    franchise: "Outkast",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué integrante de Outkast escribió, produjo y canta «Hey Ya!»?",
    options: ["André 3000", "Big Boi", "Sleepy Brown", "Cee Lo Green"],
    correct: 0,
    official: "André 3000",
  },
  {
    id: "outkast-bigboi",
    franchise: "Outkast",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el otro miembro de Outkast, además de André 3000?",
    options: ["Big Boi", "Big Pun", "Big Sean", "Big Daddy Kane"],
    correct: 0,
    official: "Big Boi",
  },
  {
    id: "outkast-vf-bigboi",
    franchise: "Outkast",
    difficulty: "media",
    format: "vf",
    prompt: "«Hey Ya!» la canta Big Boi.",
    correct: false,
    official: "Falso",
    note: "La canta André 3000, que además la escribió y la produjo.",
  },

  // --- Conjuntos de los 2000 ---
  {
    id: "2000s-relacionar",
    franchise: "Los 2000 en inglés",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada canción con quien la canta.",
    pairs: [
      { left: "Toxic", right: "Britney Spears" },
      { left: "Umbrella", right: "Rihanna" },
      { left: "Hey Ya!", right: "Outkast" },
      { left: "Mr. Brightside", right: "The Killers" },
    ],
    official:
      "Toxic–Britney Spears, Umbrella–Rihanna, Hey Ya!–Outkast y Mr. Brightside–The Killers",
  },
  {
    id: "2000s-orden",
    franchise: "Los 2000 en inglés",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas canciones de la más antigua a la más reciente.",
    items: ["Oops!... I Did It Again", "Crazy in Love", "Umbrella", "Viva la Vida"],
    official:
      "Oops!... I Did It Again (2000), Crazy in Love (2003), Umbrella (2007) y Viva la Vida (2008)",
  },
  {
    id: "2000s-vf-maxmartin",
    franchise: "Los 2000 en inglés",
    difficulty: "media",
    format: "vf",
    prompt:
      "El mismo productor sueco está detrás de «Oops!... I Did It Again» de Britney Spears y del álbum «1989» de Taylor Swift.",
    correct: true,
    official: "Verdadero",
    note: "Max Martin, que lleva treinta años firmando éxitos de medio mundo.",
  },
  {
    id: "2000s-relacionar-albumes",
    franchise: "Los 2000 en inglés",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada álbum con su grupo o artista.",
    pairs: [
      { left: "Hybrid Theory", right: "Linkin Park" },
      { left: "Hot Fuss", right: "The Killers" },
      { left: "Back to Black", right: "Amy Winehouse" },
      { left: "Dangerously in Love", right: "Beyoncé" },
    ],
    official:
      "Hybrid Theory–Linkin Park, Hot Fuss–The Killers, Back to Black–Amy Winehouse y Dangerously in Love–Beyoncé",
  },
];
