import type { Question } from "../types";

/** Series de televisión, Studio Ghibli, anime y producciones de Clan y Boing. */
export const SERIES: Question[] = [
  // --- Bob Esponja ---
  {
    id: "bobesponja-patricio",
    franchise: "Bob Esponja",
    emoji: "🧽",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la estrella de mar, mejor amigo de Bob Esponja?",
    hint: "(Solo el nombre.)",
    accepted: [["Patricio", "Patricio Estrella"]],
    official: "Patricio Estrella",
  },
  {
    id: "bobesponja-restaurante",
    franchise: "Bob Esponja",
    emoji: "🧽",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el restaurante en el que trabaja Bob Esponja?",
    accepted: [["Crustáceo Cascarudo", "el Crustáceo Cascarudo", "Crustaceo Cascarudo"]],
    official: "El Crustáceo Cascarudo",
  },
  {
    id: "bobesponja-arenita",
    franchise: "Bob Esponja",
    emoji: "🧽",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Arenita Mejillas, que vive dentro de una cúpula de aire?",
    options: ["Una ardilla", "Una nutria", "Una marmota", "Un castor"],
    correct: 0,
    official: "Una ardilla",
  },
  {
    id: "bobesponja-calamardo",
    franchise: "Bob Esponja",
    emoji: "🧽",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es el vecino cascarrabias de Bob Esponja, trabaja en la caja del restaurante y toca el clarinete.",
    hint: "(Solo el nombre.)",
    accepted: [["Calamardo"]],
    official: "Calamardo",
  },

  // --- Avatar: la leyenda de Aang ---
  {
    id: "avatar-hermanos",
    franchise: "Avatar: la leyenda de Aang",
    emoji: "💨",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llaman los dos hermanos de la Tribu Agua que encuentran a Aang en el hielo?",
    options: [
      "Katara y Sokka",
      "Toph y Sokka",
      "Katara y Zuko",
      "Suki y Sokka",
    ],
    correct: 0,
    official: "Katara y Sokka",
  },
  {
    id: "avatar-appa",
    franchise: "Avatar: la leyenda de Aang",
    emoji: "💨",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es Appa, la montura voladora de Aang?",
    options: [
      "Un bisonte volador",
      "Un dragón de aire",
      "Un lémur gigante",
      "Un búfalo alado",
    ],
    correct: 0,
    official: "Un bisonte volador",
  },

  // --- Los Padrinos Mágicos ---
  {
    id: "padrinos-vicky",
    franchise: "Los Padrinos Mágicos",
    emoji: "🪄",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la niñera tirana que amarga la vida a Timmy?",
    options: ["Vicky", "Trixie", "Tootie", "Wanda"],
    correct: 0,
    official: "Vicky",
  },

  // --- Las Tortugas Ninja ---
  {
    id: "tortugas-splinter",
    franchise: "Las Tortugas Ninja",
    emoji: "🐢",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la rata que ejerce de maestro y padre de las tortugas?",
    hint: "(Solo el nombre.)",
    accepted: [["Splinter", "Maestro Splinter", "Astilla"]],
    official: "Splinter",
  },
  {
    id: "tortugas-nombres",
    franchise: "Las Tortugas Ninja",
    emoji: "🐢",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué se tomaron prestados los nombres de las cuatro tortugas?",
    options: [
      "De pintores y escultores del Renacimiento",
      "De filósofos griegos",
      "De emperadores romanos",
      "De compositores italianos",
    ],
    correct: 0,
    official: "De artistas del Renacimiento italiano",
    note: "Leonardo, Rafael, Donatello y Miguel Ángel.",
  },
  {
    id: "tortugas-destructor",
    franchise: "Las Tortugas Ninja",
    emoji: "🐢",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el enemigo acorazado que dirige el Clan del Pie?",
    options: ["Destructor", "Krang", "Bebop", "Rocksteady"],
    correct: 0,
    official: "Destructor",
    note: "En la versión original es Shredder.",
  },

  // --- Hora de aventuras ---
  {
    id: "horaaventuras-jake",
    franchise: "Hora de aventuras",
    emoji: "🗡️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el perro elástico que acompaña a Finn?",
    hint: "(Solo el nombre.)",
    accepted: [["Jake"]],
    official: "Jake",
  },
  {
    id: "horaaventuras-chicle",
    franchise: "Hora de aventuras",
    emoji: "🗡️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Quién gobierna el Dulce Reino?",
    options: [
      "La Dulce Princesa",
      "La Princesa Grumosa",
      "La Reina Helada",
      "Marceline",
    ],
    correct: 0,
    official: "La Dulce Princesa",
  },

  // --- Escandalosos ---
  {
    id: "escandalosos-hermanos",
    franchise: "Escandalosos",
    emoji: "🐻",
    difficulty: "facil",
    format: "multiple",
    prompt: "Además de Panda, ¿cómo se llaman los otros dos hermanos osos?",
    options: ["Pardo y Polar", "Grizz y Nieve", "Bruno y Blanco", "Pardo y Nube"],
    correct: 0,
    official: "Pardo y Polar",
  },

  // --- El asombroso mundo de Gumball ---
  {
    id: "gumball-darwin",
    franchise: "El asombroso mundo de Gumball",
    emoji: "🐟",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el pez de colores que se convirtió en hermano adoptivo de Gumball?",
    hint: "(Solo el nombre.)",
    accepted: [["Darwin"]],
    official: "Darwin",
  },

  // --- Las Supernenas ---
  {
    id: "supernenas-mojo",
    franchise: "Las Supernenas",
    emoji: "💥",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el mono de cerebro descomunal que es su archienemigo?",
    options: ["Mojo Jojo", "Él", "Fuzzy", "Princesa"],
    correct: 0,
    official: "Mojo Jojo",
  },
  {
    id: "supernenas-nombres",
    franchise: "Las Supernenas",
    emoji: "💥",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman las tres Supernenas en el doblaje español?",
    options: [
      "Pétalo, Burbuja y Cactus",
      "Pétalo, Burbuja y Bombón",
      "Rosa, Burbuja y Cactus",
      "Flor, Pompa y Cactus",
    ],
    correct: 0,
    official: "Pétalo, Burbuja y Cactus",
  },

  // --- Ben 10 ---
  {
    id: "ben10-abuelo",
    franchise: "Ben 10",
    emoji: "⌚",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el abuelo con el que Ben y Gwen viajan en autocaravana?",
    options: ["Max", "Kevin", "Vilgax", "Frank"],
    correct: 0,
    official: "El abuelo Max",
  },

  // --- Steven Universe ---
  {
    id: "steven-gemas",
    franchise: "Steven Universe",
    emoji: "💎",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman las tres Gemas de Cristal que crían a Steven?",
    options: [
      "Garnet, Amatista y Perla",
      "Garnet, Peridot y Perla",
      "Rubí, Zafiro y Perla",
      "Amatista, Perla y Lapislázuli",
    ],
    correct: 0,
    official: "Garnet, Amatista y Perla",
  },

  // --- Phineas y Ferb ---
  {
    id: "phineas-candace",
    franchise: "Phineas y Ferb",
    emoji: "🔺",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la hermana mayor que intenta pillar a Phineas y Ferb?",
    hint: "(Solo el nombre.)",
    accepted: [["Candace"]],
    official: "Candace",
  },
  {
    id: "phineas-ornitorrinco",
    franchise: "Phineas y Ferb",
    emoji: "🔺",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Perry, la mascota de Phineas y Ferb?",
    options: ["Un ornitorrinco", "Una nutria", "Un castor", "Un armadillo"],
    correct: 0,
    official: "Un ornitorrinco",
  },

  // --- Gravity Falls ---
  {
    id: "gravityfalls-bill",
    franchise: "Gravity Falls",
    emoji: "🔻",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el demonio triangular amarillo de un solo ojo?",
    options: ["Bill Cifra", "Ford Pines", "Gideon", "Stan"],
    correct: 0,
    official: "Bill Cifra",
  },

  // --- Kim Possible ---
  {
    id: "kimpossible-ron",
    franchise: "Kim Possible",
    emoji: "🕵️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el mejor amigo y compañero de misiones de Kim?",
    options: ["Ron Imparable", "Wade", "Drakken", "Josh"],
    correct: 0,
    official: "Ron Imparable",
  },

  // --- Scooby-Doo ---
  {
    id: "scooby-furgoneta",
    franchise: "Scooby-Doo",
    emoji: "🐶",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la furgoneta en la que viaja la pandilla?",
    accepted: [["Máquina del Misterio", "la Máquina del Misterio", "Maquina del Misterio"]],
    official: "La Máquina del Misterio",
  },
  {
    id: "scooby-vilma",
    franchise: "Scooby-Doo",
    emoji: "🐶",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es la más lista de la pandilla, lleva jersey naranja y se le caen las gafas continuamente.",
    hint: "(Solo el nombre.)",
    accepted: [["Vilma"]],
    official: "Vilma",
  },

  // --- Los Picapiedra ---
  {
    id: "picapiedra-pablo",
    franchise: "Los Picapiedra",
    emoji: "🦕",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el vecino y mejor amigo de Pedro Picapiedra?",
    accepted: [["Pablo Mármol", "Pablo"]],
    official: "Pablo Mármol",
  },

  // --- Looney Tunes ---
  {
    id: "looney-coyote",
    franchise: "Looney Tunes",
    emoji: "🥕",
    difficulty: "facil",
    format: "corta",
    prompt: "¿A quién persigue sin descanso el Coyote?",
    hint: "(El personaje.)",
    accepted: [["Correcaminos", "el Correcaminos"]],
    official: "Al Correcaminos",
  },
  {
    id: "looney-lucas",
    franchise: "Looney Tunes",
    emoji: "🥕",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el pato negro, eterno rival de Bugs Bunny?",
    options: ["El Pato Lucas", "El Pato Donald", "Piolín", "Silvestre"],
    correct: 0,
    official: "El Pato Lucas",
  },

  // --- Los Simpson ---
  {
    id: "simpson-springfield",
    franchise: "Los Simpson",
    emoji: "🍩",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la ciudad donde viven los Simpson?",
    hint: "(Solo el nombre.)",
    accepted: [["Springfield"]],
    official: "Springfield",
  },
  {
    id: "simpson-burns",
    franchise: "Los Simpson",
    emoji: "🍩",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el dueño de la central nuclear donde trabaja Homer?",
    options: ["El señor Burns", "Waylon Smithers", "Moe Szyslak", "Apu"],
    correct: 0,
    official: "El señor Burns",
  },
  {
    id: "simpson-krusty",
    franchise: "Los Simpson",
    emoji: "🍩",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el payaso de la televisión que idolatra Bart?",
    hint: "(Solo el nombre.)",
    accepted: [["Krusty", "Krusty el payaso"]],
    official: "Krusty el payaso",
  },

  // --- Futurama ---
  {
    id: "futurama-bender",
    franchise: "Futurama",
    emoji: "🚀",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el robot bebedor y ladrón de la tripulación de Planet Express?",
    options: ["Bender", "Zoidberg", "Fry", "Nibbler"],
    correct: 0,
    official: "Bender",
  },

  // --- Studio Ghibli ---
  {
    id: "chihiro-sincara",
    franchise: "El viaje de Chihiro",
    emoji: "🏮",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el espíritu enmascarado y silencioso que devora todo en la casa de baños?",
    options: ["Sin Cara", "Haku", "Bôh", "Kamaji"],
    correct: 0,
    official: "Sin Cara",
  },
  {
    id: "chihiro-haku",
    franchise: "El viaje de Chihiro",
    emoji: "🏮",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el chico que ayuda a Chihiro y que puede transformarse en dragón?",
    hint: "(Solo el nombre.)",
    accepted: [["Haku"]],
    official: "Haku",
  },
  {
    id: "totoro-gatobus",
    franchise: "Mi vecino Totoro",
    emoji: "🌰",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el autobús con forma de gato de doce patas?",
    accepted: [["Gatobús", "Gatobus", "el Gatobús"]],
    official: "El Gatobús",
  },
  {
    id: "totoro-hermanas",
    franchise: "Mi vecino Totoro",
    emoji: "🌰",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman las dos hermanas protagonistas?",
    options: ["Satsuki y Mei", "Satsuki y Kiki", "Mei y Ponyo", "Sumi y Mei"],
    correct: 0,
    official: "Satsuki y Mei",
  },
  {
    id: "mononoke-ashitaka",
    franchise: "La princesa Mononoke",
    emoji: "🐺",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el joven guerrero maldito que llega al bosque?",
    options: ["Ashitaka", "Jiro", "Kenji", "Haku"],
    correct: 0,
    official: "Ashitaka",
  },
  {
    id: "howl-sophie",
    franchise: "El castillo ambulante",
    emoji: "🏚️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la joven sombrerera a la que una bruja convierte en anciana?",
    options: ["Sophie", "Suliman", "Lettie", "Marie"],
    correct: 0,
    official: "Sophie",
  },
  {
    id: "nicky-jiji",
    franchise: "Nicky, la aprendiz de bruja",
    emoji: "🧹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el gato negro que acompaña a Nicky?",
    hint: "(Solo el nombre.)",
    accepted: [["Jiji"]],
    official: "Jiji",
  },
  {
    id: "ponyo-pez",
    franchise: "Ponyo",
    emoji: "🐡",
    difficulty: "facil",
    format: "vf",
    prompt: "Ponyo es una niña humana que desea convertirse en pez.",
    correct: false,
    official: "Falso: es un pez que quiere convertirse en humana",
  },

  // --- Dragon Ball ---
  {
    id: "dragonball-siete",
    franchise: "Dragon Ball",
    emoji: "🐉",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuántas bolas de dragón hay que reunir para invocar a Shenron?",
    hint: "(Un número.)",
    accepted: [["siete", "7"]],
    official: "Siete",
  },
  {
    id: "dragonball-vegeta",
    franchise: "Dragon Ball",
    emoji: "🐉",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el príncipe de los saiyans, eterno rival de Goku?",
    hint: "(Solo el nombre.)",
    accepted: [["Vegeta"]],
    official: "Vegeta",
  },
  {
    id: "dragonball-roshi",
    franchise: "Dragon Ball",
    emoji: "🐉",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el anciano maestro de artes marciales que vive en una isla?",
    options: ["Mutenroshi", "Karin", "Kamisama", "Yajirobe"],
    correct: 0,
    official: "Mutenroshi, el Maestro Tortuga",
  },

  // --- Pokémon ---
  {
    id: "pokemon-jessiejames",
    franchise: "Pokémon",
    emoji: "⚡",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llaman los dos humanos del Team Rocket que persiguen a Pikachu?",
    options: [
      "Jessie y James",
      "Jessie y Meowth",
      "Cassidy y Butch",
      "Mia y James",
    ],
    correct: 0,
    official: "Jessie y James",
  },
  {
    id: "pokemon-paleta",
    franchise: "Pokémon",
    emoji: "⚡",
    difficulty: "facil",
    format: "corta",
    prompt: "¿En qué pueblo empieza Ash su viaje?",
    accepted: [["Pueblo Paleta", "Paleta"]],
    official: "Pueblo Paleta",
  },

  // --- Naruto ---
  {
    id: "naruto-konoha",
    franchise: "Naruto",
    emoji: "🍥",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la aldea en la que vive Naruto?",
    accepted: [["Konoha", "Aldea Oculta de la Hoja", "la Hoja"]],
    official: "Konoha, la Aldea Oculta de la Hoja",
  },
  {
    id: "naruto-kurama",
    franchise: "Naruto",
    emoji: "🍥",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué criatura está sellada dentro de Naruto?",
    options: [
      "Un zorro de nueve colas",
      "Un lobo de siete colas",
      "Un dragón de fuego",
      "Un tejón de una cola",
    ],
    correct: 0,
    official: "Un zorro de nueve colas",
    note: "Se llama Kurama.",
  },

  // --- One Piece ---
  {
    id: "onepiece-luffy",
    franchise: "One Piece",
    emoji: "🏴‍☠️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el capitán de la banda de los Sombrero de Paja?",
    accepted: [["Luffy", "Monkey D. Luffy"]],
    official: "Monkey D. Luffy",
  },
  {
    id: "onepiece-zoro",
    franchise: "One Piece",
    emoji: "🏴‍☠️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el espadachín que pelea con tres katanas a la vez?",
    options: ["Zoro", "Sanji", "Usopp", "Shanks"],
    correct: 0,
    official: "Zoro",
  },

  // --- Doraemon ---
  {
    id: "doraemon-bolsillo",
    franchise: "Doraemon",
    emoji: "🔔",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De dónde saca Doraemon todos sus inventos del futuro?",
    hint: "(Una respuesta breve.)",
    accepted: [["bolsillo", "del bolsillo", "bolsillo mágico", "bolsillo de cuatro dimensiones"]],
    official: "De su bolsillo mágico",
  },
  {
    id: "doraemon-nobita",
    franchise: "Doraemon",
    emoji: "🔔",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el niño al que acompaña Doraemon?",
    options: ["Nobita", "Gigante", "Suneo", "Shizuka"],
    correct: 0,
    official: "Nobita",
  },

  // --- Shin Chan ---
  {
    id: "shinchan-nevado",
    franchise: "Shin Chan",
    emoji: "✏️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el perro blanco de la familia Nohara?",
    hint: "(Solo el nombre.)",
    accepted: [["Nevado"]],
    official: "Nevado",
  },
  {
    id: "shinchan-himawari",
    franchise: "Shin Chan",
    emoji: "✏️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la hermana pequeña de Shin Chan?",
    options: ["Himawari", "Misae", "Nene", "Ai"],
    correct: 0,
    official: "Himawari",
  },

  // --- Detective Conan ---
  {
    id: "conan-shinichi",
    franchise: "Detective Conan",
    emoji: "🔍",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuál es la verdadera identidad de Conan Edogawa?",
    options: ["Shinichi Kudo", "Heiji Hattori", "Kaito Kid", "Kogoro Mouri"],
    correct: 0,
    official: "Shinichi Kudo",
  },

  // --- Sailor Moon ---
  {
    id: "sailormoon-luna",
    franchise: "Sailor Moon",
    emoji: "🌙",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la gata negra que guía a la protagonista?",
    options: ["Luna", "Artemis", "Diana", "Selene"],
    correct: 0,
    official: "Luna",
  },

  // --- Mortadelo y Filemón ---
  {
    id: "mortadelo-tia",
    franchise: "Mortadelo y Filemón",
    emoji: "🕵️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la organización de espionaje para la que trabajan?",
    hint: "(Las siglas.)",
    accepted: [["TIA", "T.I.A.", "la TIA"]],
    official: "La T.I.A.",
  },

  // --- Pocoyó ---
  {
    id: "pocoyo-color",
    franchise: "Pocoyó",
    emoji: "🔵",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De qué color es la ropa de Pocoyó?",
    hint: "(Un color.)",
    accepted: [["azul"]],
    official: "Azul",
  },

  // --- Peppa Pig ---
  {
    id: "peppa-george",
    franchise: "Peppa Pig",
    emoji: "🐷",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el hermano pequeño de Peppa?",
    hint: "(Solo el nombre.)",
    accepted: [["George"]],
    official: "George",
  },

  // --- David el Gnomo ---
  {
    id: "davidgnomo-zorro",
    franchise: "David el Gnomo",
    emoji: "🍄",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué animal usa David el Gnomo como montura para desplazarse?",
    options: ["Un zorro", "Un ciervo", "Un lobo", "Un jabalí"],
    correct: 0,
    official: "Un zorro",
  },

  // --- Las Tres Mellizas ---
  {
    id: "tresmellizas-bruja",
    franchise: "Las Tres Mellizas",
    emoji: "👧",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la bruja que castiga a las mellizas metiéndolas en cuentos?",
    options: [
      "La Bruja Aburrida",
      "La Bruja Piruja",
      "La Bruja Avería",
      "La Bruja Gruñona",
    ],
    correct: 0,
    official: "La Bruja Aburrida",
  },

  // --- Orden y relacionar (transversales) ---
  {
    id: "orden-ghibli",
    franchise: "Studio Ghibli",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Studio Ghibli de la más antigua a la más reciente.",
    items: [
      "Mi vecino Totoro",
      "La princesa Mononoke",
      "El viaje de Chihiro",
      "Ponyo",
    ],
    official:
      "Mi vecino Totoro (1988), La princesa Mononoke (1997), El viaje de Chihiro (2001) y Ponyo (2008)",
  },
  {
    id: "relacionar-ciudades",
    franchise: "Lugares de ficción",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada lugar con la obra a la que pertenece.",
    pairs: [
      { left: "Springfield", right: "Los Simpson" },
      { left: "Fondo de Bikini", right: "Bob Esponja" },
      { left: "Radiador Springs", right: "Cars" },
      { left: "Arendelle", right: "Frozen" },
    ],
    official:
      "Springfield–Los Simpson, Fondo de Bikini–Bob Esponja, Radiador Springs–Cars y Arendelle–Frozen",
  },
  {
    id: "relacionar-mascotas-series",
    franchise: "Mascotas de series",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada animal con su dueño o compañero.",
    pairs: [
      { left: "Jiji", right: "Nicky" },
      { left: "Nevado", right: "Shin Chan" },
      { left: "Max", right: "el Grinch" },
      { left: "Jake", right: "Finn" },
    ],
    official: "Jiji–Nicky, Nevado–Shin Chan, Max–el Grinch y Jake–Finn",
  },
  {
    id: "describir-doraemon",
    franchise: "Anime clásico",
    emoji: "🔎",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es un gato robot azul sin orejas, viene del siglo XXII y saca inventos de un bolsillo en la barriga.",
    hint: "(Solo el nombre.)",
    accepted: [["Doraemon"]],
    official: "Doraemon",
  },
  {
    id: "describir-walle",
    franchise: "Robots de la animación",
    emoji: "🔎",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Robot amarillo con forma de cubo, compacta basura en una Tierra abandonada y colecciona cachivaches.",
    hint: "(Solo el nombre.)",
    accepted: [["WALL-E", "WALL·E", "WALLE", "Wall E"]],
    official: "WALL·E",
  },
];
