import type { Question } from "../types";

/** Series de televisión, Studio Ghibli, anime y producciones de Clan y Boing. */
export const SERIES: Question[] = [
  // --- Bob Esponja ---
  {
    id: "bobesponja-patricio",
    franchise: "Bob Esponja",
    emoji: "🧽",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la estrella de mar, mejor amigo de Bob Esponja?",
    hint: "(Solo el nombre.)",
    accepted: [["Patricio", "Patricio Estrella"]],
    official: "Patricio Estrella",
  },
  {
    id: "bobesponja-restaurante",
    franchise: "Bob Esponja",
    emoji: "🧽",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el restaurante en el que trabaja Bob Esponja?",
    accepted: [["Crustáceo Cascarudo", "el Crustáceo Cascarudo", "Crustaceo Cascarudo"]],
    official: "El Crustáceo Cascarudo",
  },
  {
    id: "bobesponja-arenita",
    franchise: "Bob Esponja",
    emoji: "🧽",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Arenita Mejillas, que vive dentro de una cúpula de aire?",
    options: ["Una ardilla", "Una nutria", "Una marmota", "Un castor"],
    correct: 0,
    official: "Una ardilla",
  },
  {
    id: "bobesponja-calamardo",
    franchise: "Bob Esponja",
    emoji: "🧽",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es el vecino cascarrabias de Bob Esponja, trabaja en la caja del restaurante y toca el clarinete.",
    hint: "(Solo el nombre.)",
    accepted: [["Calamardo"]],
    official: "Calamardo",
  },

  // --- Avatar: la leyenda de Aang ---
  {
    id: "avatar-hermanos",
    franchise: "Avatar: la leyenda de Aang",
    emoji: "💨",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llaman los dos hermanos de la Tribu Agua que encuentran a Aang en el hielo?",
    options: [
      "Katara y Sokka",
      "Toph y Sokka",
      "Katara y Zuko",
      "Suki y Sokka",
    ],
    correct: 0,
    official: "Katara y Sokka",
  },
  {
    id: "avatar-appa",
    franchise: "Avatar: la leyenda de Aang",
    emoji: "💨",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es Appa, la montura voladora de Aang?",
    options: [
      "Un bisonte volador",
      "Un dragón de aire",
      "Un lémur gigante",
      "Un búfalo alado",
    ],
    correct: 0,
    official: "Un bisonte volador",
  },

  // --- Los Padrinos Mágicos ---
  {
    id: "padrinos-vicky",
    franchise: "Los Padrinos Mágicos",
    emoji: "🪄",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la niñera tirana que amarga la vida a Timmy?",
    options: ["Vicky", "Trixie", "Tootie", "Wanda"],
    correct: 0,
    official: "Vicky",
  },

  // --- Las Tortugas Ninja ---
  {
    id: "tortugas-splinter",
    franchise: "Las Tortugas Ninja",
    emoji: "🐢",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la rata que ejerce de maestro y padre de las tortugas?",
    hint: "(Solo el nombre.)",
    accepted: [["Splinter", "Maestro Splinter", "Astilla"]],
    official: "Splinter",
  },
  {
    id: "tortugas-nombres",
    franchise: "Las Tortugas Ninja",
    emoji: "🐢",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué se tomaron prestados los nombres de las cuatro tortugas?",
    options: [
      "De pintores y escultores del Renacimiento",
      "De filósofos griegos",
      "De emperadores romanos",
      "De compositores italianos",
    ],
    correct: 0,
    official: "De artistas del Renacimiento italiano",
    note: "Leonardo, Rafael, Donatello y Miguel Ángel.",
  },
  {
    id: "tortugas-destructor",
    franchise: "Las Tortugas Ninja",
    emoji: "🐢",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el enemigo acorazado que dirige el Clan del Pie?",
    options: ["Destructor", "Krang", "Bebop", "Rocksteady"],
    correct: 0,
    official: "Destructor",
    note: "En la versión original es Shredder.",
  },

  // --- Hora de aventuras ---
  {
    id: "horaaventuras-jake",
    franchise: "Hora de aventuras",
    emoji: "🗡️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el perro elástico que acompaña a Finn?",
    hint: "(Solo el nombre.)",
    accepted: [["Jake"]],
    official: "Jake",
  },
  {
    id: "horaaventuras-chicle",
    franchise: "Hora de aventuras",
    emoji: "🗡️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Quién gobierna el Dulce Reino?",
    options: [
      "La Dulce Princesa",
      "La Princesa Grumosa",
      "La Reina Helada",
      "Marceline",
    ],
    correct: 0,
    official: "La Dulce Princesa",
  },

  // --- Somos osos ---
  {
    id: "escandalosos-hermanos",
    franchise: "Somos osos",
    emoji: "🐻",
    difficulty: "facil",
    format: "multiple",
    prompt: "Además de Panda, ¿cómo se llaman los otros dos hermanos osos?",
    options: ["Pardo y Polar", "Grizz y Nieve", "Bruno y Blanco", "Pardo y Nube"],
    correct: 0,
    official: "Pardo y Polar",
  },

  // --- El asombroso mundo de Gumball ---
  {
    id: "gumball-darwin",
    franchise: "El asombroso mundo de Gumball",
    emoji: "🐟",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el pez de colores que se convirtió en hermano adoptivo de Gumball?",
    hint: "(Solo el nombre.)",
    accepted: [["Darwin"]],
    official: "Darwin",
  },

  // --- Las Supernenas ---
  {
    id: "supernenas-mojo",
    franchise: "Las Supernenas",
    emoji: "💥",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el mono de cerebro descomunal que es su archienemigo?",
    options: ["Mojo Jojo", "Él", "Fuzzy", "Princesa"],
    correct: 0,
    official: "Mojo Jojo",
  },
  {
    id: "supernenas-nombres",
    franchise: "Las Supernenas",
    emoji: "💥",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman las tres Supernenas en el doblaje español?",
    options: [
      "Pétalo, Burbuja y Cactus",
      "Pétalo, Burbuja y Bombón",
      "Rosa, Burbuja y Cactus",
      "Flor, Pompa y Cactus",
    ],
    correct: 0,
    official: "Pétalo, Burbuja y Cactus",
  },

  // --- Ben 10 ---
  {
    id: "ben10-abuelo",
    franchise: "Ben 10",
    emoji: "⌚",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el abuelo con el que Ben y Gwen viajan en autocaravana?",
    options: ["Max", "Kevin", "Vilgax", "Frank"],
    correct: 0,
    official: "El abuelo Max",
  },

  // --- Steven Universe ---
  {
    id: "steven-gemas",
    franchise: "Steven Universe",
    emoji: "💎",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman las tres Gemas de Cristal que crían a Steven?",
    options: [
      "Garnet, Amatista y Perla",
      "Garnet, Peridot y Perla",
      "Rubí, Zafiro y Perla",
      "Amatista, Perla y Lapislázuli",
    ],
    correct: 0,
    official: "Garnet, Amatista y Perla",
  },

  // --- Phineas y Ferb ---
  {
    id: "phineas-candace",
    franchise: "Phineas y Ferb",
    emoji: "🔺",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la hermana mayor que intenta pillar a Phineas y Ferb?",
    hint: "(Solo el nombre.)",
    accepted: [["Candace"]],
    official: "Candace",
  },
  {
    id: "phineas-ornitorrinco",
    franchise: "Phineas y Ferb",
    emoji: "🔺",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Perry, la mascota de Phineas y Ferb?",
    options: ["Un ornitorrinco", "Una nutria", "Un castor", "Un armadillo"],
    correct: 0,
    official: "Un ornitorrinco",
  },

  // --- Gravity Falls ---
  {
    id: "gravityfalls-bill",
    franchise: "Gravity Falls",
    emoji: "🔻",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el demonio triangular amarillo de un solo ojo?",
    options: ["Bill Cifra", "Ford Pines", "Gideon", "Stan"],
    correct: 0,
    official: "Bill Cifra",
  },

  // --- Kim Possible ---
  {
    id: "kimpossible-ron",
    franchise: "Kim Possible",
    emoji: "🕵️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el mejor amigo y compañero de misiones de Kim?",
    options: ["Ron Imparable", "Wade", "Drakken", "Josh"],
    correct: 0,
    official: "Ron Imparable",
  },

  // --- Scooby-Doo ---
  {
    id: "scooby-furgoneta",
    franchise: "Scooby-Doo",
    emoji: "🐶",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la furgoneta en la que viaja la pandilla?",
    accepted: [["Máquina del Misterio", "la Máquina del Misterio", "Maquina del Misterio"]],
    official: "La Máquina del Misterio",
  },
  {
    id: "scooby-vilma",
    franchise: "Scooby-Doo",
    emoji: "🐶",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es la más lista de la pandilla, lleva jersey naranja y se le caen las gafas continuamente.",
    hint: "(Solo el nombre.)",
    accepted: [["Vilma"]],
    official: "Vilma",
  },

  // --- Los Picapiedra ---
  {
    id: "picapiedra-pablo",
    franchise: "Los Picapiedra",
    emoji: "🦕",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el vecino y mejor amigo de Pedro Picapiedra?",
    accepted: [["Pablo Mármol", "Pablo"]],
    official: "Pablo Mármol",
  },

  // --- Looney Tunes ---
  {
    id: "looney-coyote",
    franchise: "Looney Tunes",
    emoji: "🥕",
    difficulty: "facil",
    format: "corta",
    prompt: "¿A quién persigue sin descanso el Coyote?",
    hint: "(El personaje.)",
    accepted: [["Correcaminos", "el Correcaminos"]],
    official: "Al Correcaminos",
  },
  {
    id: "looney-lucas",
    franchise: "Looney Tunes",
    emoji: "🥕",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el pato negro, eterno rival de Bugs Bunny?",
    options: ["El Pato Lucas", "El Pato Donald", "Piolín", "Silvestre"],
    correct: 0,
    official: "El Pato Lucas",
  },

  // --- Los Simpson ---
  {
    id: "simpson-springfield",
    franchise: "Los Simpson",
    emoji: "🍩",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la ciudad donde viven los Simpson?",
    hint: "(Solo el nombre.)",
    accepted: [["Springfield"]],
    official: "Springfield",
  },
  {
    id: "simpson-burns",
    franchise: "Los Simpson",
    emoji: "🍩",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el dueño de la central nuclear donde trabaja Homer?",
    options: ["El señor Burns", "Waylon Smithers", "Moe Szyslak", "Apu"],
    correct: 0,
    official: "El señor Burns",
  },
  {
    id: "simpson-krusty",
    franchise: "Los Simpson",
    emoji: "🍩",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el payaso de la televisión que idolatra Bart?",
    hint: "(Solo el nombre.)",
    accepted: [["Krusty", "Krusty el payaso"]],
    official: "Krusty el payaso",
  },

  // --- Futurama ---
  {
    id: "futurama-bender",
    franchise: "Futurama",
    emoji: "🚀",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el robot bebedor y ladrón de la tripulación de Planet Express?",
    options: ["Bender", "Zoidberg", "Fry", "Nibbler"],
    correct: 0,
    official: "Bender",
  },

  // --- Studio Ghibli ---
  {
    id: "chihiro-sincara",
    franchise: "El viaje de Chihiro",
    emoji: "🏮",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el espíritu enmascarado y silencioso que devora todo en la casa de baños?",
    options: ["Sin Cara", "Haku", "Bôh", "Kamaji"],
    correct: 0,
    official: "Sin Cara",
  },
  {
    id: "chihiro-haku",
    franchise: "El viaje de Chihiro",
    emoji: "🏮",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el chico que ayuda a Chihiro y que puede transformarse en dragón?",
    hint: "(Solo el nombre.)",
    accepted: [["Haku"]],
    official: "Haku",
  },
  {
    id: "totoro-gatobus",
    franchise: "Mi vecino Totoro",
    emoji: "🌰",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el autobús con forma de gato de doce patas?",
    accepted: [["Gatobús", "Gatobus", "el Gatobús"]],
    official: "El Gatobús",
  },
  {
    id: "totoro-hermanas",
    franchise: "Mi vecino Totoro",
    emoji: "🌰",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman las dos hermanas protagonistas?",
    options: ["Satsuki y Mei", "Satsuki y Kiki", "Mei y Ponyo", "Sumi y Mei"],
    correct: 0,
    official: "Satsuki y Mei",
  },
  {
    id: "mononoke-ashitaka",
    franchise: "La princesa Mononoke",
    emoji: "🐺",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el joven guerrero maldito que llega al bosque?",
    options: ["Ashitaka", "Jiro", "Kenji", "Haku"],
    correct: 0,
    official: "Ashitaka",
  },
  {
    id: "howl-sophie",
    franchise: "El castillo ambulante",
    emoji: "🏚️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la joven sombrerera a la que una bruja convierte en anciana?",
    options: ["Sophie", "Suliman", "Lettie", "Marie"],
    correct: 0,
    official: "Sophie",
  },
  {
    id: "nicky-jiji",
    franchise: "Nicky, la aprendiz de bruja",
    emoji: "🧹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el gato negro que acompaña a Nicky?",
    hint: "(Solo el nombre.)",
    accepted: [["Jiji"]],
    official: "Jiji",
  },
  {
    id: "ponyo-pez",
    franchise: "Ponyo",
    emoji: "🐡",
    difficulty: "facil",
    format: "vf",
    prompt: "Ponyo es una niña humana que desea convertirse en pez.",
    correct: false,
    official: "Falso: es un pez que quiere convertirse en humana",
  },

  // --- Dragon Ball ---
  {
    id: "dragonball-siete",
    franchise: "Dragon Ball",
    emoji: "🐉",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuántas bolas de dragón hay que reunir para invocar a Shenron?",
    hint: "(Un número.)",
    accepted: [["siete", "7"]],
    official: "Siete",
  },
  {
    id: "dragonball-vegeta",
    franchise: "Dragon Ball",
    emoji: "🐉",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el príncipe de los saiyans, eterno rival de Goku?",
    hint: "(Solo el nombre.)",
    accepted: [["Vegeta"]],
    official: "Vegeta",
  },
  {
    id: "dragonball-roshi",
    franchise: "Dragon Ball",
    emoji: "🐉",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el anciano maestro de artes marciales que vive en una isla?",
    options: ["Mutenroshi", "Karin", "Kamisama", "Yajirobe"],
    correct: 0,
    official: "Mutenroshi, el Maestro Tortuga",
  },

  // --- Pokémon ---
  {
    id: "pokemon-jessiejames",
    franchise: "Pokémon",
    emoji: "⚡",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llaman los dos humanos del Team Rocket que persiguen a Pikachu?",
    options: [
      "Jessie y James",
      "Jessie y Meowth",
      "Cassidy y Butch",
      "Mia y James",
    ],
    correct: 0,
    official: "Jessie y James",
  },
  {
    id: "pokemon-paleta",
    franchise: "Pokémon",
    emoji: "⚡",
    difficulty: "facil",
    format: "corta",
    prompt: "¿En qué pueblo empieza Ash su viaje?",
    accepted: [["Pueblo Paleta", "Paleta"]],
    official: "Pueblo Paleta",
  },

  // --- Naruto ---
  {
    id: "naruto-konoha",
    franchise: "Naruto",
    emoji: "🍥",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la aldea en la que vive Naruto?",
    accepted: [["Konoha", "Aldea Oculta de la Hoja", "la Hoja"]],
    official: "Konoha, la Aldea Oculta de la Hoja",
  },
  {
    id: "naruto-kurama",
    franchise: "Naruto",
    emoji: "🍥",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué criatura está sellada dentro de Naruto?",
    options: [
      "Un zorro de nueve colas",
      "Un lobo de siete colas",
      "Un dragón de fuego",
      "Un tejón de una cola",
    ],
    correct: 0,
    official: "Un zorro de nueve colas",
    note: "Se llama Kurama.",
  },

  // --- One Piece ---
  {
    id: "onepiece-luffy",
    franchise: "One Piece",
    emoji: "🏴‍☠️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el capitán de la banda de los Sombrero de Paja?",
    accepted: [["Luffy", "Monkey D. Luffy"]],
    official: "Monkey D. Luffy",
  },
  {
    id: "onepiece-zoro",
    franchise: "One Piece",
    emoji: "🏴‍☠️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el espadachín que pelea con tres katanas a la vez?",
    options: ["Zoro", "Sanji", "Usopp", "Shanks"],
    correct: 0,
    official: "Zoro",
  },

  // --- Doraemon ---
  {
    id: "doraemon-bolsillo",
    franchise: "Doraemon",
    emoji: "🔔",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De dónde saca Doraemon todos sus inventos del futuro?",
    hint: "(Una respuesta breve.)",
    accepted: [["bolsillo", "del bolsillo", "bolsillo mágico", "bolsillo de cuatro dimensiones"]],
    official: "De su bolsillo mágico",
  },
  {
    id: "doraemon-nobita",
    franchise: "Doraemon",
    emoji: "🔔",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el niño al que acompaña Doraemon?",
    options: ["Nobita", "Gigante", "Suneo", "Shizuka"],
    correct: 0,
    official: "Nobita",
  },

  // --- Shin Chan ---
  {
    id: "shinchan-nevado",
    franchise: "Shin Chan",
    emoji: "✏️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el perro blanco de la familia Nohara?",
    hint: "(Solo el nombre.)",
    accepted: [["Nevado"]],
    official: "Nevado",
  },
  {
    id: "shinchan-himawari",
    franchise: "Shin Chan",
    emoji: "✏️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la hermana pequeña de Shin Chan?",
    options: ["Himawari", "Misae", "Nene", "Ai"],
    correct: 0,
    official: "Himawari",
  },

  // --- Detective Conan ---
  {
    id: "conan-shinichi",
    franchise: "Detective Conan",
    emoji: "🔍",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuál es la verdadera identidad de Conan Edogawa?",
    options: ["Shinichi Kudo", "Heiji Hattori", "Kaito Kid", "Kogoro Mouri"],
    correct: 0,
    official: "Shinichi Kudo",
  },

  // --- Sailor Moon ---
  {
    id: "sailormoon-luna",
    franchise: "Sailor Moon",
    emoji: "🌙",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la gata negra que guía a la protagonista?",
    options: ["Luna", "Artemis", "Diana", "Selene"],
    correct: 0,
    official: "Luna",
  },

  // --- Mortadelo y Filemón ---
  {
    id: "mortadelo-tia",
    franchise: "Mortadelo y Filemón",
    emoji: "🕵️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la organización de espionaje para la que trabajan?",
    hint: "(Las siglas.)",
    accepted: [["TIA", "T.I.A.", "la TIA"]],
    official: "La T.I.A.",
  },

  // --- Pocoyó ---
  {
    id: "pocoyo-color",
    franchise: "Pocoyó",
    emoji: "🦆",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De qué color es la ropa de Pocoyó?",
    hint: "(Un color.)",
    accepted: [["azul"]],
    official: "Azul",
  },

  // --- Peppa Pig ---
  {
    id: "peppa-george",
    franchise: "Peppa Pig",
    emoji: "🐷",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el hermano pequeño de Peppa?",
    hint: "(Solo el nombre.)",
    accepted: [["George"]],
    official: "George",
  },

  // --- David el Gnomo ---
  {
    id: "davidgnomo-zorro",
    franchise: "David el Gnomo",
    emoji: "🍄",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué animal usa David el Gnomo como montura para desplazarse?",
    options: ["Un zorro", "Un ciervo", "Un lobo", "Un jabalí"],
    correct: 0,
    official: "Un zorro",
  },

  // --- Las Tres Mellizas ---
  {
    id: "tresmellizas-bruja",
    franchise: "Las Tres Mellizas",
    emoji: "👧",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama la bruja que castiga a las mellizas metiéndolas en cuentos?",
    options: [
      "La Bruja Aburrida",
      "La Bruja Piruja",
      "La Bruja Avería",
      "La Bruja Gruñona",
    ],
    correct: 0,
    official: "La Bruja Aburrida",
  },

  // --- Orden y relacionar (transversales) ---
  {
    id: "orden-ghibli",
    franchise: "Studio Ghibli",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Studio Ghibli de la más antigua a la más reciente.",
    items: [
      "Mi vecino Totoro",
      "La princesa Mononoke",
      "El viaje de Chihiro",
      "Ponyo",
    ],
    official:
      "Mi vecino Totoro (1988), La princesa Mononoke (1997), El viaje de Chihiro (2001) y Ponyo (2008)",
  },
  {
    id: "relacionar-ciudades",
    franchise: "Lugares de ficción",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada lugar con la obra a la que pertenece.",
    pairs: [
      { left: "Springfield", right: "Los Simpson" },
      { left: "Fondo de Bikini", right: "Bob Esponja" },
      { left: "Radiador Springs", right: "Cars" },
      { left: "Arendelle", right: "Frozen" },
    ],
    official:
      "Springfield–Los Simpson, Fondo de Bikini–Bob Esponja, Radiador Springs–Cars y Arendelle–Frozen",
  },
  {
    id: "relacionar-mascotas-series",
    franchise: "Mascotas de series",
    emoji: "🔗",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada animal con su dueño o compañero.",
    pairs: [
      { left: "Jiji", right: "Nicky" },
      { left: "Nevado", right: "Shin Chan" },
      { left: "Max", right: "el Grinch" },
      { left: "Jake", right: "Finn" },
    ],
    official: "Jiji–Nicky, Nevado–Shin Chan, Max–el Grinch y Jake–Finn",
  },
  {
    id: "describir-doraemon",
    franchise: "Anime clásico",
    emoji: "🔎",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Es un gato robot azul sin orejas, viene del siglo XXII y saca inventos de un bolsillo en la barriga.",
    hint: "(Solo el nombre.)",
    accepted: [["Doraemon"]],
    official: "Doraemon",
  },
  {
    id: "describir-walle",
    franchise: "Robots de la animación",
    emoji: "🔎",
    difficulty: "facil",
    format: "describir",
    prompt:
      "Robot amarillo con forma de cubo, compacta basura en una Tierra abandonada y colecciona cachivaches.",
    hint: "(Solo el nombre.)",
    accepted: [["WALL-E", "WALL·E", "WALLE", "Wall E"]],
    official: "WALL·E",
  },

  // --- Heidi ---
  {
    id: "heidi-clara",
    franchise: "Heidi",
    emoji: "🏔️",
    difficulty: "facil",
    format: "describir",
    prompt: "Niña de ciudad que va en silla de ruedas y se hace amiga de Heidi en Fráncfort.",
    hint: "(Solo el nombre.)",
    accepted: [["Clara"]],
    official: "Clara",
  },
  {
    id: "heidi-pedro",
    franchise: "Heidi",
    emoji: "🏔️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿A qué se dedica Pedro, el amigo de Heidi?",
    options: ["Es pastor de cabras", "Es panadero", "Es leñador", "Es cartero"],
    correct: 0,
    official: "Es pastor de cabras",
  },

  // --- Marco ---
  {
    id: "marco-madre",
    franchise: "Marco",
    emoji: "🐒",
    difficulty: "facil",
    format: "corta",
    prompt: "¿A quién busca Marco cruzando medio mundo?",
    hint: "(Un familiar.)",
    accepted: [["su madre", "madre", "a su madre"]],
    official: "A su madre",
  },

  // --- La abeja Maya ---
  {
    id: "abejamaya-willy",
    franchise: "La abeja Maya",
    emoji: "🐝",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la abeja gordita y dormilona, mejor amigo de Maya?",
    hint: "(Solo el nombre.)",
    accepted: [["Willy"]],
    official: "Willy",
  },

  // --- La vuelta al mundo de Willy Fog ---
  {
    id: "willyfog-dias",
    franchise: "Willy Fog",
    emoji: "🎩",
    difficulty: "facil",
    format: "corta",
    prompt: "¿En cuántos días apuesta Willy Fog que dará la vuelta al mundo?",
    hint: "(Un número.)",
    accepted: [["80", "ochenta"]],
    official: "En 80 días",
  },

  // --- D'Artacan y los tres mosqueperros ---
  {
    id: "dartacan-pom",
    franchise: "D'Artacan",
    emoji: "⚔️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el ratón que acompaña a D'Artacan?",
    options: ["Pom", "Tom", "Pim", "Pon"],
    correct: 0,
    official: "Pom",
  },

  // --- Los Fruittis ---
  {
    id: "fruittis-personajes",
    franchise: "Los Fruittis",
    emoji: "🍍",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman los tres protagonistas de Los Fruittis?",
    options: [
      "Mochilo, Pincho y Gazpacho",
      "Mochilo, Pincho y Melón",
      "Kiwi, Pincho y Gazpacho",
      "Mochilo, Piña y Gazpacho",
    ],
    correct: 0,
    official: "Mochilo, Pincho y Gazpacho",
  },

  // --- Los Trotamúsicos ---
  {
    id: "trotamusicos-cuento",
    franchise: "Los Trotamúsicos",
    emoji: "🎺",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué cuento clásico se basa Los Trotamúsicos?",
    options: [
      "Los músicos de Bremen",
      "El flautista de Hamelín",
      "Los tres cerditos",
      "El patito feo",
    ],
    correct: 0,
    official: "Los músicos de Bremen",
  },

  // --- Oliver y Benji ---
  {
    id: "oliverbenji-portero",
    franchise: "Oliver y Benji",
    emoji: "🎬",
    difficulty: "facil",
    format: "vf",
    prompt: "Benji es el delantero estrella del equipo y el que mete todos los goles.",
    correct: false,
    official: "Falso: Benji es el portero",
  },

  // --- Los Pitufos ---
  {
    id: "pitufos-gato",
    franchise: "Los Pitufos",
    emoji: "🐈",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el gato de Gargamel?",
    options: ["Azrael", "Azarel", "Isidoro", "Belcebú"],
    correct: 0,
    official: "Azrael",
  },

  // --- Inspector Gadget ---
  {
    id: "gadget-perro",
    franchise: "Inspector Gadget",
    emoji: "🕵️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el perro que ayuda a Penny a resolver los casos?",
    options: ["Sultán", "Cerebro", "Chispa", "Rayo"],
    correct: 0,
    official: "Sultán",
    note: "En el original es Brain, y en el doblaje latino, Cerebro.",
  },

  // --- Los Rugrats ---
  {
    id: "rugrats-tommy",
    franchise: "Los Rugrats",
    emoji: "🍼",
    difficulty: "facil",
    format: "describir",
    prompt: "Bebé calvo en pañales azules que lidera al grupo y siempre lleva un destornillador.",
    hint: "(Solo el nombre.)",
    accepted: [["Tommy"]],
    official: "Tommy",
  },


  // --- Agallas, el perro cobarde ---
  {
    id: "coraje-duenos",
    franchise: "Agallas, el perro cobarde",
    emoji: "🐕",
    difficulty: "facil",
    format: "vf",
    prompt: "Agallas vive con un matrimonio de ancianos en una granja en medio de la nada.",
    correct: true,
    official: "Verdadero",
    note: "En España se llama Agallas; en el doblaje latino, Coraje.",
  },

  // --- La Patrulla Canina ---
  {
    id: "patrullacanina-marshall",
    franchise: "La Patrulla Canina",
    emoji: "🚒",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué es Marshall, el dálmata torpón de la patrulla?",
    options: ["Bombero", "Policía", "Piloto", "Constructor"],
    correct: 0,
    official: "Bombero",
  },

  // --- Bluey ---
  {
    id: "bluey-raza",
    franchise: "Bluey",
    emoji: "🐶",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué país es la serie Bluey, protagonizada por una familia de perros?",
    options: ["Australia", "Estados Unidos", "Reino Unido", "Canadá"],
    correct: 0,
    official: "Australia",
  },

  // --- Peppa Pig ---
  {
    id: "peppa-charcos",
    franchise: "Peppa Pig",
    emoji: "🐷",
    difficulty: "facil",
    format: "vf",
    prompt: "Lo que más le gusta a Peppa es saltar en la cama elástica.",
    correct: false,
    official: "Falso: lo suyo es saltar en charcos de barro",
  },

  // --- Pocoyó ---
  {
    id: "pocoyo-pato",
    franchise: "Pocoyó",
    emoji: "🦆",
    difficulty: "facil",
    format: "vf",
    prompt: "Pato es el amigo amarillo de Pocoyó, y Elly, la elefanta rosa.",
    correct: true,
    official: "Verdadero",
  },


  // --- Masha y el Oso ---
  {
    id: "masha-oso",
    franchise: "Masha y el Oso",
    emoji: "🐻",
    difficulty: "facil",
    format: "vf",
    prompt: "En la serie, la niña vive sus travesuras junto a un oso que fue artista de circo.",
    correct: true,
    official: "Verdadero",
  },

  // --- Mortadelo y Filemón ---



  // --- Los Picapiedra ---


  // --- Gravity Falls ---
  {
    id: "gravityfalls-gemelos",
    franchise: "Gravity Falls",
    emoji: "🌲",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llaman los dos hermanos gemelos que pasan el verano en el pueblo?",
    hint: "(Los dos nombres.)",
    accepted: [["Dipper"], ["Mabel"]],
    official: "Dipper y Mabel",
  },

  // --- Steven Universe ---
  {
    id: "stevenuniverse-gemas",
    franchise: "Steven Universe",
    emoji: "💎",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el grupo de gemas que protege la Tierra junto a Steven?",
    options: [
      "Las Gemas de Cristal",
      "Las Gemas del Alba",
      "Las Guardianas de Cristal",
      "Las Gemas Puras",
    ],
    correct: 0,
    official: "Las Gemas de Cristal",
  },

  // --- Somos osos ---
  {
    id: "escandalosos-osos",
    franchise: "Somos osos",
    emoji: "🎬",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué tres osos protagonizan Somos osos?",
    options: [
      "Pardo, Panda y Polar",
      "Pardo, Panda y Koala",
      "Grizzly, Panda y Pardo",
      "Polar, Panda y Koala",
    ],
    correct: 0,
    official: "Pardo, Panda y Polar",
  },


  // --- Los Padrinos Mágicos ---
  {
    id: "padrinos-nombres",
    franchise: "Los Padrinos Mágicos",
    emoji: "🪄",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llaman los dos padrinos mágicos de Timmy?",
    hint: "(Los dos nombres.)",
    accepted: [["Cosmo"], ["Wanda"]],
    official: "Cosmo y Wanda",
  },

  // --- Ben 10 ---
  {
    id: "ben10-reloj",
    franchise: "Ben 10",
    emoji: "⌚",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el reloj que permite a Ben convertirse en alienígenas?",
    options: ["Omnitrix", "Alientrix", "Ultimatrix", "Cronotrix"],
    correct: 0,
    official: "El Omnitrix",
  },

  // --- Kim Possible ---
  {
    id: "kimpossible-rufus",
    franchise: "Kim Possible",
    emoji: "🕵️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Rufus, la mascota de Ron?",
    options: ["Una rata topo lampiña", "Un hámster", "Un hurón", "Un ratón"],
    correct: 0,
    official: "Una rata topo lampiña",
  },

  // --- Anime y Ghibli ---
  {
    id: "chihiro-padres",
    franchise: "El viaje de Chihiro",
    emoji: "🐷",
    difficulty: "facil",
    format: "vf",
    prompt: "Los padres de Chihiro se convierten en cerdos por comerse una comida que no era suya.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "castilloambulante-calcifer",
    franchise: "El castillo ambulante",
    emoji: "🔥",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el demonio de fuego que mueve el castillo?",
    options: ["Calcifer", "Calisto", "Cinder", "Caliban"],
    correct: 0,
    official: "Calcifer",
  },
  {
    id: "mononoke-san",
    franchise: "La princesa Mononoke",
    emoji: "🎬",
    difficulty: "facil",
    format: "vf",
    prompt: "San, la princesa Mononoke, ha sido criada por una manada de osos.",
    correct: false,
    official: "Falso: la crían lobos",
  },
  {
    id: "pokemon-equipo",
    franchise: "Pokémon",
    emoji: "⚡",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la organización de Jessie, James y Meowth?",
    hint: "(Dos palabras.)",
    accepted: [["Equipo Rocket", "Team Rocket", "Rocket"]],
    official: "El Equipo Rocket",
  },
  {
    id: "onepiece-sombrero",
    franchise: "One Piece",
    emoji: "🏴‍☠️",
    difficulty: "facil",
    format: "vf",
    prompt: "A la tripulación de Luffy se la conoce como los Piratas del Sombrero de Paja.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "conan-encogido",
    franchise: "Detective Conan",
    emoji: "🔍",
    difficulty: "facil",
    format: "vf",
    prompt: "Conan siempre ha sido un niño: nunca llegó a tener otro cuerpo.",
    correct: false,
    official: "Falso: es un detective adolescente al que un veneno dejó con cuerpo de niño",
  },
  {
    id: "dragonball-nube",
    franchise: "Dragon Ball",
    emoji: "☁️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la nube amarilla en la que vuela Goku?",
    hint: "(Dos palabras.)",
    accepted: [["Nube Kinton", "Kinton", "nube voladora"]],
    official: "La Nube Kinton",
  },

  // --- Series clásicas de televisión ---
  {
    id: "simpsons-vecino",
    franchise: "Los Simpson",
    emoji: "🍩",
    difficulty: "facil",
    format: "describir",
    prompt: "Vecino de bigote y jersey verde, muy religioso, que saluda con un «hola, holita».",
    hint: "(El apellido basta.)",
    accepted: [["Flanders", "Ned Flanders", "Ned"]],
    official: "Ned Flanders",
  },
  {
    id: "looney-correcaminos",
    franchise: "Looney Tunes",
    emoji: "🐦",
    difficulty: "facil",
    format: "vf",
    prompt: "El Coyote nunca llega a atrapar al Correcaminos.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "bobesponja-mascota",
    franchise: "Bob Esponja",
    emoji: "🧽",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Gary, la mascota de Bob Esponja?",
    options: ["Un caracol", "Un cangrejo", "Un pez", "Una tortuga"],
    correct: 0,
    official: "Un caracol",
    note: "Y maúlla como un gato.",
  },

  // --- Cronologías y relaciones de series ---
  {
    id: "orden-clasicos-tv",
    franchise: "Anime clásico",
    emoji: "📺",
    difficulty: "facil",
    format: "orden",
    prompt: "Ordena estas series de la más antigua a la más reciente.",
    items: ["Heidi", "Dragon Ball", "Pokémon", "Bob Esponja"],
    official: "Heidi (1974), Dragon Ball (1986), Pokémon (1997) y Bob Esponja (1999)",
  },
  {
    id: "relacionar-series-mascotas",
    franchise: "Mascotas de series",
    emoji: "🐾",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada mascota con su serie.",
    pairs: [
      { left: "Gary", right: "Bob Esponja" },
      { left: "Nevado", right: "Shin Chan" },
      { left: "Dino", right: "Los Picapiedra" },
      { left: "Perry", right: "Phineas y Ferb" },
    ],
    official: "Gary–Bob Esponja, Nevado–Shin Chan, Dino–Los Picapiedra y Perry–Phineas y Ferb",
  },
  {
    id: "relacionar-anime-protagonistas",
    franchise: "Anime clásico",
    emoji: "📺",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada protagonista con su serie.",
    pairs: [
      { left: "Goku", right: "Dragon Ball" },
      { left: "Luffy", right: "One Piece" },
      { left: "Ash", right: "Pokémon" },
      { left: "Nobita", right: "Doraemon" },
    ],
    official: "Goku–Dragon Ball, Luffy–One Piece, Ash–Pokémon y Nobita–Doraemon",
  },
  {
    id: "relacionar-ghibli-criaturas",
    franchise: "Studio Ghibli",
    emoji: "🌳",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada criatura o personaje con su película de Ghibli.",
    pairs: [
      { left: "Totoro", right: "Mi vecino Totoro" },
      { left: "Sin Cara", right: "El viaje de Chihiro" },
      { left: "Calcifer", right: "El castillo ambulante" },
      { left: "Jiji", right: "Nicky, la aprendiz de bruja" },
    ],
    official:
      "Totoro–Mi vecino Totoro, Sin Cara–El viaje de Chihiro, Calcifer–El castillo ambulante y Jiji–Nicky",
  },
  {
    id: "relacionar-clasicos-espanoles",
    franchise: "Series españolas",
    emoji: "🇪🇸",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada personaje con su serie.",
    pairs: [
      { left: "Mochilo", right: "Los Fruittis" },
      { left: "Pom", right: "D'Artacan" },
      { left: "Swift", right: "David el Gnomo" },
      { left: "La Bruja Aburrida", right: "Las Tres Mellizas" },
    ],
    official:
      "Mochilo–Los Fruittis, Pom–D'Artacan, Swift–David el Gnomo y la Bruja Aburrida–Las Tres Mellizas",
  },
  {
    id: "relacionar-cartoon-network",
    franchise: "Series de dibujos",
    emoji: "📺",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada personaje con su serie.",
    pairs: [
      { left: "Finn", right: "Hora de aventuras" },
      { left: "Dipper", right: "Gravity Falls" },
      { left: "Darwin", right: "El asombroso mundo de Gumball" },
      { left: "DeeDee", right: "El laboratorio de Dexter" },
    ],
    official:
      "Finn–Hora de aventuras, Dipper–Gravity Falls, Darwin–Gumball y DeeDee–El laboratorio de Dexter",
  },
  {
    id: "relacionar-infantil-preescolar",
    franchise: "Series preescolares",
    emoji: "🧸",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada personaje con su serie.",
    pairs: [
      { left: "George", right: "Peppa Pig" },
      { left: "Bingo", right: "Bluey" },
      { left: "Ryder", right: "La Patrulla Canina" },
      { left: "Botas", right: "Dora la exploradora" },
    ],
    official: "George–Peppa Pig, Bingo–Bluey, Ryder–La Patrulla Canina y Botas–Dora la exploradora",
  },
  {
    id: "completar-bobesponja-lema",
    franchise: "Bob Esponja",
    emoji: "🧽",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa dónde vive Bob Esponja: «una piña debajo del ___».",
    accepted: [["mar"]],
    official: "Una piña debajo del mar",
  },
  {
    id: "completar-simpsons-homer",
    franchise: "Los Simpson",
    emoji: "🍩",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa la exclamación de Homer Simpson: «¡___!», cuando algo le sale mal.",
    accepted: [["Mosquis", "D'oh"]],
    official: "¡Mosquis!",
    note: "En el doblaje español, el «D'oh» original se convirtió en «mosquis».",
  },
  {
    id: "completar-pokemon-lema",
    franchise: "Pokémon",
    emoji: "⚡",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el lema de la serie: «¡Hazte con ___!».",
    accepted: [["todos"]],
    official: "¡Hazte con todos!",
  },
  {
    id: "completar-pitufos-cancion",
    franchise: "Los Pitufos",
    emoji: "🔵",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el nombre de la única chica del pueblo pitufo: «Pituf___».",
    accepted: [["ina"]],
    official: "Pitufina",
  },
  {
    id: "completar-tortugas-comida",
    franchise: "Las Tortugas Ninja",
    emoji: "🐢",
    difficulty: "facil",
    format: "completar",
    prompt:
      "Completa la frase: las Tortugas Ninja son cuatro hermanos que viven en las alcantarillas y se vuelven locos por la ___.",
    accepted: [["pizza"]],
    official: "La pizza",
  },
  {
    id: "completar-heidi-cancion",
    franchise: "Heidi",
    emoji: "🏔️",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa la sintonía de la serie: «Abuelito, dime ___».",
    accepted: [["tú"]],
    official: "Abuelito, dime tú",
  },
  {
    id: "orden-disney-pixar-mezcla",
    franchise: "Lugares de ficción",
    emoji: "🗺️",
    difficulty: "facil",
    format: "orden",
    prompt: "Ordena estas películas de la más antigua a la más reciente.",
    items: ["Blancanieves", "El Rey León", "Frozen", "Encanto"],
    official: "Blancanieves (1937), El Rey León (1994), Frozen (2013) y Encanto (2021)",
  },
  {
    id: "orden-anime-90",
    franchise: "Anime clásico",
    emoji: "📺",
    difficulty: "facil",
    format: "orden",
    prompt: "Ordena estas series de anime de la más antigua a la más reciente.",
    items: ["Dragon Ball", "Sailor Moon", "Pokémon", "One Piece"],
    official: "Dragon Ball (1986), Sailor Moon (1992), Pokémon (1997) y One Piece (1999)",
  },
  {
    id: "orden-series-espanolas",
    franchise: "Series españolas",
    emoji: "🇪🇸",
    difficulty: "facil",
    format: "orden",
    prompt: "Ordena estas series españolas de la más antigua a la más reciente.",
    items: ["Willy Fog", "David el Gnomo", "Los Fruittis", "Las Tres Mellizas"],
    official:
      "Willy Fog (1983), David el Gnomo (1985), Los Fruittis (1990) y Las Tres Mellizas (1995)",
  },

  // --- Más cronologías, relaciones y personajes ---
  {
    id: "describir-pikachu",
    franchise: "Pokémon",
    emoji: "⚡",
    difficulty: "facil",
    format: "describir",
    prompt: "Ratón eléctrico amarillo, con las mejillas rojas y la cola en forma de rayo.",
    hint: "(Solo el nombre.)",
    accepted: [["Pikachu"]],
    official: "Pikachu",
  },
  {
    id: "describir-shinchan",
    franchise: "Shin Chan",
    emoji: "🍑",
    difficulty: "facil",
    format: "describir",
    prompt: "Niño de cinco años, dibujado con cuatro trazos, que enseña el culete y saca de quicio a su madre.",
    hint: "(Solo el nombre.)",
    accepted: [["Shin Chan", "Shinchan", "Shin-chan"]],
    official: "Shin Chan",
  },
  {
    id: "orden-pixar-decadas",
    franchise: "Pixar clásico",
    emoji: "🎞️",
    difficulty: "facil",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Toy Story", "Buscando a Nemo", "Up", "Coco"],
    official: "Toy Story (1995), Buscando a Nemo (2003), Up (2009) y Coco (2017)",
  },
  {
    id: "orden-pixar-2000",
    franchise: "Pixar clásico",
    emoji: "🎞️",
    difficulty: "facil",
    format: "orden",
    prompt: "Ordena estas películas de Pixar de la más antigua a la más reciente.",
    items: ["Bichos", "Los Increíbles", "Ratatouille", "Del revés"],
    official: "Bichos (1998), Los Increíbles (2004), Ratatouille (2007) y Del revés (2015)",
  },
  {
    id: "orden-ghibli-brujas",
    franchise: "Studio Ghibli",
    emoji: "🎞️",
    difficulty: "facil",
    format: "orden",
    prompt: "Ordena estas películas de Ghibli de la más antigua a la más reciente.",
    items: [
      "Nicky, la aprendiz de bruja",
      "La princesa Mononoke",
      "El castillo ambulante",
      "Ponyo",
    ],
    official:
      "Nicky, la aprendiz de bruja (1989), La princesa Mononoke (1997), El castillo ambulante (2004) y Ponyo (2008)",
  },
  {
    id: "orden-estudios-mezcla",
    franchise: "Estudios de animación",
    emoji: "🎞️",
    difficulty: "facil",
    format: "orden",
    prompt: "Ordena estas películas de la más antigua a la más reciente.",
    items: ["Shrek", "Madagascar", "Mi villano favorito", "Canta"],
    official: "Shrek (2001), Madagascar (2005), Mi villano favorito (2010) y Canta (2016)",
  },
  {
    id: "orden-animales-cine",
    franchise: "Estudios de animación",
    emoji: "🐾",
    difficulty: "facil",
    format: "orden",
    prompt: "Ordena estas películas de animales de la más antigua a la más reciente.",
    items: ["Ice Age", "Madagascar", "Río", "Mascotas"],
    official: "Ice Age (2002), Madagascar (2005), Río (2011) y Mascotas (2016)",
  },
  {
    id: "orden-anime-decadas",
    franchise: "Anime clásico",
    emoji: "📺",
    difficulty: "facil",
    format: "orden",
    prompt: "Ordena estas series de anime de la más antigua a la más reciente.",
    items: ["Doraemon", "Dragon Ball", "Detective Conan", "One Piece"],
    official: "Doraemon (1979), Dragon Ball (1986), Detective Conan (1996) y One Piece (1999)",
  },
  {
    id: "orden-dibujos-tv",
    franchise: "Series de dibujos",
    emoji: "📺",
    difficulty: "facil",
    format: "orden",
    prompt: "Ordena estas series de la más antigua a la más reciente.",
    items: ["Los Rugrats", "Bob Esponja", "Hora de aventuras", "Gravity Falls"],
    official:
      "Los Rugrats (1991), Bob Esponja (1999), Hora de aventuras (2010) y Gravity Falls (2012)",
  },
  {
    id: "relacionar-villanos-series",
    franchise: "Series de dibujos",
    emoji: "😈",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada villano con su serie.",
    pairs: [
      { left: "Gargamel", right: "Los Pitufos" },
      { left: "Plankton", right: "Bob Esponja" },
      { left: "El Equipo Rocket", right: "Pokémon" },
      { left: "Destructor", right: "Las Tortugas Ninja" },
    ],
    official:
      "Gargamel–Los Pitufos, Plankton–Bob Esponja, el Equipo Rocket–Pokémon y Destructor–Las Tortugas Ninja",
  },
  {
    id: "relacionar-lugares-series",
    franchise: "Lugares de ficción",
    emoji: "🗺️",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada lugar con la serie a la que pertenece.",
    pairs: [
      { left: "Fondo de Bikini", right: "Bob Esponja" },
      { left: "Springfield", right: "Los Simpson" },
      { left: "Konoha", right: "Naruto" },
      { left: "Pueblo Paleta", right: "Pokémon" },
    ],
    official:
      "Fondo de Bikini–Bob Esponja, Springfield–Los Simpson, Konoha–Naruto y Pueblo Paleta–Pokémon",
  },
  {
    id: "relacionar-objetos-series",
    franchise: "Series de dibujos",
    emoji: "🎒",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada objeto con la historia en la que aparece.",
    pairs: [
      { left: "El Omnitrix", right: "Ben 10" },
      { left: "La Nube Kinton", right: "Dragon Ball" },
      { left: "El bolsillo mágico", right: "Doraemon" },
      { left: "La Máquina del Misterio", right: "Scooby-Doo" },
    ],
    official:
      "El Omnitrix–Ben 10, la Nube Kinton–Dragon Ball, el bolsillo mágico–Doraemon y la Máquina del Misterio–Scooby-Doo",
  },
  {
    id: "relacionar-comidas",
    franchise: "Lugares de ficción",
    emoji: "🗺️",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada comida con la historia en la que es famosa.",
    pairs: [
      { left: "La pizza", right: "Las Tortugas Ninja" },
      { left: "La miel", right: "Winnie the Pooh" },
      { left: "El queso", right: "Wallace y Gromit" },
      { left: "La bellota", right: "Ice Age" },
    ],
    official:
      "La pizza–Las Tortugas Ninja, la miel–Winnie the Pooh, el queso–Wallace y Gromit y la bellota–Ice Age",
  },

  // --- Reemplazos: personajes que aún no salían ---
  {
    id: "reyleon-scar",
    franchise: "El Rey León",
    emoji: "🦁",
    difficulty: "media",
    format: "describir",
    prompt: "León de melena negra y cicatriz en el ojo que envidia el trono de su hermano.",
    hint: "(Solo el nombre.)",
    accepted: [["Scar"]],
    official: "Scar",
  },
  {
    id: "bella-potts",
    franchise: "La Bella y la Bestia",
    emoji: "🌹",
    difficulty: "media",
    format: "describir",
    prompt: "Tetera bonachona del castillo encantado, que hace de madre de todos y canta la canción principal.",
    hint: "(Solo el nombre.)",
    accepted: [["Señora Potts", "Sra. Potts", "Potts"]],
    official: "La señora Potts",
  },
  {
    id: "enredados-flynn",
    franchise: "Enredados",
    emoji: "💇",
    difficulty: "media",
    format: "describir",
    prompt: "Ladrón chulesco que se cuela en la torre huyendo de la guardia y acaba guiando a Rapunzel.",
    hint: "(Cualquiera de sus dos nombres.)",
    accepted: [["Flynn Rider", "Flynn", "Eugene", "Eugene Fitzherbert"]],
    official: "Flynn Rider, que en realidad se llama Eugene",
  },
  {
    id: "peterpan-garfio",
    franchise: "Peter Pan",
    emoji: "🧚",
    difficulty: "facil",
    format: "describir",
    prompt: "Capitán pirata de melena negra con un garfio en lugar de mano, aterrado por un cocodrilo.",
    hint: "(Solo el nombre.)",
    accepted: [["Garfio", "Capitán Garfio"]],
    official: "El capitán Garfio",
  },
  {
    id: "selva-bagheera",
    franchise: "El libro de la selva",
    emoji: "🐆",
    difficulty: "facil",
    format: "describir",
    prompt: "Pantera negra sensata y protectora que se empeña en llevar a Mowgli con los hombres.",
    hint: "(Solo el nombre.)",
    accepted: [["Bagheera", "Baguera"]],
    official: "Bagheera",
  },
  {
    id: "frozen-sven",
    franchise: "Frozen",
    emoji: "🦌",
    difficulty: "facil",
    format: "describir",
    prompt: "Reno leal al que su dueño pone voz para hacer que conteste por él.",
    hint: "(Solo el nombre.)",
    accepted: [["Sven"]],
    official: "Sven",
  },
  {
    id: "bobesponja-cangrejo",
    franchise: "Bob Esponja",
    emoji: "🦀",
    difficulty: "facil",
    format: "describir",
    prompt: "Cangrejo tacaño, dueño del restaurante, capaz de cualquier cosa por una moneda.",
    hint: "(Solo el nombre.)",
    accepted: [["Don Cangrejo", "Cangrejo"]],
    official: "Don Cangrejo",
  },
  {
    id: "aladdin-abu",
    franchise: "Aladdín",
    emoji: "🧞",
    difficulty: "facil",
    format: "describir",
    prompt: "Mono ladronzuelo con fez rojo y chalequito morado que acompaña a Aladdín.",
    hint: "(Solo el nombre.)",
    accepted: [["Abú"]],
    official: "Abú",
  },
  {
    id: "monstruos-mike",
    franchise: "Monstruos S.A.",
    emoji: "👁️",
    difficulty: "facil",
    format: "describir",
    prompt: "Monstruo verde, redondo y con un único ojo enorme, compañero inseparable de Sulley.",
    hint: "(El nombre basta.)",
    accepted: [["Mike", "Mike Wazowski", "Wazowski"]],
    official: "Mike Wazowski",
  },
  {
    id: "kfp-tailung",
    franchise: "Kung Fu Panda",
    emoji: "🐼",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el leopardo de las nieves que escapa de prisión para vengarse?",
    options: ["Tai Lung", "Lord Shen", "Kai", "Tigresa"],
    correct: 0,
    official: "Tai Lung",
  },
  {
    id: "pocahontas-colibri",
    franchise: "Pocahontas",
    emoji: "🍃",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el colibrí gruñón que acompaña a Pocahontas?",
    options: ["Flit", "Meeko", "Percy", "Kekata"],
    correct: 0,
    official: "Flit",
    note: "Meeko es el mapache y Percy, el perro del gobernador.",
  },
  {
    id: "tiana-louis",
    franchise: "Tiana y el sapo",
    emoji: "🐊",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el cocodrilo que sueña con tocar la trompeta en una banda de jazz?",
    options: ["Louis", "Ray", "Naveen", "Lawrence"],
    correct: 0,
    official: "Louis",
  },
  {
    id: "sailormoon-artemis",
    franchise: "Sailor Moon",
    emoji: "🌙",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el gato blanco que acompaña a las guerreras, pareja de Luna?",
    options: ["Artemis", "Apolo", "Selene", "Diana"],
    correct: 0,
    official: "Artemis",
  },
  {
    id: "zootropolis-nick",
    franchise: "Zootrópolis",
    emoji: "🦊",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el zorro estafador que acaba ayudando a Judy?",
    hint: "(El nombre basta.)",
    accepted: [["Nick", "Nick Wilde", "Wilde"]],
    official: "Nick Wilde",
  },
  {
    id: "grinch-cindy",
    franchise: "El Grinch",
    emoji: "🎄",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la niña que se cruza con el Grinch y le hace replantearse todo?",
    hint: "(El nombre basta.)",
    accepted: [["Cindy", "Cindy Lou", "Cindy Lou Quién"]],
    official: "Cindy Lou",
  },
  {
    id: "tortugas-april",
    franchise: "Las Tortugas Ninja",
    emoji: "🐢",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la reportera pelirroja amiga de las tortugas?",
    hint: "(El nombre basta.)",
    accepted: [["April", "April O'Neil", "O'Neil"]],
    official: "April O'Neil",
  },
  {
    id: "picapiedra-dinosaurio",
    franchise: "Los Picapiedra",
    emoji: "🦕",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la mascota de la familia Picapiedra, que se comporta como un perro?",
    hint: "(Solo el nombre.)",
    accepted: [["Dino"]],
    official: "Dino",
  },
  {
    id: "nicky-edad",
    franchise: "Nicky, la aprendiz de bruja",
    emoji: "🧹",
    difficulty: "facil",
    format: "corta",
    prompt: "¿A qué edad tienen que irse de casa las brujas para formarse por su cuenta?",
    hint: "(Un número.)",
    accepted: [["13", "trece"]],
    official: "A los 13 años",
  },
  {
    id: "shinchan-madre",
    franchise: "Shin Chan",
    emoji: "🍑",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la madre de Shin Chan, la que más le sufre?",
    hint: "(Solo el nombre.)",
    accepted: [["Misae"]],
    official: "Misae",
  },
  {
    id: "mortadelo-secretaria",
    franchise: "Mortadelo y Filemón",
    emoji: "🕶️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la secretaria de la T.I.A., enamorada de Mortadelo?",
    hint: "(Solo el nombre.)",
    accepted: [["Ofelia"]],
    official: "Ofelia",
  },
  {
    id: "toystory-serpiente",
    franchise: "Toy Story",
    emoji: "🤠",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa lo que dice Woody cuando le tiran del cordel: «¡Hay una serpiente en mi ___!».",
    accepted: [["bota"]],
    official: "¡Hay una serpiente en mi bota!",
  },
  {
    id: "dragonball-ondavital",
    franchise: "Dragon Ball",
    emoji: "💥",
    difficulty: "facil",
    format: "completar",
    prompt:
      "Completa el nombre con el que se conoció en España el ataque más famoso de Goku: «Onda ___».",
    accepted: [["vital"]],
    official: "Onda vital",
    note: "En el original es Kamehameha; el doblaje español lo rebautizó y se hizo célebre.",
  },

  // --- Mazinger Z ---
  {
    id: "mazinger-que-es",
    franchise: "Mazinger Z",
    emoji: "🤖",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué es Mazinger Z?",
    options: ["Un robot gigante pilotado", "Un alienígena", "Una nave", "Un superhéroe"],
    correct: 0,
    official: "Un robot gigante que se pilota desde dentro",
  },
  {
    id: "mazinger-koji",
    franchise: "Mazinger Z",
    emoji: "🕹️",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el joven que pilota a Mazinger Z?",
    hint: "(El nombre basta.)",
    accepted: [["Koji", "Koji Kabuto", "Kabuto"]],
    official: "Koji Kabuto",
  },
  {
    id: "mazinger-puños",
    franchise: "Mazinger Z",
    emoji: "👊",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el ataque más famoso de Mazinger Z: «¡Puños ___!».",
    accepted: [["fuera"]],
    official: "¡Puños fuera!",
  },
  {
    id: "mazinger-generacion",
    franchise: "Mazinger Z",
    emoji: "📺",
    difficulty: "facil",
    format: "vf",
    prompt: "Mazinger Z nunca llegó a emitirse en la televisión española.",
    correct: false,
    official: "Falso: fue uno de los primeros animes que se vieron aquí",
  },

  // --- Los Caballeros del Zodiaco ---
  {
    id: "zodiaco-armaduras",
    franchise: "Los Caballeros del Zodiaco",
    emoji: "♈",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué visten los protagonistas para combatir?",
    options: ["Armaduras", "Capas mágicas", "Trajes espaciales", "Kimonos"],
    correct: 0,
    official: "Armaduras",
  },
  {
    id: "zodiaco-signos",
    franchise: "Los Caballeros del Zodiaco",
    emoji: "⭐",
    difficulty: "facil",
    format: "vf",
    prompt: "Las armaduras de los caballeros se corresponden con constelaciones y signos del zodiaco.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "zodiaco-seiya",
    franchise: "Los Caballeros del Zodiaco",
    emoji: "🐴",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el protagonista, el caballero de Pegaso?",
    hint: "(Solo el nombre.)",
    accepted: [["Seiya"]],
    official: "Seiya",
  },
  {
    id: "zodiaco-diosa",
    franchise: "Los Caballeros del Zodiaco",
    emoji: "🏛️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿A qué diosa protegen los caballeros?",
    options: ["Atenea", "Afrodita", "Hera", "Artemisa"],
    correct: 0,
    official: "Atenea",
  },

  // --- Digimon ---
  {
    id: "digimon-que-son",
    franchise: "Digimon",
    emoji: "🥚",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué son los digimon?",
    options: [
      "Monstruos digitales de otro mundo",
      "Robots de combate",
      "Alienígenas",
      "Animales mutantes",
    ],
    correct: 0,
    official: "Monstruos digitales",
  },
  {
    id: "digimon-digievolucion",
    franchise: "Digimon",
    emoji: "✨",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el proceso por el que un digimon se transforma en otro más fuerte?",
    hint: "(Una palabra.)",
    accepted: [["digievolución", "digievolucion", "digievolucionar", "evolución"]],
    official: "La digievolución",
  },
  {
    id: "digimon-niños",
    franchise: "Digimon",
    emoji: "🏕️",
    difficulty: "media",
    format: "vf",
    prompt:
      "La primera serie arranca con unos niños que acaban en el mundo digital desde el colegio.",
    correct: false,
    official: "Falso: están en un campamento de verano",
  },
  {
    id: "digimon-agumon",
    franchise: "Digimon",
    emoji: "🦖",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el digimon naranja con forma de dinosaurio del protagonista?",
    hint: "(Solo el nombre.)",
    accepted: [["Agumon"]],
    official: "Agumon",
  },

  // --- Ranma ½ ---
  {
    id: "ranma-transformacion",
    franchise: "Ranma ½",
    emoji: "💧",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué le pasa a Ranma cuando le cae agua fría encima?",
    options: [
      "Se convierte en chica",
      "Se convierte en panda",
      "Pierde la memoria",
      "Se vuelve invisible",
    ],
    correct: 0,
    official: "Se convierte en chica",
  },
  {
    id: "ranma-caliente",
    franchise: "Ranma ½",
    emoji: "♨️",
    difficulty: "media",
    format: "vf",
    prompt: "Con agua caliente, la transformación de Ranma se vuelve permanente.",
    correct: false,
    official: "Falso: con agua caliente vuelve a su forma original",
  },
  {
    id: "ranma-padre",
    franchise: "Ranma ½",
    emoji: "💧",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué se convierte el padre de Ranma con el agua fría?",
    options: ["En panda", "En cerdito", "En gato", "En pato"],
    correct: 0,
    official: "En panda",
  },

  // --- Érase una vez el hombre ---
  {
    id: "eraseunavez-maestro",
    franchise: "Érase una vez el hombre",
    emoji: "🧔",
    difficulty: "media",
    format: "describir",
    prompt: "Anciano de barba blanca que aparece en cada época de la serie para explicar la historia.",
    hint: "(Cómo se le llama.)",
    accepted: [["el Maestro", "Maestro"]],
    official: "El Maestro",
  },
  {
    id: "eraseunavez-tema",
    franchise: "Érase una vez el hombre",
    emoji: "📚",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué trata Érase una vez el hombre?",
    options: [
      "De la historia de la humanidad",
      "De un viaje espacial",
      "De la vida en la selva",
      "De cuentos clásicos",
    ],
    correct: 0,
    official: "De la historia de la humanidad, época por época",
  },
  {
    id: "eraseunavez-cuerpo",
    franchise: "Érase una vez el hombre",
    emoji: "🫀",
    difficulty: "facil",
    format: "vf",
    prompt: "Érase una vez el hombre nunca tuvo una versión dedicada al cuerpo humano.",
    correct: false,
    official: "Falso: la tuvo, y fue igual de famosa",
  },

  // --- Otros clásicos ---
  {
    id: "chicho-deporte",
    franchise: "Chicho Terremoto",
    emoji: "📏",
    difficulty: "media",
    format: "corta",
    prompt: "¿A qué deporte juega Chicho Terremoto?",
    hint: "(Un deporte.)",
    accepted: [["baloncesto", "basket", "básquet"]],
    official: "Al baloncesto",
  },
  {
    id: "chicho-altura",
    franchise: "Chicho Terremoto",
    emoji: "📏",
    difficulty: "media",
    format: "vf",
    prompt: "Chicho destaca en la cancha porque es el más alto del equipo.",
    correct: false,
    official: "Falso: es bajito, y esa es la gracia",
  },
  {
    id: "musculman-lucha",
    franchise: "Musculman",
    emoji: "🤼",
    difficulty: "media",
    format: "multiple",
    prompt: "¿A qué se dedican los personajes de Musculman?",
    options: ["A la lucha libre", "Al fútbol", "Al boxeo", "A las carreras"],
    correct: 0,
    official: "A la lucha libre",
  },
  {
    id: "musculman-fideos",
    franchise: "Musculman",
    emoji: "🤼",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿De qué planeta viene Musculman?",
    options: ["Del planeta Fideo", "Del planeta Músculo", "De Marte", "De la Luna"],
    correct: 0,
    official: "Del planeta Fideo",
  },
  {
    id: "candycandy-huerfana",
    franchise: "Candy Candy",
    emoji: "🎀",
    difficulty: "media",
    format: "vf",
    prompt: "Candy es la hija de una familia rica que se escapa de casa.",
    correct: false,
    official: "Falso: es huérfana y se cría en un hogar de acogida",
  },
  {
    id: "candycandy-tono",
    franchise: "Candy Candy",
    emoji: "😢",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Por qué se recuerda sobre todo a Candy Candy?",
    options: [
      "Por lo mucho que se llora con ella",
      "Por sus escenas de acción",
      "Por su humor",
      "Por su banda sonora de rock",
    ],
    correct: 0,
    official: "Por lo mucho que se llora con ella",
  },
  {
    id: "banner-animal",
    franchise: "Banner y Flappy",
    emoji: "🎬",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué animales son Banner y Flappy?",
    options: ["Ardillas", "Conejos", "Ratones", "Castores"],
    correct: 0,
    official: "Ardillas",
  },

  // --- Ampliación de las que ya estaban ---
  {
    id: "dragonball-bulma",
    franchise: "Dragon Ball",
    emoji: "💙",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la chica del pelo azul que acompaña a Goku al principio?",
    hint: "(Solo el nombre.)",
    accepted: [["Bulma"]],
    official: "Bulma",
  },
  {
    id: "dragonball-cola",
    franchise: "Dragon Ball",
    emoji: "🐉",
    difficulty: "facil",
    format: "vf",
    prompt: "De pequeño, Goku tenía alas.",
    correct: false,
    official: "Falso: lo que tenía era cola de mono",
  },
  {
    id: "dragonball-krilin",
    franchise: "Dragon Ball",
    emoji: "🥋",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el amigo bajito y calvo de Goku, sin nariz?",
    hint: "(Solo el nombre.)",
    accepted: [["Krilín", "Krilin", "Kuririn"]],
    official: "Krilín",
  },
  {
    id: "dragonball-esferas",
    franchise: "Dragon Ball",
    emoji: "🐉",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué pasa al reunir las siete bolas de dragón?",
    options: [
      "Aparece un dragón que concede un deseo",
      "Se abre un portal",
      "Se obtiene un poder eterno",
      "Se cura cualquier herida",
    ],
    correct: 0,
    official: "Aparece Shenron y concede un deseo",
  },
  {
    id: "dragonball-supersaiyan",
    franchise: "Dragon Ball",
    emoji: "🐉",
    difficulty: "media",
    format: "corta",
    prompt: "¿De qué color se le pone el pelo a Goku al transformarse en Super Saiyan?",
    hint: "(Un color.)",
    accepted: [["rubio", "amarillo", "dorado"]],
    official: "Rubio",
  },
  {
    id: "pokemon-ash-sueño",
    franchise: "Pokémon",
    emoji: "🏆",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué quiere llegar a ser Ash?",
    hint: "(Dos palabras.)",
    accepted: [["maestro pokémon", "maestro pokemon", "el mejor entrenador", "maestro"]],
    official: "Maestro Pokémon",
  },
  {
    id: "pokemon-pokeball",
    franchise: "Pokémon",
    emoji: "⚪",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la bola con la que se atrapan los pokémon?",
    hint: "(Una palabra.)",
    accepted: [["pokéball", "pokeball", "poké ball"]],
    official: "Pokéball",
  },
  {
    id: "pokemon-pikachu-tipo",
    franchise: "Pokémon",
    emoji: "⚡",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué tipo es Pikachu?",
    options: ["Eléctrico", "Fuego", "Agua", "Planta"],
    correct: 0,
    official: "Eléctrico",
  },
  {
    id: "pokemon-meowth",
    franchise: "Pokémon",
    emoji: "🐱",
    difficulty: "media",
    format: "vf",
    prompt: "El Meowth del Equipo Rocket es de los pocos pokémon que hablan como las personas.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "pokemon-numero-inicial",
    franchise: "Pokémon",
    emoji: "🔥",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuáles son los tres pokémon iniciales de la primera generación?",
    options: [
      "Bulbasaur, Charmander y Squirtle",
      "Pikachu, Charmander y Squirtle",
      "Bulbasaur, Eevee y Squirtle",
      "Charmander, Squirtle y Meowth",
    ],
    correct: 0,
    official: "Bulbasaur, Charmander y Squirtle",
  },
  {
    id: "doraemon-puerta",
    franchise: "Doraemon",
    emoji: "🔔",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el invento de Doraemon que lleva a cualquier sitio al cruzarlo?",
    hint: "(Dos palabras.)",
    accepted: [["puerta mágica", "la puerta mágica", "puerta a cualquier lugar"]],
    official: "La puerta mágica",
  },
  {
    id: "doraemon-miedo",
    franchise: "Doraemon",
    emoji: "🐭",
    difficulty: "media",
    format: "vf",
    prompt: "A Doraemon, siendo un gato robot, le encanta cazar ratones.",
    correct: false,
    official: "Falso: les tiene pánico",
  },
  {
    id: "doraemon-gigante",
    franchise: "Doraemon",
    emoji: "😤",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el abusón grandullón que atormenta a Nobita?",
    hint: "(Solo el nombre.)",
    accepted: [["Gigante", "Gian"]],
    official: "Gigante",
  },
  {
    id: "shinchan-hermana-perro",
    franchise: "Shin Chan",
    emoji: "🐶",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el padre de Shin Chan?",
    hint: "(Solo el nombre.)",
    accepted: [["Hiroshi"]],
    official: "Hiroshi",
  },
  {
    id: "shinchan-baile",
    franchise: "Shin Chan",
    emoji: "🍑",
    difficulty: "facil",
    format: "vf",
    prompt: "Shin Chan es famoso por enseñar el culete y hacer el baile del elefante.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "shinchan-edad",
    franchise: "Shin Chan",
    emoji: "🎂",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuántos años tiene Shin Chan?",
    hint: "(Un número.)",
    accepted: [["5", "cinco"]],
    official: "Cinco años",
  },
  {
    id: "naruto-sueño",
    franchise: "Naruto",
    emoji: "🍥",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué quiere llegar a ser Naruto?",
    hint: "(Un cargo de su aldea.)",
    accepted: [["Hokage", "el Hokage"]],
    official: "Hokage, el líder de su aldea",
  },
  {
    id: "naruto-comida",
    franchise: "Naruto",
    emoji: "🍥",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cuál es la comida favorita de Naruto?",
    hint: "(Un plato.)",
    accepted: [["ramen", "el ramen", "fideos"]],
    official: "El ramen",
  },
  {
    id: "onepiece-tesoro",
    franchise: "One Piece",
    emoji: "💰",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el tesoro que busca Luffy y que da nombre a la serie?",
    hint: "(Dos palabras.)",
    accepted: [["One Piece", "el One Piece"]],
    official: "El One Piece",
  },
  {
    id: "onepiece-goma",
    franchise: "One Piece",
    emoji: "🫳",
    difficulty: "facil",
    format: "vf",
    prompt: "Luffy tiene el cuerpo de acero por haber comido una fruta del diablo.",
    correct: false,
    official: "Falso: lo tiene de goma",
  },
  {
    id: "sailormoon-transformacion",
    franchise: "Sailor Moon",
    emoji: "🌙",
    difficulty: "facil",
    format: "vf",
    prompt: "Las protagonistas son chicas normales que se transforman en guerreras.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "sailormoon-planetas",
    franchise: "Sailor Moon",
    emoji: "🪐",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Con qué se corresponden los nombres de las guerreras?",
    options: ["Con planetas", "Con constelaciones", "Con piedras preciosas", "Con flores"],
    correct: 0,
    official: "Con planetas",
  },
  {
    id: "conan-gafas",
    franchise: "Detective Conan",
    emoji: "👓",
    difficulty: "facil",
    format: "vf",
    prompt: "Conan lleva unas gafas que en realidad son un aparato con funciones ocultas.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "conan-capitulos",
    franchise: "Detective Conan",
    emoji: "📺",
    difficulty: "media",
    format: "vf",
    prompt: "Detective Conan terminó con menos de cien episodios.",
    correct: false,
    official: "Falso: lleva más de mil",
  },
  {
    id: "heidi-cabra",
    franchise: "Heidi",
    emoji: "🐐",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la cabrita blanca preferida de Heidi?",
    hint: "(Dos palabras.)",
    accepted: [["Copo de Nieve", "Copito de Nieve", "Copo"]],
    official: "Copo de Nieve",
  },
  {
    id: "heidi-ciudad",
    franchise: "Heidi",
    emoji: "🏙️",
    difficulty: "media",
    format: "vf",
    prompt: "Heidi se adapta encantada a la vida en la ciudad y no echa de menos la montaña.",
    correct: false,
    official: "Falso: enferma de tristeza",
  },
  {
    id: "marco-pais",
    franchise: "Marco",
    emoji: "🚢",
    difficulty: "media",
    format: "multiple",
    prompt: "¿A qué continente viaja Marco buscando a su madre?",
    options: ["A América del Sur", "A África", "A Asia", "A Oceanía"],
    correct: 0,
    official: "A América del Sur",
  },
  {
    id: "abejamaya-donde",
    franchise: "La abeja Maya",
    emoji: "🌻",
    difficulty: "facil",
    format: "vf",
    prompt: "Maya adora la vida ordenada de la colmena y nunca se plantea marcharse.",
    correct: false,
    official: "Falso: se marcha justo porque no la soporta",
  },
  {
    id: "oliverbenji-campo",
    franchise: "Oliver y Benji",
    emoji: "⚽",
    difficulty: "facil",
    format: "vf",
    prompt: "En Oliver y Benji, cada partido se resuelve en un solo episodio.",
    correct: false,
    official: "Falso: una jugada puede durar episodios enteros",
  },

  // --- Conjuntos ---
  {
    id: "orden-anime-espana",
    franchise: "Anime clásico",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de anime de la más antigua a la más reciente.",
    items: ["Mazinger Z", "Heidi", "Los Caballeros del Zodiaco", "Digimon"],
    official:
      "Mazinger Z (1972), Heidi (1974), Los Caballeros del Zodiaco (1986) y Digimon (1999)",
  },
  {
    id: "relacionar-anime-companeros",
    franchise: "Anime clásico",
    emoji: "🐾",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada protagonista con su compañero.",
    pairs: [
      { left: "Ash", right: "Pikachu" },
      { left: "Nobita", right: "Doraemon" },
      { left: "Tai", right: "Agumon" },
      { left: "Seiya", right: "La armadura de Pegaso" },
    ],
    official:
      "Ash–Pikachu, Nobita–Doraemon, Tai–Agumon y Seiya–la armadura de Pegaso",
  },
  {
    id: "relacionar-anime-frases",
    franchise: "Anime clásico",
    emoji: "💬",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada ataque o lema con su serie.",
    pairs: [
      { left: "Onda vital", right: "Dragon Ball" },
      { left: "Puños fuera", right: "Mazinger Z" },
      { left: "Hazte con todos", right: "Pokémon" },
      { left: "Abuelito, dime tú", right: "Heidi" },
    ],
    official:
      "Onda vital–Dragon Ball, Puños fuera–Mazinger Z, Hazte con todos–Pokémon y Abuelito dime tú–Heidi",
  },
];
