import type { Question } from "../types";

/**
 * Marvel, DC y Spider-Man, en animación. Da igual el estudio: aquí manda el
 * personaje, así que Spider-Verse (Sony) convive con la Patrulla X (Marvel) y
 * con Batman (DC).
 *
 * Los nombres del doblaje de España son media gracia del bloque: Lobezno y no
 * Wolverine, la Patrulla X y no los X-Men, Pícara y no Rogue, Estela Plateada y
 * no Silver Surfer. En latino son otros y no valen.
 */
export const SUPERHEROES: Question[] = [
  // --- La Patrulla X ---
  {
    id: "patrullax-lobezno",
    franchise: "Marvel",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama en España el mutante gruñón de las garras de adamantium?",
    hint: "(Solo el nombre.)",
    accepted: [["Lobezno"]],
    official: "Lobezno",
    note: "En el original es Wolverine; en el doblaje latino, Guepardo.",
  },
  {
    id: "patrullax-xavier",
    franchise: "Marvel",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Quién dirige la escuela donde se forman los mutantes?",
    options: ["El profesor Xavier", "Magneto", "Nick Furia", "Hank Pym"],
    correct: 0,
    official: "El profesor Xavier",
  },
  {
    id: "patrullax-tormenta",
    franchise: "Marvel",
    difficulty: "facil",
    format: "describir",
    prompt: "Mutante de pelo blanco y ojos en blanco que controla el tiempo atmosférico.",
    hint: "(Solo el nombre.)",
    accepted: [["Tormenta", "Storm"]],
    official: "Tormenta",
  },
  {
    id: "patrullax-picara",
    franchise: "Marvel",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama en España la mutante que absorbe los poderes de quien toca?",
    options: ["Pícara", "Rogue", "Tormenta", "Fénix"],
    correct: 0,
    official: "Pícara",
  },
  {
    id: "patrullax-rondador",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el mutante azul con cola que se teletransporta?",
    hint: "(El nombre en España.)",
    accepted: [["Rondador Nocturno", "Rondador"]],
    official: "Rondador Nocturno",
  },
  {
    id: "patrullax-magneto",
    franchise: "Marvel",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el villano que domina el magnetismo y lleva casco morado?",
    hint: "(Solo el nombre.)",
    accepted: [["Magneto"]],
    official: "Magneto",
  },
  {
    id: "patrullax-nombre",
    franchise: "Marvel",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se conoció en España al grupo de mutantes de la escuela de Xavier?",
    options: ["La Patrulla X", "Los Vengadores", "Los Nuevos Mutantes", "La Brigada X"],
    correct: 0,
    official: "La Patrulla X",
  },
  {
    id: "patrullax-relacionar-nombres",
    franchise: "Marvel",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada personaje con el nombre que recibió en España.",
    pairs: [
      { left: "Wolverine", right: "Lobezno" },
      { left: "Rogue", right: "Pícara" },
      { left: "Nightcrawler", right: "Rondador Nocturno" },
      { left: "Silver Surfer", right: "Estela Plateada" },
    ],
    official:
      "Wolverine–Lobezno, Rogue–Pícara, Nightcrawler–Rondador Nocturno y Silver Surfer–Estela Plateada",
  },

  // --- X-Men '97 ---
  {
    id: "xmen97-continuacion",
    franchise: "Marvel",
    difficulty: "facil",
    format: "vf",
    prompt: "X-Men '97 retoma la serie animada de los 90 conservando su estilo y su cabecera.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "xmen97-plataforma",
    franchise: "Marvel",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué plataforma se estrenó X-Men '97?",
    options: ["Disney+", "Netflix", "Prime Video", "HBO Max"],
    correct: 0,
    official: "Disney+",
  },
  {
    id: "xmen97-original",
    franchise: "Marvel",
    difficulty: "media",
    format: "multiple",
    prompt: "¿De qué década es la serie de la Patrulla X que X-Men '97 continúa?",
    options: ["Los noventa", "Los ochenta", "Los dos mil", "Los setenta"],
    correct: 0,
    official: "Los noventa",
  },

  // --- Los Vengadores ---
  {
    id: "marvel-capitan",
    franchise: "Marvel",
    difficulty: "facil",
    format: "describir",
    prompt: "Héroe con un escudo redondo de estrella que pasó décadas congelado en el hielo.",
    hint: "(Solo el nombre.)",
    accepted: [["Capitán América", "Capitan America"]],
    official: "El Capitán América",
  },
  {
    id: "marvel-ironman",
    franchise: "Marvel",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el héroe que es en realidad Tony Stark dentro de una armadura?",
    hint: "(Solo el nombre.)",
    accepted: [["Iron Man", "Ironman", "el Hombre de Hierro"]],
    official: "Iron Man",
  },
  {
    id: "marvel-thor",
    franchise: "Marvel",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el arma de Thor?",
    options: ["Un martillo", "Un hacha", "Una espada", "Un tridente"],
    correct: 0,
    official: "Un martillo, el Mjolnir",
  },
  {
    id: "marvel-hulk-color",
    franchise: "Marvel",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De qué color se pone Bruce Banner cuando se enfada?",
    hint: "(Un color.)",
    accepted: [["verde"]],
    official: "Verde",
  },
  {
    id: "marvel-lamasa",
    franchise: "Marvel",
    difficulty: "media",
    format: "vf",
    prompt: "En España, Hulk se conoció durante años con el nombre de «La Masa».",
    correct: true,
    official: "Verdadero",
  },

  // --- Los 4 Fantásticos ---
  {
    id: "marvel-lacosa",
    franchise: "Marvel",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama en español el miembro de los 4 Fantásticos hecho de roca naranja?",
    options: ["La Cosa", "La Mole", "El Coloso", "La Roca"],
    correct: 0,
    official: "La Cosa",
  },
  {
    id: "marvel-estela",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama en España el héroe plateado que surca el espacio sobre una tabla?",
    hint: "(Dos palabras.)",
    accepted: [["Estela Plateada"]],
    official: "Estela Plateada",
  },

  // --- What If...? ---
  {
    id: "whatif-premisa",
    franchise: "Marvel",
    difficulty: "facil",
    format: "vf",
    prompt: "What If…? cuenta las mismas historias de siempre de Marvel, sin cambiar nada.",
    correct: false,
    official: "Falso: imagina qué habría pasado si los hechos hubieran ido de otra manera",
  },
  {
    id: "whatif-vigilante",
    franchise: "Marvel",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Quién narra los episodios de What If…?",
    options: ["El Vigilante", "Nick Furia", "Stan Lee", "Loki"],
    correct: 0,
    official: "El Vigilante",
  },
  {
    id: "whatif-carter",
    franchise: "Marvel",
    difficulty: "dificil",
    format: "multiple",
    prompt: "En What If…?, ¿en qué se convierte Peggy Carter al tomar ella el suero?",
    options: ["Capitana Carter", "Miss América", "Agente Escudo", "Lady Liberty"],
    correct: 0,
    official: "Capitana Carter",
  },

  // --- Marvel Zombies ---
  {
    id: "marvelzombies-premisa",
    franchise: "Marvel",
    difficulty: "facil",
    format: "vf",
    prompt: "En Marvel Zombies los propios héroes acaban convertidos en zombis.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "marvelzombies-origen",
    franchise: "Marvel",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿De qué serie animada de Marvel salió la idea de Marvel Zombies?",
    options: ["What If…?", "Los Vengadores Unidos", "X-Men '97", "Yo soy Groot"],
    correct: 0,
    official: "De What If…?",
  },

  // --- Moon Girl ---
  {
    id: "moongirl-dinosaurio",
    franchise: "Marvel",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué acompaña a Moon Girl en su serie?",
    options: ["Un dinosaurio rojo", "Un lobo blanco", "Un robot", "Un mapache"],
    correct: 0,
    official: "Un dinosaurio rojo, el Dinosaurio Diabólico",
  },
  {
    id: "moongirl-quien",
    franchise: "Marvel",
    difficulty: "media",
    format: "describir",
    prompt: "Niña superdotada que fabrica inventos en su laboratorio secreto y va con un tiranosaurio.",
    hint: "(Su nombre de heroína.)",
    accepted: [["Moon Girl"]],
    official: "Moon Girl",
  },

  // --- Groot y Hit-Monkey ---
  {
    id: "marvel-groot",
    franchise: "Marvel",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué única frase dice Groot una y otra vez?",
    hint: "(Tres palabras.)",
    accepted: [["Yo soy Groot", "soy Groot"]],
    official: "«Yo soy Groot»",
  },
  {
    id: "marvel-hitmonkey",
    franchise: "Marvel",
    difficulty: "media",
    format: "vf",
    prompt: "Hit-Monkey va de un mono que monta una agencia de detectives en Nueva York.",
    correct: false,
    official: "Falso: es un macaco japonés que se dedica a matar sicarios",
  },
  {
    id: "marvel-orden-series",
    franchise: "Marvel",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de Marvel de la más antigua a la más reciente.",
    items: ["La Patrulla X", "Ultimate Spider-Man", "What If…?", "X-Men '97"],
    official:
      "La Patrulla X (1992), Ultimate Spider-Man (2012), What If…? (2021) y X-Men '97 (2024)",
  },

  // --- Spider-Man ---
  {
    id: "spiderman-lema",
    franchise: "Spider-Man",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el lema de Spider-Man: «Un gran poder conlleva una gran ___».",
    accepted: [["responsabilidad"]],
    official: "Un gran poder conlleva una gran responsabilidad",
  },
  {
    id: "spiderman-tia",
    franchise: "Spider-Man",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la tía que cría a Peter Parker?",
    hint: "(Solo el nombre.)",
    accepted: [["May", "tía May"]],
    official: "La tía May",
  },
  {
    id: "spiderman-duende",
    franchise: "Spider-Man",
    difficulty: "facil",
    format: "describir",
    prompt: "Villano de máscara verde y traje morado que vuela en un planeador y lanza calabazas.",
    hint: "(El nombre en español.)",
    accepted: [["Duende Verde", "el Duende Verde"]],
    official: "El Duende Verde",
  },
  {
    id: "spiderman-veneno",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama en español el simbionte negro que se pega a Peter Parker?",
    options: ["Veneno", "Matanza", "Sombra", "Tinta"],
    correct: 0,
    official: "Veneno",
  },
  {
    id: "spiderman-octopus",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué científico con cuatro brazos mecánicos es enemigo de Spider-Man?",
    options: ["El Doctor Octopus", "El Buitre", "Kraven", "El Lagarto"],
    correct: 0,
    official: "El Doctor Octopus",
  },
  {
    id: "spiderman-ciudad",
    franchise: "Spider-Man",
    difficulty: "facil",
    format: "corta",
    prompt: "¿En qué ciudad se columpia Spider-Man entre rascacielos?",
    hint: "(Una ciudad.)",
    accepted: [["Nueva York", "New York"]],
    official: "Nueva York",
  },
  {
    id: "spiderman-multiverso",
    franchise: "Spider-Man",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se titula la película que continúa Spider-Man: Un nuevo universo?",
    options: [
      "Cruzando el Multiverso",
      "Regreso al Multiverso",
      "Guerra del Multiverso",
      "Otro universo",
    ],
    correct: 0,
    official: "Spider-Man: Cruzando el Multiverso",
  },
  {
    id: "spiderman-cientos",
    franchise: "Spider-Man",
    difficulty: "facil",
    format: "vf",
    prompt: "En Cruzando el Multiverso aparecen cientos de versiones distintas de Spider-Man.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "spiderman-peni",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "corta",
    prompt:
      "En Un nuevo universo, ¿cómo se llama el cerdo con traje de Spider-Man y aires de dibujo animado?",
    hint: "(Dos palabras.)",
    accepted: [["Spider-Ham", "Spiderham", "Peter Porker"]],
    official: "Spider-Ham",
  },
  {
    id: "spiderman-araña",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "vf",
    prompt: "Peter Parker consigue sus poderes por la picadura de un escorpión radiactivo.",
    correct: false,
    official: "Falso: le pica una araña",
  },

  // --- Batman ---
  {
    id: "dc-gotham",
    franchise: "DC",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la ciudad que protege Batman?",
    hint: "(Una palabra.)",
    accepted: [["Gotham"]],
    official: "Gotham",
  },
  {
    id: "dc-joker",
    franchise: "DC",
    difficulty: "facil",
    format: "describir",
    prompt: "Villano de piel blanca, pelo verde y sonrisa permanente, obsesionado con Batman.",
    hint: "(Solo el nombre.)",
    accepted: [["Joker", "el Joker"]],
    official: "El Joker",
  },
  {
    id: "dc-brucewayne",
    franchise: "DC",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es la identidad secreta de Batman?",
    options: ["Bruce Wayne", "Clark Kent", "Oliver Queen", "Hal Jordan"],
    correct: 0,
    official: "Bruce Wayne",
  },
  {
    id: "dc-enigma",
    franchise: "DC",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama en España el villano de las adivinanzas y los interrogantes?",
    options: ["Enigma", "El Acertijo", "El Pingüino", "Espantapájaros"],
    correct: 0,
    official: "Enigma",
  },
  {
    id: "dc-relacionar-ciudades",
    franchise: "DC",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada héroe con el lugar al que pertenece.",
    pairs: [
      { left: "Batman", right: "Gotham" },
      { left: "Superman", right: "Metrópolis" },
      { left: "Aquaman", right: "Atlantis" },
      { left: "Wonder Woman", right: "Themyscira" },
    ],
    official:
      "Batman–Gotham, Superman–Metrópolis, Aquaman–Atlantis y Wonder Woman–Themyscira",
  },
  {
    id: "dc-flash",
    franchise: "DC",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el héroe de rojo que corre a una velocidad imposible?",
    hint: "(Solo el nombre.)",
    accepted: [["Flash", "el Flash"]],
    official: "Flash",
  },
  {
    id: "dc-linterna",
    franchise: "DC",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama en español el héroe cuyo poder sale de un anillo?",
    options: ["Linterna Verde", "Faro Verde", "Anillo Esmeralda", "Green Arrow"],
    correct: 0,
    official: "Linterna Verde",
  },
  {
    id: "dc-batmanfuturo",
    franchise: "DC",
    difficulty: "media",
    format: "multiple",
    prompt: "En Batman del futuro, ¿cómo se llama el joven que hereda el traje?",
    options: ["Terry McGinnis", "Dick Grayson", "Tim Drake", "Jason Todd"],
    correct: 0,
    official: "Terry McGinnis",
  },
  {
    id: "dc-batmanfuturo-bruce",
    franchise: "DC",
    difficulty: "media",
    format: "vf",
    prompt: "En Batman del futuro, Bruce Wayne sigue vivo pero ya anciano, guiando al nuevo Batman.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "dc-titanes-lider",
    franchise: "DC",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Quién lidera a los Jóvenes Titanes?",
    options: ["Robin", "Chico Bestia", "Cyborg", "Raven"],
    correct: 0,
    official: "Robin",
  },
  {
    id: "dc-titanes-starfire",
    franchise: "DC",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la titán alienígena de pelo naranja que vuela?",
    hint: "(Solo el nombre.)",
    accepted: [["Starfire"]],
    official: "Starfire",
  },
  {
    id: "dc-titanes-go",
    franchise: "DC",
    difficulty: "facil",
    format: "vf",
    prompt: "Los Jóvenes Titanes en Acción es una versión más oscura y seria que la serie original.",
    correct: false,
    official: "Falso: es la versión de humor, mucho más gamberra",
  },
  {
    id: "dc-superman-nombre",
    franchise: "DC",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuál es el nombre kryptoniano de Superman?",
    hint: "(Dos sílabas con guion.)",
    accepted: [["Kal-El", "Kal El", "Kalel"]],
    official: "Kal-El",
  },
  {
    id: "dc-kryptonita",
    franchise: "DC",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué mineral deja a Superman sin fuerzas?",
    options: ["La kryptonita", "El vibranium", "El adamantium", "El uranio"],
    correct: 0,
    official: "La kryptonita",
  },
  {
    id: "dc-harley",
    franchise: "DC",
    difficulty: "media",
    format: "describir",
    prompt: "Villana de coletas roja y azul, bate de béisbol y pasado como psiquiatra del Joker.",
    hint: "(Solo el nombre.)",
    accepted: [["Harley Quinn", "Harley"]],
    official: "Harley Quinn",
  },
  {
    id: "dc-harley-origen",
    franchise: "DC",
    difficulty: "media",
    format: "vf",
    prompt: "Harley Quinn nació en la serie animada de Batman, no en los cómics.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "dc-superman-anime",
    franchise: "DC",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Con qué estilo de dibujo está hecha la serie Mis aventuras con Superman?",
    options: ["Estilo anime", "Estilo cómic clásico", "Stop-motion", "Animación por ordenador"],
    correct: 0,
    official: "Estilo anime",
  },
  {
    id: "dc-creature-commandos",
    franchise: "DC",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Quién está detrás de Creature Commandos, la serie que abre el nuevo universo DC?",
    options: ["James Gunn", "Zack Snyder", "Bruce Timm", "Christopher Nolan"],
    correct: 0,
    official: "James Gunn",
  },
  {
    id: "dc-caped-crusader",
    franchise: "DC",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué plataforma se estrenó la serie Batman: El enmascarado?",
    options: ["Prime Video", "Disney+", "Netflix", "HBO Max"],
    correct: 0,
    official: "Prime Video",
  },
  {
    id: "dc-orden-series",
    franchise: "DC",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de DC de la más antigua a la más reciente.",
    items: [
      "Batman: la serie animada",
      "Batman del futuro",
      "La Liga de la Justicia",
      "Los Jóvenes Titanes",
    ],
    official:
      "Batman: la serie animada (1992), Batman del futuro (1999), La Liga de la Justicia (2001) y Los Jóvenes Titanes (2003)",
  },

  // --- Marvel, imagen real: el UCM ---
  {
    id: "ucm-primera",
    franchise: "Marvel",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué año se estrenó Iron Man, la película que abrió el Universo Cinematográfico?",
    options: ["2008", "2005", "2010", "2012"],
    correct: 0,
    official: "En 2008",
  },
  {
    id: "ucm-tony-frase",
    franchise: "Marvel",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa lo que dice Tony Stark al final de la primera película: «Yo soy ___».",
    accepted: [["Iron Man"]],
    official: "Yo soy Iron Man",
  },
  {
    id: "ucm-thanos",
    franchise: "Marvel",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el titán morado que quiere borrar a la mitad del universo?",
    hint: "(Solo el nombre.)",
    accepted: [["Thanos"]],
    official: "Thanos",
  },
  {
    id: "ucm-chasquido",
    franchise: "Marvel",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Con qué gesto hace desaparecer Thanos a la mitad de los seres vivos?",
    options: ["Un chasquido de dedos", "Un aplauso", "Un puñetazo", "Un grito"],
    correct: 0,
    official: "Un chasquido de dedos",
  },
  {
    id: "ucm-gemas",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cuántas Gemas del Infinito hay?",
    hint: "(Un número.)",
    accepted: [["6", "seis"]],
    official: "Seis",
  },
  {
    id: "ucm-guantelete",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "¿En qué objeto engarza Thanos las Gemas del Infinito?",
    hint: "(Una prenda.)",
    accepted: [["guantelete", "un guantelete", "guante", "el guantelete"]],
    official: "En un guantelete",
  },
  {
    id: "ucm-ultron",
    franchise: "Marvel",
    difficulty: "media",
    format: "multiple",
    prompt: "En La era de Ultrón, ¿quién crea sin querer al villano que da título a la película?",
    options: ["Tony Stark", "Bruce Banner solo", "Nick Furia", "Hank Pym"],
    correct: 0,
    official: "Tony Stark, con ayuda de Bruce Banner",
  },
  {
    id: "ucm-vision",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el androide rojo con una gema en la frente que nace en La era de Ultrón?",
    hint: "(Solo el nombre.)",
    accepted: [["Visión", "Vision"]],
    official: "Visión",
  },
  {
    id: "ucm-gemelos",
    franchise: "Marvel",
    difficulty: "media",
    format: "vf",
    prompt: "En La era de Ultrón aparecen por primera vez los hermanos Bruja Escarlata y Mercurio.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "ucm-endgame-tiempo",
    franchise: "Marvel",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el plan de los Vengadores en Endgame para deshacer el chasquido?",
    options: [
      "Viajar en el tiempo a por las Gemas",
      "Fabricar unas gemas nuevas",
      "Revivir a Thanos",
      "Buscar otro universo",
    ],
    correct: 0,
    official: "Viajar en el tiempo a por las Gemas",
  },
  {
    id: "ucm-endgame-final",
    franchise: "Marvel",
    difficulty: "facil",
    format: "vf",
    prompt: "En Endgame, Tony Stark sobrevive al chasquido final y se retira tranquilamente.",
    correct: false,
    official: "Falso: muere al hacerlo él",
  },
  {
    id: "ucm-escudo",
    franchise: "Marvel",
    difficulty: "media",
    format: "multiple",
    prompt: "¿De qué material está hecho el escudo del Capitán América?",
    options: ["Vibranium", "Adamantium", "Titanio", "Uru"],
    correct: 0,
    official: "Vibranium",
  },
  {
    id: "ucm-escudo-final",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "Al final de Endgame, ¿a quién le entrega el Capitán América su escudo?",
    hint: "(Su nombre de héroe.)",
    accepted: [["Falcon", "Sam", "Sam Wilson", "el Halcón"]],
    official: "A Falcon, Sam Wilson",
  },
  {
    id: "ucm-bucky",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se conoce a Bucky Barnes tras ser capturado y manipulado?",
    hint: "(Tres palabras.)",
    accepted: [["Soldado de Invierno", "el Soldado de Invierno"]],
    official: "El Soldado de Invierno",
  },
  {
    id: "ucm-loki",
    franchise: "Marvel",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el hermano adoptivo de Thor, dios del engaño?",
    hint: "(Solo el nombre.)",
    accepted: [["Loki"]],
    official: "Loki",
  },
  {
    id: "ucm-hela",
    franchise: "Marvel",
    difficulty: "dificil",
    format: "multiple",
    prompt: "En Thor: Ragnarok, ¿quién destroza el martillo de Thor con una mano?",
    options: ["Hela", "Surtur", "Loki", "El Gran Maestro"],
    correct: 0,
    official: "Hela",
  },
  {
    id: "ucm-wakanda",
    franchise: "Marvel",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el país africano que gobierna Pantera Negra?",
    hint: "(Una palabra.)",
    accepted: [["Wakanda"]],
    official: "Wakanda",
  },
  {
    id: "ucm-tchalla",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el rey que se esconde tras la máscara de Pantera Negra?",
    hint: "(Solo el nombre.)",
    accepted: [["T'Challa", "TChalla", "Tchalla"]],
    official: "T'Challa",
  },
  {
    id: "ucm-starlord",
    franchise: "Marvel",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se hace llamar Peter Quill, el líder de los Guardianes de la Galaxia?",
    options: ["Star-Lord", "Space-Lord", "Star-Man", "Sky-Lord"],
    correct: 0,
    official: "Star-Lord",
  },
  {
    id: "ucm-rocket",
    franchise: "Marvel",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué animal es Rocket, el guardián que maneja las armas?",
    hint: "(El animal.)",
    accepted: [["mapache", "un mapache"]],
    official: "Un mapache",
  },
  {
    id: "ucm-guardianes-musica",
    franchise: "Marvel",
    difficulty: "media",
    format: "vf",
    prompt: "Star-Lord conserva un walkman con una cinta de canciones que le dejó su madre.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "ucm-strange",
    franchise: "Marvel",
    difficulty: "media",
    format: "multiple",
    prompt: "¿A qué se dedicaba Stephen Strange antes del accidente que le arruina las manos?",
    options: ["Era cirujano", "Era abogado", "Era físico", "Era piloto"],
    correct: 0,
    official: "Era cirujano",
  },
  {
    id: "ucm-antman",
    franchise: "Marvel",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el poder del traje de Ant-Man?",
    options: [
      "Encoger y crecer a voluntad",
      "Volverse invisible",
      "Volar",
      "Multiplicarse",
    ],
    correct: 0,
    official: "Encoger y crecer",
  },
  {
    id: "ucm-viudanegra",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cuál es el nombre real de la Viuda Negra?",
    hint: "(El nombre basta.)",
    accepted: [["Natasha", "Natasha Romanoff", "Romanoff"]],
    official: "Natasha Romanoff",
  },
  {
    id: "ucm-capitanamarvel",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cuál es el nombre real de Capitana Marvel?",
    hint: "(El nombre basta.)",
    accepted: [["Carol", "Carol Danvers", "Danvers"]],
    official: "Carol Danvers",
  },
  {
    id: "ucm-furia",
    franchise: "Marvel",
    difficulty: "facil",
    format: "describir",
    prompt: "Hombre calvo, negro, con gabardina y un parche en el ojo, que recluta a los Vengadores.",
    hint: "(El nombre basta.)",
    accepted: [["Nick Furia", "Furia", "Nick Fury"]],
    official: "Nick Furia",
  },
  {
    id: "ucm-shield",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la agencia secreta que dirige Nick Furia?",
    hint: "(Unas siglas.)",
    accepted: [["SHIELD", "S.H.I.E.L.D."]],
    official: "S.H.I.E.L.D.",
  },
  {
    id: "ucm-stanlee",
    franchise: "Marvel",
    difficulty: "media",
    format: "vf",
    prompt: "Stan Lee, el creador de muchos de estos personajes, aparecía de refilón en casi todas las películas.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "ucm-deadpool",
    franchise: "Marvel",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué hace Deadpool constantemente y casi ningún otro héroe hace?",
    options: [
      "Hablarle directamente al espectador",
      "Volar sin traje",
      "Cambiar de cara",
      "Leer la mente",
    ],
    correct: 0,
    official: "Romper la cuarta pared y hablarle al espectador",
  },
  {
    id: "ucm-hulk-actor",
    franchise: "Marvel",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué actor ha interpretado a Hulk en la mayoría de las películas de los Vengadores?",
    options: ["Mark Ruffalo", "Edward Norton", "Eric Bana", "Chris Evans"],
    correct: 0,
    official: "Mark Ruffalo",
  },
  {
    id: "ucm-ironman-actor",
    franchise: "Marvel",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué actor interpreta a Tony Stark?",
    options: ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Jeremy Renner"],
    correct: 0,
    official: "Robert Downey Jr.",
  },
  {
    id: "ucm-capi-actor",
    franchise: "Marvel",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué actor interpreta al Capitán América?",
    options: ["Chris Evans", "Chris Hemsworth", "Chris Pratt", "Sebastian Stan"],
    correct: 0,
    official: "Chris Evans",
  },
  {
    id: "ucm-thor-actor",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "¿Qué actor australiano interpreta a Thor?",
    hint: "(El apellido basta.)",
    accepted: [["Hemsworth", "Chris Hemsworth"]],
    official: "Chris Hemsworth",
  },
  {
    id: "ucm-wandavision",
    franchise: "Marvel",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué tiene de raro la serie WandaVision?",
    options: [
      "Imita a las comedias de televisión de cada década",
      "Está rodada sin diálogo",
      "Es en blanco y negro entera",
      "Se cuenta al revés",
    ],
    correct: 0,
    official: "Imita a las comedias televisivas de cada década",
  },
  {
    id: "ucm-loki-serie",
    franchise: "Marvel",
    difficulty: "media",
    format: "vf",
    prompt: "En su serie, Loki acaba trabajando para una agencia que vigila el tiempo.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "ucm-mssmarvel",
    franchise: "Marvel",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿De qué origen es Kamala Khan, la protagonista de Ms. Marvel?",
    options: ["Paquistaní", "India", "Egipcia", "Iraní"],
    correct: 0,
    official: "Paquistaní, criada en Nueva Jersey",
  },
  {
    id: "ucm-orden-fases",
    franchise: "Marvel",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Marvel de la más antigua a la más reciente.",
    items: ["Iron Man", "Los Vengadores", "La era de Ultrón", "Endgame"],
    official:
      "Iron Man (2008), Los Vengadores (2012), La era de Ultrón (2015) y Endgame (2019)",
  },
  {
    id: "ucm-orden-guardianes",
    franchise: "Marvel",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Marvel de la más antigua a la más reciente.",
    items: ["Guardianes de la Galaxia", "Pantera Negra", "Viuda Negra", "Deadpool y Lobezno"],
    official:
      "Guardianes de la Galaxia (2014), Pantera Negra (2018), Viuda Negra (2021) y Deadpool y Lobezno (2024)",
  },
  {
    id: "ucm-relacionar-actores",
    franchise: "Marvel",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada actor con el personaje que interpreta.",
    pairs: [
      { left: "Robert Downey Jr.", right: "Iron Man" },
      { left: "Chris Evans", right: "Capitán América" },
      { left: "Scarlett Johansson", right: "Viuda Negra" },
      { left: "Chris Pratt", right: "Star-Lord" },
    ],
    official:
      "Robert Downey Jr.–Iron Man, Chris Evans–Capitán América, Scarlett Johansson–Viuda Negra y Chris Pratt–Star-Lord",
  },
  {
    id: "ucm-relacionar-equipos",
    franchise: "Marvel",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada héroe con su compañero inseparable.",
    pairs: [
      { left: "Rocket", right: "Groot" },
      { left: "Capitán América", right: "El Soldado de Invierno" },
      { left: "Thor", right: "Loki" },
      { left: "Wanda", right: "Visión" },
    ],
    official:
      "Rocket–Groot, el Capitán América–el Soldado de Invierno, Thor–Loki y Wanda–Visión",
  },
  {
    id: "ucm-civilwar",
    franchise: "Marvel",
    difficulty: "media",
    format: "multiple",
    prompt: "En Civil War, ¿qué divide a los Vengadores en dos bandos?",
    options: [
      "Si deben someterse al control de los gobiernos",
      "Un reparto de dinero",
      "La llegada de Thanos",
      "La muerte de Nick Furia",
    ],
    correct: 0,
    official: "Si deben someterse al control de los gobiernos",
  },
  {
    id: "ucm-eternals",
    franchise: "Marvel",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué son los Eternos?",
    options: [
      "Seres inmortales que llevan milenios en la Tierra",
      "Un equipo de mutantes",
      "Robots antiguos",
      "Dioses nórdicos",
    ],
    correct: 0,
    official: "Seres inmortales que llevan milenios en la Tierra",
  },
  {
    id: "ucm-shangchi",
    franchise: "Marvel",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cuál es el arma característica del padre de Shang-Chi?",
    options: ["Diez anillos", "Un bastón", "Dos espadas", "Un látigo"],
    correct: 0,
    official: "Los Diez Anillos",
  },
  {
    id: "ucm-hawkeye",
    franchise: "Marvel",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Con qué arma lucha Ojo de Halcón?",
    hint: "(Un arma.)",
    accepted: [["arco", "el arco", "arco y flechas", "flechas"]],
    official: "Con arco y flechas",
  },
  {
    id: "ucm-vengadores-frase",
    franchise: "Marvel",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa la orden que da el Capitán América en Endgame: «Vengadores… ___».",
    accepted: [["reuníos", "reunios", "uníos", "unios"]],
    official: "Vengadores, reuníos",
  },
  {
    id: "ucm-mjolnir-capi",
    franchise: "Marvel",
    difficulty: "media",
    format: "vf",
    prompt: "En Endgame, el Capitán América consigue levantar el martillo de Thor.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "ucm-hulk-transformacion",
    franchise: "Marvel",
    difficulty: "facil",
    format: "vf",
    prompt: "Bruce Banner se transforma en Hulk cuando se queda tranquilo y relajado.",
    correct: false,
    official: "Falso: se transforma al enfadarse",
  },
  {
    id: "ucm-xmen-fox",
    franchise: "Marvel",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué actor interpretó a Lobezno durante casi veinte años en el cine?",
    options: ["Hugh Jackman", "Liev Schreiber", "Ryan Reynolds", "James Marsden"],
    correct: 0,
    official: "Hugh Jackman",
  },
  {
    id: "ucm-groot-actor",
    franchise: "Marvel",
    difficulty: "media",
    format: "vf",
    prompt: "Groot y Rocket están hechos por ordenador, no son actores disfrazados.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "ucm-thanos-hija",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la guardiana de piel verde que es hija adoptiva de Thanos?",
    hint: "(Solo el nombre.)",
    accepted: [["Gamora"]],
    official: "Gamora",
  },
  {
    id: "ucm-escenas-postcreditos",
    franchise: "Marvel",
    difficulty: "facil",
    format: "vf",
    prompt: "Las películas de Marvel tienen escenas escondidas después de los títulos de crédito.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "ucm-torre",
    franchise: "Marvel",
    difficulty: "media",
    format: "vf",
    prompt: "La torre de los Vengadores en Nueva York era antes la Torre Wayne.",
    correct: false,
    official: "Falso: era la Torre Stark; la Wayne es de Batman, que es de DC",
  },
  {
    id: "ucm-jarvis",
    franchise: "Marvel",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la inteligencia artificial que asiste a Tony Stark?",
    hint: "(Solo el nombre.)",
    accepted: [["JARVIS", "Jarvis"]],
    official: "JARVIS",
  },
  {
    id: "ucm-drax",
    franchise: "Marvel",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué le pasa a Drax con las metáforas?",
    options: [
      "Se las toma todas al pie de la letra",
      "No las entiende y se enfada",
      "Las inventa sin parar",
      "Las traduce mal",
    ],
    correct: 0,
    official: "Se las toma literalmente",
  },
  {
    id: "ucm-pelicula-oscar",
    franchise: "Marvel",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué película de Marvel fue la primera de superhéroes nominada al Óscar a mejor película?",
    options: ["Pantera Negra", "Endgame", "Los Vengadores", "Iron Man"],
    correct: 0,
    official: "Pantera Negra",
  },

  // --- DC, imagen real ---
  {
    id: "dcreal-nolan-actor",
    franchise: "DC",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué actor fue Batman en la trilogía de Christopher Nolan?",
    options: ["Christian Bale", "Michael Keaton", "Ben Affleck", "Robert Pattinson"],
    correct: 0,
    official: "Christian Bale",
  },
  {
    id: "dcreal-ledger",
    franchise: "DC",
    difficulty: "media",
    format: "corta",
    prompt: "¿Qué actor ganó un Óscar póstumo por interpretar al Joker en El caballero oscuro?",
    hint: "(El apellido basta.)",
    accepted: [["Heath Ledger", "Ledger"]],
    official: "Heath Ledger",
  },
  {
    id: "dcreal-bane",
    franchise: "DC",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el villano de la máscara que le parte la espalda a Batman en la tercera de Nolan?",
    options: ["Bane", "Ra's al Ghul", "El Espantapájaros", "Dos Caras"],
    correct: 0,
    official: "Bane",
  },
  {
    id: "dcreal-joker-phoenix",
    franchise: "DC",
    difficulty: "media",
    format: "vf",
    prompt: "La película Joker de 2019 le dio un Óscar a Joaquin Phoenix.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "dcreal-pattinson",
    franchise: "DC",
    difficulty: "media",
    format: "corta",
    prompt: "¿Qué actor protagoniza The Batman de 2022?",
    hint: "(El apellido basta.)",
    accepted: [["Pattinson", "Robert Pattinson"]],
    official: "Robert Pattinson",
  },
  {
    id: "dcreal-keaton",
    franchise: "DC",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué director hizo el Batman de 1989 con Michael Keaton?",
    options: ["Tim Burton", "Christopher Nolan", "Zack Snyder", "Joel Schumacher"],
    correct: 0,
    official: "Tim Burton",
  },
  {
    id: "dcreal-nicholson",
    franchise: "DC",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué actor hizo del Joker en el Batman de 1989?",
    options: ["Jack Nicholson", "Jim Carrey", "Danny DeVito", "Tommy Lee Jones"],
    correct: 0,
    official: "Jack Nicholson",
  },
  {
    id: "dcreal-superman-cavill",
    franchise: "DC",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué actor interpretó a Superman en El hombre de acero?",
    options: ["Henry Cavill", "Brandon Routh", "Christopher Reeve", "Tyler Hoechlin"],
    correct: 0,
    official: "Henry Cavill",
  },
  {
    id: "dcreal-superman-reeve",
    franchise: "DC",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Quién fue el Superman de las películas de los años setenta y ochenta?",
    options: ["Christopher Reeve", "Henry Cavill", "Brandon Routh", "George Reeves"],
    correct: 0,
    official: "Christopher Reeve",
  },
  {
    id: "dcreal-wonderwoman",
    franchise: "DC",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué actriz israelí interpreta a Wonder Woman en el cine?",
    hint: "(El nombre basta.)",
    accepted: [["Gal Gadot", "Gadot"]],
    official: "Gal Gadot",
  },
  {
    id: "dcreal-lazo",
    franchise: "DC",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué hace el lazo de Wonder Woman?",
    options: [
      "Obliga a decir la verdad",
      "Da fuerza infinita",
      "Vuelve invisible",
      "Cura heridas",
    ],
    correct: 0,
    official: "Obliga a decir la verdad",
  },
  {
    id: "dcreal-aquaman",
    franchise: "DC",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué actor interpreta a Aquaman?",
    options: ["Jason Momoa", "Jason Statham", "Chris Hemsworth", "Ben Affleck"],
    correct: 0,
    official: "Jason Momoa",
  },
  {
    id: "dcreal-harley-robbie",
    franchise: "DC",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué actriz australiana interpreta a Harley Quinn en el cine?",
    hint: "(El nombre basta.)",
    accepted: [["Margot Robbie", "Robbie", "Margot"]],
    official: "Margot Robbie",
  },
  {
    id: "dcreal-escuadron",
    franchise: "DC",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Quiénes forman el Escuadrón Suicida?",
    options: [
      "Villanos encarcelados obligados a hacer misiones",
      "Un cuerpo especial del ejército",
      "Héroes retirados",
      "Científicos",
    ],
    correct: 0,
    official: "Villanos encarcelados a los que obligan a hacer misiones",
  },
  {
    id: "dcreal-shazam",
    franchise: "DC",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué tiene de particular Shazam?",
    options: [
      "Es un niño que se transforma en un héroe adulto",
      "Es un robot",
      "Es un extraterrestre",
      "Es inmortal desde niño",
    ],
    correct: 0,
    official: "Es un niño que al decir la palabra mágica se convierte en un héroe adulto",
  },
  {
    id: "dcreal-batman-superman",
    franchise: "DC",
    difficulty: "media",
    format: "vf",
    prompt: "Batman y Superman llegaron a enfrentarse en una película que llevaba su duelo en el título.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "dcreal-smallville",
    franchise: "DC",
    difficulty: "media",
    format: "multiple",
    prompt: "¿De qué trata la serie Smallville?",
    options: [
      "De la juventud de Superman antes de serlo",
      "De la juventud de Batman",
      "De una ciudad sin héroes",
      "De los villanos de Metrópolis",
    ],
    correct: 0,
    official: "De la juventud de Clark Kent antes de ser Superman",
  },
  {
    id: "dcreal-arrow",
    franchise: "DC",
    difficulty: "media",
    format: "vf",
    prompt: "Arrow fue una serie aislada que no dio pie a ninguna otra de DC en televisión.",
    correct: false,
    official: "Falso: de ella salió todo un universo de series",
  },
  {
    id: "dcreal-gotham-serie",
    franchise: "DC",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿A quién sigue la serie Gotham?",
    options: [
      "Al comisario Gordon antes de que exista Batman",
      "A Batman de joven",
      "Al Joker",
      "A Alfred",
    ],
    correct: 0,
    official: "Al policía James Gordon, antes de que exista Batman",
  },
  {
    id: "dcreal-orden-batman",
    franchise: "DC",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Batman de la más antigua a la más reciente.",
    items: ["Batman (de Tim Burton)", "Batman Begins", "El caballero oscuro", "The Batman"],
    official:
      "Batman (1989), Batman Begins (2005), El caballero oscuro (2008) y The Batman (2022)",
  },
  {
    id: "dcreal-relacionar-actores",
    franchise: "DC",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada actor con el personaje de DC que interpretó.",
    pairs: [
      { left: "Heath Ledger", right: "El Joker" },
      { left: "Gal Gadot", right: "Wonder Woman" },
      { left: "Jason Momoa", right: "Aquaman" },
      { left: "Margot Robbie", right: "Harley Quinn" },
    ],
    official:
      "Heath Ledger–el Joker, Gal Gadot–Wonder Woman, Jason Momoa–Aquaman y Margot Robbie–Harley Quinn",
  },
  {
    id: "dcreal-alfred",
    franchise: "DC",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el mayordomo que cría a Bruce Wayne?",
    hint: "(Solo el nombre.)",
    accepted: [["Alfred"]],
    official: "Alfred",
  },
  {
    id: "dcreal-baticueva",
    franchise: "DC",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el escondite subterráneo de Batman?",
    hint: "(Una palabra.)",
    accepted: [["baticueva", "la baticueva", "batcueva"]],
    official: "La baticueva",
  },
  {
    id: "dcreal-padres",
    franchise: "DC",
    difficulty: "facil",
    format: "vf",
    prompt: "Bruce Wayne se hace Batman después de ver cómo asesinan a sus padres siendo niño.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "dcreal-superman-planeta",
    franchise: "DC",
    difficulty: "media",
    format: "corta",
    prompt: "¿De qué planeta viene Superman?",
    hint: "(Una palabra.)",
    accepted: [["Krypton", "Kriptón", "Cripton"]],
    official: "Krypton",
  },
  {
    id: "dcreal-loislane",
    franchise: "DC",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la periodista de la que se enamora Clark Kent?",
    hint: "(El nombre basta.)",
    accepted: [["Lois", "Lois Lane", "Lane"]],
    official: "Lois Lane",
  },
  {
    id: "dcreal-luthor",
    franchise: "DC",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el empresario calvo que es el gran enemigo de Superman?",
    hint: "(El nombre basta.)",
    accepted: [["Lex Luthor", "Luthor", "Lex"]],
    official: "Lex Luthor",
  },
  {
    id: "dcreal-periodico",
    franchise: "DC",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué periódico trabaja Clark Kent?",
    options: ["El Planeta", "La Gaceta de Gotham", "El Heraldo", "El Faro"],
    correct: 0,
    official: "En El Planeta, el Daily Planet",
  },
  {
    id: "dcreal-liga",
    franchise: "DC",
    difficulty: "facil",
    format: "vf",
    prompt: "Batman, Superman, Wonder Woman, Flash y Aquaman forman la Liga de la Justicia.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "dcreal-catwoman",
    franchise: "DC",
    difficulty: "media",
    format: "describir",
    prompt: "Ladrona con traje de cuero negro y látigo, entre enemiga y aliada de Batman.",
    hint: "(Su nombre de villana.)",
    accepted: [["Catwoman", "Gatúbela"]],
    official: "Catwoman",
  },
  {
    id: "dcreal-pinguino",
    franchise: "DC",
    difficulty: "media",
    format: "corta",
    prompt: "¿Qué villano de Batman va con paraguas y monóculo, y toma el nombre de un ave?",
    hint: "(Un animal.)",
    accepted: [["Pingüino", "el Pingüino", "pinguino"]],
    official: "El Pingüino",
  },
  {
    id: "dcreal-doscaras",
    franchise: "DC",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Con qué decide sus actos el villano Dos Caras?",
    options: ["Lanzando una moneda", "Tirando los dados", "Con cartas", "A suertes con una ruleta"],
    correct: 0,
    official: "Lanzando una moneda",
  },
  {
    id: "dcreal-flash-poder",
    franchise: "DC",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el poder de Flash?",
    options: ["La supervelocidad", "La superfuerza", "Volar", "Leer la mente"],
    correct: 0,
    official: "La supervelocidad",
  },
  {
    id: "dcreal-robin",
    franchise: "DC",
    difficulty: "facil",
    format: "vf",
    prompt: "Robin es el ayudante de Superman.",
    correct: false,
    official: "Falso: es el de Batman",
  },
  {
    id: "dcreal-gafas",
    franchise: "DC",
    difficulty: "facil",
    format: "vf",
    prompt: "Para pasar por humano, Superman se pone una máscara que le tapa media cara.",
    correct: false,
    official: "Falso: todo su disfraz son unas gafas y un peinado distinto",
  },
  {
    id: "dcreal-marvel-dc",
    franchise: "DC",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuál de estos personajes NO es de DC?",
    options: ["Iron Man", "Batman", "Wonder Woman", "Flash"],
    correct: 0,
    official: "Iron Man, que es de Marvel",
  },
  {
    id: "dcreal-affleck",
    franchise: "DC",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué actor fue Batman en Batman v Superman y en la Liga de la Justicia?",
    options: ["Ben Affleck", "Christian Bale", "Michael Keaton", "Val Kilmer"],
    correct: 0,
    official: "Ben Affleck",
  },

  // --- Spider-Man, imagen real ---
  {
    id: "spiderreal-maguire",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué actor fue el primer Spider-Man del cine moderno, en 2002?",
    options: ["Tobey Maguire", "Andrew Garfield", "Tom Holland", "Jake Gyllenhaal"],
    correct: 0,
    official: "Tobey Maguire",
  },
  {
    id: "spiderreal-garfield",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué actor protagonizó The Amazing Spider-Man?",
    options: ["Andrew Garfield", "Tobey Maguire", "Tom Holland", "Chris Evans"],
    correct: 0,
    official: "Andrew Garfield",
  },
  {
    id: "spiderreal-holland",
    franchise: "Spider-Man",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué actor hace de Spider-Man en las películas de Marvel?",
    hint: "(El apellido basta.)",
    accepted: [["Tom Holland", "Holland"]],
    official: "Tom Holland",
  },
  {
    id: "spiderreal-tres",
    franchise: "Spider-Man",
    difficulty: "facil",
    format: "vf",
    prompt: "En No Way Home aparecen juntos los tres actores que han hecho de Spider-Man.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "spiderreal-beso",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo es el beso más famoso de la primera película de Raimi?",
    options: [
      "Colgado boca abajo bajo la lluvia",
      "En lo alto de un puente",
      "En una azotea al amanecer",
      "Dentro de un taxi",
    ],
    correct: 0,
    official: "Colgado boca abajo, bajo la lluvia",
  },
  {
    id: "spiderreal-maryjane",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la pelirroja de la que Peter está enamorado en las de Raimi?",
    hint: "(El nombre basta.)",
    accepted: [["Mary Jane", "MJ", "Mary Jane Watson"]],
    official: "Mary Jane",
  },
  {
    id: "spiderreal-tio",
    franchise: "Spider-Man",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el tío de Peter, cuya muerte le enseña la lección de su vida?",
    hint: "(Solo el nombre.)",
    accepted: [["Ben", "tío Ben"]],
    official: "El tío Ben",
  },
  {
    id: "spiderreal-lagarto",
    franchise: "Spider-Man",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cuál es el villano de The Amazing Spider-Man con Andrew Garfield?",
    options: ["El Lagarto", "El Buitre", "Electro", "Rhino"],
    correct: 0,
    official: "El Lagarto",
  },
  {
    id: "spiderreal-mysterio",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Quién es el villano de Spider-Man: Lejos de casa?",
    options: ["Mysterio", "El Buitre", "Electro", "Kraven"],
    correct: 0,
    official: "Mysterio",
  },
  {
    id: "spiderreal-venom-actor",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "corta",
    prompt: "¿Qué actor protagoniza las películas de Venom?",
    hint: "(El apellido basta.)",
    accepted: [["Tom Hardy", "Hardy"]],
    official: "Tom Hardy",
  },
  {
    id: "spiderreal-telarañas",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "vf",
    prompt: "En las películas de Tobey Maguire, las telarañas le salen del cuerpo, no de un aparato.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "spiderreal-instituto",
    franchise: "Spider-Man",
    difficulty: "facil",
    format: "vf",
    prompt: "El Spider-Man de Tom Holland es un adulto con trabajo fijo cuando lo conocemos.",
    correct: false,
    official: "Falso: es un adolescente que va al instituto",
  },
  {
    id: "spiderreal-stark",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "vf",
    prompt: "En el cine de Marvel, Tony Stark hace de mentor del joven Peter Parker.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "spiderreal-orden",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas películas de Spider-Man de la más antigua a la más reciente.",
    items: [
      "Spider-Man (de Sam Raimi)",
      "The Amazing Spider-Man",
      "Spider-Man: Homecoming",
      "Spider-Man: No Way Home",
    ],
    official:
      "Spider-Man (2002), The Amazing Spider-Man (2012), Homecoming (2017) y No Way Home (2021)",
  },
  {
    id: "spiderreal-relacionar-actores",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada actor con la etapa de Spider-Man que protagonizó.",
    pairs: [
      { left: "Tobey Maguire", right: "La trilogía de Sam Raimi" },
      { left: "Andrew Garfield", right: "The Amazing Spider-Man" },
      { left: "Tom Holland", right: "Las de Marvel" },
      { left: "Tom Hardy", right: "Venom" },
    ],
    official:
      "Tobey Maguire–la trilogía de Raimi, Andrew Garfield–The Amazing Spider-Man, Tom Holland–las de Marvel y Tom Hardy–Venom",
  },
  {
    id: "spiderreal-jonah",
    franchise: "Spider-Man",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el director del periódico que odia a Spider-Man?",
    options: ["J. Jonah Jameson", "Ben Urich", "Joe Robertson", "Eddie Brock"],
    correct: 0,
    official: "J. Jonah Jameson",
  },
  {
    id: "spiderreal-fotografo",
    franchise: "Spider-Man",
    difficulty: "media",
    format: "multiple",
    prompt: "¿De qué trabaja Peter Parker en las películas de Raimi?",
    options: ["De fotógrafo de prensa", "De camarero", "De científico", "De profesor"],
    correct: 0,
    official: "De fotógrafo de prensa",
  },
];
