import type { Question } from "../types";

/**
 * Marvel, DC y Spider-Man, en animación. Da igual el estudio: aquí manda el
 * personaje, así que Spider-Verse (Sony) convive con la Patrulla X (Marvel) y
 * con Batman (DC).
 *
 * Los nombres del doblaje de España son media gracia del bloque: Lobezno y no
 * Wolverine, la Patrulla X y no los X-Men, Pícara y no Rogue, Estela Plateada y
 * no Silver Surfer. En latino son otros y no valen.
 */
export const SUPERHEROES: Question[] = [
  // --- La Patrulla X ---
  {
    id: "patrullax-lobezno",
    franchise: "Marvel",
    emoji: "🐾",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama en España el mutante gruñón de las garras de adamantium?",
    hint: "(Solo el nombre.)",
    accepted: [["Lobezno"]],
    official: "Lobezno",
    note: "En el original es Wolverine; en el doblaje latino, Guepardo.",
  },
  {
    id: "patrullax-xavier",
    franchise: "Marvel",
    emoji: "🧠",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Quién dirige la escuela donde se forman los mutantes?",
    options: ["El profesor Xavier", "Magneto", "Nick Furia", "Hank Pym"],
    correct: 0,
    official: "El profesor Xavier",
  },
  {
    id: "patrullax-tormenta",
    franchise: "Marvel",
    emoji: "⛈️",
    difficulty: "facil",
    format: "describir",
    prompt: "Mutante de pelo blanco y ojos en blanco que controla el tiempo atmosférico.",
    hint: "(Solo el nombre.)",
    accepted: [["Tormenta", "Storm"]],
    official: "Tormenta",
  },
  {
    id: "patrullax-picara",
    franchise: "Marvel",
    emoji: "🧤",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama en España la mutante que absorbe los poderes de quien toca?",
    options: ["Pícara", "Rogue", "Tormenta", "Fénix"],
    correct: 0,
    official: "Pícara",
  },
  {
    id: "patrullax-rondador",
    franchise: "Marvel",
    emoji: "💨",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el mutante azul con cola que se teletransporta?",
    hint: "(El nombre en España.)",
    accepted: [["Rondador Nocturno", "Rondador"]],
    official: "Rondador Nocturno",
  },
  {
    id: "patrullax-magneto",
    franchise: "Marvel",
    emoji: "🧲",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el villano que domina el magnetismo y lleva casco morado?",
    hint: "(Solo el nombre.)",
    accepted: [["Magneto"]],
    official: "Magneto",
  },
  {
    id: "patrullax-nombre",
    franchise: "Marvel",
    emoji: "❌",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se conoció en España al grupo de mutantes de la escuela de Xavier?",
    options: ["La Patrulla X", "Los Vengadores", "Los Nuevos Mutantes", "La Brigada X"],
    correct: 0,
    official: "La Patrulla X",
  },
  {
    id: "patrullax-relacionar-nombres",
    franchise: "Marvel",
    emoji: "🔤",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada personaje con el nombre que recibió en España.",
    pairs: [
      { left: "Wolverine", right: "Lobezno" },
      { left: "Rogue", right: "Pícara" },
      { left: "Nightcrawler", right: "Rondador Nocturno" },
      { left: "Silver Surfer", right: "Estela Plateada" },
    ],
    official:
      "Wolverine–Lobezno, Rogue–Pícara, Nightcrawler–Rondador Nocturno y Silver Surfer–Estela Plateada",
  },

  // --- X-Men '97 ---
  {
    id: "xmen97-continuacion",
    franchise: "Marvel",
    emoji: "📺",
    difficulty: "facil",
    format: "vf",
    prompt: "X-Men '97 retoma la serie animada de los 90 conservando su estilo y su cabecera.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "xmen97-plataforma",
    franchise: "Marvel",
    emoji: "📺",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué plataforma se estrenó X-Men '97?",
    options: ["Disney+", "Netflix", "Prime Video", "HBO Max"],
    correct: 0,
    official: "Disney+",
  },
  {
    id: "xmen97-original",
    franchise: "Marvel",
    emoji: "📺",
    difficulty: "media",
    format: "multiple",
    prompt: "¿De qué década es la serie de la Patrulla X que X-Men '97 continúa?",
    options: ["Los noventa", "Los ochenta", "Los dos mil", "Los setenta"],
    correct: 0,
    official: "Los noventa",
  },

  // --- Los Vengadores ---
  {
    id: "marvel-capitan",
    franchise: "Marvel",
    emoji: "🛡️",
    difficulty: "facil",
    format: "describir",
    prompt: "Héroe con un escudo redondo de estrella que pasó décadas congelado en el hielo.",
    hint: "(Solo el nombre.)",
    accepted: [["Capitán América", "Capitan America"]],
    official: "El Capitán América",
  },
  {
    id: "marvel-ironman",
    franchise: "Marvel",
    emoji: "🤖",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el héroe que es en realidad Tony Stark dentro de una armadura?",
    hint: "(Solo el nombre.)",
    accepted: [["Iron Man", "Ironman", "el Hombre de Hierro"]],
    official: "Iron Man",
  },
  {
    id: "marvel-thor",
    franchise: "Marvel",
    emoji: "🔨",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el arma de Thor?",
    options: ["Un martillo", "Un hacha", "Una espada", "Un tridente"],
    correct: 0,
    official: "Un martillo, el Mjolnir",
  },
  {
    id: "marvel-hulk-color",
    franchise: "Marvel",
    emoji: "💚",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De qué color se pone Bruce Banner cuando se enfada?",
    hint: "(Un color.)",
    accepted: [["verde"]],
    official: "Verde",
  },
  {
    id: "marvel-lamasa",
    franchise: "Marvel",
    emoji: "💚",
    difficulty: "media",
    format: "vf",
    prompt: "En España, Hulk se conoció durante años con el nombre de «La Masa».",
    correct: true,
    official: "Verdadero",
  },

  // --- Los 4 Fantásticos ---
  {
    id: "marvel-lacosa",
    franchise: "Marvel",
    emoji: "🧡",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama en español el miembro de los 4 Fantásticos hecho de roca naranja?",
    options: ["La Cosa", "La Mole", "El Coloso", "La Roca"],
    correct: 0,
    official: "La Cosa",
  },
  {
    id: "marvel-estela",
    franchise: "Marvel",
    emoji: "🏄",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama en España el héroe plateado que surca el espacio sobre una tabla?",
    hint: "(Dos palabras.)",
    accepted: [["Estela Plateada"]],
    official: "Estela Plateada",
  },

  // --- What If...? ---
  {
    id: "whatif-premisa",
    franchise: "Marvel",
    emoji: "❓",
    difficulty: "facil",
    format: "vf",
    prompt: "What If…? cuenta las mismas historias de siempre de Marvel, sin cambiar nada.",
    correct: false,
    official: "Falso: imagina qué habría pasado si los hechos hubieran ido de otra manera",
  },
  {
    id: "whatif-vigilante",
    franchise: "Marvel",
    emoji: "👁️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Quién narra los episodios de What If…?",
    options: ["El Vigilante", "Nick Furia", "Stan Lee", "Loki"],
    correct: 0,
    official: "El Vigilante",
  },
  {
    id: "whatif-carter",
    franchise: "Marvel",
    emoji: "❓",
    difficulty: "dificil",
    format: "multiple",
    prompt: "En What If…?, ¿en qué se convierte Peggy Carter al tomar ella el suero?",
    options: ["Capitana Carter", "Miss América", "Agente Escudo", "Lady Liberty"],
    correct: 0,
    official: "Capitana Carter",
  },

  // --- Marvel Zombies ---
  {
    id: "marvelzombies-premisa",
    franchise: "Marvel",
    emoji: "🧟",
    difficulty: "facil",
    format: "vf",
    prompt: "En Marvel Zombies los propios héroes acaban convertidos en zombis.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "marvelzombies-origen",
    franchise: "Marvel",
    emoji: "🧟",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿De qué serie animada de Marvel salió la idea de Marvel Zombies?",
    options: ["What If…?", "Los Vengadores Unidos", "X-Men '97", "Yo soy Groot"],
    correct: 0,
    official: "De What If…?",
  },

  // --- Moon Girl ---
  {
    id: "moongirl-dinosaurio",
    franchise: "Marvel",
    emoji: "🦖",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué acompaña a Moon Girl en su serie?",
    options: ["Un dinosaurio rojo", "Un lobo blanco", "Un robot", "Un mapache"],
    correct: 0,
    official: "Un dinosaurio rojo, el Dinosaurio Diabólico",
  },
  {
    id: "moongirl-quien",
    franchise: "Marvel",
    emoji: "🌙",
    difficulty: "media",
    format: "describir",
    prompt: "Niña superdotada que fabrica inventos en su laboratorio secreto y va con un tiranosaurio.",
    hint: "(Su nombre de heroína.)",
    accepted: [["Moon Girl"]],
    official: "Moon Girl",
  },

  // --- Groot y Hit-Monkey ---
  {
    id: "marvel-groot",
    franchise: "Marvel",
    emoji: "🌱",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué única frase dice Groot una y otra vez?",
    hint: "(Tres palabras.)",
    accepted: [["Yo soy Groot", "soy Groot"]],
    official: "«Yo soy Groot»",
  },
  {
    id: "marvel-hitmonkey",
    franchise: "Marvel",
    emoji: "🐒",
    difficulty: "media",
    format: "vf",
    prompt: "Hit-Monkey va de un mono que monta una agencia de detectives en Nueva York.",
    correct: false,
    official: "Falso: es un macaco japonés que se dedica a matar sicarios",
  },
  {
    id: "marvel-orden-series",
    franchise: "Marvel",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de Marvel de la más antigua a la más reciente.",
    items: ["La Patrulla X", "Ultimate Spider-Man", "What If…?", "X-Men '97"],
    official:
      "La Patrulla X (1992), Ultimate Spider-Man (2012), What If…? (2021) y X-Men '97 (2024)",
  },

  // --- Spider-Man ---
  {
    id: "spiderman-lema",
    franchise: "Spider-Man",
    emoji: "🕷️",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el lema de Spider-Man: «Un gran poder conlleva una gran ___».",
    accepted: [["responsabilidad"]],
    official: "Un gran poder conlleva una gran responsabilidad",
  },
  {
    id: "spiderman-tia",
    franchise: "Spider-Man",
    emoji: "🕷️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la tía que cría a Peter Parker?",
    hint: "(Solo el nombre.)",
    accepted: [["May", "tía May"]],
    official: "La tía May",
  },
  {
    id: "spiderman-duende",
    franchise: "Spider-Man",
    emoji: "🎃",
    difficulty: "facil",
    format: "describir",
    prompt: "Villano de máscara verde y traje morado que vuela en un planeador y lanza calabazas.",
    hint: "(El nombre en español.)",
    accepted: [["Duende Verde", "el Duende Verde"]],
    official: "El Duende Verde",
  },
  {
    id: "spiderman-veneno",
    franchise: "Spider-Man",
    emoji: "🖤",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama en español el simbionte negro que se pega a Peter Parker?",
    options: ["Veneno", "Matanza", "Sombra", "Tinta"],
    correct: 0,
    official: "Veneno",
  },
  {
    id: "spiderman-octopus",
    franchise: "Spider-Man",
    emoji: "🐙",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué científico con cuatro brazos mecánicos es enemigo de Spider-Man?",
    options: ["El Doctor Octopus", "El Buitre", "Kraven", "El Lagarto"],
    correct: 0,
    official: "El Doctor Octopus",
  },
  {
    id: "spiderman-ciudad",
    franchise: "Spider-Man",
    emoji: "🏙️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿En qué ciudad se columpia Spider-Man entre rascacielos?",
    hint: "(Una ciudad.)",
    accepted: [["Nueva York", "New York"]],
    official: "Nueva York",
  },
  {
    id: "spiderman-multiverso",
    franchise: "Spider-Man",
    emoji: "🕸️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se titula la película que continúa Spider-Man: Un nuevo universo?",
    options: [
      "Cruzando el Multiverso",
      "Regreso al Multiverso",
      "Guerra del Multiverso",
      "Otro universo",
    ],
    correct: 0,
    official: "Spider-Man: Cruzando el Multiverso",
  },
  {
    id: "spiderman-cientos",
    franchise: "Spider-Man",
    emoji: "🕸️",
    difficulty: "facil",
    format: "vf",
    prompt: "En Cruzando el Multiverso aparecen cientos de versiones distintas de Spider-Man.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "spiderman-peni",
    franchise: "Spider-Man",
    emoji: "🤖",
    difficulty: "media",
    format: "corta",
    prompt:
      "En Un nuevo universo, ¿cómo se llama el cerdo con traje de Spider-Man y aires de dibujo animado?",
    hint: "(Dos palabras.)",
    accepted: [["Spider-Ham", "Spiderham", "Peter Porker"]],
    official: "Spider-Ham",
  },
  {
    id: "spiderman-araña",
    franchise: "Spider-Man",
    emoji: "🕷️",
    difficulty: "media",
    format: "vf",
    prompt: "Peter Parker consigue sus poderes por la picadura de un escorpión radiactivo.",
    correct: false,
    official: "Falso: le pica una araña",
  },

  // --- Batman ---
  {
    id: "dc-gotham",
    franchise: "DC",
    emoji: "🦇",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la ciudad que protege Batman?",
    hint: "(Una palabra.)",
    accepted: [["Gotham"]],
    official: "Gotham",
  },
  {
    id: "dc-joker",
    franchise: "DC",
    emoji: "🃏",
    difficulty: "facil",
    format: "describir",
    prompt: "Villano de piel blanca, pelo verde y sonrisa permanente, obsesionado con Batman.",
    hint: "(Solo el nombre.)",
    accepted: [["Joker", "el Joker"]],
    official: "El Joker",
  },
  {
    id: "dc-brucewayne",
    franchise: "DC",
    emoji: "🦇",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es la identidad secreta de Batman?",
    options: ["Bruce Wayne", "Clark Kent", "Oliver Queen", "Hal Jordan"],
    correct: 0,
    official: "Bruce Wayne",
  },
  {
    id: "dc-enigma",
    franchise: "DC",
    emoji: "❓",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama en España el villano de las adivinanzas y los interrogantes?",
    options: ["Enigma", "El Acertijo", "El Pingüino", "Espantapájaros"],
    correct: 0,
    official: "Enigma",
  },
  {
    id: "dc-relacionar-ciudades",
    franchise: "DC",
    emoji: "🗺️",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada héroe con el lugar al que pertenece.",
    pairs: [
      { left: "Batman", right: "Gotham" },
      { left: "Superman", right: "Metrópolis" },
      { left: "Aquaman", right: "Atlantis" },
      { left: "Wonder Woman", right: "Themyscira" },
    ],
    official:
      "Batman–Gotham, Superman–Metrópolis, Aquaman–Atlantis y Wonder Woman–Themyscira",
  },
  {
    id: "dc-flash",
    franchise: "DC",
    emoji: "⚡",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el héroe de rojo que corre a una velocidad imposible?",
    hint: "(Solo el nombre.)",
    accepted: [["Flash", "el Flash"]],
    official: "Flash",
  },
  {
    id: "dc-linterna",
    franchise: "DC",
    emoji: "💚",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama en español el héroe cuyo poder sale de un anillo?",
    options: ["Linterna Verde", "Faro Verde", "Anillo Esmeralda", "Green Arrow"],
    correct: 0,
    official: "Linterna Verde",
  },
  {
    id: "dc-batmanfuturo",
    franchise: "DC",
    emoji: "🦇",
    difficulty: "media",
    format: "multiple",
    prompt: "En Batman del futuro, ¿cómo se llama el joven que hereda el traje?",
    options: ["Terry McGinnis", "Dick Grayson", "Tim Drake", "Jason Todd"],
    correct: 0,
    official: "Terry McGinnis",
  },
  {
    id: "dc-batmanfuturo-bruce",
    franchise: "DC",
    emoji: "🦇",
    difficulty: "media",
    format: "vf",
    prompt: "En Batman del futuro, Bruce Wayne sigue vivo pero ya anciano, guiando al nuevo Batman.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "dc-titanes-lider",
    franchise: "DC",
    emoji: "🟡",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Quién lidera a los Jóvenes Titanes?",
    options: ["Robin", "Chico Bestia", "Cyborg", "Raven"],
    correct: 0,
    official: "Robin",
  },
  {
    id: "dc-titanes-starfire",
    franchise: "DC",
    emoji: "🟠",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la titán alienígena de pelo naranja que vuela?",
    hint: "(Solo el nombre.)",
    accepted: [["Starfire"]],
    official: "Starfire",
  },
  {
    id: "dc-titanes-go",
    franchise: "DC",
    emoji: "🟡",
    difficulty: "facil",
    format: "vf",
    prompt: "Los Jóvenes Titanes en Acción es una versión más oscura y seria que la serie original.",
    correct: false,
    official: "Falso: es la versión de humor, mucho más gamberra",
  },
  {
    id: "dc-superman-nombre",
    franchise: "DC",
    emoji: "🔵",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuál es el nombre kryptoniano de Superman?",
    hint: "(Dos sílabas con guion.)",
    accepted: [["Kal-El", "Kal El", "Kalel"]],
    official: "Kal-El",
  },
  {
    id: "dc-kryptonita",
    franchise: "DC",
    emoji: "💎",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué mineral deja a Superman sin fuerzas?",
    options: ["La kryptonita", "El vibranium", "El adamantium", "El uranio"],
    correct: 0,
    official: "La kryptonita",
  },
  {
    id: "dc-harley",
    franchise: "DC",
    emoji: "🔨",
    difficulty: "media",
    format: "describir",
    prompt: "Villana de coletas roja y azul, bate de béisbol y pasado como psiquiatra del Joker.",
    hint: "(Solo el nombre.)",
    accepted: [["Harley Quinn", "Harley"]],
    official: "Harley Quinn",
  },
  {
    id: "dc-harley-origen",
    franchise: "DC",
    emoji: "🔨",
    difficulty: "media",
    format: "vf",
    prompt: "Harley Quinn nació en la serie animada de Batman, no en los cómics.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "dc-superman-anime",
    franchise: "DC",
    emoji: "🔵",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Con qué estilo de dibujo está hecha la serie Mis aventuras con Superman?",
    options: ["Estilo anime", "Estilo cómic clásico", "Stop-motion", "Animación por ordenador"],
    correct: 0,
    official: "Estilo anime",
  },
  {
    id: "dc-creature-commandos",
    franchise: "DC",
    emoji: "👹",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Quién está detrás de Creature Commandos, la serie que abre el nuevo universo DC?",
    options: ["James Gunn", "Zack Snyder", "Bruce Timm", "Christopher Nolan"],
    correct: 0,
    official: "James Gunn",
  },
  {
    id: "dc-caped-crusader",
    franchise: "DC",
    emoji: "🦇",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué plataforma se estrenó la serie Batman: El enmascarado?",
    options: ["Prime Video", "Disney+", "Netflix", "HBO Max"],
    correct: 0,
    official: "Prime Video",
  },
  {
    id: "dc-orden-series",
    franchise: "DC",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de DC de la más antigua a la más reciente.",
    items: [
      "Batman: la serie animada",
      "Batman del futuro",
      "La Liga de la Justicia",
      "Los Jóvenes Titanes",
    ],
    official:
      "Batman: la serie animada (1992), Batman del futuro (1999), La Liga de la Justicia (2001) y Los Jóvenes Titanes (2003)",
  },
];
