import type { Question } from "../types";

/**
 * Televisión: los clásicos de cine de dibujos que acabaron en la tele (Tom y
 * Jerry, la Pantera Rosa, Popeye), la hornada de Cartoon Network y Nickelodeon
 * de los 90 y 2000, y la animación para adultos.
 *
 * Nombres del doblaje de España, como en el resto del banco.
 */
export const TELEVISION: Question[] = [
  // --- Tom y Jerry ---
  {
    id: "tomyjerry-quien",
    franchise: "Tom y Jerry",
    emoji: "🐱",
    difficulty: "facil",
    format: "corta",
    prompt: "De los dos protagonistas, ¿cuál es el gato?",
    hint: "(Solo el nombre.)",
    accepted: [["Tom"]],
    official: "Tom es el gato y Jerry, el ratón",
  },
  {
    id: "tomyjerry-jerry",
    franchise: "Tom y Jerry",
    emoji: "🐭",
    difficulty: "facil",
    format: "describir",
    prompt: "Ratón marrón, pequeño y listísimo, que siempre acaba ganando la partida al gato.",
    hint: "(Solo el nombre.)",
    accepted: [["Jerry"]],
    official: "Jerry",
  },
  {
    id: "tomyjerry-hablan",
    franchise: "Tom y Jerry",
    emoji: "🤐",
    difficulty: "facil",
    format: "vf",
    prompt: "En sus cortos clásicos, Tom y Jerry casi nunca hablan.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "tomyjerry-spike",
    franchise: "Tom y Jerry",
    emoji: "🐶",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es Spike, que suele darle un escarmiento a Tom?",
    options: ["Un bulldog", "Un pastor alemán", "Un lobo", "Un oso"],
    correct: 0,
    official: "Un bulldog",
  },
  {
    id: "tomyjerry-final",
    franchise: "Tom y Jerry",
    emoji: "🧀",
    difficulty: "facil",
    format: "vf",
    prompt: "En los cortos clásicos, Tom acaba comiéndose a Jerry en más de la mitad de ellos.",
    correct: false,
    official: "Falso: no se lo come nunca",
  },
  {
    id: "tomyjerry-oscars",
    franchise: "Tom y Jerry",
    emoji: "🏆",
    difficulty: "media",
    format: "vf",
    prompt: "Pese a su fama, los cortos de Tom y Jerry nunca ganaron un Óscar.",
    correct: false,
    official: "Falso: ganaron varios en los años cuarenta",
  },
  {
    id: "tomyjerry-color",
    franchise: "Tom y Jerry",
    emoji: "🐱",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De qué color es Tom?",
    hint: "(Un color.)",
    accepted: [["gris", "azul grisáceo", "gris azulado"]],
    official: "Gris azulado",
  },
  {
    id: "tomyjerry-persecucion",
    franchise: "Tom y Jerry",
    emoji: "💥",
    difficulty: "media",
    format: "describir",
    prompt:
      "Recurso constante de la serie: el gato se estampa, se aplasta o se parte en trozos, y al plano siguiente está intacto.",
    hint: "(Cómo se llama ese tipo de humor.)",
    accepted: [["slapstick", "humor slapstick", "cartoon", "humor físico", "humor de golpes"]],
    official: "El humor físico o slapstick",
  },

  // --- La Pantera Rosa ---
  {
    id: "pantera-color",
    franchise: "La Pantera Rosa",
    emoji: "🩷",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De qué color es la pantera protagonista?",
    hint: "(Un color.)",
    accepted: [["rosa"]],
    official: "Rosa",
  },
  {
    id: "pantera-habla",
    franchise: "La Pantera Rosa",
    emoji: "🩷",
    difficulty: "media",
    format: "vf",
    prompt: "La Pantera Rosa es un personaje muy hablador que comenta todo lo que hace.",
    correct: false,
    official: "Falso: es mudo casi siempre, todo va por gestos y por la música",
  },
  {
    id: "pantera-musica",
    franchise: "La Pantera Rosa",
    emoji: "🎷",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué instrumento lleva el peso de la famosa sintonía de la Pantera Rosa?",
    options: ["El saxofón", "El piano", "La trompeta", "El violín"],
    correct: 0,
    official: "El saxofón",
  },
  {
    id: "pantera-origen",
    franchise: "La Pantera Rosa",
    emoji: "🎬",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿De dónde salió originalmente la Pantera Rosa?",
    options: [
      "De los títulos de crédito de una película",
      "De un cómic de prensa",
      "De un anuncio de televisión",
      "De un cuento infantil",
    ],
    correct: 0,
    official: "De los títulos de crédito de una película de cine",
  },
  {
    id: "pantera-inspector",
    franchise: "La Pantera Rosa",
    emoji: "🕵️",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el inspector torpe asociado a la Pantera Rosa?",
    hint: "(El apellido.)",
    accepted: [["Clouseau", "inspector Clouseau"]],
    official: "El inspector Clouseau",
  },

  // --- Popeye ---
  {
    id: "popeye-espinacas",
    franchise: "Popeye",
    emoji: "🥬",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué come Popeye para volverse fortísimo de golpe?",
    hint: "(Una verdura.)",
    accepted: [["espinacas", "espinaca"]],
    official: "Espinacas",
  },
  {
    id: "popeye-novia",
    franchise: "Popeye",
    emoji: "💚",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la novia flaquísima de Popeye?",
    options: ["Olivia", "Rosario", "Petunia", "Margarita"],
    correct: 0,
    official: "Olivia",
  },
  {
    id: "popeye-oficio",
    franchise: "Popeye",
    emoji: "⚓",
    difficulty: "facil",
    format: "corta",
    prompt: "¿A qué se dedica Popeye?",
    hint: "(Un oficio.)",
    accepted: [["marino", "marinero"]],
    official: "Es marinero",
  },
  {
    id: "popeye-brutus",
    franchise: "Popeye",
    emoji: "💪",
    difficulty: "media",
    format: "vf",
    prompt: "El rival grandullón y barbudo de Popeye se llama Brutus.",
    correct: true,
    official: "Verdadero",
  },

  // --- El laboratorio de Dexter ---
  {
    id: "dexter-laboratorio",
    franchise: "El laboratorio de Dexter",
    emoji: "🧪",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Dónde tiene Dexter escondido su laboratorio?",
    hint: "(Un sitio de la casa.)",
    accepted: [["su habitación", "habitación", "cuarto", "su cuarto", "dormitorio"]],
    official: "Detrás de la estantería de su habitación",
  },
  {
    id: "dexter-hermana",
    franchise: "El laboratorio de Dexter",
    emoji: "💃",
    difficulty: "facil",
    format: "describir",
    prompt: "Hermana mayor rubia y bailonga que entra en el laboratorio y lo destroza todo sin querer.",
    hint: "(Solo el nombre.)",
    accepted: [["DeeDee", "Dee Dee"]],
    official: "DeeDee",
  },
  {
    id: "dexter-acento",
    franchise: "El laboratorio de Dexter",
    emoji: "🧪",
    difficulty: "media",
    format: "vf",
    prompt: "Los padres de Dexter saben perfectamente que su hijo tiene un laboratorio en casa.",
    correct: false,
    official: "Falso: no se enteran nunca",
  },

  // --- Johnny Bravo ---
  {
    id: "johnnybravo-pelo",
    franchise: "Johnny Bravo",
    emoji: "🕶️",
    difficulty: "media",
    format: "describir",
    prompt: "Rubio cachas con tupé, gafas de sol y camiseta negra, al que ninguna chica hace caso.",
    hint: "(Solo el nombre.)",
    accepted: [["Johnny Bravo", "Johnny"]],
    official: "Johnny Bravo",
  },
  {
    id: "johnnybravo-exito",
    franchise: "Johnny Bravo",
    emoji: "💔",
    difficulty: "media",
    format: "vf",
    prompt: "Johnny Bravo se pasa la serie ligando con éxito con todas las chicas.",
    correct: false,
    official: "Falso: le dan calabazas siempre",
  },

  // --- Vaca y Pollo ---
  {
    id: "vacaypollo-hermanos",
    franchise: "Vaca y Pollo",
    emoji: "🐄",
    difficulty: "media",
    format: "vf",
    prompt: "En Vaca y Pollo, los dos protagonistas son padre e hijo.",
    correct: false,
    official: "Falso: son hermanos, y sus padres son humanos",
  },
  {
    id: "vacaypollo-villano",
    franchise: "Vaca y Pollo",
    emoji: "😈",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el villano rojo y sin pantalones que atormenta a los hermanos?",
    options: ["El Chico Rojo", "El Diablillo", "Don Rojo", "El Colorado"],
    correct: 0,
    official: "El Chico Rojo",
  },

  // --- Ed, Edd y Eddy ---
  {
    id: "ededdeddy-nombres",
    franchise: "Ed, Edd y Eddy",
    emoji: "🍬",
    difficulty: "media",
    format: "vf",
    prompt: "Los tres protagonistas se llaman parecido y se pasan la serie intentando ganar dinero.",
    correct: true,
    official: "Verdadero",
    note: "Su obsesión son las chuches de bola de gominola.",
  },

  // --- Billy y Mandy ---
  {
    id: "billymandy-muerte",
    franchise: "Las macabras aventuras de Billy y Mandy",
    emoji: "💀",
    difficulty: "media",
    format: "corta",
    prompt: "¿Quién es el amigo obligado de Billy y Mandy tras perder una apuesta?",
    hint: "(Un personaje muy reconocible.)",
    accepted: [["la Muerte", "Muerte", "la Parca", "Parca", "Puro Hueso"]],
    official: "La Muerte, que en España se llamó Puro Hueso",
  },

  // --- Foster ---
  {
    id: "foster-casa",
    franchise: "Foster",
    emoji: "🏠",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Quiénes viven en la casa de Foster?",
    options: [
      "Amigos imaginarios abandonados",
      "Monstruos de debajo de la cama",
      "Fantasmas",
      "Robots",
    ],
    correct: 0,
    official: "Amigos imaginarios abandonados",
  },

  // --- Oye Arnold ---
  {
    id: "oyearnold-cabeza",
    franchise: "Oye Arnold",
    emoji: "🏈",
    difficulty: "media",
    format: "describir",
    prompt: "Niño rubio con gorra azul cuya cabeza tiene forma de balón de rugby.",
    hint: "(Solo el nombre.)",
    accepted: [["Arnold"]],
    official: "Arnold",
  },
  {
    id: "oyearnold-helga",
    franchise: "Oye Arnold",
    emoji: "🎀",
    difficulty: "media",
    format: "vf",
    prompt: "Helga trata fatal a Arnold en público, pero en secreto está enamorada de él.",
    correct: true,
    official: "Verdadero",
  },

  // --- Los Castores Cascarrabias ---
  {
    id: "castores-hermanos",
    franchise: "Los Castores Cascarrabias",
    emoji: "🦫",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué son Norbert y Dagoberto, los protagonistas de la serie?",
    options: ["Dos castores hermanos", "Dos nutrias", "Dos mapaches", "Dos ardillas"],
    correct: 0,
    official: "Dos castores hermanos",
  },

  // --- Invasor Zim ---
  {
    id: "zim-mision",
    franchise: "Invasor Zim",
    emoji: "👽",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuál es la misión de Zim en la Tierra?",
    options: ["Conquistarla", "Estudiar a los humanos", "Buscar a su familia", "Esconderse"],
    correct: 0,
    official: "Conquistarla",
  },
  {
    id: "zim-gir",
    franchise: "Invasor Zim",
    emoji: "🤖",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el robot atolondrado que ayuda a Zim disfrazado de perro verde?",
    options: ["GIR", "ZAP", "MIR", "BOB"],
    correct: 0,
    official: "GIR",
  },

  // --- Jimmy Neutrón ---
  {
    id: "jimmyneutron-perro",
    franchise: "Jimmy Neutrón",
    emoji: "🐕",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el perro robot de Jimmy Neutrón?",
    hint: "(Solo el nombre.)",
    accepted: [["Goddard"]],
    official: "Goddard",
  },
  {
    id: "jimmyneutron-pelo",
    franchise: "Jimmy Neutrón",
    emoji: "🧠",
    difficulty: "media",
    format: "vf",
    prompt: "Jimmy Neutrón lleva la cabeza rapada al cero.",
    correct: false,
    official: "Falso: tiene un tupé con forma de helado",
  },

  // --- Danny Phantom ---
  {
    id: "dannyphantom-poderes",
    franchise: "Danny Phantom",
    emoji: "👻",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué se convierte Danny tras el accidente en el laboratorio de sus padres?",
    options: ["En medio fantasma", "En vampiro", "En invisible permanente", "En robot"],
    correct: 0,
    official: "En medio fantasma",
  },

  // --- Los Thornberrys ---
  {
    id: "thornberrys-eliza",
    franchise: "Los Thornberrys",
    emoji: "🦓",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué don tiene Eliza Thornberry?",
    options: [
      "Habla con los animales",
      "Se vuelve invisible",
      "Vuela",
      "Entiende todos los idiomas",
    ],
    correct: 0,
    official: "Habla con los animales",
  },

  // --- Rocko ---
  {
    id: "rocko-animal",
    franchise: "La vida moderna de Rocko",
    emoji: "🦘",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué animal es Rocko?",
    options: ["Un ualabí", "Un conejo", "Un ratón", "Un koala"],
    correct: 0,
    official: "Un ualabí",
  },

  // --- Bloque de la época ---
  {
    id: "relacionar-cn-noventas",
    franchise: "Series de dibujos",
    emoji: "📺",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada personaje con su serie.",
    pairs: [
      { left: "DeeDee", right: "El laboratorio de Dexter" },
      { left: "Helga", right: "Oye Arnold" },
      { left: "GIR", right: "Invasor Zim" },
      { left: "Goddard", right: "Jimmy Neutrón" },
    ],
    official:
      "DeeDee–El laboratorio de Dexter, Helga–Oye Arnold, GIR–Invasor Zim y Goddard–Jimmy Neutrón",
  },
  {
    id: "orden-nickelodeon",
    franchise: "Series de dibujos",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de la más antigua a la más reciente.",
    items: ["Los Rugrats", "Oye Arnold", "Bob Esponja", "Jimmy Neutrón"],
    official:
      "Los Rugrats (1991), Oye Arnold (1996), Bob Esponja (1999) y Jimmy Neutrón (2002)",
  },
  {
    id: "orden-cartoonnetwork",
    franchise: "Series de dibujos",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de Cartoon Network de la más antigua a la más reciente.",
    items: [
      "El laboratorio de Dexter",
      "Las Supernenas",
      "Hora de aventuras",
      "El asombroso mundo de Gumball",
    ],
    official:
      "El laboratorio de Dexter (1996), Las Supernenas (1998), Hora de aventuras (2010) y El asombroso mundo de Gumball (2011)",
  },

  // --- Padre de familia ---
  {
    id: "padrefamilia-bebe",
    franchise: "Padre de familia",
    emoji: "👶",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el bebé de cabeza ovalada que habla y planea maldades?",
    hint: "(Solo el nombre.)",
    accepted: [["Stewie"]],
    official: "Stewie",
  },
  {
    id: "padrefamilia-perro",
    franchise: "Padre de familia",
    emoji: "🐕",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el perro que habla, bebe martinis y escribe novelas?",
    hint: "(Solo el nombre.)",
    accepted: [["Brian"]],
    official: "Brian",
  },
  {
    id: "padrefamilia-ciudad",
    franchise: "Padre de familia",
    emoji: "🏘️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué ciudad inventada viven los Griffin?",
    options: ["Quahog", "Springfield", "Langley Falls", "South Park"],
    correct: 0,
    official: "Quahog",
  },
  {
    id: "padrefamilia-gag",
    franchise: "Padre de familia",
    emoji: "🐔",
    difficulty: "media",
    format: "vf",
    prompt: "Un gag recurrente de la serie son las peleas larguísimas de Peter con un pollo gigante.",
    correct: true,
    official: "Verdadero",
  },

  // --- South Park ---
  {
    id: "southpark-kenny",
    franchise: "South Park",
    emoji: "🧡",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el niño de la parka naranja al que no se le entiende al hablar?",
    hint: "(Solo el nombre.)",
    accepted: [["Kenny"]],
    official: "Kenny",
  },
  {
    id: "southpark-estilo",
    franchise: "South Park",
    emoji: "✂️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿A qué imita el estilo visual de South Park?",
    options: [
      "A recortables de cartulina",
      "A plastilina",
      "A dibujo a lápiz",
      "A marionetas de hilo",
    ],
    correct: 0,
    official: "A recortables de cartulina",
  },
  {
    id: "southpark-estado",
    franchise: "South Park",
    emoji: "🏔️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué estado de Estados Unidos está el pueblo de South Park?",
    options: ["Colorado", "Nevada", "Montana", "Wyoming"],
    correct: 0,
    official: "Colorado",
  },
  {
    id: "southpark-cartman",
    franchise: "South Park",
    emoji: "😠",
    difficulty: "media",
    format: "describir",
    prompt: "Niño gordo, egoísta y malhablado, con gorro azul de pompón, que manda en el grupo.",
    hint: "(Solo el nombre.)",
    accepted: [["Cartman", "Eric Cartman"]],
    official: "Cartman",
  },

  // --- Rick y Morty ---
  {
    id: "rickymorty-parentesco",
    franchise: "Rick y Morty",
    emoji: "🧪",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué son Rick y Morty el uno del otro?",
    options: ["Abuelo y nieto", "Padre e hijo", "Tío y sobrino", "Hermanos"],
    correct: 0,
    official: "Abuelo y nieto",
  },
  {
    id: "rickymorty-pistola",
    franchise: "Rick y Morty",
    emoji: "🌀",
    difficulty: "media",
    format: "corta",
    prompt: "¿Qué usa Rick para abrir portales a otras dimensiones?",
    hint: "(Un objeto.)",
    accepted: [["pistola de portales", "pistola", "pistola dimensional", "portales"]],
    official: "Una pistola de portales",
  },
  {
    id: "rickymorty-frase",
    franchise: "Rick y Morty",
    emoji: "🥒",
    difficulty: "media",
    format: "completar",
    prompt: "Completa el episodio más celebrado de la serie: «Rick ___», cuando se convierte en pepinillo.",
    accepted: [["Pickle", "pepinillo", "Pickle Rick"]],
    official: "Pickle Rick",
  },
  {
    id: "rickymorty-tono",
    franchise: "Rick y Morty",
    emoji: "🧪",
    difficulty: "media",
    format: "vf",
    prompt: "Rick y Morty es una serie infantil pensada para verse en familia.",
    correct: false,
    official: "Falso: es animación para adultos",
  },

  // --- Arcane ---
  {
    id: "arcane-videojuego",
    franchise: "Arcane",
    emoji: "⚡",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué videojuego se basa Arcane?",
    options: ["League of Legends", "Fortnite", "Overwatch", "Valorant"],
    correct: 0,
    official: "League of Legends",
  },
  {
    id: "arcane-hermanas",
    franchise: "Arcane",
    emoji: "💙",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llaman las dos hermanas protagonistas de Arcane?",
    hint: "(Los dos nombres.)",
    accepted: [["Vi"], ["Jinx", "Powder"]],
    official: "Vi y Jinx",
  },
  {
    id: "arcane-ciudades",
    franchise: "Arcane",
    emoji: "🏙️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman la ciudad de arriba y la de abajo en Arcane?",
    options: [
      "Piltover y Zaun",
      "Piltover y Noxus",
      "Demacia y Zaun",
      "Ionia y Zaun",
    ],
    correct: 0,
    official: "Piltover y Zaun",
  },
  {
    id: "arcane-publico",
    franchise: "Arcane",
    emoji: "⚡",
    difficulty: "media",
    format: "vf",
    prompt: "Arcane es una serie infantil, pese a estar basada en un videojuego competitivo.",
    correct: false,
    official: "Falso: es una serie adulta y bastante dura",
  },

  // --- Super Mario ---
  {
    id: "supermario-hermano",
    franchise: "Super Mario",
    emoji: "🍄",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el hermano de Mario, el alto y de verde?",
    hint: "(Solo el nombre.)",
    accepted: [["Luigi"]],
    official: "Luigi",
  },
  {
    id: "supermario-villano",
    franchise: "Super Mario",
    emoji: "🐢",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el rey tortuga que secuestra a la princesa?",
    options: ["Bowser", "Wario", "Donkey Kong", "Waluigi"],
    correct: 0,
    official: "Bowser",
  },
  {
    id: "supermario-princesa",
    franchise: "Super Mario",
    emoji: "👑",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la princesa del Reino Champiñón?",
    hint: "(Solo el nombre.)",
    accepted: [["Peach"]],
    official: "Peach",
  },
  {
    id: "supermario-oficio",
    franchise: "Super Mario",
    emoji: "🔧",
    difficulty: "facil",
    format: "vf",
    prompt: "Mario y Luigi son fontaneros.",
    correct: true,
    official: "Verdadero",
  },
];
