import type { Question } from "../types";

/**
 * Televisión: los clásicos de cine de dibujos que acabaron en la tele (Tom y
 * Jerry, la Pantera Rosa, Popeye), la hornada de Cartoon Network y Nickelodeon
 * de los 90 y 2000, y la animación para adultos.
 *
 * Nombres del doblaje de España, como en el resto del banco.
 */
export const TELEVISION: Question[] = [
  // --- Tom y Jerry ---
  {
    id: "tomyjerry-quien",
    franchise: "Tom y Jerry",
    emoji: "🐱",
    difficulty: "facil",
    format: "corta",
    prompt: "De los dos protagonistas, ¿cuál es el gato?",
    hint: "(Solo el nombre.)",
    accepted: [["Tom"]],
    official: "Tom es el gato y Jerry, el ratón",
  },
  {
    id: "tomyjerry-jerry",
    franchise: "Tom y Jerry",
    emoji: "🐭",
    difficulty: "facil",
    format: "describir",
    prompt: "Ratón marrón, pequeño y listísimo, que siempre acaba ganando la partida al gato.",
    hint: "(Solo el nombre.)",
    accepted: [["Jerry"]],
    official: "Jerry",
  },
  {
    id: "tomyjerry-hablan",
    franchise: "Tom y Jerry",
    emoji: "🤐",
    difficulty: "facil",
    format: "vf",
    prompt: "En sus cortos clásicos, Tom y Jerry casi nunca hablan.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "tomyjerry-spike",
    franchise: "Tom y Jerry",
    emoji: "🐶",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es Spike, que suele darle un escarmiento a Tom?",
    options: ["Un bulldog", "Un pastor alemán", "Un lobo", "Un oso"],
    correct: 0,
    official: "Un bulldog",
  },
  {
    id: "tomyjerry-final",
    franchise: "Tom y Jerry",
    emoji: "🧀",
    difficulty: "facil",
    format: "vf",
    prompt: "En los cortos clásicos, Tom acaba comiéndose a Jerry en más de la mitad de ellos.",
    correct: false,
    official: "Falso: no se lo come nunca",
  },
  {
    id: "tomyjerry-oscars",
    franchise: "Tom y Jerry",
    emoji: "🏆",
    difficulty: "media",
    format: "vf",
    prompt: "Pese a su fama, los cortos de Tom y Jerry nunca ganaron un Óscar.",
    correct: false,
    official: "Falso: ganaron varios en los años cuarenta",
  },
  {
    id: "tomyjerry-color",
    franchise: "Tom y Jerry",
    emoji: "🐱",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De qué color es Tom?",
    hint: "(Un color.)",
    accepted: [["gris", "azul grisáceo", "gris azulado"]],
    official: "Gris azulado",
  },
  {
    id: "tomyjerry-persecucion",
    franchise: "Tom y Jerry",
    emoji: "💥",
    difficulty: "media",
    format: "describir",
    prompt:
      "Recurso constante de la serie: el gato se estampa, se aplasta o se parte en trozos, y al plano siguiente está intacto.",
    hint: "(Cómo se llama ese tipo de humor.)",
    accepted: [["slapstick", "humor slapstick", "cartoon", "humor físico", "humor de golpes"]],
    official: "El humor físico o slapstick",
  },

  // --- La Pantera Rosa ---
  {
    id: "pantera-color",
    franchise: "La Pantera Rosa",
    emoji: "🩷",
    difficulty: "facil",
    format: "corta",
    prompt: "¿De qué color es la pantera protagonista?",
    hint: "(Un color.)",
    accepted: [["rosa"]],
    official: "Rosa",
  },
  {
    id: "pantera-habla",
    franchise: "La Pantera Rosa",
    emoji: "🩷",
    difficulty: "media",
    format: "vf",
    prompt: "La Pantera Rosa es un personaje muy hablador que comenta todo lo que hace.",
    correct: false,
    official: "Falso: es mudo casi siempre, todo va por gestos y por la música",
  },
  {
    id: "pantera-musica",
    franchise: "La Pantera Rosa",
    emoji: "🎷",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué instrumento lleva el peso de la famosa sintonía de la Pantera Rosa?",
    options: ["El saxofón", "El piano", "La trompeta", "El violín"],
    correct: 0,
    official: "El saxofón",
  },
  {
    id: "pantera-origen",
    franchise: "La Pantera Rosa",
    emoji: "🎬",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿De dónde salió originalmente la Pantera Rosa?",
    options: [
      "De los títulos de crédito de una película",
      "De un cómic de prensa",
      "De un anuncio de televisión",
      "De un cuento infantil",
    ],
    correct: 0,
    official: "De los títulos de crédito de una película de cine",
  },
  {
    id: "pantera-inspector",
    franchise: "La Pantera Rosa",
    emoji: "🕵️",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el inspector torpe asociado a la Pantera Rosa?",
    hint: "(El apellido.)",
    accepted: [["Clouseau", "inspector Clouseau"]],
    official: "El inspector Clouseau",
  },

  // --- Popeye ---
  {
    id: "popeye-espinacas",
    franchise: "Popeye",
    emoji: "🥬",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué come Popeye para volverse fortísimo de golpe?",
    hint: "(Una verdura.)",
    accepted: [["espinacas", "espinaca"]],
    official: "Espinacas",
  },
  {
    id: "popeye-novia",
    franchise: "Popeye",
    emoji: "💚",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la novia flaquísima de Popeye?",
    options: ["Olivia", "Rosario", "Petunia", "Margarita"],
    correct: 0,
    official: "Olivia",
  },
  {
    id: "popeye-oficio",
    franchise: "Popeye",
    emoji: "⚓",
    difficulty: "facil",
    format: "corta",
    prompt: "¿A qué se dedica Popeye?",
    hint: "(Un oficio.)",
    accepted: [["marino", "marinero"]],
    official: "Es marinero",
  },
  {
    id: "popeye-brutus",
    franchise: "Popeye",
    emoji: "💪",
    difficulty: "media",
    format: "vf",
    prompt: "El rival grandullón y barbudo de Popeye se llama Brutus.",
    correct: true,
    official: "Verdadero",
  },

  // --- El laboratorio de Dexter ---
  {
    id: "dexter-laboratorio",
    franchise: "El laboratorio de Dexter",
    emoji: "🧪",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Dónde tiene Dexter escondido su laboratorio?",
    hint: "(Un sitio de la casa.)",
    accepted: [["su habitación", "habitación", "cuarto", "su cuarto", "dormitorio"]],
    official: "Detrás de la estantería de su habitación",
  },
  {
    id: "dexter-hermana",
    franchise: "El laboratorio de Dexter",
    emoji: "💃",
    difficulty: "facil",
    format: "describir",
    prompt: "Hermana mayor rubia y bailonga que entra en el laboratorio y lo destroza todo sin querer.",
    hint: "(Solo el nombre.)",
    accepted: [["DeeDee", "Dee Dee"]],
    official: "DeeDee",
  },
  {
    id: "dexter-acento",
    franchise: "El laboratorio de Dexter",
    emoji: "🧪",
    difficulty: "media",
    format: "vf",
    prompt: "Los padres de Dexter saben perfectamente que su hijo tiene un laboratorio en casa.",
    correct: false,
    official: "Falso: no se enteran nunca",
  },

  // --- Johnny Bravo ---
  {
    id: "johnnybravo-pelo",
    franchise: "Johnny Bravo",
    emoji: "🕶️",
    difficulty: "media",
    format: "describir",
    prompt: "Rubio cachas con tupé, gafas de sol y camiseta negra, al que ninguna chica hace caso.",
    hint: "(Solo el nombre.)",
    accepted: [["Johnny Bravo", "Johnny"]],
    official: "Johnny Bravo",
  },
  {
    id: "johnnybravo-exito",
    franchise: "Johnny Bravo",
    emoji: "💔",
    difficulty: "media",
    format: "vf",
    prompt: "Johnny Bravo se pasa la serie ligando con éxito con todas las chicas.",
    correct: false,
    official: "Falso: le dan calabazas siempre",
  },

  // --- Vaca y Pollo ---
  {
    id: "vacaypollo-hermanos",
    franchise: "Vaca y Pollo",
    emoji: "🐄",
    difficulty: "media",
    format: "vf",
    prompt: "En Vaca y Pollo, los dos protagonistas son padre e hijo.",
    correct: false,
    official: "Falso: son hermanos, y sus padres son humanos",
  },
  {
    id: "vacaypollo-villano",
    franchise: "Vaca y Pollo",
    emoji: "😈",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el villano rojo y sin pantalones que atormenta a los hermanos?",
    options: ["El Chico Rojo", "El Diablillo", "Don Rojo", "El Colorado"],
    correct: 0,
    official: "El Chico Rojo",
  },

  // --- Ed, Edd y Eddy ---
  {
    id: "ededdeddy-nombres",
    franchise: "Ed, Edd y Eddy",
    emoji: "🍬",
    difficulty: "media",
    format: "vf",
    prompt: "Los tres protagonistas se llaman parecido y se pasan la serie intentando ganar dinero.",
    correct: true,
    official: "Verdadero",
    note: "Su obsesión son las chuches de bola de gominola.",
  },

  // --- Billy y Mandy ---
  {
    id: "billymandy-muerte",
    franchise: "Las macabras aventuras de Billy y Mandy",
    emoji: "💀",
    difficulty: "media",
    format: "corta",
    prompt: "¿Quién es el amigo obligado de Billy y Mandy tras perder una apuesta?",
    hint: "(Un personaje muy reconocible.)",
    accepted: [["la Muerte", "Muerte", "la Parca", "Parca", "Puro Hueso"]],
    official: "La Muerte, que en España se llamó Puro Hueso",
  },

  // --- Foster ---
  {
    id: "foster-casa",
    franchise: "Foster",
    emoji: "🏠",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Quiénes viven en la casa de Foster?",
    options: [
      "Amigos imaginarios abandonados",
      "Monstruos de debajo de la cama",
      "Fantasmas",
      "Robots",
    ],
    correct: 0,
    official: "Amigos imaginarios abandonados",
  },

  // --- Oye Arnold ---
  {
    id: "oyearnold-cabeza",
    franchise: "Oye Arnold",
    emoji: "🏈",
    difficulty: "media",
    format: "describir",
    prompt: "Niño rubio con gorra azul cuya cabeza tiene forma de balón de rugby.",
    hint: "(Solo el nombre.)",
    accepted: [["Arnold"]],
    official: "Arnold",
  },
  {
    id: "oyearnold-helga",
    franchise: "Oye Arnold",
    emoji: "🎀",
    difficulty: "media",
    format: "vf",
    prompt: "Helga trata fatal a Arnold en público, pero en secreto está enamorada de él.",
    correct: true,
    official: "Verdadero",
  },

  // --- Los Castores Cascarrabias ---
  {
    id: "castores-hermanos",
    franchise: "Los Castores Cascarrabias",
    emoji: "🦫",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué son Norbert y Dagoberto, los protagonistas de la serie?",
    options: ["Dos castores hermanos", "Dos nutrias", "Dos mapaches", "Dos ardillas"],
    correct: 0,
    official: "Dos castores hermanos",
  },

  // --- Invasor Zim ---
  {
    id: "zim-mision",
    franchise: "Invasor Zim",
    emoji: "👽",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cuál es la misión de Zim en la Tierra?",
    options: ["Conquistarla", "Estudiar a los humanos", "Buscar a su familia", "Esconderse"],
    correct: 0,
    official: "Conquistarla",
  },
  {
    id: "zim-gir",
    franchise: "Invasor Zim",
    emoji: "🤖",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el robot atolondrado que ayuda a Zim disfrazado de perro verde?",
    options: ["GIR", "ZAP", "MIR", "BOB"],
    correct: 0,
    official: "GIR",
  },

  // --- Jimmy Neutrón ---
  {
    id: "jimmyneutron-perro",
    franchise: "Jimmy Neutrón",
    emoji: "🐕",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el perro robot de Jimmy Neutrón?",
    hint: "(Solo el nombre.)",
    accepted: [["Goddard"]],
    official: "Goddard",
  },
  {
    id: "jimmyneutron-pelo",
    franchise: "Jimmy Neutrón",
    emoji: "🧠",
    difficulty: "media",
    format: "vf",
    prompt: "Jimmy Neutrón lleva la cabeza rapada al cero.",
    correct: false,
    official: "Falso: tiene un tupé con forma de helado",
  },

  // --- Danny Phantom ---
  {
    id: "dannyphantom-poderes",
    franchise: "Danny Phantom",
    emoji: "👻",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué se convierte Danny tras el accidente en el laboratorio de sus padres?",
    options: ["En medio fantasma", "En vampiro", "En invisible permanente", "En robot"],
    correct: 0,
    official: "En medio fantasma",
  },

  // --- Los Thornberrys ---
  {
    id: "thornberrys-eliza",
    franchise: "Los Thornberrys",
    emoji: "🦓",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué don tiene Eliza Thornberry?",
    options: [
      "Habla con los animales",
      "Se vuelve invisible",
      "Vuela",
      "Entiende todos los idiomas",
    ],
    correct: 0,
    official: "Habla con los animales",
  },

  // --- Rocko ---
  {
    id: "rocko-animal",
    franchise: "La vida moderna de Rocko",
    emoji: "🦘",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué animal es Rocko?",
    options: ["Un ualabí", "Un conejo", "Un ratón", "Un koala"],
    correct: 0,
    official: "Un ualabí",
  },

  // --- Bloque de la época ---
  {
    id: "relacionar-cn-noventas",
    franchise: "Series de dibujos",
    emoji: "📺",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada personaje con su serie.",
    pairs: [
      { left: "DeeDee", right: "El laboratorio de Dexter" },
      { left: "Helga", right: "Oye Arnold" },
      { left: "GIR", right: "Invasor Zim" },
      { left: "Goddard", right: "Jimmy Neutrón" },
    ],
    official:
      "DeeDee–El laboratorio de Dexter, Helga–Oye Arnold, GIR–Invasor Zim y Goddard–Jimmy Neutrón",
  },
  {
    id: "orden-nickelodeon",
    franchise: "Series de dibujos",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de la más antigua a la más reciente.",
    items: ["Los Rugrats", "Oye Arnold", "Bob Esponja", "Jimmy Neutrón"],
    official:
      "Los Rugrats (1991), Oye Arnold (1996), Bob Esponja (1999) y Jimmy Neutrón (2002)",
  },
  {
    id: "orden-cartoonnetwork",
    franchise: "Series de dibujos",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de Cartoon Network de la más antigua a la más reciente.",
    items: [
      "El laboratorio de Dexter",
      "Las Supernenas",
      "Hora de aventuras",
      "El asombroso mundo de Gumball",
    ],
    official:
      "El laboratorio de Dexter (1996), Las Supernenas (1998), Hora de aventuras (2010) y El asombroso mundo de Gumball (2011)",
  },

  // --- Padre de familia ---
  {
    id: "padrefamilia-bebe",
    franchise: "Padre de familia",
    emoji: "👶",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el bebé de cabeza ovalada que habla y planea maldades?",
    hint: "(Solo el nombre.)",
    accepted: [["Stewie"]],
    official: "Stewie",
  },
  {
    id: "padrefamilia-perro",
    franchise: "Padre de familia",
    emoji: "🐕",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el perro que habla, bebe martinis y escribe novelas?",
    hint: "(Solo el nombre.)",
    accepted: [["Brian"]],
    official: "Brian",
  },
  {
    id: "padrefamilia-ciudad",
    franchise: "Padre de familia",
    emoji: "🏘️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué ciudad inventada viven los Griffin?",
    options: ["Quahog", "Springfield", "Langley Falls", "South Park"],
    correct: 0,
    official: "Quahog",
  },
  {
    id: "padrefamilia-gag",
    franchise: "Padre de familia",
    emoji: "🐔",
    difficulty: "media",
    format: "vf",
    prompt: "Un gag recurrente de la serie son las peleas larguísimas de Peter con un pollo gigante.",
    correct: true,
    official: "Verdadero",
  },

  // --- South Park ---
  {
    id: "southpark-kenny",
    franchise: "South Park",
    emoji: "🧡",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el niño de la parka naranja al que no se le entiende al hablar?",
    hint: "(Solo el nombre.)",
    accepted: [["Kenny"]],
    official: "Kenny",
  },
  {
    id: "southpark-estilo",
    franchise: "South Park",
    emoji: "✂️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿A qué imita el estilo visual de South Park?",
    options: [
      "A recortables de cartulina",
      "A plastilina",
      "A dibujo a lápiz",
      "A marionetas de hilo",
    ],
    correct: 0,
    official: "A recortables de cartulina",
  },
  {
    id: "southpark-estado",
    franchise: "South Park",
    emoji: "🏔️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿En qué estado de Estados Unidos está el pueblo de South Park?",
    options: ["Colorado", "Nevada", "Montana", "Wyoming"],
    correct: 0,
    official: "Colorado",
  },
  {
    id: "southpark-cartman",
    franchise: "South Park",
    emoji: "😠",
    difficulty: "media",
    format: "describir",
    prompt: "Niño gordo, egoísta y malhablado, con gorro azul de pompón, que manda en el grupo.",
    hint: "(Solo el nombre.)",
    accepted: [["Cartman", "Eric Cartman"]],
    official: "Cartman",
  },

  // --- Rick y Morty ---
  {
    id: "rickymorty-parentesco",
    franchise: "Rick y Morty",
    emoji: "🧪",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué son Rick y Morty el uno del otro?",
    options: ["Abuelo y nieto", "Padre e hijo", "Tío y sobrino", "Hermanos"],
    correct: 0,
    official: "Abuelo y nieto",
  },
  {
    id: "rickymorty-pistola",
    franchise: "Rick y Morty",
    emoji: "🌀",
    difficulty: "media",
    format: "corta",
    prompt: "¿Qué usa Rick para abrir portales a otras dimensiones?",
    hint: "(Un objeto.)",
    accepted: [["pistola de portales", "pistola", "pistola dimensional", "portales"]],
    official: "Una pistola de portales",
  },
  {
    id: "rickymorty-frase",
    franchise: "Rick y Morty",
    emoji: "🥒",
    difficulty: "media",
    format: "completar",
    prompt: "Completa el episodio más celebrado de la serie: «Rick ___», cuando se convierte en pepinillo.",
    accepted: [["Pickle", "pepinillo", "Pickle Rick"]],
    official: "Pickle Rick",
  },
  {
    id: "rickymorty-tono",
    franchise: "Rick y Morty",
    emoji: "🧪",
    difficulty: "media",
    format: "vf",
    prompt: "Rick y Morty es una serie infantil pensada para verse en familia.",
    correct: false,
    official: "Falso: es animación para adultos",
  },

  // --- Arcane ---
  {
    id: "arcane-videojuego",
    franchise: "Arcane",
    emoji: "⚡",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué videojuego se basa Arcane?",
    options: ["League of Legends", "Fortnite", "Overwatch", "Valorant"],
    correct: 0,
    official: "League of Legends",
  },
  {
    id: "arcane-hermanas",
    franchise: "Arcane",
    emoji: "💙",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llaman las dos hermanas protagonistas de Arcane?",
    hint: "(Los dos nombres.)",
    accepted: [["Vi"], ["Jinx", "Powder"]],
    official: "Vi y Jinx",
  },
  {
    id: "arcane-ciudades",
    franchise: "Arcane",
    emoji: "🏙️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman la ciudad de arriba y la de abajo en Arcane?",
    options: [
      "Piltover y Zaun",
      "Piltover y Noxus",
      "Demacia y Zaun",
      "Ionia y Zaun",
    ],
    correct: 0,
    official: "Piltover y Zaun",
  },
  {
    id: "arcane-publico",
    franchise: "Arcane",
    emoji: "⚡",
    difficulty: "media",
    format: "vf",
    prompt: "Arcane es una serie infantil, pese a estar basada en un videojuego competitivo.",
    correct: false,
    official: "Falso: es una serie adulta y bastante dura",
  },

  // --- Super Mario ---
  {
    id: "supermario-hermano",
    franchise: "Super Mario",
    emoji: "🍄",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el hermano de Mario, el alto y de verde?",
    hint: "(Solo el nombre.)",
    accepted: [["Luigi"]],
    official: "Luigi",
  },
  {
    id: "supermario-villano",
    franchise: "Super Mario",
    emoji: "🐢",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama el rey tortuga que secuestra a la princesa?",
    options: ["Bowser", "Wario", "Donkey Kong", "Waluigi"],
    correct: 0,
    official: "Bowser",
  },
  {
    id: "supermario-princesa",
    franchise: "Super Mario",
    emoji: "👑",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la princesa del Reino Champiñón?",
    hint: "(Solo el nombre.)",
    accepted: [["Peach"]],
    official: "Peach",
  },
  {
    id: "supermario-oficio",
    franchise: "Super Mario",
    emoji: "🔧",
    difficulty: "facil",
    format: "vf",
    prompt: "Mario y Luigi son fontaneros.",
    correct: true,
    official: "Verdadero",
  },

  // --- Los Autos Locos ---
  {
    id: "autoslocos-patan",
    franchise: "Los Autos Locos",
    emoji: "🏎️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el perro que se ríe entre dientes de su propio amo?",
    hint: "(Solo el nombre.)",
    accepted: [["Patán"]],
    official: "Patán",
  },
  {
    id: "autoslocos-nodoyuna",
    franchise: "Los Autos Locos",
    emoji: "🏁",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se llama en España el tramposo que hace todo lo posible por ganar la carrera?",
    options: ["Pierre Nodoyuna", "Dick Dastardly", "Pierre Malaleche", "Don Trampas"],
    correct: 0,
    official: "Pierre Nodoyuna",
  },
  {
    id: "autoslocos-gana",
    franchise: "Los Autos Locos",
    emoji: "🏆",
    difficulty: "facil",
    format: "vf",
    prompt: "Pierre Nodoyuna acaba ganando casi todas las carreras gracias a sus trampas.",
    correct: false,
    official: "Falso: no gana nunca, las trampas siempre le salen mal",
  },
  {
    id: "autoslocos-que",
    franchise: "Los Autos Locos",
    emoji: "🚗",
    difficulty: "facil",
    format: "corta",
    prompt: "¿En qué compiten los personajes de esta serie?",
    hint: "(Una prueba.)",
    accepted: [["una carrera", "carrera", "carreras", "carreras de coches"]],
    official: "En una carrera de coches",
  },

  // --- Don Gato ---
  {
    id: "dongato-quien",
    franchise: "Don Gato",
    emoji: "🎩",
    difficulty: "facil",
    format: "describir",
    prompt: "Gato amarillo con chaleco morado y sombrero que lidera una pandilla en un callejón.",
    hint: "(Solo el nombre.)",
    accepted: [["Don Gato"]],
    official: "Don Gato",
  },
  {
    id: "dongato-matute",
    franchise: "Don Gato",
    emoji: "👮",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el policía que intenta pillar a la pandilla?",
    hint: "(El apellido.)",
    accepted: [["Matute", "oficial Matute"]],
    official: "El oficial Matute",
  },
  {
    id: "dongato-donde",
    franchise: "Don Gato",
    emoji: "🗑️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Dónde vive la pandilla de Don Gato?",
    options: ["En un callejón", "En una casa abandonada", "En el metro", "En un tejado"],
    correct: 0,
    official: "En un callejón",
  },
  {
    id: "dongato-benito",
    franchise: "Don Gato",
    emoji: "🧢",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el gatito pequeño y despistado de la pandilla?",
    hint: "(El nombre en España.)",
    accepted: [["Benito", "Benito Bodoque", "Bodoque"]],
    official: "Benito Bodoque",
  },

  // --- Los Supersónicos ---
  {
    id: "supersonicos-epoca",
    franchise: "Los Supersónicos",
    emoji: "🚀",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué época viven Los Supersónicos?",
    options: ["En el futuro", "En la prehistoria", "En la Edad Media", "En los años 50"],
    correct: 0,
    official: "En el futuro",
  },
  {
    id: "supersonicos-picapiedra",
    franchise: "Los Supersónicos",
    emoji: "🛸",
    difficulty: "facil",
    format: "vf",
    prompt: "Los Supersónicos y Los Picapiedra son de estudios distintos y no tienen nada que ver.",
    correct: false,
    official: "Falso: son del mismo estudio, uno en la prehistoria y otro en el futuro",
  },
  {
    id: "supersonicos-robotina",
    franchise: "Los Supersónicos",
    emoji: "🤖",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la robot que se ocupa de la casa?",
    hint: "(Solo el nombre.)",
    accepted: [["Robotina"]],
    official: "Robotina",
  },

  // --- El Oso Yogui ---
  {
    id: "yogui-cestas",
    franchise: "El Oso Yogui",
    emoji: "🧺",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué le roba Yogui a los visitantes del parque?",
    hint: "(Un objeto.)",
    accepted: [["cestas", "cestas de picnic", "cesta", "la comida", "picnic"]],
    official: "Las cestas de picnic",
  },
  {
    id: "yogui-bubu",
    franchise: "El Oso Yogui",
    emoji: "🐻",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el osito pequeño que acompaña a Yogui?",
    hint: "(Solo el nombre.)",
    accepted: [["Bubu"]],
    official: "Bubu",
  },
  {
    id: "yogui-parque",
    franchise: "El Oso Yogui",
    emoji: "🌲",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el parque en el que vive Yogui?",
    options: ["Jellystone", "Yellowstone", "Pinewood", "Greenstone"],
    correct: 0,
    official: "Jellystone",
  },

  // --- Looney Tunes ---
  {
    id: "looney-zanahoria",
    franchise: "Looney Tunes",
    emoji: "🥕",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué está siempre comiendo Bugs Bunny?",
    hint: "(Una verdura.)",
    accepted: [["zanahoria", "zanahorias", "una zanahoria"]],
    official: "Zanahorias",
  },
  {
    id: "looney-frase",
    franchise: "Looney Tunes",
    emoji: "🐰",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el saludo de Bugs Bunny: «¿Qué hay de nuevo, ___?».",
    accepted: [["viejo"]],
    official: "¿Qué hay de nuevo, viejo?",
  },
  {
    id: "looney-piolin",
    franchise: "Looney Tunes",
    emoji: "🐤",
    difficulty: "facil",
    format: "describir",
    prompt: "Canario amarillo diminuto y cabezón al que un gato lleva persiguiendo toda la vida.",
    hint: "(Solo el nombre.)",
    accepted: [["Piolín"]],
    official: "Piolín",
  },
  {
    id: "looney-silvestre",
    franchise: "Looney Tunes",
    emoji: "🐈",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el gato ceceante que persigue a Piolín?",
    hint: "(Solo el nombre.)",
    accepted: [["Silvestre"]],
    official: "Silvestre",
  },
  {
    id: "looney-bugs-animal",
    franchise: "Looney Tunes",
    emoji: "🐰",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Bugs Bunny?",
    options: ["Un conejo", "Una liebre de campo", "Un canguro", "Un ratón"],
    correct: 0,
    official: "Un conejo",
  },
  {
    id: "looney-porky",
    franchise: "Looney Tunes",
    emoji: "🐷",
    difficulty: "media",
    format: "describir",
    prompt: "Cerdito tartamudo que sale al final a despedir el corto.",
    hint: "(Solo el nombre.)",
    accepted: [["Porky"]],
    official: "Porky",
  },
  {
    id: "looney-elmer",
    franchise: "Looney Tunes",
    emoji: "🔫",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el cazador calvo que nunca consigue cazar a Bugs Bunny?",
    hint: "(Solo el nombre.)",
    accepted: [["Elmer", "Elmer Gruñón"]],
    official: "Elmer",
  },
  {
    id: "looney-speedy",
    franchise: "Looney Tunes",
    emoji: "🐭",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el ratón mexicano más rápido del mundo?",
    options: ["Speedy González", "Rápido Ramírez", "Turbo Martínez", "Veloz Sánchez"],
    correct: 0,
    official: "Speedy González",
  },

  // --- Los Simpson ---
  {
    id: "simpsons-maggie",
    franchise: "Los Simpson",
    emoji: "🍼",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la bebé de la familia Simpson, la del chupete?",
    hint: "(Solo el nombre.)",
    accepted: [["Maggie"]],
    official: "Maggie",
  },
  {
    id: "simpsons-milhouse",
    franchise: "Los Simpson",
    emoji: "👓",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el mejor amigo de Bart, el de las gafas y el pelo azul?",
    hint: "(Solo el nombre.)",
    accepted: [["Milhouse"]],
    official: "Milhouse",
  },
  {
    id: "simpsons-homer",
    franchise: "Los Simpson",
    emoji: "🍩",
    difficulty: "facil",
    format: "describir",
    prompt: "Padre calvo y barrigón, adicto a las rosquillas y a la cerveza, trabaja en la central nuclear.",
    hint: "(Solo el nombre.)",
    accepted: [["Homer"]],
    official: "Homer",
  },
  {
    id: "simpsons-trabajo",
    franchise: "Los Simpson",
    emoji: "☢️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Dónde trabaja Homer Simpson?",
    options: [
      "En la central nuclear",
      "En la fábrica de rosquillas",
      "En la escuela",
      "En la taberna",
    ],
    correct: 0,
    official: "En la central nuclear",
  },
  {
    id: "simpsons-lisa",
    franchise: "Los Simpson",
    emoji: "🎷",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué instrumento toca Lisa Simpson?",
    hint: "(Un instrumento.)",
    accepted: [["saxofón", "saxo", "el saxofón"]],
    official: "El saxofón",
  },
  {
    id: "simpsons-amarillos",
    franchise: "Los Simpson",
    emoji: "💛",
    difficulty: "facil",
    format: "vf",
    prompt: "Los Simpson son de color amarillo.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "simpsons-perro",
    franchise: "Los Simpson",
    emoji: "🐕",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el perro galgo de la familia?",
    hint: "(Tres palabras.)",
    accepted: [["Ayudante de Santa Claus", "Ayudante de Papá Noel", "Ayudante"]],
    official: "Ayudante de Santa Claus",
  },
  {
    id: "simpsons-bart-frase",
    franchise: "Los Simpson",
    emoji: "🛹",
    difficulty: "media",
    format: "completar",
    prompt: "Completa lo que responde Bart cuando le pillan: «Yo no he sido, nadie me ha visto, no ___ probar nada».",
    accepted: [["podéis", "podeis", "puedes"]],
    official: "No podéis probar nada",
  },

  // --- Bob Esponja ---
  {
    id: "bobesponja-plankton",
    franchise: "Bob Esponja",
    emoji: "🦠",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el ser diminuto que quiere robar la fórmula secreta?",
    hint: "(Solo el nombre.)",
    accepted: [["Plankton", "Plancton"]],
    official: "Plankton",
  },
  {
    id: "bobesponja-trabajo",
    franchise: "Bob Esponja",
    emoji: "🍔",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuál es el trabajo de Bob Esponja?",
    options: ["Cocinero", "Camarero", "Socorrista", "Cartero"],
    correct: 0,
    official: "Cocinero",
  },
  {
    id: "bobesponja-hamburguesa",
    franchise: "Bob Esponja",
    emoji: "🍔",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la hamburguesa estrella del restaurante?",
    hint: "(Una palabra.)",
    accepted: [["Cangreburger", "cangreburguer", "cangreburguesa"]],
    official: "La Cangreburger",
  },
  {
    id: "bobesponja-carne",
    franchise: "Bob Esponja",
    emoji: "🚗",
    difficulty: "facil",
    format: "vf",
    prompt: "Bob Esponja lleva años sin conseguir aprobar el examen de conducir.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "bobesponja-arenita-quien",
    franchise: "Bob Esponja",
    emoji: "🐿️",
    difficulty: "facil",
    format: "describir",
    prompt: "Ardilla de Texas que vive bajo el mar dentro de una cúpula de aire y hace kárate.",
    hint: "(Solo el nombre.)",
    accepted: [["Arenita", "Arenita Mejillas"]],
    official: "Arenita Mejillas",
  },
  {
    id: "bobesponja-ciudad",
    franchise: "Bob Esponja",
    emoji: "🌊",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la ciudad submarina donde vive Bob Esponja?",
    options: ["Fondo de Bikini", "Ciudad Coral", "Bahía Concha", "Playa Almeja"],
    correct: 0,
    official: "Fondo de Bikini",
  },

  // --- Las Tortugas Ninja ---
  {
    id: "tortugas-leonardo",
    franchise: "Las Tortugas Ninja",
    emoji: "💙",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué color es el antifaz de Leonardo, el líder?",
    options: ["Azul", "Rojo", "Naranja", "Morado"],
    correct: 0,
    official: "Azul",
  },
  {
    id: "tortugas-alcantarillas",
    franchise: "Las Tortugas Ninja",
    emoji: "🕳️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Dónde viven las Tortugas Ninja?",
    hint: "(Un sitio.)",
    accepted: [["alcantarillas", "las alcantarillas", "alcantarilla", "cloacas"]],
    official: "En las alcantarillas",
  },
  {
    id: "tortugas-nunchakus",
    franchise: "Las Tortugas Ninja",
    emoji: "🧡",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué arma usa Miguel Ángel, el del antifaz naranja?",
    options: ["Los nunchakus", "Las katanas", "El bastón", "Los sais"],
    correct: 0,
    official: "Los nunchakus",
  },

  // --- Los Picapiedra ---
  {
    id: "picapiedra-vilma",
    franchise: "Los Picapiedra",
    emoji: "👩",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama la mujer de Pedro Picapiedra?",
    hint: "(Solo el nombre.)",
    accepted: [["Vilma"]],
    official: "Vilma",
  },
  {
    id: "picapiedra-epoca",
    franchise: "Los Picapiedra",
    emoji: "🦴",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué época viven Los Picapiedra?",
    options: ["En la prehistoria", "En la Edad Media", "En el futuro", "En el Antiguo Egipto"],
    correct: 0,
    official: "En la prehistoria",
  },
  {
    id: "picapiedra-grito",
    franchise: "Los Picapiedra",
    emoji: "📢",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa el grito de Pedro Picapiedra: «¡Yabba dabba ___!».",
    accepted: [["doo", "du", "dú"]],
    official: "¡Yabba dabba doo!",
  },

  // --- Los Pitufos ---
  {
    id: "pitufos-papa",
    franchise: "Los Pitufos",
    emoji: "🧙",
    difficulty: "facil",
    format: "describir",
    prompt: "Pitufo de barba blanca y ropa roja que manda en la aldea y prepara pociones.",
    hint: "(Dos palabras.)",
    accepted: [["Papá Pitufo", "Gran Pitufo"]],
    official: "Papá Pitufo",
  },
  {
    id: "pitufos-pantalones",
    franchise: "Los Pitufos",
    emoji: "🩳",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿De qué color son el gorro y los pantalones de casi todos los pitufos?",
    options: ["Blancos", "Rojos", "Azules", "Verdes"],
    correct: 0,
    official: "Blancos",
  },
  {
    id: "pitufos-gruñon",
    franchise: "Los Pitufos",
    emoji: "😠",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el pitufo que empieza todas sus frases con «yo odio»?",
    hint: "(Dos palabras.)",
    accepted: [["Pitufo Gruñón", "Gruñón"]],
    official: "El Pitufo Gruñón",
  },

  // --- Futurama ---
  {
    id: "futurama-fry",
    franchise: "Futurama",
    emoji: "🧊",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el repartidor de pizzas que se pasa mil años congelado?",
    hint: "(Solo el nombre.)",
    accepted: [["Fry"]],
    official: "Fry",
  },
  {
    id: "futurama-empresa",
    franchise: "Futurama",
    emoji: "📦",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama la empresa de reparto en la que trabajan?",
    options: ["Planet Express", "Space Delivery", "Cosmo Cargo", "Galaxy Post"],
    correct: 0,
    official: "Planet Express",
  },
  {
    id: "futurama-leela",
    franchise: "Futurama",
    emoji: "👁️",
    difficulty: "media",
    format: "describir",
    prompt: "Capitana de piel morada, coleta y un único ojo enorme en mitad de la cara.",
    hint: "(Solo el nombre.)",
    accepted: [["Leela"]],
    official: "Leela",
  },

  // --- Hora de aventuras ---
  {
    id: "horaaventuras-finn",
    franchise: "Hora de aventuras",
    emoji: "🎒",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el niño humano del gorro blanco con orejas?",
    hint: "(Solo el nombre.)",
    accepted: [["Finn"]],
    official: "Finn",
  },
  {
    id: "horaaventuras-reyhielo",
    franchise: "Hora de aventuras",
    emoji: "👑",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Quién es el villano de la corona mágica que secuestra princesas?",
    options: ["El Rey Hielo", "El Lich", "Marceline", "El Conde Limón"],
    correct: 0,
    official: "El Rey Hielo",
  },
  {
    id: "horaaventuras-marceline",
    franchise: "Hora de aventuras",
    emoji: "🎸",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la reina vampiro que toca el bajo?",
    hint: "(Solo el nombre.)",
    accepted: [["Marceline"]],
    official: "Marceline",
  },

  // --- Gravity Falls ---
  {
    id: "gravityfalls-stan",
    franchise: "Gravity Falls",
    emoji: "🏚️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el tío abuelo que regenta la Cabaña del Misterio?",
    hint: "(Solo el nombre.)",
    accepted: [["Stan", "tío Stan"]],
    official: "Stan",
  },
  {
    id: "gravityfalls-diario",
    franchise: "Gravity Falls",
    emoji: "📓",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué encuentra Dipper en el bosque y cambia todo el verano?",
    options: ["Un diario numerado", "Un mapa del tesoro", "Una brújula", "Una cámara"],
    correct: 0,
    official: "Un diario numerado",
  },
  {
    id: "gravityfalls-pueblo",
    franchise: "Gravity Falls",
    emoji: "🌲",
    difficulty: "facil",
    format: "vf",
    prompt: "Gravity Falls es un pueblo tranquilo y de lo más normal, sin nada raro.",
    correct: false,
    official: "Falso: está plagado de criaturas y fenómenos imposibles",
  },

  // --- Phineas y Ferb ---
  {
    id: "phineas-doofenshmirtz",
    franchise: "Phineas y Ferb",
    emoji: "🥼",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el científico malvado al que se enfrenta Perry?",
    hint: "(El apellido basta.)",
    accepted: [["Doofenshmirtz", "Doofenshmirt", "Doof"]],
    official: "El doctor Doofenshmirtz",
  },
  {
    id: "phineas-frase",
    franchise: "Phineas y Ferb",
    emoji: "🔨",
    difficulty: "facil",
    format: "completar",
    prompt: "Completa lo que dice Phineas cada mañana: «Ferb, ya sé lo que vamos a hacer ___».",
    accepted: [["hoy"]],
    official: "Ya sé lo que vamos a hacer hoy",
  },
  {
    id: "phineas-verano",
    franchise: "Phineas y Ferb",
    emoji: "☀️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿A qué dedican los hermanos cada día de sus vacaciones de verano?",
    options: [
      "A construir un invento enorme",
      "A irse de viaje",
      "A buscar un tesoro",
      "A montar un negocio",
    ],
    correct: 0,
    official: "A construir un invento enorme",
  },

  // --- Las Supernenas ---
  {
    id: "supernenas-profesor",
    franchise: "Las Supernenas",
    emoji: "🧪",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el científico que crea a las Supernenas?",
    hint: "(El apellido.)",
    accepted: [["Utonio", "profesor Utonio"]],
    official: "El profesor Utonio",
  },
  {
    id: "supernenas-ingrediente",
    franchise: "Las Supernenas",
    emoji: "⚗️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué ingrediente accidental les dio los superpoderes?",
    options: ["La sustancia X", "Un rayo cósmico", "Un meteorito", "Una vacuna"],
    correct: 0,
    official: "La sustancia X",
  },

  // --- Steven Universe ---
  {
    id: "steven-playa",
    franchise: "Steven Universe",
    emoji: "🏖️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo se llama el pueblo costero donde vive Steven?",
    options: ["Ciudad Playa", "Bahía Gema", "Costa Cristal", "Puerto Rosa"],
    correct: 0,
    official: "Ciudad Playa",
  },
  {
    id: "steven-gema",
    franchise: "Steven Universe",
    emoji: "💎",
    difficulty: "facil",
    format: "vf",
    prompt: "Steven lleva la gema heredada de su madre incrustada en la frente.",
    correct: false,
    official: "Falso: la lleva en el ombligo",
  },

  // --- El asombroso mundo de Gumball ---
  {
    id: "gumball-hermana",
    franchise: "El asombroso mundo de Gumball",
    emoji: "🐰",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la hermana pequeña y superdotada de Gumball?",
    hint: "(Solo el nombre.)",
    accepted: [["Anaïs", "Anais"]],
    official: "Anaïs",
  },
  {
    id: "gumball-animal",
    franchise: "El asombroso mundo de Gumball",
    emoji: "🐱",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Gumball?",
    options: ["Un gato azul", "Un conejo azul", "Un perro azul", "Un ratón azul"],
    correct: 0,
    official: "Un gato azul",
  },

  // --- Avatar ---
  {
    id: "avatar-aang",
    franchise: "Avatar: la leyenda de Aang",
    emoji: "💨",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el niño calvo con la flecha azul tatuada en la cabeza?",
    hint: "(Solo el nombre.)",
    accepted: [["Aang"]],
    official: "Aang",
  },
  {
    id: "avatar-elementos",
    franchise: "Avatar: la leyenda de Aang",
    emoji: "🔥",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuáles son los cuatro elementos que se dominan en Avatar?",
    options: [
      "Agua, tierra, fuego y aire",
      "Agua, hielo, fuego y viento",
      "Tierra, metal, fuego y aire",
      "Agua, tierra, rayo y aire",
    ],
    correct: 0,
    official: "Agua, tierra, fuego y aire",
  },
  {
    id: "avatar-zuko",
    franchise: "Avatar: la leyenda de Aang",
    emoji: "🔥",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el príncipe desterrado de la Nación del Fuego con una cicatriz en el ojo?",
    hint: "(Solo el nombre.)",
    accepted: [["Zuko"]],
    official: "Zuko",
  },

  // --- Ben 10 ---
  {
    id: "ben10-prima",
    franchise: "Ben 10",
    emoji: "👧",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la prima de Ben que viaja con él?",
    hint: "(Solo el nombre.)",
    accepted: [["Gwen"]],
    official: "Gwen",
  },
  {
    id: "ben10-que-hace",
    franchise: "Ben 10",
    emoji: "⌚",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué le permite hacer a Ben el reloj que encuentra?",
    options: [
      "Convertirse en alienígenas",
      "Viajar en el tiempo",
      "Volverse invisible",
      "Hablar con animales",
    ],
    correct: 0,
    official: "Convertirse en alienígenas",
  },

  // --- Scooby-Doo ---
  {
    id: "scooby-shaggy",
    franchise: "Scooby-Doo",
    emoji: "🥪",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el chico flacucho y tragón, mejor amigo de Scooby?",
    hint: "(Solo el nombre.)",
    accepted: [["Shaggy"]],
    official: "Shaggy",
  },
  {
    id: "scooby-animal",
    franchise: "Scooby-Doo",
    emoji: "🐕",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué raza de perro es Scooby-Doo?",
    options: ["Un gran danés", "Un labrador", "Un dogo", "Un San Bernardo"],
    correct: 0,
    official: "Un gran danés",
  },
  {
    id: "scooby-monstruos",
    franchise: "Scooby-Doo",
    emoji: "👻",
    difficulty: "facil",
    format: "vf",
    prompt: "En Scooby-Doo, los monstruos casi siempre resultan ser una persona disfrazada.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "scooby-galletas",
    franchise: "Scooby-Doo",
    emoji: "🍪",
    difficulty: "media",
    format: "corta",
    prompt: "¿Con qué se soborna a Scooby para que se atreva a entrar en un sitio?",
    hint: "(Una chuchería.)",
    accepted: [["galletas", "Scooby galletas", "una galleta"]],
    official: "Con Scooby galletas",
  },

  // --- Conjuntos ---
  {
    id: "relacionar-hannabarbera",
    franchise: "Series de dibujos",
    emoji: "📺",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada personaje con su serie.",
    pairs: [
      { left: "Patán", right: "Los Autos Locos" },
      { left: "Bubu", right: "El Oso Yogui" },
      { left: "Benito Bodoque", right: "Don Gato" },
      { left: "Robotina", right: "Los Supersónicos" },
    ],
    official:
      "Patán–Los Autos Locos, Bubu–El Oso Yogui, Benito Bodoque–Don Gato y Robotina–Los Supersónicos",
  },
  {
    id: "relacionar-looney",
    franchise: "Series de dibujos",
    emoji: "🐰",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada personaje de los Looney Tunes con lo que le define.",
    pairs: [
      { left: "Bugs Bunny", right: "La zanahoria" },
      { left: "Piolín", right: "La jaula" },
      { left: "El Coyote", right: "Los inventos de ACME" },
      { left: "Porky", right: "El tartamudeo" },
    ],
    official:
      "Bugs Bunny–la zanahoria, Piolín–la jaula, el Coyote–los inventos de ACME y Porky–el tartamudeo",
  },
  {
    id: "orden-hannabarbera",
    franchise: "Series de dibujos",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de la más antigua a la más reciente.",
    items: ["Los Picapiedra", "Los Supersónicos", "El Oso Yogui", "Los Autos Locos"],
    official:
      "El Oso Yogui (1958), Los Picapiedra (1960), Los Supersónicos (1962) y Los Autos Locos (1968)",
  },
  {
    id: "relacionar-parejas-persecucion",
    franchise: "Mascotas de series",
    emoji: "🏃",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada perseguidor con su perseguido.",
    pairs: [
      { left: "Tom", right: "Jerry" },
      { left: "Silvestre", right: "Piolín" },
      { left: "El Coyote", right: "El Correcaminos" },
      { left: "Gargamel", right: "Los pitufos" },
    ],
    official:
      "Tom–Jerry, Silvestre–Piolín, el Coyote–el Correcaminos y Gargamel–los pitufos",
  },
  {
    id: "series-dibujos-dificil",
    franchise: "Series de dibujos",
    emoji: "🏢",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué estudio está detrás de Los Picapiedra, Don Gato y El Oso Yogui?",
    options: ["Hanna-Barbera", "Warner Bros.", "MGM", "Disney"],
    correct: 0,
    official: "Hanna-Barbera",
  },

  // --- Disney Channel: animación de los 2000 y 2010 ---
  {
    id: "casamickey-formato",
    franchise: "La casa de Mickey Mouse",
    emoji: "🏠",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué le pide la serie al espectador todo el rato?",
    options: [
      "Que participe y conteste en voz alta",
      "Que cante el final",
      "Que dibuje",
      "Que adivine el villano",
    ],
    correct: 0,
    official: "Que participe y conteste, es una serie interactiva",
  },
  {
    id: "casamickey-pandilla",
    franchise: "La casa de Mickey Mouse",
    emoji: "🐭",
    difficulty: "facil",
    format: "vf",
    prompt: "En La casa de Mickey Mouse salen Minnie, Donald, Daisy, Goofy y Pluto.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "casamickey-publico",
    franchise: "La casa de Mickey Mouse",
    emoji: "🧸",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿A qué público va dirigida?",
    options: ["A los más pequeños", "A adolescentes", "A adultos", "A toda la familia por igual"],
    correct: 0,
    official: "A preescolar",
  },
  {
    id: "lilostitch-serie",
    franchise: "Lilo & Stitch",
    emoji: "👽",
    difficulty: "media",
    format: "multiple",
    prompt: "¿A qué se dedican Lilo y Stitch en la serie de televisión?",
    options: [
      "A capturar los demás experimentos",
      "A viajar por el espacio",
      "A montar un negocio",
      "A ir al colegio",
    ],
    correct: 0,
    official: "A capturar a los demás experimentos de Jumba",
  },
  {
    id: "americandragon-jake",
    franchise: "American Dragon",
    emoji: "🐲",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué le pasa a Jake Long, el protagonista?",
    options: [
      "Puede convertirse en dragón",
      "Puede volar sin más",
      "Lee la mente",
      "Se hace invisible",
    ],
    correct: 0,
    official: "Puede convertirse en dragón",
  },
  {
    id: "kuzco-cole",
    franchise: "El emperador y sus locuras",
    emoji: "🎒",
    difficulty: "media",
    format: "vf",
    prompt: "La serie derivada de la película manda a Kuzco al colegio para poder ser emperador.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "doctorajuguetes-oficio",
    franchise: "Doctora Juguetes",
    emoji: "🩺",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿A qué se dedica la Doctora Juguetes?",
    options: ["A curar juguetes", "A fabricar juguetes", "A venderlos", "A coleccionarlos"],
    correct: 0,
    official: "A curar juguetes",
  },
  {
    id: "doctorajuguetes-estetoscopio",
    franchise: "Doctora Juguetes",
    emoji: "✨",
    difficulty: "facil",
    format: "vf",
    prompt: "Los juguetes cobran vida cuando ella se pone su estetoscopio.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "jakepiratas-villano",
    franchise: "Jake y los piratas de Nunca Jamás",
    emoji: "🏴‍☠️",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué pirata clásico de Disney hace de villano en esta serie?",
    hint: "(Solo el nombre.)",
    accepted: [["Garfio", "capitán Garfio"]],
    official: "El capitán Garfio",
  },
  {
    id: "jakepiratas-mundo",
    franchise: "Jake y los piratas de Nunca Jamás",
    emoji: "🗺️",
    difficulty: "facil",
    format: "vf",
    prompt: "La serie transcurre en la Isla del Tesoro, la de Long John Silver.",
    correct: false,
    official: "Falso: transcurre en el País de Nunca Jamás, el de Peter Pan",
  },
  {
    id: "sofia-amuleto",
    franchise: "Sofía la Primera",
    emoji: "💜",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cómo se convierte Sofía en princesa?",
    options: [
      "Su madre se casa con el rey",
      "Gana un concurso",
      "La adopta una reina",
      "Encuentra una corona",
    ],
    correct: 0,
    official: "Su madre se casa con el rey",
  },
  {
    id: "sofia-princesas",
    franchise: "Sofía la Primera",
    emoji: "👑",
    difficulty: "media",
    format: "vf",
    prompt: "En la serie aparecen de visita princesas Disney clásicas como Cenicienta o Ariel.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "star-varita",
    franchise: "Star contra las fuerzas del mal",
    emoji: "🪄",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué es Star Butterfly?",
    options: [
      "Una princesa mágica de otra dimensión",
      "Una alienígena",
      "Una bruja de la Tierra",
      "Una robot",
    ],
    correct: 0,
    official: "Una princesa mágica de otra dimensión",
  },
  {
    id: "star-marco",
    franchise: "Star contra las fuerzas del mal",
    emoji: "🌎",
    difficulty: "media",
    format: "vf",
    prompt: "Star llega a la Tierra y se instala ella sola en un castillo abandonado.",
    correct: false,
    official: "Falso: se instala en casa de un chico, Marco",
  },
  {
    id: "randy-ninja",
    franchise: "Randy Cunningham",
    emoji: "🥷",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué es Randy Cunningham además de estudiante?",
    options: ["El ninja del instituto", "Un mago", "Un detective", "Un piloto"],
    correct: 0,
    official: "El ninja que protege el instituto",
  },
  {
    id: "pecezuelos-donde",
    franchise: "Pecezuelos",
    emoji: "🐠",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Dónde transcurre Pecezuelos?",
    options: [
      "En un instituto dentro de una pecera",
      "En el fondo del mar",
      "En un acuario público",
      "En un río",
    ],
    correct: 0,
    official: "En un instituto dentro de una pecera de tienda",
  },
  {
    id: "reemplazantes-telefono",
    franchise: "Los reemplazantes",
    emoji: "☎️",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué pueden hacer los hermanos protagonistas con su teléfono?",
    options: [
      "Sustituir a cualquier adulto por otro",
      "Viajar en el tiempo",
      "Pedir cualquier objeto",
      "Hablar con animales",
    ],
    correct: 0,
    official: "Sustituir a cualquier adulto que les moleste por otro",
  },
  {
    id: "wander-viajero",
    franchise: "Wander",
    emoji: "🧡",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo es Wander, el protagonista naranja de esta serie?",
    options: [
      "Un viajero optimista que recorre la galaxia",
      "Un soldado",
      "Un científico",
      "Un ladrón",
    ],
    correct: 0,
    official: "Un viajero optimista que recorre la galaxia ayudando a todo el mundo",
  },

  // --- Clan ---
  {
    id: "caillou-edad",
    franchise: "Caillou",
    emoji: "👦",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué llama la atención del aspecto de Caillou?",
    options: ["Que es calvo", "Que es pelirrojo", "Que lleva gafas", "Que es muy alto"],
    correct: 0,
    official: "Que es calvo",
  },
  {
    id: "caillou-hermana",
    franchise: "Caillou",
    emoji: "👧",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama la hermana pequeña de Caillou?",
    hint: "(Solo el nombre.)",
    accepted: [["Rosie", "Rosita"]],
    official: "Rosie",
  },
  {
    id: "lazytown-sportacus",
    franchise: "Lazy Town",
    emoji: "🤸",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué predica Sportacus, el héroe de bigote azul?",
    options: [
      "Hacer deporte y comer sano",
      "Estudiar mucho",
      "Ahorrar dinero",
      "Dormir bien",
    ],
    correct: 0,
    official: "Hacer deporte y comer sano",
  },
  {
    id: "lazytown-robbie",
    franchise: "Lazy Town",
    emoji: "😈",
    difficulty: "media",
    format: "corta",
    prompt: "¿Cómo se llama el villano vago que quiere que todos sigan siendo perezosos?",
    hint: "(Dos palabras.)",
    accepted: [["Robbie Rotten", "Robbie"]],
    official: "Robbie Rotten",
  },
  {
    id: "lazytown-stephanie",
    franchise: "Lazy Town",
    emoji: "🩷",
    difficulty: "media",
    format: "vf",
    prompt: "La niña protagonista de Lazy Town tiene el pelo azul.",
    correct: false,
    official: "Falso: lo tiene rosa",
  },
  {
    id: "dora-mochila",
    franchise: "Dora la exploradora",
    emoji: "🎒",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué dos objetos ayudan a Dora en cada aventura?",
    options: ["La mochila y el mapa", "Una brújula y una linterna", "Un cuaderno y un lápiz", "Un móvil y unas llaves"],
    correct: 0,
    official: "La mochila y el mapa",
  },
  {
    id: "dora-zorro",
    franchise: "Dora la exploradora",
    emoji: "🦊",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el zorro que intenta robarles las cosas?",
    hint: "(Solo el nombre.)",
    accepted: [["Swiper", "Zorro", "el Zorro"]],
    official: "Swiper, el Zorro",
  },
  {
    id: "dora-idioma",
    franchise: "Dora la exploradora",
    emoji: "🗣️",
    difficulty: "media",
    format: "vf",
    prompt: "La serie original enseña palabras en español a niños de habla inglesa.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "backyardigans-patio",
    franchise: "Los Backyardigans",
    emoji: "🏡",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Dónde ocurren de verdad las aventuras de los Backyardigans?",
    options: [
      "En el patio de casa, imaginándolas",
      "En un mundo mágico",
      "En el espacio",
      "En un parque de atracciones",
    ],
    correct: 0,
    official: "En el patio de casa: se lo imaginan todo",
  },
  {
    id: "backyardigans-musica",
    franchise: "Los Backyardigans",
    emoji: "🎵",
    difficulty: "media",
    format: "vf",
    prompt: "Todos los episodios de Los Backyardigans usan el mismo estilo musical.",
    correct: false,
    official: "Falso: cada uno va con un estilo distinto",
  },
  {
    id: "littleeinsteins-nave",
    franchise: "Little Einsteins",
    emoji: "🚀",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué viajan los cuatro niños de Little Einsteins?",
    options: ["En un cohete", "En un tren", "En un barco", "En un globo"],
    correct: 0,
    official: "En un cohete",
  },
  {
    id: "littleeinsteins-tema",
    franchise: "Little Einsteins",
    emoji: "🎻",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué enseña la serie en cada episodio?",
    options: [
      "Música clásica y obras de arte",
      "Matemáticas",
      "Idiomas",
      "Historia natural",
    ],
    correct: 0,
    official: "Música clásica y obras de arte famosas",
  },
  {
    id: "garfield-lasana",
    franchise: "El show de Garfield",
    emoji: "🍝",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cuál es la comida favorita de Garfield?",
    hint: "(Un plato.)",
    accepted: [["lasaña", "lasagna", "la lasaña"]],
    official: "La lasaña",
  },
  {
    id: "garfield-odie",
    franchise: "El show de Garfield",
    emoji: "🐶",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el perro baboso que convive con Garfield?",
    hint: "(Solo el nombre.)",
    accepted: [["Odie"]],
    official: "Odie",
  },
  {
    id: "garfield-lunes",
    franchise: "El show de Garfield",
    emoji: "😾",
    difficulty: "facil",
    format: "vf",
    prompt: "Garfield adora los lunes y odia dormir.",
    correct: false,
    official: "Falso: odia los lunes y le encanta dormir",
  },

  // --- Animación española de la época ---
  {
    id: "bernard-oso",
    franchise: "Bernard",
    emoji: "🐻‍❄️",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animal es Bernard, el protagonista de esta serie sin diálogos?",
    options: ["Un oso polar", "Un pingüino", "Una foca", "Un lobo"],
    correct: 0,
    official: "Un oso polar",
  },
  {
    id: "bernard-final",
    franchise: "Bernard",
    emoji: "🤕",
    difficulty: "media",
    format: "vf",
    prompt: "En casi todos los episodios, a Bernard le acaba saliendo todo mal y se hace daño.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "jellyjamm-planeta",
    franchise: "Jelly Jamm",
    emoji: "🎵",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué tiene de especial el planeta de Jelly Jamm?",
    options: [
      "Es donde nace la música del universo",
      "Está hecho de gelatina",
      "No tiene gravedad",
      "Es todo de agua",
    ],
    correct: 0,
    official: "Es donde nace la música del universo",
  },
  {
    id: "jellyjamm-origen",
    franchise: "Jelly Jamm",
    emoji: "🇪🇸",
    difficulty: "media",
    format: "vf",
    prompt: "Jelly Jamm es una serie de producción española.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "luckyfred-robot",
    franchise: "Lucky Fred",
    emoji: "🤖",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué le toca en suerte a Fred en esta serie española?",
    options: ["Un robot que puede transformarse en cualquier cosa", "Un coche volador", "Un perro que habla", "Una casa nueva"],
    correct: 0,
    official: "Un robot capaz de transformarse en lo que sea",
  },
  {
    id: "sandra-cuentos",
    franchise: "Sandra detective de cuentos",
    emoji: "🔎",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué investiga Sandra en esta serie española?",
    options: [
      "Casos dentro de los cuentos clásicos",
      "Robos en su barrio",
      "Fenómenos paranormales",
      "Desapariciones de animales",
    ],
    correct: 0,
    official: "Casos que ocurren dentro de los cuentos clásicos",
  },

  // --- Boing y Cartoon Network de la época ---
  {
    id: "historiascorrientes-trabajo",
    franchise: "Historias corrientes",
    emoji: "🌳",
    difficulty: "media",
    format: "multiple",
    prompt: "¿En qué trabajan Mordecai y Rigby?",
    options: ["De jardineros en un parque", "En una tienda", "En un restaurante", "En una fábrica"],
    correct: 0,
    official: "De jardineros en un parque",
  },
  {
    id: "historiascorrientes-animales",
    franchise: "Historias corrientes",
    emoji: "🦝",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué animales son Mordecai y Rigby?",
    options: ["Un arrendajo y un mapache", "Un cuervo y una nutria", "Un loro y un zorro", "Un búho y un tejón"],
    correct: 0,
    official: "Un arrendajo azul y un mapache",
  },
  {
    id: "historiascorrientes-tono",
    franchise: "Historias corrientes",
    emoji: "🌀",
    difficulty: "media",
    format: "vf",
    prompt:
      "En Historias corrientes las tareas del parque se resuelven siempre de forma normal y aburrida.",
    correct: false,
    official: "Falso: la tontería más pequeña acaba en aventura disparatada",
  },
  {
    id: "clarence-caracter",
    franchise: "Clarence",
    emoji: "😄",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Cómo es Clarence, el protagonista?",
    options: [
      "Un niño gordito y optimista al que todo le parece genial",
      "Un niño tímido",
      "Un niño gruñón",
      "Un niño superdotado",
    ],
    correct: 0,
    official: "Un niño gordito y optimista",
  },
  {
    id: "clarence-amigos",
    franchise: "Clarence",
    emoji: "👬",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llaman los dos mejores amigos de Clarence?",
    options: ["Jeff y Sumo", "Jeff y Max", "Sumo y Leo", "Tom y Sumo"],
    correct: 0,
    official: "Jeff y Sumo",
  },
  {
    id: "generatorrex-poder",
    franchise: "Generator Rex",
    emoji: "🦾",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Qué puede hacer Rex con su cuerpo?",
    options: [
      "Transformar partes en máquinas y armas",
      "Volverse líquido",
      "Duplicarse",
      "Volar sin traje",
    ],
    correct: 0,
    official: "Transformar partes de su cuerpo en máquinas",
  },

  // --- Anime de la época ---
  {
    id: "yokai-reloj",
    franchise: "Yo-Kai Watch",
    emoji: "⌚",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Para qué sirve el reloj de Yo-Kai Watch?",
    options: [
      "Para ver espíritus invisibles",
      "Para viajar en el tiempo",
      "Para volar",
      "Para hablar con animales",
    ],
    correct: 0,
    official: "Para ver a los yokai, espíritus invisibles",
  },
  {
    id: "yokai-jibanyan",
    franchise: "Yo-Kai Watch",
    emoji: "🐱",
    difficulty: "dificil",
    format: "multiple",
    prompt: "¿Cómo se llama el yokai gato rojo más famoso de la serie?",
    options: ["Jibanyan", "Komasan", "Whisper", "Nyanko"],
    correct: 0,
    official: "Jibanyan",
  },
  {
    id: "inazuma-deporte",
    franchise: "Inazuma Eleven",
    emoji: "⚽",
    difficulty: "facil",
    format: "corta",
    prompt: "¿A qué deporte se juega en Inazuma Eleven?",
    hint: "(Un deporte.)",
    accepted: [["fútbol", "futbol"]],
    official: "Al fútbol",
  },
  {
    id: "inazuma-tecnicas",
    franchise: "Inazuma Eleven",
    emoji: "🔥",
    difficulty: "media",
    format: "vf",
    prompt: "En Inazuma Eleven los jugadores usan supertécnicas con nombre propio y efectos imposibles.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "bakugan-bolas",
    franchise: "Bakugan",
    emoji: "🔴",
    difficulty: "media",
    format: "multiple",
    prompt: "¿Qué son los bakugan?",
    options: [
      "Bolas que se abren y se convierten en criaturas",
      "Cartas mágicas",
      "Robots gigantes",
      "Espíritus",
    ],
    correct: 0,
    official: "Bolas que al lanzarlas se abren y se convierten en criaturas",
  },
  {
    id: "ninjago-lego",
    franchise: "Lego Ninjago",
    emoji: "🧱",
    difficulty: "facil",
    format: "vf",
    prompt: "Los personajes de Ninjago son figuras de Lego.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "ninjago-elementos",
    franchise: "Lego Ninjago",
    emoji: "🥷",
    difficulty: "media",
    format: "vf",
    prompt: "Todos los ninjas de Ninjago dominan exactamente el mismo elemento.",
    correct: false,
    official: "Falso: cada uno domina el suyo, como el fuego o el hielo",
  },

  // --- Conjuntos ---
  {
    id: "relacionar-preescolar-2000",
    franchise: "Series preescolares",
    emoji: "🧸",
    difficulty: "facil",
    format: "relacionar",
    prompt: "Relaciona cada personaje con su serie.",
    pairs: [
      { left: "Rosie", right: "Caillou" },
      { left: "Sportacus", right: "Lazy Town" },
      { left: "Swiper", right: "Dora la exploradora" },
      { left: "Odie", right: "El show de Garfield" },
    ],
    official:
      "Rosie–Caillou, Sportacus–Lazy Town, Swiper–Dora la exploradora y Odie–El show de Garfield",
  },
  {
    id: "relacionar-disney-2000",
    franchise: "Disney reciente",
    emoji: "📺",
    difficulty: "media",
    format: "relacionar",
    prompt: "Relaciona cada serie de Disney con su premisa.",
    pairs: [
      { left: "Doctora Juguetes", right: "Cura juguetes" },
      { left: "Jake y los piratas", right: "Aventuras en Nunca Jamás" },
      { left: "American Dragon", right: "Un chico que se vuelve dragón" },
      { left: "Sofía la Primera", right: "Una niña que pasa a ser princesa" },
    ],
    official:
      "Doctora Juguetes–cura juguetes, Jake y los piratas–Nunca Jamás, American Dragon–un chico dragón y Sofía la Primera–una niña que pasa a ser princesa",
  },
  {
    id: "orden-infantil-2000",
    franchise: "Series preescolares",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de la más antigua a la más reciente.",
    items: ["Dora la exploradora", "Lazy Town", "La casa de Mickey Mouse", "Doctora Juguetes"],
    official:
      "Dora la exploradora (2000), Lazy Town (2004), La casa de Mickey Mouse (2006) y Doctora Juguetes (2012)",
  },
  {
    id: "orden-boing-2010",
    franchise: "Series de dibujos",
    emoji: "🎞️",
    difficulty: "media",
    format: "orden",
    prompt: "Ordena estas series de la más antigua a la más reciente.",
    items: ["Historias corrientes", "Lego Ninjago", "Clarence", "Somos osos"],
    official:
      "Historias corrientes (2010), Lego Ninjago (2011), Clarence (2014) y Somos osos (2015)",
  },
  {
    id: "casamickey-toodles",
    franchise: "La casa de Mickey Mouse",
    emoji: "🧰",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Para qué llama Mickey a Toodles en cada episodio?",
    options: [
      "Para que le traiga las herramientas que necesita",
      "Para que cante",
      "Para que abra la puerta",
      "Para que cuente un cuento",
    ],
    correct: 0,
    official: "Para que le traiga las mickeyherramientas",
  },
  {
    id: "dora-botas-animal",
    franchise: "Dora la exploradora",
    emoji: "🐵",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Qué animal es Botas, el amigo de Dora?",
    options: ["Un mono", "Un perro", "Un oso", "Un zorro"],
    correct: 0,
    official: "Un mono",
  },
  {
    id: "caillou-familia",
    franchise: "Caillou",
    emoji: "🐈",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Qué mascota tiene la familia de Caillou?",
    hint: "(Un animal.)",
    accepted: [["gato", "un gato", "gata"]],
    official: "Un gato, Gilbert",
  },
  {
    id: "garfield-dueno",
    franchise: "El show de Garfield",
    emoji: "🧑",
    difficulty: "facil",
    format: "corta",
    prompt: "¿Cómo se llama el dueño de Garfield?",
    hint: "(Solo el nombre.)",
    accepted: [["Jon"]],
    official: "Jon",
  },
  {
    id: "lazytown-formato",
    franchise: "Lazy Town",
    emoji: "🎭",
    difficulty: "facil",
    format: "vf",
    prompt: "Lazy Town mezcla actores de carne y hueso con muñecos.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "doctorajuguetes-color",
    franchise: "Doctora Juguetes",
    emoji: "🧸",
    difficulty: "facil",
    format: "vf",
    prompt: "La Doctora Juguetes es una niña que quiere ser médica como su madre.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "sofia-edad",
    franchise: "Sofía la Primera",
    emoji: "👑",
    difficulty: "facil",
    format: "vf",
    prompt: "Sofía nació princesa y siempre vivió en palacio.",
    correct: false,
    official: "Falso: era una niña normal hasta que su madre se casó con el rey",
  },
  {
    id: "inazuma-portero",
    franchise: "Inazuma Eleven",
    emoji: "🥅",
    difficulty: "facil",
    format: "vf",
    prompt: "En Inazuma Eleven los partidos se juegan con las reglas normales del fútbol y sin nada raro.",
    correct: false,
    official: "Falso: hay técnicas imposibles con nombre propio",
  },
  {
    id: "ninjago-armas",
    franchise: "Lego Ninjago",
    emoji: "⚔️",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿A qué se dedican los protagonistas de Ninjago?",
    options: ["Son ninjas", "Son piratas", "Son astronautas", "Son bomberos"],
    correct: 0,
    official: "Son ninjas",
  },
  {
    id: "bakugan-lanzar",
    franchise: "Bakugan",
    emoji: "🎯",
    difficulty: "facil",
    format: "vf",
    prompt: "En Bakugan, los jugadores lanzan sus bolas sobre cartas para hacerlas abrirse.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "yokai-invisibles",
    franchise: "Yo-Kai Watch",
    emoji: "👻",
    difficulty: "facil",
    format: "vf",
    prompt: "Los yokai son visibles para todo el mundo sin necesidad de nada.",
    correct: false,
    official: "Falso: solo se ven con el reloj",
  },
  {
    id: "historiascorrientes-parque",
    franchise: "Historias corrientes",
    emoji: "🌳",
    difficulty: "facil",
    format: "vf",
    prompt: "Mordecai y Rigby son dos animales que hablan y trabajan como cualquier persona.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "clarence-tono",
    franchise: "Clarence",
    emoji: "🌈",
    difficulty: "facil",
    format: "vf",
    prompt: "Clarence es un niño amargado al que nada le parece bien.",
    correct: false,
    official: "Falso: es justo lo contrario, todo le parece estupendo",
  },
  {
    id: "backyardigans-cuantos",
    franchise: "Los Backyardigans",
    emoji: "🐧",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuántos amigos protagonizan Los Backyardigans?",
    options: ["Cinco", "Tres", "Cuatro", "Seis"],
    correct: 0,
    official: "Cinco",
  },
  {
    id: "littleeinsteins-cuantos",
    franchise: "Little Einsteins",
    emoji: "🧒",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿Cuántos niños forman el equipo de Little Einsteins?",
    options: ["Cuatro", "Tres", "Cinco", "Dos"],
    correct: 0,
    official: "Cuatro",
  },
  {
    id: "lilostitch-experimentos",
    franchise: "Lilo & Stitch",
    emoji: "🧪",
    difficulty: "facil",
    format: "vf",
    prompt: "En la serie, Stitch no es el único experimento de Jumba: hay muchos más sueltos.",
    correct: true,
    official: "Verdadero",
  },
  {
    id: "americandragon-ciudad",
    franchise: "American Dragon",
    emoji: "🗽",
    difficulty: "facil",
    format: "multiple",
    prompt: "¿En qué ciudad vive Jake Long?",
    options: ["Nueva York", "Los Ángeles", "Chicago", "San Francisco"],
    correct: 0,
    official: "Nueva York",
  },
];
