/**
 * Categorías del banco.
 *
 * La categoría NO es un campo de cada pregunta, sino un mapa de franquicia a
 * categoría que vive aquí. Son 273 franquicias y 1183 preguntas: tocar 1183
 * objetos para repetir un dato que ya se deduce de la franquicia sería pedir
 * que se desincronicen. Con el mapa hay un único sitio donde mirar y donde
 * corregir.
 *
 * Por lo mismo vive aquí el emoji: también se deduce de la categoría.
 *
 * `validarBanco()` comprueba que toda franquicia del banco esté aquí, así que
 * añadir una franquicia nueva sin categoría rompe `npm run validar`.
 */

export const CATEGORIAS = [
  "Disney",
  "Pixar",
  "DreamWorks",
  "Illumination",
  "Ghibli",
  "Anime",
  "Series de dibujos",
  "Infantil",
  "Animación española",
  "Superhéroes",
  "Series de imagen real",
  "Otros estudios",

  // Tema Música.
  "Trap y rap latino",
  "Reggaetón",
  "Música española",
  "Salsa y pop latino",
  "Pop internacional",
  "Los 2000 en inglés",

  // Tema Historia. Se agrupa por cultura y no por siglos a propósito: el
  // objetivo del tema es que Europa sea una más, y ordenar por épocas la
  // devolvería al centro, porque «Edad Media» o «Edad Moderna» son cortes
  // europeos que no significan lo mismo en China, en Malí o en el Pacífico.
  "Mesopotamia y Egipto",
  "Grecia y Roma",
  "China",
  "Japón y Corea",
  "India",
  "El mundo islámico",
  "África",
  "América precolombina",
  "Oceanía y el Pacífico",
  "Europa medieval y moderna",
  "El mundo contemporáneo",
] as const;

export type Categoria = (typeof CATEGORIAS)[number];

/**
 * Se agrupa por estudio o por origen, que es como lo tiene clasificado
 * cualquiera que vea dibujos. Ratatouille es Pixar aunque su pregunta viva en
 * `banco/disney.ts`: manda la franquicia, no en qué fichero se escribió.
 */
const POR_FRANQUICIA: Record<string, Categoria> = {
  // --- Disney ---
  "101 dálmatas": "Disney",
  Aladdín: "Disney",
  "Alicia en el País de las Maravillas": "Disney",
  Atlantis: "Disney",
  Bambi: "Disney",
  "Big Hero 6": "Disney",
  Blancanieves: "Disney",
  Bolt: "Disney",
  Cenicienta: "Disney",
  "Clásicos Disney": "Disney",
  "Compañeros Disney": "Disney",
  "Disney años 90 y 2000": "Disney",
  "Disney reciente": "Disney",
  Dumbo: "Disney",
  "El Rey León": "Disney",
  "El emperador y sus locuras": "Disney",
  "El jorobado de Notre Dame": "Disney",
  "El libro de la selva": "Disney",
  "El planeta del tesoro": "Disney",
  Encanto: "Disney",
  Enredados: "Disney",
  Frozen: "Disney",
  "Hermano Oso": "Disney",
  Hércules: "Disney",
  "La Bella Durmiente": "Disney",
  "La Bella y la Bestia": "Disney",
  "La Sirenita": "Disney",
  "Lilo & Stitch": "Disney",
  "Los Aristogatos": "Disney",
  "Los Rescatadores": "Disney",
  "Mascotas Disney": "Disney",
  "Mickey Mouse": "Disney",
  Mulán: "Disney",
  "Pato Donald": "Disney",
  "Peter Pan": "Disney",
  Pinocho: "Disney",
  Pocahontas: "Disney",
  "Princesas Disney": "Disney",
  "Raya y el último dragón": "Disney",
  "Robin Hood": "Disney",
  "Rompe Ralph": "Disney",
  Tarzán: "Disney",
  "Tiana y el sapo": "Disney",
  "Tod y Toby": "Disney",
  Vaiana: "Disney",
  "Villanos Disney": "Disney",
  "Winnie the Pooh": "Disney",
  Wish: "Disney",
  Zootrópolis: "Disney",

  Fantasía: "Disney",
  "La dama y el vagabundo": "Disney",
  "Merlín el encantador": "Disney",
  "Basil el ratón superdetective": "Disney",
  "Oliver y su pandilla": "Disney",
  "El caldero mágico": "Disney",
  "Chicken Little": "Disney",

  // --- Pixar ---
  Bichos: "Pixar",
  Brave: "Pixar",
  "Buscando a Dory": "Pixar",
  "Buscando a Nemo": "Pixar",
  Cars: "Pixar",
  Coco: "Pixar",
  "Del revés": "Pixar",
  "El viaje de Arlo": "Pixar",
  Elemental: "Pixar",
  "Los Increíbles": "Pixar",
  Luca: "Pixar",
  "Monstruos S.A.": "Pixar",
  "Monstruos University": "Pixar",
  Onward: "Pixar",
  "Pixar clásico": "Pixar",
  "Pixar reciente": "Pixar",
  Ratatouille: "Pixar",
  Red: "Pixar",
  Soul: "Pixar",
  "Toy Story": "Pixar",
  Up: "Pixar",
  "Villanos Pixar": "Pixar",
  "WALL·E": "Pixar",

  // --- DreamWorks ---
  "Bee Movie": "DreamWorks",
  Spirit: "DreamWorks",
  "Monstruos contra alienígenas": "DreamWorks",
  "Cómo entrenar a tu dragón": "DreamWorks",
  DreamWorks: "DreamWorks",
  "El gato con botas": "DreamWorks",
  "El origen de los guardianes": "DreamWorks",
  "El príncipe de Egipto": "DreamWorks",
  "Kung Fu Panda": "DreamWorks",
  "Los Croods": "DreamWorks",
  Madagascar: "DreamWorks",
  Megamind: "DreamWorks",
  Shrek: "DreamWorks",
  Trolls: "DreamWorks",

  // --- Illumination ---
  Canta: "Illumination",
  "El Grinch": "Illumination",
  "El Lorax": "Illumination",
  "Los Minions": "Illumination",
  Mascotas: "Illumination",
  "Mi villano favorito": "Illumination",

  // --- Ghibli ---
  "El castillo ambulante": "Ghibli",
  "El viaje de Chihiro": "Ghibli",
  "La princesa Mononoke": "Ghibli",
  "Mi vecino Totoro": "Ghibli",
  "Nicky, la aprendiz de bruja": "Ghibli",
  Ponyo: "Ghibli",
  "Studio Ghibli": "Ghibli",

  // --- Anime ---
  // Heidi, Marco y La abeja Maya son anime japonés, aunque aquí se vieran como
  // dibujos de sobremesa; Oliver y Benji, igual.
  "Anime clásico": "Anime",
  "Mazinger Z": "Anime",
  "Los Caballeros del Zodiaco": "Anime",
  Digimon: "Anime",
  "Ranma ½": "Anime",
  "Érase una vez el hombre": "Anime",
  "Chicho Terremoto": "Anime",
  Musculman: "Anime",
  "Candy Candy": "Anime",
  "Banner y Flappy": "Anime",
  "Detective Conan": "Anime",
  Doraemon: "Anime",
  "Dragon Ball": "Anime",
  Heidi: "Anime",
  "La abeja Maya": "Anime",
  Marco: "Anime",
  Naruto: "Anime",
  "Oliver y Benji": "Anime",
  "One Piece": "Anime",
  Pokémon: "Anime",
  "Sailor Moon": "Anime",
  "Mermaid Melody Pichi Pichi Pitch": "Anime",
  "Shin Chan": "Anime",

  // --- Series de dibujos ---
  "Agallas, el perro cobarde": "Series de dibujos",
  "Avatar: la leyenda de Aang": "Series de dibujos",
  "Ben 10": "Series de dibujos",
  "Bob Esponja": "Series de dibujos",
  "El asombroso mundo de Gumball": "Series de dibujos",
  Futurama: "Series de dibujos",
  "Gravity Falls": "Series de dibujos",
  "Hora de aventuras": "Series de dibujos",
  "Inspector Gadget": "Series de dibujos",
  "Kim Possible": "Series de dibujos",
  "Las Supernenas": "Series de dibujos",
  "Las Tortugas Ninja": "Series de dibujos",
  "Looney Tunes": "Series de dibujos",
  "Los Padrinos Mágicos": "Series de dibujos",
  "Los Picapiedra": "Series de dibujos",
  "Los Pitufos": "Series de dibujos",
  "Los Rugrats": "Series de dibujos",
  "Los Simpson": "Series de dibujos",
  "Mascotas de series": "Series de dibujos",
  "Phineas y Ferb": "Series de dibujos",
  "Scooby-Doo": "Series de dibujos",
  "Series de dibujos": "Series de dibujos",
  "Somos osos": "Series de dibujos",
  "Steven Universe": "Series de dibujos",

  "Los Autos Locos": "Series de dibujos",
  "Don Gato": "Series de dibujos",
  "Los Supersónicos": "Series de dibujos",
  "El Oso Yogui": "Series de dibujos",
  "Tom y Jerry": "Series de dibujos",
  "La Pantera Rosa": "Series de dibujos",
  Popeye: "Series de dibujos",
  "El laboratorio de Dexter": "Series de dibujos",
  "Johnny Bravo": "Series de dibujos",
  "Vaca y Pollo": "Series de dibujos",
  "Ed, Edd y Eddy": "Series de dibujos",
  "Las macabras aventuras de Billy y Mandy": "Series de dibujos",
  Foster: "Series de dibujos",
  "Oye Arnold": "Series de dibujos",
  "Los Castores Cascarrabias": "Series de dibujos",
  "Invasor Zim": "Series de dibujos",
  "Jimmy Neutrón": "Series de dibujos",
  "Danny Phantom": "Series de dibujos",
  "Los Thornberrys": "Series de dibujos",
  "La vida moderna de Rocko": "Series de dibujos",
  "Padre de familia": "Series de dibujos",
  "South Park": "Series de dibujos",
  "Rick y Morty": "Series de dibujos",
  Arcane: "Series de dibujos",
  "Super Mario": "Otros estudios",

  "La casa de Mickey Mouse": "Disney",
  "American Dragon": "Disney",
  "Doctora Juguetes": "Disney",
  "Jake y los piratas de Nunca Jamás": "Disney",
  "Sofía la Primera": "Disney",
  "Star contra las fuerzas del mal": "Disney",
  "Randy Cunningham": "Disney",
  Pecezuelos: "Disney",
  "Los reemplazantes": "Disney",
  Wander: "Disney",
  Caillou: "Infantil",
  "Lazy Town": "Infantil",
  "Dora la exploradora": "Infantil",
  "Los Backyardigans": "Infantil",
  "Little Einsteins": "Infantil",
  "El show de Garfield": "Series de dibujos",
  "Historias corrientes": "Series de dibujos",
  Clarence: "Series de dibujos",
  "Generator Rex": "Series de dibujos",
  "Lego Ninjago": "Series de dibujos",
  Bernard: "Animación española",
  "Jelly Jamm": "Animación española",
  "Lucky Fred": "Animación española",
  "Sandra detective de cuentos": "Animación española",
  "Yo-Kai Watch": "Anime",
  "Inazuma Eleven": "Anime",
  Bakugan: "Anime",

  // --- Infantil ---
  Bluey: "Infantil",
  "La Patrulla Canina": "Infantil",
  "Masha y el Oso": "Infantil",
  "Peppa Pig": "Infantil",
  Pocoyó: "Infantil",
  "Series preescolares": "Infantil",

  // --- Animación española ---
  "D'Artacan": "Animación española",
  "David el Gnomo": "Animación española",
  Klaus: "Animación española",
  "Las Tres Mellizas": "Animación española",
  "Los Fruittis": "Animación española",
  "Los Trotamúsicos": "Animación española",
  "Mortadelo y Filemón": "Animación española",
  "Series españolas": "Animación española",
  "Willy Fog": "Animación española",

  // --- Superhéroes ---
  // Manda el personaje, no el estudio: Spider-Man es de Sony y aquí está.
  Marvel: "Superhéroes",
  DC: "Superhéroes",
  "Spider-Man": "Superhéroes",

  // --- Series de imagen real ---
  // Disney Channel y Nickelodeon de los 2000 y 2010. No son animación, pero
  // desde que entró el UCM el banco ya no es solo de dibujos.
  "Hannah Montana": "Series de imagen real",
  "Los magos de Waverly Place": "Series de imagen real",
  "Buena suerte Charlie": "Series de imagen real",
  "Zack y Cody": "Series de imagen real",
  "Es tan Raven": "Series de imagen real",
  "Lizzie McGuire": "Series de imagen real",
  "Phil del futuro": "Series de imagen real",
  "Cory en la Casa Blanca": "Series de imagen real",
  "Sonny entre estrellas": "Series de imagen real",
  "Camp Rock": "Series de imagen real",
  "High School Musical": "Series de imagen real",
  Violetta: "Series de imagen real",
  "Soy Luna": "Series de imagen real",
  Jessie: "Series de imagen real",
  "Austin y Ally": "Series de imagen real",
  "A todo ritmo": "Series de imagen real",
  "Liv y Maddie": "Series de imagen real",
  Descendientes: "Series de imagen real",
  iCarly: "Series de imagen real",
  "Drake y Josh": "Series de imagen real",
  Victorious: "Series de imagen real",
  "Zoey 101": "Series de imagen real",
  "Big Time Rush": "Series de imagen real",
  "Los Thundermans": "Series de imagen real",
  "Manual de supervivencia escolar de Ned": "Series de imagen real",
  "Henry Danger": "Series de imagen real",
  "Series de imagen real": "Series de imagen real",

  // Europeas que aquí se vieron en Clan, Boing y Jetix.
  "Winx Club": "Series de dibujos",
  "Código Lyoko": "Series de dibujos",
  Gormiti: "Series de dibujos",

  // --- Otros estudios ---
  // Sony, Blue Sky, Aardman, Laika, Warner y las mezclas de varios estudios.
  Anastasia: "Otros estudios",
  "Chicken Run": "Otros estudios",
  Coraline: "Otros estudios",
  "El Gigante de Hierro": "Otros estudios",
  "El Principito": "Otros estudios",
  "Estudios de animación": "Otros estudios",
  "Hotel Transilvania": "Otros estudios",
  "Ice Age": "Otros estudios",
  "Lluvia de albóndigas": "Otros estudios",
  "Lugares de ficción": "Otros estudios",
  "Los Boxtrolls": "Otros estudios",
  Kubo: "Otros estudios",
  ParaNorman: "Otros estudios",
  "Los Mitchell contra las máquinas": "Otros estudios",
  "El robot salvaje": "Otros estudios",
  Nimona: "Otros estudios",
  "Pesadilla antes de Navidad": "Otros estudios",
  "Robots de la animación": "Otros estudios",
  Río: "Otros estudios",
  "Wallace y Gromit": "Otros estudios",

  // --- Música: aquí la franquicia es el artista ---
  // Así la regla de «no repetir franquicia en 8 preguntas» se convierte en «no
  // repetir artista», que es exactamente lo que hace falta en este tema.
  Duki: "Trap y rap latino",
  "Eladio Carrión": "Trap y rap latino",
  Bizarrap: "Trap y rap latino",
  "Bad Bunny": "Reggaetón",
  Estopa: "Música española",
  Huecco: "Música española",
  "Marc Anthony": "Salsa y pop latino",
  "Taylor Swift": "Pop internacional",
  Eminem: "Los 2000 en inglés",
  "Amy Winehouse": "Los 2000 en inglés",
  "Britney Spears": "Los 2000 en inglés",
  "Linkin Park": "Los 2000 en inglés",
  "The Killers": "Los 2000 en inglés",
  Coldplay: "Los 2000 en inglés",
  Rihanna: "Los 2000 en inglés",
  Beyoncé: "Los 2000 en inglés",
  Outkast: "Los 2000 en inglés",
  // Comodín para las preguntas que cruzan artistas, como en Palomitas.
  "Los 2000 en inglés": "Los 2000 en inglés",

  // --- Artistas de las listas de Spotify (ver lib/banco/musica-listas.ts) ---
  // Trap y rap latino
  "6ix9ine": "Trap y rap latino",
  "8belial": "Trap y rap latino",
  Aissa: "Trap y rap latino",
  Alejo: "Trap y rap latino",
  Alleh: "Trap y rap latino",
  "Alvaro Diaz": "Trap y rap latino",
  Arcángel: "Trap y rap latino",
  Beéle: "Trap y rap latino",
  "Big One": "Trap y rap latino",
  "C.R.O": "Trap y rap latino",
  "Caleb Calloway": "Trap y rap latino",
  "Calle 13": "Trap y rap latino",
  Clarent: "Trap y rap latino",
  "Cris MJ": "Trap y rap latino",
  Easykid: "Trap y rap latino",
  Emilia: "Trap y rap latino",
  Gonzy: "Trap y rap latino",
  JHAYCO: "Trap y rap latino",
  "Jon Z": "Trap y rap latino",
  KHEA: "Trap y rap latino",
  "Kidd Voodoo": "Trap y rap latino",
  "LiL CaKe": "Trap y rap latino",
  "LIT killah": "Trap y rap latino",
  "Luck Ra": "Trap y rap latino",
  "Maria Becerra": "Trap y rap latino",
  Mesita: "Trap y rap latino",
  "Milo j": "Trap y rap latino",
  "Modo Diablo": "Trap y rap latino",
  Mora: "Trap y rap latino",
  MYA: "Trap y rap latino",
  "Neo Pistea": "Trap y rap latino",
  "Omar Courtz": "Trap y rap latino",
  Oscu: "Trap y rap latino",
  "Paulo Londra": "Trap y rap latino",
  "Polimá Westcoast": "Trap y rap latino",
  Quevedo: "Trap y rap latino",
  Rei: "Trap y rap latino",
  rusowsky: "Trap y rap latino",
  SAIKO: "Trap y rap latino",
  "Tiago PZK": "Trap y rap latino",
  Trueno: "Trap y rap latino",
  "W Sound": "Trap y rap latino",
  "Yan Block": "Trap y rap latino",
  "Yng Lvcas": "Trap y rap latino",
  "Young Cister": "Trap y rap latino",

  // Reggaetón
  "Alex Rose": "Reggaetón",
  "Alexis y Fido": "Reggaetón",
  Ankhal: "Reggaetón",
  "Anuel AA": "Reggaetón",
  "Big Yamo": "Reggaetón",
  Boza: "Reggaetón",
  "Bryant Myers": "Reggaetón",
  Cauty: "Reggaetón",
  "Chino & Nacho": "Reggaetón",
  "Chris Jedi": "Reggaetón",
  "Chris Viz": "Reggaetón",
  "Comando Tiburon": "Reggaetón",
  "Daddy Yankee": "Reggaetón",
  Dalex: "Reggaetón",
  Darell: "Reggaetón",
  "DJ Nelson": "Reggaetón",
  "Don Omar": "Reggaetón",
  "Dyland & Lenny": "Reggaetón",
  "El Alfa": "Reggaetón",
  Farruko: "Reggaetón",
  Feid: "Reggaetón",
  "Flow La Movie": "Reggaetón",
  "Franco \"El Gorilla\"": "Reggaetón",
  Fuego: "Reggaetón",
  "Ghetto Kids": "Reggaetón",
  Guaynaa: "Reggaetón",
  "Héctor \"El Father\"": "Reggaetón",
  "Hector & Tito": "Reggaetón",
  "J Balvin": "Reggaetón",
  "Jay Wheeler": "Reggaetón",
  "Justin Quiles": "Reggaetón",
  "Kafu Banton": "Reggaetón",
  "KAROL G": "Reggaetón",
  "KEVIN ROLDAN": "Reggaetón",
  "Lele Pons": "Reggaetón",
  Lunay: "Reggaetón",
  "Luny Tunes": "Reggaetón",
  Maluma: "Reggaetón",
  "Manuel Turizo": "Reggaetón",
  "Mariah Angeliq": "Reggaetón",
  "Myke Towers": "Reggaetón",
  Nacho: "Reggaetón",
  "Nicky Jam": "Reggaetón",
  "Nio Garcia": "Reggaetón",
  "Ñejo & Dalmata": "Reggaetón",
  "Ovy On The Drums": "Reggaetón",
  Ozuna: "Reggaetón",
  "Plan B": "Reggaetón",
  "Rauw Alejandro": "Reggaetón",
  Sech: "Reggaetón",
  "Sky Rompiendo": "Reggaetón",
  "Super Yei": "Reggaetón",
  Tainy: "Reggaetón",
  "Tego Calderón": "Reggaetón",
  "Tito \"El Bambino\"": "Reggaetón",
  Wisin: "Reggaetón",
  "Wisin & Yandel": "Reggaetón",
  Yandel: "Reggaetón",
  Zion: "Reggaetón",

  // Música española
  "Abraham Mateo": "Música española",
  "Agrupacion LatinHits": "Música española",
  Aitana: "Música española",
  "Alex Ubago": "Música española",
  "Amaia Montero": "Música española",
  Amaral: "Música española",
  "Bad Gyal": "Música española",
  Bustamante: "Música española",
  "C. Tangana": "Música española",
  Cano: "Música española",
  "David Bisbal": "Música española",
  DCS: "Música española",
  Despistaos: "Música española",
  "Don Patricio": "Música española",
  "Efecto Mariposa": "Música española",
  "El Bobe": "Música española",
  "El Canto Del Loco": "Música española",
  "El Sueño de Morfeo": "Música española",
  "Enrique Iglesias": "Música española",
  "Fito y Fitipaldis": "Música española",
  Haze: "Música española",
  "Hombres G": "Música española",
  "Jarabe De Palo": "Música española",
  "JC Reyes": "Música española",
  "Juan Magán": "Música española",
  "K-Narias": "Música española",
  "La La Love You": "Música española",
  "La Oreja de Van Gogh": "Música española",
  "La Pantera": "Música española",
  Locoplaya: "Música española",
  "Lola Indigo": "Música española",
  "Los Sufridos": "Música española",
  "M-Clan": "Música española",
  Macaco: "Música española",
  "Magan & Rodríguez": "Música española",
  "Maldita Nerea": "Música española",
  "María Villalón": "Música española",
  Melendi: "Música española",
  "Nena Daconte": "Música española",
  "Omar Montes": "Música española",
  Pereza: "Música española",
  Pignoise: "Música española",
  "Rels B": "Música española",
  ROSALÍA: "Música española",
  Rvfv: "Música española",

  // Salsa y pop latino
  Aventura: "Salsa y pop latino",
  "Cali Y El Dandee": "Salsa y pop latino",
  "Carlos Baute": "Salsa y pop latino",
  Chayanne: "Salsa y pop latino",
  "Danny Ocean": "Salsa y pop latino",
  "Elvis Crespo": "Salsa y pop latino",
  FloyyMenor: "Salsa y pop latino",
  Juanes: "Salsa y pop latino",
  "MC Fioti": "Salsa y pop latino",
  Nek: "Salsa y pop latino",
  OMI: "Salsa y pop latino",
  "Pedro Capó": "Salsa y pop latino",
  Pitbull: "Salsa y pop latino",
  "Prince Royce": "Salsa y pop latino",
  "Ricky Martin": "Salsa y pop latino",
  sangiovanni: "Salsa y pop latino",
  "Sebastian Yatra": "Salsa y pop latino",
  Shakira: "Salsa y pop latino",
  Soolking: "Salsa y pop latino",

  // Los 2000 en inglés
  "50 Cent": "Los 2000 en inglés",
  "Avril Lavigne": "Los 2000 en inglés",
  "Black Eyed Peas": "Los 2000 en inglés",
  "Daft Punk": "Los 2000 en inglés",
  Evanescence: "Los 2000 en inglés",
  "Franz Ferdinand": "Los 2000 en inglés",
  Gorillaz: "Los 2000 en inglés",
  "Green Day": "Los 2000 en inglés",
  "Gwen Stefani": "Los 2000 en inglés",
  "Jason Mraz": "Los 2000 en inglés",
  "JAY-Z": "Los 2000 en inglés",
  "Kanye West": "Los 2000 en inglés",
  "Kelly Clarkson": "Los 2000 en inglés",
  "Kings of Leon": "Los 2000 en inglés",
  "Kylie Minogue": "Los 2000 en inglés",
  LMFAO: "Los 2000 en inglés",
  "Mark Ronson": "Los 2000 en inglés",
  "Maroon 5": "Los 2000 en inglés",
  "Missy Elliott": "Los 2000 en inglés",
  "Pharrell Williams": "Los 2000 en inglés",
  "Robin Thicke": "Los 2000 en inglés",
  "Snow Patrol": "Los 2000 en inglés",
  "The Fray": "Los 2000 en inglés",
  "The Rasmus": "Los 2000 en inglés",
  "The White Stripes": "Los 2000 en inglés",
  Timbaland: "Los 2000 en inglés",
  Train: "Los 2000 en inglés",
  USHER: "Los 2000 en inglés",

  // Pop internacional
  Adele: "Pop internacional",
  "Alan Walker": "Pop internacional",
  "Arctic Monkeys": "Pop internacional",
  "Ariana Grande": "Pop internacional",
  Avicii: "Pop internacional",
  "Billie Eilish": "Pop internacional",
  "Bruno Mars": "Pop internacional",
  "Calvin Harris": "Pop internacional",
  "Carly Rae Jepsen": "Pop internacional",
  "Clean Bandit": "Pop internacional",
  "David Guetta": "Pop internacional",
  "DJ Snake": "Pop internacional",
  "Doja Cat": "Pop internacional",
  Drake: "Pop internacional",
  "Dua Lipa": "Pop internacional",
  "Ed Sheeran": "Pop internacional",
  "Foster The People": "Pop internacional",
  "fun.": "Pop internacional",
  "Gabry Ponte": "Pop internacional",
  Gotye: "Pop internacional",
  "Harry Styles": "Pop internacional",
  Hozier: "Pop internacional",
  "Imagine Dragons": "Pop internacional",
  "Justin Bieber": "Pop internacional",
  "Katy Perry": "Pop internacional",
  Kesha: "Pop internacional",
  "Lady Gaga": "Pop internacional",
  "Lil Nas X": "Pop internacional",
  "Lilly Wood and The Prick": "Pop internacional",
  Lorde: "Pop internacional",
  "Major Lazer": "Pop internacional",
  Marshmello: "Pop internacional",
  "Miley Cyrus": "Pop internacional",
  "Mr. Probz": "Pop internacional",
  "Of Monsters and Men": "Pop internacional",
  "One Direction": "Pop internacional",
  OneRepublic: "Pop internacional",
  "Owl City": "Pop internacional",
  "Post Malone": "Pop internacional",
  Sia: "Pop internacional",
  "Swedish House Mafia": "Pop internacional",
  "The Chainsmokers": "Pop internacional",
  "The Weeknd": "Pop internacional",
  "Tones And I": "Pop internacional",
  "Twenty One Pilots": "Pop internacional",

  // --- Historia: la franquicia es la civilización o el imperio ---
  // Así la regla de no repetir franquicia en 8 preguntas evita que salgan
  // cuatro de Roma seguidas, y la categoría agrupa por cultura.
  Mesopotamia: "Mesopotamia y Egipto",
  "Antiguo Egipto": "Mesopotamia y Egipto",
  "Reino de Kush": "Mesopotamia y Egipto",

  "Antigua Grecia": "Grecia y Roma",
  "Antigua Roma": "Grecia y Roma",
  "Imperio bizantino": "Grecia y Roma",

  "China imperial": "China",
  "Imperio mongol": "China",

  "Japón": "Japón y Corea",
  Corea: "Japón y Corea",

  "Civilización del Indo": "India",
  "Imperio maurya": "India",
  "India antigua": "India",
  "Imperio mogol": "India",
  "India contemporánea": "India",

  "Islam medieval": "El mundo islámico",
  "Al-Ándalus": "El mundo islámico",
  "Imperio otomano": "El mundo islámico",

  "Imperio de Malí": "África",
  "Gran Zimbabue": "África",
  "Reino de Aksum": "África",
  "Etiopía": "África",
  "Reino de Benín": "África",
  "África colonial": "África",
  "Sudáfrica": "África",
  // Comodín para las preguntas que cruzan reinos africanos.
  "África": "África",

  "Civilización caral": "América precolombina",
  "Civilización maya": "América precolombina",
  "Imperio mexica": "América precolombina",
  "Imperio inca": "América precolombina",
  "América precolombina": "América precolombina",

  Polinesia: "Oceanía y el Pacífico",
  "Nueva Zelanda": "Oceanía y el Pacífico",
  "Rapa Nui": "Oceanía y el Pacífico",
  Australia: "Oceanía y el Pacífico",

  "Europa medieval": "Europa medieval y moderna",
  "Europa moderna": "Europa medieval y moderna",

  "Primera Guerra Mundial": "El mundo contemporáneo",
  "Segunda Guerra Mundial": "El mundo contemporáneo",
  "Guerra Fría": "El mundo contemporáneo",
  "Descolonización": "El mundo contemporáneo",
  "Siglo XX": "El mundo contemporáneo",

  // Comodines para las preguntas que cruzan artistas
  "Trap y rap latino": "Trap y rap latino",
  "Reggaetón": "Reggaetón",
  "Música española": "Música española",
  "Salsa y pop latino": "Salsa y pop latino",
  "Pop internacional": "Pop internacional",
};

/** La categoría de una franquicia, o null si no está mapeada. */
export function categoriaDe(franquicia: string): Categoria | null {
  return POR_FRANQUICIA[franquicia] ?? null;
}

/**
 * El emoji que acompaña a la franquicia en la cabecera de la pregunta.
 *
 * Antes cada pregunta traía el suyo y eso salió mal dos veces. La primera, que
 * chivaban: 🦥 en «¿qué animal es Sid?» regalaba el punto. La segunda, que ni
 * siquiera coincidían entre preguntas de la misma película: de 269 franquicias,
 * 170 usaban más de un emoji, y Bob Esponja llegó a tener siete.
 *
 * Ahora lo pone la categoría, y eso lo arregla de raíz por una razón que no
 * depende del criterio de nadie: **al lado del emoji ya se enseña la
 * franquicia, y la franquicia determina la categoría**. Así que el emoji no
 * añade ni un dato que no estuviera ya en pantalla, y lo que no informa no
 * puede delatar. Con un emoji por pregunta había 1080 sitios que vigilar; así
 * no queda ninguno.
 *
 * De paso son los mismos que agrupan el resumen de fin de partida, así que la
 * categoría se lee igual jugando que en las estadísticas.
 *
 * Al elegirlos se ha evitado cualquiera que nombre una cosa (un animal, un
 * color, un objeto): todos dicen de qué estudio o de qué clase de contenido es
 * la pregunta, que es justo lo que la franquicia ya cuenta.
 */
export const EMOJI_DE_CATEGORIA: Record<Categoria, string> = {
  Disney: "🏰",
  Pixar: "💡",
  DreamWorks: "🌙",
  Illumination: "🎦",
  Ghibli: "⛩️",
  Anime: "🎌",
  "Series de dibujos": "📺",
  Infantil: "🎠",
  "Animación española": "🇪🇸",
  Superhéroes: "🦸",
  "Series de imagen real": "🎬",
  "Otros estudios": "🎞️",

  // Música. Mismo criterio que arriba: ninguno nombra una cosa que pueda ser
  // respuesta, así que un 🎸 o un 🎺 quedan descartados aunque peguen con el
  // tema; «guitarra» y «trompeta» sí pueden ser la solución de una pregunta.
  "Trap y rap latino": "🎧",
  "Reggaetón": "🪩",
  "Música española": "💃",
  "Salsa y pop latino": "📻",
  "Pop internacional": "🎤",
  "Los 2000 en inglés": "💿",

  // Historia. Los tres globos terráqueos no son pereza: el emoji enseña
  // literalmente la región de la que va la pregunta, que es lo más neutro que
  // hay. Y siguen valiendo las reglas de siempre: nada que pueda ser respuesta,
  // así que un 🐉 para China o un 🪶 para América quedan descartados.
  "Mesopotamia y Egipto": "🏺",
  "Grecia y Roma": "🏛️",
  China: "🏮",
  "Japón y Corea": "🏯",
  India: "🕉️",
  "El mundo islámico": "🕌",
  "África": "🌍",
  "América precolombina": "🌎",
  "Oceanía y el Pacífico": "🌏",
  "Europa medieval y moderna": "⚜️",
  "El mundo contemporáneo": "📰",
};

/**
 * El emoji de una franquicia. El de reserva solo saltaría con una franquicia
 * sin categoría, cosa que `validarBanco()` no deja pasar.
 */
export function emojiDe(franquicia: string): string {
  const categoria = categoriaDe(franquicia);
  return categoria ? EMOJI_DE_CATEGORIA[categoria] : "🎞️";
}
